### PR TITLE
Avoid arg expansion that leads to broken code

### LINKED ISSUE #7518: Unstable single-line comments in destructured function argument
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAhAThAawUwF5MAlOAQzBgDoAzCXAdytwBNKGAKH4ADpQBMMAAsAlgBsOuBABohIgPTLMARiUxVmAExaYEmFLiLhMSRw4KtOgMxCAvvMxyGASlIA+TDy0AeDgkAN1c4BhJgN0cvLRFgcWlZBEcA5SDg2Kh3dxB5EAgAB0N0ZFB2fBYABXYENGQQKmCICQ48kAAjXBoiGABlQpoJKABzZBhcAFdTEDEYAFspAHVJeDRBsDg+uqMQowBPBrA0evzhtDhcGCrukfmqZAYqKQv8gCs0AA88Hrh+qnmcAAMsM4I9nq8QB9Pn1hiMTABFSYQeDgl4zQa4C64BodKgdfZSaDtQq4YYwJatCzIAAcAAZ8qSIBclt1Cg1SXBscEwfkAI7I+A3Ir1FBUNAAWigcDg1ja+TkAokchuVDuDyQT3R+Qu8wk4ymMzQcMRgrBmohMxg+MpHGpSF0+QmVGkcIAwhB5vcGlBoLyQJMLgAVfGirWQ4LTACSUGssD6YDJxQAgrG+jBCebw3BHI4gA)
```sh
--parser babylon
```

**Input:**
```jsx
const Broken = React.forwardRef(({
	children,
	// 1
	// 2
	title,
	hidden,
	// 3
}, ref) => (
	<div ref={ref}>
		{children}
	</div>
))
```

**Output:**
```jsx
const Broken = React.forwardRef(({ children, // 1
  // 2
  title, hidden }, ref) => <div ref={ref
  // 3
    }>{children}</div>);

```

**Second output:**
```jsx
const Broken = React.forwardRef(({ children, // 2 // 1
  title, hidden }, ref) => (
  <div
    ref={
      ref
      // 3
    }
  >
    {children}
  </div>
));
```

**Third output:**
```jsx
const Broken = React.forwardRef(({ children, title, hidden }, ref) => ( // 2 // 1
  <div
    ref={
      ref
      // 3
    }
  >
    {children}
  </div>
));
```

**Fourth output:**
```jsx
const Broken = React.forwardRef((
  { children, title, hidden },
  ref // 2 // 1
) => (
  <div
    ref={
      ref
      // 3
    }
  >
    {children}
  </div>
));
```

**Expected behavior:**
```jsx
const Broken = React.forwardRef(({
  children,
  // 1
  // 2
  title,
  hidden
  // 3
}, ref) => (
  <div ref={ref}>{children}</div>
));
```

### LINKED ISSUE #10708: Incorrect formatting with comment in empty object pattern
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjCqA6VMwHQAmEAMgBSnAAEAhgDSWpKXDa64D07lkAtjwjFYwAvsICUlALwA+SgGcI-GAAsAllADmQ3HjgAbOXGyUTpnfsMVxYkLRAQADjFXQ5yUNQBOniAHcACl4IbijUer7UAJ5udqie1GAA1nAwAMoOCeoayDCeAK5wdnA8qHAEBGXE1Jp51BpwAGIQnjzUMM6ayCDUeTAQtiDKMDx6AOpq8HIZYHCpwarOAG4LkV1gcjEg6oaeMP7xGq3IAGZhhnYAVnIAHgBC8UkpqdT8xOpwJ2eFIFfXqVl6OAARTyEHgnwM3wynh2XVQ1FKegGDk86hgo1UBBUyAAHAAGOwoiCGUbxBxdFFwHaLD52ACOoPg+0cIW6cgAtFA4GUygNPHAGap+fs6kckKdIXZDDxVDl8t85ADgYyPuKvnYYAiMVjlMgAEwa+KqPRZADCijFICpAFYBnlDAAVBEhCXnECLAoASSgFVgqTAqKcAEEfakYJFARDDKIgA)

```sh
--parser babel
```

**Input:**

```jsx
bob
	.doL(({ a, b: {
		// comment
	}}) => something
		.else
      	.else({}))
```

**Output:**

```jsx
bob.doL(({ a, b: {
    // comment} }) => something.else.else({}));

```

**Expected behavior:**
Unsure what the "correct" behaviour is here, but definitely the comment needs to be on its own line, so something like this could work

```jsx
bob.doL(({ a, b: {
    // comment
    }}) => something.else.else({}));

```

### PR DESCRIPTION
**Pull request by thorn0**
## Description

Fixes #10708
Fixes #7518

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/common/ast-path.js [hunk 1]
```diff
@@ -110,6 +110,22 @@ class AstPath {
...
+  try(callback, onCaught) {
+    const { stack } = this;
+    const { length } = stack;
+    try {
+      callback();
+    } catch (error) {
+      stack.length = length;
+      onCaught(error);
+    }
+  }
```
Comment (fisker) [inline src/common/ast-path.js:127]: Use error looks usual too me, but  how about

```js
try(callback) {
  callback();
} finally {
  stack.length = length;
 }
```

so we can use 

```js
try {
	path.try(() => {/* ... */})	
} catch (error) {}
```

Comment (fisker) [reply src/common/ast-path.js:127]: Wait, if `callback` callParent, restore `.length` is not right.

Comment (thorn0) [reply src/common/ast-path.js:127]: I used `caught` because this thing we catch here logically is something expected, not an error.

> Wait, if callback callParent, restore .length is not right

Oh, you're right!

Comment (thorn0) [reply src/common/ast-path.js:127]: > but how about

Looks interesting, I'll try it.

Comment (fisker) [reply src/common/ast-path.js:126]: Are you familiar with `CanvasRenderingContext2D.{save, restore}()`?

```js
path.save();
try {
  iterateCallArgumentsPath(...)
} catch (caught) {
  path.restore();
  // ....
}
```

WDYT? 😄

Comment (thorn0) [reply src/common/ast-path.js:126]: `path.try` in its current form matches the style of other methods of `AstPath`.

Comment (fisker) [reply src/common/ast-path.js:126]: OR

```js
const [error, result]= path.try(() => {/* ... */});

if (error) {
  ...
}
```

Comment (thorn0) [reply src/common/ast-path.js:126]: I like the current form more for its simplicity and because it makes you handle the error, you can't ignore it. But feel free to change it if you want.

File: src/common/ast-path.js [hunk 2]
```diff
@@ -110,6 +110,21 @@ class AstPath {
...
 
+  /**
+   * @param {() => void} callback
+   * @internal Unstable API. Don't use in plugins for now.
+   */
+  try(callback) {
+    const { stack } = this;
+    const stackBackup = [...stack];
+    try {
+      callback();
```
Comment (fisker) [inline src/common/ast-path.js:121]:
```suggestion
      return callback();
```

Let's add `return` here, `path.try(() => path.map(...))`

**Review by fisker — APPROVED** [review]
One comment
