### PR TITLE
Fix formatting for AssignmentExpression with ClassExpression

### LINKED ISSUE #9740: AssignmentExpression with ClassExpression are systematically wrapped regardless of length
**Prettier 2.2.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbCATArgGzgOjgA8AHCAJxgGcACAXhrBwEMraBBG4+KDWgIRrAAOlBo1UcGAAtMNABQBKIaPHjIUKhDz4cEAObzhIAGYQIxxQG5VNAL6i7VkABoQEEjACW0KslDM5OQQAO4ACoEIfijMOCHMAJ5+bgBG5MxgANZSAMokGV5Q+sgw5FhwbnCoKXAYGLUAMsxFWMz6cABiFKjMMN5FyCDMWDAQriDSMKg4AOrSXvBU+WBwOVELXgBuCwmDYGzjhVRwlGHp+j3IJrHHbgBWVET86Vm5zJINhXBXNxUgD0QcoV9HgAIpYCDwH44W4gfLkY7kQYpZg1HDjEjkQowGZeDAyZAADgADG5MRBjjN0iRBpi4IjNt83ABHCHwM4eaJDKgAWigcFqtXG5DgrK8IrObUuSGuML+x1QXhKZXlwLBbO+Mt+bhgqNx+OkyAATDr0l4cMCAMIQVDSkD0gCs4ywxwAKqjorLYZtygBJXgIGA5MBYzzsXg5GAJPDQ452OxAA)
```sh
--parser babel
```

**Input:**
```jsx
module.exports = class A extends B {
  method () {
    console.log("foo");
  }
};
```

**Output:**
```jsx
module.exports = class A extends (
  B
) {
  method() {
    console.log("foo");
  }
};

```

**Expected behavior:**

The input should not be modified by Prettier when the superclass name is of reasonable length and/or does not have any namespaces. This behavior was changed in Prettier 2.2.0 and is probably caused by this [new feature](https://prettier.io/blog/2020/11/20/2.2.0.html#improve-formatting-for-assignments-of-classes-with-long-superclass-names-9341httpsgithubcomprettierprettierpull9341-by-sosukesuzukihttpsgithubcomsosukesuzuki) which was implemented in #9341. The intent was to wrap assignments with long superclass names when using the Google Closure library for example. However, it applies to everything, even if the superclass name is a single letter. This seems to do more harm than good on code readability.

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #9740

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-js/print/class.js [hunk 1]
```diff
@@ -131,13 +131,18 @@ function printList(path, options, print, listName) {
...
-      ifBreak("("),
-      indent(concat([softline, printed])),
-      softline,
-      ifBreak(")"),
-    ]);
+  if (parent.type === "AssignmentExpression") {
+    return group(
+      ifBreak(
+        concat([
+          ifBreak("("),
```
Comment (thorn0) [inline src/language-js/print/class.js:138]:
```suggestion
          "(",
```

File: src/language-js/print/class.js [hunk 2]
```diff
@@ -131,13 +131,18 @@ function printList(path, options, print, listName) {
...
+          indent(concat([softline, printed])),
+          softline,
+          ifBreak(")"),
```
Comment (thorn0) [inline src/language-js/print/class.js:141]:
```suggestion
          ")",
```

**Review by thorn0 — APPROVED** [review]

**Review by fisker — APPROVED** [review]
