### PR TITLE
Print semi before Flow variance sigil w/ no-semi

### LINKED ISSUE #11397: Flow variance sigil with no-semi leads to incorrect output
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6UOOA1NHDgLw4Bu6qAFAJQDcJZ5MA7hLQZM2JAL4kQAGhAQADjACW0TMlDoATuoi8AChoQqUTXugCeK6QCN16MAGs4MAMqzbCqAHNkMdQFc40nAAtpZwACZh4QAy6J6+6B5wAGIQ6kHoMIqeyCDovjAQUiAAFjBBqADqxQrwmK5gcE4GNQr0NaY5YNhF7phw6jA6Nh7pyABmTH3SAFaYAB4AQjb2jk7oQXBR7nDjkwEgs3NO7h6ocACKvhDwu6hTIK7qfeo5Y6jaRbLq7jAVCmEwYrIAAcAAZpF8IH0KjZZDkvnBnvQdtIAI5XeBDOSGXKYAC0UDg4XCRXUcHRCjJQwSoyQEzu+z6QQUt3umBOZ0u1x2dL20hg6EsfwBQKQACZ+TYFKgTgBhCBBWkgREAViKvj6ABVBYZ6fd6P4AJJQSKwJxgb7yPAmpwwUxnVlwUSiIA)

```sh
--parser flow
--no-semi
```

**Input:**

```jsx
class A {
  +one = val();
  +two = val()
}

```

**Output:**

```jsx
class A {
  +one = val()
  +two = val()
}

```
Without semicolons, the code above is equivalent to 

```jsx
class A {
  +one = val() + two = val()
}
```
i.e. the `+` is treated as a normal arithmetic plus operator instead of the intended [Flow variance sigil](https://flow.org/blog/2016/10/04/Property-Variance/#property-variance). This leads to a parsing error, or incorrect runtime behavior if there were no assignment or type definition in lower property `two`.

**Expected behavior:**
Flow variance sigil `+` and `-` should get semicolon at the end of the previous line, like computed properties do.

```jsx
class A {
  +one = val();
  +two = val()
}

```

### PR DESCRIPTION
**Pull request by noppa**
Fixes #11397. Omitting semicolon before class property with a Flow
variance sigil `+` or `-` may lead to output that is syntatically
incorrect or has incorrect runtime behaviour.

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
@fisker Are you okay with merging this PR?

File: tests/format/flow/no-semi/flow-class-properties.js [hunk 1]
```diff
@@ -0,0 +1,7 @@
+class A {
+  +one = val();
+  +two = val();
```
Comment (fisker) [inline tests/format/flow/no-semi/flow-class-properties.js:3]: Let's add one computed property test, and change one of them to `-`.

**Review by fisker — APPROVED** [review]
One comment https://github.com/prettier/prettier/pull/11398#discussion_r698136408

File: tests/format/flow/no-semi/flow-class-properties.js (hunk 1 above)
Comment (fisker) [reply tests/format/flow/no-semi/flow-class-properties.js:3]: And better add one property that is a function

```js
+one = function () {}
```

File: src/language-js/print/statement.js [hunk 2]
```diff
@@ -201,6 +201,18 @@ function shouldPrintSemicolonAfterClassProperty(node, nextNode) {
     }
   }
 
+  // Flow variance sigil +/- requires semi if there's no
+  // "declare" or "static" keyword before it.
+  if (
+    (nextNode.type === "ClassProperty" ||
```
Comment (fisker) [inline src/language-js/print/statement.js:207]: Even though the ast seems  not possible to be `PropertyDefinition`, but should we use `isClassProperty`? After all that's estree standard. Not important.

File: tests/format/flow/no-semi/flow-class-properties.js (hunk 1 above)
Comment (noppa) [reply tests/format/flow/no-semi/flow-class-properties.js]: Added these in 60230f9b3

File: src/language-js/print/statement.js (hunk 2 above)
Comment (noppa) [reply src/language-js/print/statement.js]: Changed to use `isClassProperty` in 14c8be5f5da. Like you said, the `"PropertyDefinition"` case shouldn't come up, but I don't think it hurts to have it there either and the function call looks slightly clearer here.

File: tests/format/flow/no-semi/flow-class-properties.js (hunk 1 above)
Comment (noppa) [reply tests/format/flow/no-semi/flow-class-properties.js]: I also added the `-` variance sigil and function property to the changelog. Didn't add computed property there because that wasn't changed in this PR.

File: tests/format/flow/no-semi/__snapshots__/jsfmt.spec.js.snap [hunk 3]
```diff
@@ -77,20 +77,22 @@ semi: false
...
 class A {
-  +one = val();
-  +two = val();
+  +one = function() {};
+  -two = val();
   static +three = val();
   +#privOne = val();
   static +#privTwo = val();
+  [computed] = val();
 }
```
Comment (fisker) [inline tests/format/flow/no-semi/__snapshots__/jsfmt.spec.js.snap:86]: I'm sorry, didn't make it clear, I mean `+[computed] = 1`, is it valid?

Comment (noppa) [reply tests/format/flow/no-semi/__snapshots__/jsfmt.spec.js.snap:86]: Ah right, I added the variance sigil in 87a72d20a  
Note though that semi is already inserted for that case in the current Prettier stable, since semi is always added before computed class properties.

**Comment by fisker** [comment]
Thank you for working on this!

**Review by fisker — APPROVED** [review]

**Review by sosukesuzuki — APPROVED** [review]
