### PR TITLE
fix: better output scss maps

### LINKED ISSUE #3235: Format SCSS deep map like CSS rules
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAtgQwA5IAQAUkANhAE74DEAjLXQDR7wAeMAtAM4AWmAJhAHd81bMzwixABjwdMxdNACUAbgA6UdahhcycPhzbYyEbHDIwAlnA74s2NujMBzOAXV48WnXt4GjJs0trRjcoDw9UACNyXjM2YkxIuGJ8AkV3PHSoFRB6EBNLaA5kUCMLWAB1C15tZAAOSTyYRKqarmQAJjyOcqdiOABFAFcIeGQAMzkOOCayTAtiXoBhCHQsZBAoaDhckEi5sABrOBgAZWxMMF7kGDIhmZAAKw5mACED47PMRwAZcp2kJNiNM8hcyNMyBswBxit04OgLDc7g8htMACqJYqAqYPcoQmAABTmTnW2OBD10AEchhZdETMCTMBMcaDjNMKnNsMzyXl+GBuSCQJgODABQ8IEMYNhJR0xQBfOVAA)
```sh
--parser css
--no-prose-wrap
```

**Input:**
```css
$map: (color: #111111, text-shadow: 1px 1px 0 salmon);

$threads-properties: map-merge(
  $threads-properties, (
    $border-label: ()
  )
);
```

**Output:**
```css
$map: (
  color: #111111,
  text-shadow: 1px 1px 0 salmon
);

$threads-properties: map-merge($threads-properties,  ($border-label: ()));

```

**Expected behavior:**
`$threads-properties:` code block to be formatted as is, over multiple lines

**Actual behavior:**
It formats the `$threads-properties:` to one line.

### PR DESCRIPTION
**Pull request by evilebottnawi**
fixes #3235

Feedback welcome :+1:

### CODE REVIEW

File: src/language-css/printer-postcss.js [hunk 1]
```diff
@@ -48,6 +49,18 @@ const isSCSSMapNode = utils.isSCSSMapNode;
 const isDetachedRulesetCallNode = utils.isDetachedRulesetCallNode;
 const isPostcssSimpleVarNode = utils.isPostcssSimpleVarNode;
 
+function shouldPrintComma(options) {
+  switch (options.trailingComma) {
+    case "all":
+    case "es5":
+      return true;
+    // fallthrough
```
Comment (j-f1) [inline src/language-css/printer-postcss.js]: You shouldn’t need this since `return` breaks out of the `switch`.

Comment (evilebottnawi) [reply src/language-css/printer-postcss.js]: @j-f1 done :+1:

File: tests/css_trailing_comma/__snapshots__/jsfmt.spec.js.snap [hunk 2]
```diff
@@ -74,42 +74,48 @@ $breakpoint-map: (
...
-$list: (
-  "Helvetica",
-  "Arial",
-  sans-serif
-);
-$colors: (
-  "red",
-  "blue"
-);
+$list: ("Helvetica", "Arial", sans-serif);
```
Comment (evilebottnawi) [inline tests/css_trailing_comma/__snapshots__/jsfmt.spec.js.snap]: @j-f1 what do you think, should we print list as map? Original issue request this, but i am not sure

**Comment by evilebottnawi** [comment]
From docs: 
> Lists are how Sass represents the values of CSS declarations

Looks like we don't touch lists. If somebody have idea have we can improve this please create new issue. In this issue i fix only maps. Thanks!

File: tests/css_trailing_comma/__snapshots__/jsfmt.spec.js.snap (hunk 2 above)
Comment (evilebottnawi) [reply tests/css_trailing_comma/__snapshots__/jsfmt.spec.js.snap]: Expected. Why https://github.com/prettier/prettier/pull/4487#issuecomment-389152753

File: src/language-css/clean.js [hunk 3]
```diff
@@ -68,10 +68,6 @@ function clean(ast, newObj) {
     newObj.value = cleanCSSStrings(newObj.value);
   }
 
-  if (ast.type === "css-import" && newObj.importPath) {
-    newObj.importPath = cleanCSSStrings(newObj.importPath);
```
Comment (evilebottnawi) [inline src/language-css/clean.js]: Not need more

File: src/language-css/clean.js [hunk 4]
```diff
@@ -110,12 +106,6 @@ function clean(ast, newObj) {
     );
   }
 
-  if (ast.type === "media-url") {
-    newObj.value = newObj.value
```
Comment (evilebottnawi) [inline src/language-css/clean.js]: Not need more

File: src/language-css/utils.js [hunk 5]
```diff
@@ -196,6 +238,16 @@ function isDetachedRulesetCallNode(node) {
   return node.raws && node.raws.params && /^\(\s*\)$/.test(node.raws.params);
 }
 
+function isPostcssSimpleVarNode(currentNode, nextNode) {
```
Comment (evilebottnawi) [inline src/language-css/utils.js]: Move for consistently

**Comment by evilebottnawi** [comment]
@lydell early for review :smile:

**Comment by lydell** [comment]
Already better than it was :)

**Comment by evilebottnawi** [comment]
It will be hard, looks all good, need refactor this complex logic, tommorow

File: src/language-css/printer-postcss.js [hunk 6]
```diff
@@ -672,22 +683,44 @@ function genericPrint(path, options, print) {
...
+                  // Key/Value pair in open paren already indented
+                  if (
+                    isKeyValuePairNode(node) &&
+                    node.type === "value-comma_group" &&
+                    node.groups &&
+                    node.groups[2] &&
+                    node.groups[2].type === "value-paren_group"
+                  ) {
+                    printed.contents.contents.parts[1] = group(
+                      printed.contents.contents.parts[1]
```
Comment (lydell) [inline src/language-css/printer-postcss.js]: This feels like a hack?

File: src/language-css/printer-postcss.js [hunk 7]
```diff
@@ -672,22 +683,44 @@ function genericPrint(path, options, print) {
...
+                    );
+
+                    return group(dedent(printed));
```
Comment (lydell) [inline src/language-css/printer-postcss.js]: Why are we dedenting here? Could we have avoided indenting in the first place?

File: src/language-css/printer-postcss.js (hunk 6 above)
Comment (evilebottnawi) [reply src/language-css/printer-postcss.js]: @lydell we have `property:<line>value` and we need use `group` on then because we break all group.
i.e.
Without hack:
```scss
$map: (
  key: 
    (
      1,
      2 
    )
);
```

Without hack:
```scss
$map: (
  key: (
      1,
      2 
  )
);
```

In theory we can add check `isSCSSMapNodeItem` in `value-colon` and don't add `line` when we in SCSS map.

**Comment by evilebottnawi** [comment]
@lydell Maybe with future refactoring I'll find out how best to solve it
