### PR TITLE
fix(vue): no error on range format

### LINKED ISSUE #4867: TypeError: options.locStart is not a function - VUE not working
**Environments:**
- Prettier Version: 1.13.7
- Running Prettier via: CLI
- Runtime: node v10.4.0
- Operating System: linux

**Steps to reproduce:**

When I perform following command with vue parser I get an error as you can see below:

```
prettier \
	--stdin \
	--no-config \
	--print-width 120 \
	--single-quote false \
	--trailing-comma none \
	--bracket-spacing true \
	--jsx-bracket-same-line false \
	--parser vue  \
	--semi true \
	--require-pragma false \
	--prose-wrap preserve \
	--arrow-parens avoid \
	--tab-width 4 \
	--use-tabs false \
	--stdin-filepath /xyz/FileDetails/index.vue \
	--cursor-offset 337 < /xyz/FileDetails/index.vue

[error] stdin: TypeError: options.locStart is not a function
[error]     at Object.findNodeAtOffset (/usr/lib/node_modules/prettier/bin-prettier.js:10017:23)
[error]     at coreFormat (/usr/lib/node_modules/prettier/bin-prettier.js:10203:32)
[error]     at format (/usr/lib/node_modules/prettier/bin-prettier.js:10369:16)
[error]     at formatWithCursor (/usr/lib/node_modules/prettier/bin-prettier.js:10381:12)
[error]     at Object.formatWithCursor (/usr/lib/node_modules/prettier/bin-prettier.js:31224:15)
[error]     at format$1 (/usr/lib/node_modules/prettier/bin-prettier.js:33227:21)
[error]     at /usr/lib/node_modules/prettier/bin-prettier.js:33321:28
[error]     at process._tickCallback (internal/process/next_tick.js:68:7)
```

I am not sure why this is a case, however when I remove --cursor-offset arg from command I get expected results back without an error. Also if I run it on JS file and not VUE it works as-well.

### PR DESCRIPTION
**Pull request by ikatyang**
Fixes #4867

### CODE REVIEW

**Comment by ikatyang** [comment]
After second investigation, we need to add `canAttachComment` for vue to get range formatting actually worked, not sure why they are associated.

https://github.com/prettier/prettier/blob/3bfaf6626cc198312c3b55f64611d622f1145fcd/src/main/range-util.js#L46-L52

https://github.com/prettier/prettier/blob/3bfaf6626cc198312c3b55f64611d622f1145fcd/src/main/comments.js#L25-L32

File: tests/range_vue/example.vue [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+  <p>Templates are not formatted yet ...
+    </p>
+</template>
+
+<<<PRETTIER_RANGE_START>>><script>
+let Prettier        = format => { your.js('though') }
+</script><<<PRETTIER_RANGE_END>>>
+
+<style>
+.and { css: too! important }
```
Comment (evilebottnawi) [inline tests/range_vue/example.vue]: Looks invalid css

Comment (ikatyang) [reply tests/range_vue/example.vue]: I copied this from the playground sample...
