### PR TITLE
Fix arrow chain indentation in calls and binaries

### LINKED ISSUE #12597: Misaligned indent in curried arrow function
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEn1ezjffSKAZxkwA9MBeTAQQDoAjACkKP3b0+NszQgAhszAATOADMA5gAsAlgCsA1gBsAtlAgAHAI4AncgFcAbgHdKATwBeI8VLlK1mnQePmrt0RMmCANBy82GL8gnY+jioaWnqGMKYWNuEOClEuse6JXva+IIGcAJS0AHz5RKxwRTTFmAAMZZgFANz5AL4c7VCdIH4gOjDy0KTIoEL6+hBmAApjCMMoQqpmQpbDvcz6QmDKcDAAykLqcAAy8lBwyJKLpHDrm9u7e9pbZ9LIMPpGtyBw6sxwYgkYmOQig0iMQmkcAAYhB9OohDABmDkMIjDAID0QLIYOpVAB1BTwUjPMBwPZzeQDExUyyosCkNYgM43fQwKabaQIy7Xb6KUiUPavVRwACKRgg8B5qhuvWehjg+lRMEs2jgpDA+nk2hgWO0Wtg+PkYhgsmQAEYAEy1OUTG74zbaVH69WKkwXXq6CXwDk6ebCUgAWnOAIBWP0cC98gjHMh3KQVxl3xu6nk70+yeFYu9FwTvN6MBERpNZqQloLm3kqleAGEIOp4z9SABWLFGG4AFRE80TspAJi+AEkoBJYHtNdqYPQR3sVSLpTdWq0gA)

```sh
--parser typescript
--print-width 120
```

**Input:**

```tsx
{
  {
    {
      const x = A.b(
        (
          c = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdef",
          d = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdef"
        ) =>
        (e) => 0
      );
    }
  }
}

```

**Output:**

```tsx
{
  {
    {
      const x = A.b(
        (
            c = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdef",
            d = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdef"
          ) =>
          (e) =>
            0
      );
    }
  }
}

```

**Expected behavior:**
Same as Input.

### PR DESCRIPTION
**Pull request by thorn0**
## Description

fixes #12597

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-js/print/function.js [hunk 1]
```diff
@@ -254,6 +255,10 @@ function printArrowChain(
 
   const groupId = Symbol("arrow-chain");
 
+  if ((isCallLikeExpression(parent) && !isCallee) || isBinaryish(parent)) {
```
Comment (fisker) [inline src/language-js/print/function.js:258]: Can it be done in `binaryish.js`? Looks little messy to me.

Comment (thorn0) [reply src/language-js/print/function.js:258]: I don't think it can be done there. The corresponding indent is located right in this file:

https://github.com/prettier/prettier/blob/9a8ebe6b4a2f3192f96c1eb9ddad8adb95354d61/src/language-js/print/function.js#L269-L275

If we remove the indent added in `binaryish.js`, we'll have output like this:
```js
const weaponizedStellatedOctahedron =
  askTrovenaBeenaDependsRowans ??
  ((
    averredBathersBoxroomBuggyNurl,
    anodyneCondosMalateOverateRetinol = "default",
  ) =>
  (annularCooeedSplicesWalksWayWay) =>
  (kochabCooieGameOnOboleUnweave) =>
      abugidicRomanocastorProvider);
```
instead of expected
```js
const weaponizedStellatedOctahedron =
  askTrovenaBeenaDependsRowans ??
  ((
    averredBathersBoxroomBuggyNurl,
    anodyneCondosMalateOverateRetinol = "default",
  ) =>
    (annularCooeedSplicesWalksWayWay) =>
    (kochabCooieGameOnOboleUnweave) =>
      abugidicRomanocastorProvider);
```

Comment (fisker) [reply src/language-js/print/function.js:258]: I didn't mean to remove `indent` for all, but move `(isCallLikeExpression(parent) && !isCallee)` there, if it matches, don't do `indent`. I'm not familiar with this part, just a question.

Comment (thorn0) [reply src/language-js/print/function.js:258]: I understood your question and showed what would happen in that case.

**Review by fisker — APPROVED** [review]

File: src/language-js/print/function.js (hunk 1 above)
Comment (fisker) [reply src/language-js/print/function.js:258]: Fine.
