### PR TITLE
Preserve spaces between CSS words and embedded expression

### LINKED ISSUE #16692: typescript formatter with template string inserts spaces (styled components + css variables + template expression)
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wAk4BDAEwBsBLKOARjwF48SBPGuKgOgAWTAAYAdKHkl4AZtBgBaInQBecJHgBuFbAAp582bEUq48gQBJgO4Hh4a4NPAF8AlGwB8tuPZquA3OLCAVDi6Fi4BNAkeOTU9IwATGwcMNy8ggl8AO50MAIAwtDSdADm1q5iElKGCkqq6lq6+jXGqmaW1l4+zm6snnYO-oHBoZg4+ITRsbQMcADMyVw8-AJzfBQwMNhEOjq9nuUuLpVSMnKtapraegbndaYWVjYDjq4eXYMuwUHio+ETUTIlBmjAALItUstBKDsrkCkVSod1pttrt9nhDsdxKcWvcGtdmncTO0nh9XuiXkMoD8oCAADQgCAYGB0KLIUDabAQLIABW0CCIyBAFBoWQonEFDIARtgKGAANZwGAAZQoAFs4AAZWbIaQiohwaWyhVK5UYOUMErILYAV0NIANaro1uwdoZYTg2DoGtgIoAKp6oNo6HBBUg9TQDQylFASjwAIo2iDwXX6+0AKyIaGVloTSZT4bTDIAjvm4DyuRgw8KiPJGLxePSQFsKHR4iVCmq1RQhSKaE2Y3G4ABBFF0KU2+A8z3axipyP2gQwNU0ADqAlyofNYDgyoFuToGlynCFYCIkpAGjtAEkoFQECqwF7mcO78rIXB51GQBguQbV7KGBCr+oaevYTYMAauAVhQJTdl+9rmtsnpCqkGChk+dDMk2v4MDAq50FQeTIAAHAADAy2BwKWdBUTBcE9oWC4MjAFBSgRRECMgCQMjaBp+mxYYRt+cBqlKvD3lQmoULGNqwXAABiODdpslq9pOEAgE4ThAA)

```sh
--parser typescript
```

**Input:**

```tsx
export const Headline1 = styled.h1`
    font-size: var(--font-size-h${({ level }) => level});
`;

export const Headline2 = styled.h2.withConfig({})`
    font-size: var(--font-size-h${({ level }) => level});
`;

export const Headline3 = styled.h3.attrs(() => ({}))`
    font-size: var(--font-size-h${({ level }) => level});
`;

export const Headline4 = styled.h4.withConfig({}).attrs(() => ({}))`
    font-size: var(--font-size-h${({ level }) => level});
`;

```

**Output:**

```tsx
export const Headline1 = styled.h1`
  font-size: var(--font-size-h ${({ level }) => level});
`;

export const Headline2 = styled.h2.withConfig({})`
  font-size: var(--font-size-h ${({ level }) => level});
`;

export const Headline3 = styled.h3.attrs(() => ({}))`
  font-size: var(--font-size-h ${({ level }) => level});
`;

export const Headline4 = styled.h4.withConfig({}).attrs(() => ({}))`
    font-size: var(--font-size-h${({ level }) => level});
`;

```

**Expected output:**

```tsx
export const Headline1 = styled.h1`
  font-size: var(--font-size-h${({ level }) => level});
`;

export const Headline2 = styled.h2.withConfig({})`
  font-size: var(--font-size-h${({ level }) => level});
`;

export const Headline3 = styled.h3.attrs(() => ({}))`
  font-size: var(--font-size-h${({ level }) => level});
`;

export const Headline4 = styled.h4.withConfig({}).attrs(() => ({}))`
    font-size: var(--font-size-h${({ level }) => level});
`;
```

**Why?**

The only correct output is the combination withConfig and attrs in the headline 4 example. Otherwise the css var has an space in the name and will be break.
Fails with --parser babel-ts also.

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #16692

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: src/language-css/print/comma-separated-value-group.js [hunk 1]
```diff
@@ -147,11 +147,17 @@ function printCommaSeparatedValueGroup(path, options, print) {
       continue;
     }
 
-    // styled.div` background: var(--${one}); `
+    // We should keep spaces between words in a embedded JS expression
```
Comment (sosukesuzuki) [inline src/language-css/print/comma-separated-value-group.js:150]: We can't know from the AST whether we can remove the spaces or whether we have to preserve them, so I believe we need to use the whitespace information from the original text.

File: src/language-css/print/comma-separated-value-group.js [hunk 2]
```diff
@@ -147,11 +147,17 @@ function printCommaSeparatedValueGroup(path, options, print) {
...
+    //   styled.div` grid-area: area-${({ area }) => area}; `;
+    //   styled.div` border: 1px ${solid} red; `;
     if (
       iNode.type === "value-word" &&
-      iNode.value.endsWith("-") &&
-      isAtWordPlaceholderNode(iNextNode)
+      isAtWordPlaceholderNode(iNextNode) &&
+      !options.originalText
+        .slice(locEnd(iNode), locStart(iNextNode))
+        .includes(" ")
```
Comment (fisker) [inline src/language-css/print/comma-separated-value-group.js:160]: I didn't take a look at the AST, but are we checking if there is a space between current node and next node? How about simply compare `locEnd(iNode) !== locStart(iNextNode)`? Will it work?

Comment (sosukesuzuki) [reply src/language-css/print/comma-separated-value-group.js]: @fisker You’re right—thanks! (Actually, we should be using `===` instead of `!==`.)

I’ve also noticed a more fundamental problem: the location info for value-words that start with a hyphen is brokwn. For the `--foo` node, both `locStart` and `locEnd` are reported two characters too far forward.

This looks like a parser bug. I worked around it with a helper function called `fixValueWordLoc` ( https://github.com/prettier/prettier/pull/17398/commits/41838a2430ee3d000b1db9ec01b5dbedd7d818c5 )

Do you have a better idea?

File: src/language-css/loc.js [hunk 3]
```diff
@@ -10,6 +21,9 @@ function calculateLocStart(node, text) {
 
   // value-* nodes have this
   if (typeof node.sourceIndex === "number") {
+    if (node.type === "value-word") {
+      return fixValueWordLoc(node, node.sourceIndex);
+    }
```
Comment (fisker) [inline src/language-css/loc.js:26]: What a mess!

**Review by fisker — APPROVED** [review]

File: src/language-css/print/comma-separated-value-group.js (hunk 2 above)
Comment (fisker) [reply src/language-css/print/comma-separated-value-group.js]: We already have so many hacks, one more doesn't matter.

`Infinity + 1 === Infinity`

File: src/language-css/loc.js [hunk 4]
```diff
@@ -2,6 +2,17 @@ import isNonEmptyArray from "../utils/is-non-empty-array.js";
...
+function fixValueWordLoc(node, originalIndex) {
+  if (node.value.startsWith("--")) {
+    if (node.value.length > 2) {
+      return originalIndex - 2;
+    }
+  } else if (node.value.startsWith("-") && node.value.length > 1) {
+    return originalIndex - 1;
+  }
+  return originalIndex;
+}
```
[the remark this answers is not in the document]
Comment (fisker) [reply src/language-css/loc.js:14]: Oh, It can be `-`?

[the remark this answers is not in the document]
Comment (fisker) [reply src/language-css/loc.js:14]:
```suggestion
function fixValueWordLoc(node, originalIndex) {
  const {value} = node;
  if (value === "-" || value.charAt(0) !== "-") {
    return originalIndex;
  }
  return originalIndex - (value.charAt(1) === "-" ? 2 : 1);
}
```

[the remark this answers is not in the document]
Comment (sosukesuzuki) [reply src/language-css/loc.js]: Thank you, fixed ( with minor tweaks from your review ) https://github.com/prettier/prettier/pull/17398/commits/4a3b262721e3c7e535962df7b4354c06877ed8c2
