### PR TITLE
Fix trailing coma print in type prameters, improve jsx parse

### LINKED ISSUE #14518: Required Comma on Unconstrained Generic Removed in .mts Files
**Prettier 2.8.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wFdiBDAMzgGEI5sw48BePAHgBUAaAPgAUpJHnIBrKBADuUAJQiubPqLwUieLgB0oIHiAgYYAS2hFkoCtmzSACpYRmUFADZSKATzN6ARtgpgxOBgAZQoAWzgAGSMoOGQqFyI4Hz8AoOCMfxiAc2QYbFJk1DDvOAATMvLIiihs0gpsuAAxHDCKGGNa5BAKUhgIXRAACxgw5wB1IaN4IkzmYIdpowA3afdusCIvEBik3Bs-bLb4xKKAKyI0YJznOABFUgh4E+ckvUzsPe6Ydww4IjA2CMhkGGCBsHGRjKMCGyAAHAAGd7WJLjPwYbpg-6MZZxPQAR0e8AOBkcPSIAFpYuVyoNsHBCUZ6QcGsckAlXkUkmEjHkClybnAAIIdIHePpwGyMaKxF5vEBEQUPJ5xdmnPQwCjeSHQ2FIABMGr8RmcOXoYTZPWczkGpCSXC1jg58uWhQAklBKrBgoDgTAhZ7gj9bnK4ABfMNAA)

```sh
# Options (if any):
tabWidth: 4
semi: false
singleQuote: true
trailingComma: all
```

**Input:**

```ts
export const unsafeCoerce = <T,>(u: unknown): T => u as T
```

**Output:**

```ts
export const unsafeCoerce = <T>(u: unknown): T => u as T
```

**Expected behavior:**

I expect the trailing comma in the generic arguments list to remain because it is a requirement from the compiler.
image

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Regular expression searches on large TypeScript files take too long. So we will reuse the function `isTSXFile` that we are already using.

Simple measurement(just enclose the relevant part in `console.time`) using a huge TS file [microsoft/TypeScript/src/compiler/checker.ts](https://raw.githubusercontent.com/microsoft/TypeScript/main/src/compiler/checker.ts)
 with about 80,000 lines:

**before:**

```
isProbablyJsx: 143.167ms
```

**after:**

```
isTSXFile: 0.05ms
```

Fixes #14518

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-js/utils/is-tsx-file.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+export default function isTSXFile(options) {
```
Comment (kachkaev) [inline src/language-js/utils/is-tsx-file.js:1]: Optional minor suggestion: StrictCamelCase for the function name:

```suggestion
export default function isTsxFile(options) {
```

**Comment by sosukesuzuki** [comment]
Ah integration tests failed..., I'll look into it.

**Comment by fisker** [comment]
If we want replace this regexp, how about pass filepath to @typescript-eslint/typescript-estree and let it [decide](https://typescript-eslint.io/architecture/parser/#jsx)?

**Comment by sosukesuzuki** [comment]
> If we want replace this regexp, how about pass filepath to @typescript-eslint/typescript-estree and let it [decide](https://typescript-eslint.io/architecture/parser/#jsx)?

I've tried it, but it does not works well.

**Comment by fisker** [comment]
@sosukesuzuki @kachkaev Let's fix #14518 here.

Current logic is,
- If `.ts` file, disable `jsx` when parsing, omit comma when possible.
- If `.jsx`, `.tsx` file, enable `jsx` when parsing, ALWAYS print comma when type parameter is single.
- Otherwise, try `jsx: true/false` when parsing,  ALWAYS  print comma when type parameter is single.

Does this sounds right to you?

//cc @bradzacher

**Comment by bradzacher** [comment]
That sounds about right to me. Does prettier handle Vue files? That's a whole other kettle of fish lol

**Comment by fisker** [comment]
> Does prettier handle Vue files?

We use html parser to parse Vue file, expressions  are parsed by `babel`(with ts support), `<script lang="ts">` block are parsed by `@typescript-eslint/typescript-estree`.

We haven't received issue about it.

**Comment by fisker** [comment]
Made a little change:

For parse,

If it's [known file type](https://typescript-eslint.io/architecture/parser/#jsx), pass filepath to `@typescript-eslint/typescript-estree`, let it decide.
Otherwise, do the old `jsx: true/false` trick.


For print,

Didn't change logic, but refactor to be more clear "only omit comma if it's .ts file".

**Review by fisker — APPROVED** [review]

**Comment by fisker** [comment]
@sosukesuzuki  Since this is your PR, you can't approve, but please take a look.

File: src/language-js/print/type-parameters.js [hunk 2]
```diff
@@ -27,6 +26,20 @@ import { printTypeScriptMappedTypeModifier } from "./mapped-type.js";
...
+// has one type parameter that isn't extend with any types.
+// Because, otherwise formatted result will be invalid as tsx.
+function shouldForceTrailingComma(path, options, paramsKey) {
+  const { node } = path;
+  return (
+    getFunctionParameters(node).length === 1 &&
+    node.type.startsWith("TS") &&
+    !(options.filepath && /\.ts$/.test(options.filepath)) &&
+    !node[paramsKey][0].constraint &&
+    path.parent.type === "ArrowFunctionExpression"
```
Comment (kachkaev) [inline src/language-js/print/type-parameters.js:39]: Could be a micropotimization, but I still wonder if we can move `path.parent.type` further up the list to the reduce the number of times a regex is tested. WDYT?

**Review by sosukesuzuki — COMMENTED** [review]
LGTM

File: src/language-js/print/type-parameters.js (hunk 2 above)
Comment (fisker) [reply src/language-js/print/type-parameters.js]: https://github.com/prettier/prettier/pull/14688/commits/332c02c315625b03bab06e492f13408e6436e98a

`path.parent` is a getter, it may not as cheap as you expect, but this is not a hot path, so not really matters.
