### PR TITLE
Fix formatting for auto-accessors with comments

### LINKED ISSUE #14036: Incorrect formatting for auto-accessors with comments
**Prettier 2.8.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6UOOAAgCZxgAUAlCWQPTM5yaoCWsAtJV0zoARqji8ocAB4xe3SRRgBPAA4cwAJy4rZHeTGbD0UXjEy9IAW0sIYTHK0XmuAcygQNce+jBgOmDxxhAG4SAF8QABoQCB0uaExkUHQNDQgAdwAFFIRElHRUdPQlROjhDR8AazgYAGV0GwAZHjhkADMCzDgyirBqupUfHhdkGA0AV26QOEthOEpqSkbjF3H0FzgAMQ9LdBgYYeQQdHGYCCiQAAsYS1QAdUuueExBv1rcp64ANyelI7BsBceF0NDBMhUXLt2p0pgArTBSWrDMQARXGEHg0NQXWigw0IKORjmqAuKi0sDuXEoMEuyAAHAAGXFpLp3CoqI5kjhwDRfVrRACO6Pg4NieWO5kk83mF08Qq4nnB6yhSA62KmXUsXFGEw1yLgeH2WmEpzgmR5zUkWJxIEw+rRGNaqph0RgIkp1NpSAATK6Klx5C4AMIQazoI4cACsF3GXQAKiI8mqbV9JgBJKDUWC1TTaGB4TO1ZRia1wMJhIA)

```sh
# Options (if any):
```

**Input:**

```js
class A {
  @dec()
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  accessor b;
}
```

**Output:**

```js
class A {
  @dec()
  accessor // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  b;
}
```

**Expected behavior:**
The comments should not be placed between the keyword `accessor` and  the identifier `b`, which causes the `accessor` to be treated as a class field instead of a keyword. Expected:

```js
class A {
  @dec()
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  accessor b;
}
```

### PR DESCRIPTION
**Pull request by fisker**
## Description

Fixes #14036

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-js/comments.js [hunk 1]
```diff
@@ -453,6 +453,9 @@ const propertyLikeNodeTypes = new Set([
   "TSAbstractMethodDefinition",
   "TSDeclareMethod",
   "MethodDefinition",
+  "ClassAccessorProperty",
+  "AccessorProperty",
+  "TSAbstractAccessorProperty",
```
Comment (fisker) [inline src/language-js/comments.js:458]: This seems can't be tested, but other `TSAbstract*` are listed here.

**Review by sosukesuzuki — APPROVED** [review]

**Review by sosukesuzuki — APPROVED** [review]
