### PR TITLE
Gracefully handle nonexistent paths passed to --stdin-filepath.

### LINKED ISSUE #5966: Passing a full path via --stdin-filepath causes an error
**Environments:**
- Prettier Version: master
- Running Prettier via: CLI
- Runtime: Node.js
- Operating System: Linux

**Steps to reproduce:**
When prettier is given a simple file name, like `foo.tsx` in its `--stdin-filepath` arg, everything works fine.

However, things fail if you try to pass a full "path", like `bar/foo.tsx`, for example. The following should reproduce the issue at master:

`echo "meep" | prettier --stdin-filepath=bar/foo.tsx`

**Expected behavior:**
Expected Prettier to use the `stdin-filepath` argument as normal to determine e.g. what parser to use.

**Actual behavior:**
Prettier fails with the following error:

```
[error] Invalid configuration file: ENOENT: no such file or directory, scandir '/path/to/cwd/bar'
```

AFAIK this wasn't an issue with 1.16.1, but is an issue with the more recent release.

### PR DESCRIPTION
**Pull request by voithos**
Previously, if you passed a nonexistent subdirectory to
--stdin-filepath, prettier would simply throw an error instead of using
the path name as information for its config. This occurred because the
editorconfig resolution code used the third party findProjectRoot
function, which throws when given a nonexistent directory.

This adds a pre step that ensures that the path passed to
findProjectRoot is an existing directory.

Fixes #5966.

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/config/resolve-config-editorconfig.js [hunk 1]
```diff
@@ -8,7 +9,15 @@ const editorConfigToPrettier = require("editorconfig-to-prettier");
 const findProjectRoot = require("find-project-root");
 
 const maybeParse = (filePath, config, parse) => {
-  const root = findProjectRoot(path.dirname(path.resolve(filePath)));
+  // findProjectRoot will throw an error if we pass a nonexistent directory to
+  // it, which is possible, for example, when the path is given via
+  // --stdin-filepath. So, first, traverse up until we find an existing
+  // directory.
+  let dirPath = path.dirname(path.resolve(filePath));
+  while (dirPath !== "/" && !fs.existsSync(dirPath)) {
```
Comment (lydell) [inline src/config/resolve-config-editorconfig.js]: Does `dirPath !== "/"` work on Windows?

Comment (voithos) [reply src/config/resolve-config-editorconfig.js]: Good catch! I don't think it would've worked. I switched it to instead use `path.parse(...).root`, and then compare the dirname to that. I tested the behavior by trying out `path.win32.parse` and `path.win32.dirname`, and it seems to work as expected.

File: src/config/resolve-config-editorconfig.js [hunk 2]
```diff
@@ -8,7 +9,16 @@ const editorConfigToPrettier = require("editorconfig-to-prettier");
...
 
 const maybeParse = (filePath, config, parse) => {
-  const root = findProjectRoot(path.dirname(path.resolve(filePath)));
+  // findProjectRoot will throw an error if we pass a nonexistent directory to
+  // it, which is possible, for example, when the path is given via
+  // --stdin-filepath. So, first, traverse up until we find an existing
+  // directory.
+  let dirPath = path.dirname(path.resolve(filePath));
+  const fsRoot = path.parse(dirPath).root;
+  while (dirPath !== fsRoot && !fs.existsSync(dirPath)) {
```
Comment (lydell) [inline src/config/resolve-config-editorconfig.js]: Why is the `while` loop needed? I’m not saying it isn’t, I’m just asking why :) For example, what would happen if we bailed out if the directory does not exist? Is it possible to add tests for this?

Comment (voithos) [reply src/config/resolve-config-editorconfig.js]: Good question! The loop is just trying to look up the resolve directory path, in case an editorconfig is present at some depth. As for just bailing out, that would also be fine. It would have the downside of ignoring editorconfigs that might otherwise have been used, but I suppose if you're running prettier via `stdin`, it doesn't really make sense to expect it to use your cwd's editorconfig, right?

If that sounds reasonable, let me know, and I'll change this to just bail.

Comment (lydell) [reply src/config/resolve-config-editorconfig.js]: Ah, thanks, now I get it.

So, in current `master`, if `dirname(stdin-filepath)` happens to exist, .editorconfig (if any, and regardless of how high up the tree) is applied, right? I think we should either _always_ apply .editorconfig for stdin, or _never._ Given that we already apply .editorconfig in `master`, I guess we should keep that behavior. And as such we should keep the `while` loop.

Do we have a test for this `while` loop? If so we’re all good. Otherwise, could you please add one?

**Comment by voithos** [comment]
Thanks for adding a test, sorry for not getting to that sooner!
