### PR TITLE
Show `(unchanged)` keyword for accessibility in CLI `--write`

### LINKED ISSUE #15396: `--write` to show text identifier for unchanged files ('grey color only' an accessibility concern 🧑‍🦯)
The output of `--write` can't distinguish between changed and unchanged text if color is not visible.

### Suggestion: Distinguish using text.

Consider that the use of color to distinguish changed vs unchanged files is not the best way to convey this difference. It has these problems:
* Visually impaired users may use a two-tone terminal that doesn't output any color information. It's impossible to distinguish in such case.
* Copying the log and pasting it somewhere else that only support plain text and no formatting, will cause the user to lose the color information. It's impossible to distinguish in such case.
* Scripts that grep the output cannot distinguish the files unless they programmatically inspect the color information. The `(cached)` keyword is unreliable as it only appears when `isCacheExists` is true.
* Cloud services that only log the text output and not the color information will not be able to display to the service user which files changed and which remain unchanged.

I think while the grey color is useful to visually distinguish, to solve the above cases we should also add the keyword `(unchanged)` after the file name. See example below.

### Example demonstrating suggestion

Take two exact copies of a project with three files, only the second of which will change in formatting.

With the current version of Prettier, running `npx/yarn prettier --write .` on first copy:

```
path/to/file1.ext 1ms
path/to/file2.ext 5ms
path/to/file3.ext 0ms (cached)
```
_(can't show color but you can imagine it: file1 and file3 will be grey)_

With a fixed version of Prettier, running `npx/yarn prettier --write .` on second copy:

```
path/to/file1.ext 1ms (unchanged)
path/to/file2.ext 5ms
path/to/file3.ext 0ms (unchanged) (cached)
```
_(can't show color but you can imagine it: file1 and file3 will be grey)_

Note: Although `(cached)` only appears for cached unchanged files, I would suggest not combining the keywords to `(unchanged, cached)` because it's harder to grep for both `(unchanged)` and `(unchanged,` in the output. Also any scripts that grep for `/ \(cached\)$/` would start to fail. That's why I suggest `(unchanged) (cached)`.

### Relevant information

Relevant code:

https://github.com/prettier/prettier/blob/f7959cccbfaf38f685b660f39eed061f5eec5ec2/src/cli/format.js#L432-L441

Relevant issues:

This was kind of hinted before in #3525 but apparently misunderstood. I believe the original author there possibly couldn't see the grey vs white distinction because the terminal didn't support colors, and everything was in the same color. This may have led to the **false** impression that all files are being overwritten when in reality, all filenames were being output to log, but only changed files were overwritten. If the output included the keyword `(unchanged)` this could possibly be avoided.

Suggestion to reduce verbosity was moved to #15480.

### I can open a pull request

I believe both suggestions can be achieved with a simple change:
* On line 435, change ``}ms`;`` to ``}ms (unchanged)`;``

Just let me know if the suggestions are acceptable.

### PR DESCRIPTION
**Pull request by ADTC**
## Description

Fixes #15396.

As described in the issue, this:

* resolves the accessibility concern by distinguishing unchanged files from changed files using the keyword `(unchanged)` instead of merely using grey color.

## Checklist

- [x] I’ve ~added~ updated tests to confirm my change works.
- [x] _(No update needed)_ (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by ADTC** [comment]
@sosukesuzuki if it's not agreeable to use `context.logger.debug` I can change it back to `context.logger.log`. The rest of the changes should be acceptable already.

PS: I also refactored the code to be concise without the `if-else` block or `const message`. Just let me know if I should revert this refactoring.

**Comment by fisker** [comment]
> if I should revert this refactoring

Please revert.

**Comment by ADTC** [comment]
@fisker it's reverted

File: src/cli/format.js [hunk 1]
```diff
@@ -437,11 +437,11 @@ async function formatFiles(context) {
       } else if (!context.argv.check && !context.argv.listDifferent) {
         const message = `${chalk.grey(fileNameToDisplay)} ${
           Date.now() - start
-        }ms`;
+        }ms (unchanged)`;
         if (isCacheExists) {
-          context.logger.log(`${message} (cached)`);
+          context.logger.debug(`${message} (cached)`);
```
Comment (sosukesuzuki) [inline src/cli/format.js:442]: I prefer `context.logger.log`.

@fisker What do you think?

Comment (fisker) [reply src/cli/format.js:442]: Same here.

**Comment by sosukesuzuki** [comment]
@ADTC Please use `context.logger.log` instead of `debug` and fix to pass tests.

**Comment by ADTC** [comment]
Hmm, okay. It changes the scope though, because then we're only adding `(unchanged)` but otherwise the output remains verbose.

**Comment by ADTC** [comment]
@sosukesuzuki it's done. Tests are okay. I ran `yarn test -u` again: everything passed and there were no further changes.

Please let me know if I missed anything.

**Comment by ADTC** [comment]
Hello @fisker, I think the failing test might be okay if you re-run it. Seems like it's an upload failure. Please help me try it again. Thanks. (If it doesn't work again, then maybe Codecov service is down.)

image

**Comment by sosukesuzuki** [comment]
@ADTC 

> Hello @fisker, I think the failing test might be okay if you re-run it. Seems like it's an upload failure. Please help me try it again. Thanks. (If it doesn't work again, then maybe Codecov service is down.)

This isn't the problem from this PR. Don't care.

**Review by sosukesuzuki — CHANGES_REQUESTED** [review]
Can you add changelog?

**Comment by ADTC** [comment]
Hi @sosukesuzuki it's done. Thank you for your patience. :)

**Review by sosukesuzuki — APPROVED** [review]

**Review by fisker — APPROVED** [review]
