### PR TITLE
Fix indentation for JSDoc comments

### LINKED ISSUE #648: Re-indent comments
As requested in #639, I'm opening up a separate ticket for [comments incorrectly being indented]

```js
function theFunction2(action$, store) {
    /*
     * comments
     */
	return true;
    /*
     * comments
     */
}
```

turns into

```js
function theFunction2(action$, store) {
  /*
     * comments
     */
  return true;
  /*
     * comments
     */
}
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20theFunction2(action%24%2C%20store)%20%7B%5Cn%20%20%20%20%2F*%5Cn%20%20%20%20%20*%20comments%5Cn%20%20%20%20%20*%2F%5Cn%5Ctreturn%20true%3B%5Cn%20%20%20%20%2F*%5Cn%20%20%20%20%20*%20comments%5Cn%20%20%20%20%20*%2F%5Cn%7D%5Cn%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

### PR DESCRIPTION
**Pull request by maxdeviant**
Multi-line comments in TypeScript aren't aligning properly. They should follow the TSLint rule [jsdoc-format](https://palantir.github.io/tslint/rules/jsdoc-format/).

This PR adds some failing tests for the issue.

I can also try to take a crack at fixing it :sweat_smile: 

Fixes #648.

### CODE REVIEW

**Comment by azz** [comment]
See #648

**Comment by maxdeviant** [comment]
I made some progress on this. Down to one failing test which I am currently looking at.

File: src/comments.js [hunk 1]
```diff
@@ -834,7 +834,33 @@ function printComment(commentPath, options) {
...
+      const isJsDocComment =
+        lines.length > 1 &&
+        lines.slice(0, lines.length - 1).every(line => line.trim()[0] === "*");
+      if (!isJsDocComment) {
+        return "/*" + comment.value + "*/";
+      }
+
+      // Determine the indentation level of the parent node.
+      const parentNode = commentPath.getParentNode();
+      const indentLevel = parentNode.loc.start.column;
```
Comment (maxdeviant) [inline src/comments.js]: Here we're trying to use the parent node of the comment to determine the indent level. This works when the parent is already properly indented, but if prettier needs to re-indent the parent, then the comment's indentation level will be where the parent was before it got re-indented.

**Comment by maxdeviant** [comment]
@azz Do you have any suggestions on how we might handle the issue with parent nodes that are incorrectly indented? (Or if this is even the right approach to begin with).

I ran a modified version of prettier with theses changes on our internal codebase (which was already formatted with prettier), and it fixed all of the broken JSDoc comments. So it appears to work for code that is indented properly.

I guess it should be noted that the first time prettier runs the comments whose parent nodes needed indentation would be indented incorrectly, but the *second* time prettier runs they would correct themselves, since the parent nodes would already be properly indented :smile:

**Comment by azz** [comment]
That's a tricky one (probably why this issue is still open). I'll do some thinking and get back to you.

File: src/comments.js [hunk 2]
```diff
@@ -834,7 +834,33 @@ function printComment(commentPath, options) {
...
     case "CommentBlock":
     case "Block":
-      return "/*" + comment.value + "*/";
+      const lines = comment.value.split("\n");
+      const isJsDocComment =
+        lines.length > 1 &&
+        lines.slice(0, lines.length - 1).every(line => line.trim()[0] === "*");
+      if (!isJsDocComment) {
+        return "/*" + comment.value + "*/";
+      }
```
Comment (vjeux) [inline src/comments.js]: I'd get rid of this check, I can't think of any kind of multi-line comment where you'd like the lines after the first one to stay at the same position if the first one is shifted.

File: src/comments.js [hunk 3]
```diff
@@ -834,7 +834,33 @@ function printComment(commentPath, options) {
...
+
+      // Determine the indentation level of the parent node.
+      const parentNode = commentPath.getParentNode();
+      const indentLevel = parentNode.loc.start.column;
+
+      let spaces = "";
+      for (let i = 0; i <= indentLevel; i++) {
+        spaces += " ";
+      }
```
Comment (vjeux) [inline src/comments.js]: This won't work as intended when using tabs. We already have logic to figure out indentation and replay it for the template literal use case: https://github.com/prettier/prettier/blob/e378f5e9baf2865b0ed6fef445f29bb3c47c2ccd/src/printer.js#L1855-L1867

I would extract it out into a reusable function and use it here.

File: src/comments.js (hunk 1 above)
Comment (vjeux) [inline src/comments.js]: You got me thinking about this and I don't think that checking the parent is the right approach after-all. If we look at what happens today, the first line of the comment has the right indentation, what's problematic are the remaining lines.

Instead of sending a raw string for the entire comment, you could send one string for each line with `hardline` in between. The question now is: how many spaces do I need to prepend each line such that when it's aligned the same as in the original line, it's going to be printed as the right position.

Solving this is easy, it's the position of the first non-whitespace - position of the beginning of the first line. You can use `align()` to specify this number for each line.

File: tests/typescript_comments/methods.ts [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+                 * rest.
+                 */
+  baz() {}
+
+      /**
+       * Buzz-Fizz.
+       * Note: This is indented too far.
+       */
+      fizzBuzz() {}
+}
```
Comment (vjeux) [inline tests/typescript_comments/methods.ts]: I'd like to see cases where the parent indent is changed as well :)

**Comment by maxdeviant** [comment]
@vjeux I will have a look at your comments!

**Comment by maxdeviant** [comment]
@vjeux (I actually finished the changes a while ago, but I forgot to submit the review :sweat_smile:)

File: src/comments.js (hunk 2 above)
Comment (vjeux) [inline src/comments.js]: `addAlignmentToDoc` is an absolute alignment, so it doesn't take into account the current indentation. If you say 6, it's going to put 6 no matter how the indentation is for this element.

Using `addAlignmentToDoc` was the first idea I had (and your code looked like it would be using) but then I thought about something else.

What we can do is to find at what indent the `/*` starts (let's call it `startIndent`) and for each line use `align()` with `lineIndent - startIndent`. This way we only have to make sure that the delta in spaces between the first line and all the lines is correct. We can let the normal algorithm decide what the first indent should be (which it does a good job at).

If we do that, we shouldn't care about reading `*` because all the spaces in the comment will be respected.

File: tests/typescript_comments/methods.ts [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+      /**
+       * Buzz-Fizz.
+       * Note: This is indented too far.
+       */
+      fizzBuzz() {}
+
+      /**
+       * Turns the given string into pig-latin.
+       */
+              pigLatinize(value: string) {}
```
Comment (vjeux) [inline tests/typescript_comments/methods.ts]: No, if you put the comment inside of `pigLatinize()` then it's what I'm talking about.

**Comment by alexjlockwood** [comment]
It would be great to see this get submitted. :)

**Comment by maxdeviant** [comment]
@alexjlockwood I haven't forgotten! Just need to find some time to work on it 😅

**Comment by maxdeviant** [comment]
@vjeux So I finally found some time to work on this again.

I merged in the changes from master, and now all of the tests are passing! It seems like Travis is having some trouble running the tests on Node 4, so the CI checks are failing because of that.

File: src/comments.js [hunk 6]
```diff
@@ -919,8 +919,35 @@ function printComment(commentPath, options) {
...
+            indentSize,
+            tabWidth
+          )
+        );
+        if (index < lines.length - 1) {
+          parts.push(docBuilders.hardline);
+        }
+      });
+
+      return docBuilders.concat(["/*", ...parts, "*/"]);
```
Comment (ikatyang) [inline src/comments.js]: Node v4 does not support `...` operator, use `concat(parts)` instead.

Comment (maxdeviant) [reply src/comments.js]: @ikatyang Good eye! Thank you :smile:

File: src/comments.js (hunk 2 above)
Comment (maxdeviant) [reply src/comments.js]: @vjeux I'm still having trouble with the approach that you described.

By the time we get to `printComment`, the `/*` has already been stripped off of `commentPath`, so we can't use it to get the `startIndent`.

I also still can't seem to get `align` to behave properly. Even if I pass in an arbitrary indent value (like `100`), it seems to have no effect on the output :confused:

Comment (lydell) [reply src/comments.js]: @maxdeviant I haven’t really been following along here, but if I were to make an attempt at fixing the indentation of jsdoc comments, this is how I’d go about it:

1. Split the comment into lines.
2. Trim whitespace from every line.
3. Add a single space at the start of every line except the first.
4. Concatenate all the lines with a hardline between each line.

That should take care of all indentation, shouldn’t it? Or am I missing something?

File: tests/typescript_comments/methods.ts [hunk 7]
```diff
@@ -0,0 +1,38 @@
...
+       */
+      fizzBuzz() {}
+
+      /**
+       * Turns the given string into pig-latin.
+       */
+              pigLatinize(value: string) {
+/**
+ * This is a block comment inside of a method.
+ */
```
Comment (lydell) [inline tests/typescript_comments/methods.ts]: Can we add a test where the stars aren’t lined up in the input?

```js
/**
* first line
 * second line
* third
    * fourth
  */
function foo() {}
```

File: src/comments.js (hunk 2 above)
Comment (maxdeviant) [reply src/comments.js]: @lydell That is actually the approach I did take. The caveat here is that I needed to only trim the whitespace for JSDoc comments, otherwise regular block comments (that don't start each line with ` * ` would have their indentation broken.

All of the tests are actually passing now, so I believe it is working as intended, just not in the way the @vjeux was describing.

File: tests/typescript_comments/methods.ts (hunk 7 above)
Comment (maxdeviant) [reply tests/typescript_comments/methods.ts]: @lydell Sure thing!

**Comment by maxdeviant** [comment]
@lydell I think we're in good shape now.

File: src/comments.js [hunk 8]
```diff
@@ -933,6 +938,38 @@ function printComment(commentPath, options) {
...
+function printJsDocComment(comment, options) {
+  const lines = comment.value.split("\n");
+  const tabWidth = options.tabWidth;
+  const indentSize = util.getIndentSize(comment.value, tabWidth);
+
+  const parts = [];
+
+  lines.forEach((line, index) => {
+    parts.push(
+      docBuilders.align(
```
Comment (lydell) [inline src/comments.js]: Why do we need to use `.align` rather than just  `(index > 0 ? " " : "") + line.trim()`?

File: src/comments.js [hunk 9]
```diff
@@ -933,6 +938,38 @@ function printComment(commentPath, options) {
...
+        indentSize,
+        // We only want to start with a leading space if we are not on
+        // the first line of a JSDoc comment.
```
Comment (lydell) [inline src/comments.js]: Does this comment provide any value?

File: src/comments.js [hunk 10]
```diff
@@ -933,6 +938,38 @@ function printComment(commentPath, options) {
...
+        (index > 0 ? " " : "") + line.trimLeft()
```
Comment (lydell) [inline src/comments.js]: Don’t we want to trim on the right side too? (`.trim()` instead of `.trimLeft()`)

File: src/comments.js (hunk 8 above)
Comment (maxdeviant) [reply src/comments.js]: You're right, the `align` is not needed. Just a remnant of a previous approach to the problem.

File: src/comments.js [hunk 11]
```diff
@@ -933,6 +938,38 @@ function printComment(commentPath, options) {
...
+      )
+    );
+    if (index < lines.length - 1) {
+      parts.push(docBuilders.hardline);
+    }
```
Comment (lydell) [inline src/comments.js]: It would be nicer to `const parts = lines.map(......); return `join(hardline, parts);`

File: src/comments.js (hunk 10 above)
Comment (maxdeviant) [reply src/comments.js]: I agree.

It does break one of the tests where the `*/` is on the same line as the last line of the comment:

```js
/** This is a regression test for a bug where we forgot to mark the fields of
  * react classes as initialized, when the class was created with createClass().
  * This would manifest as complaining that metric requires an annotation */
```
becomes

```js
/** This is a regression test for a bug where we forgot to mark the fields of
  * react classes as initialized, when the class was created with createClass().
  * This would manifest as complaining that metric requires an annotation*/
```

Do we need to build in an edge-case here? (i.e., `.trimLeft()` if the `*/` is not on its own line?

**Comment by maxdeviant** [comment]
@lydell I made the changes you suggested.

File: src/comments.js [hunk 12]
```diff
@@ -933,6 +938,31 @@ function printComment(commentPath, options) {
...
+  );
+}
+
+function printJsDocComment(comment) {
+  const lines = comment.value.split("\n");
+
+  return docBuilders.concat([
+    "/*",
+    join(
+      docBuilders.hardline,
```
Comment (lydell) [inline src/comments.js]: Can you remove `docBuilders.` from this line and 3 lines above?

File: src/comments.js [hunk 13]
```diff
@@ -933,6 +938,31 @@ function printComment(commentPath, options) {
...
+      lines.map(
+        (line, index) =>
+          (index > 0 ? " " : "") +
+          (index < lines.length - 1 ? line.trim() : line.trimLeft())
```
Comment (lydell) [inline src/comments.js]: Why can’t we `.trim()` the last line?

Comment (maxdeviant) [reply src/comments.js]: @lydell See my comment [here](https://github.com/prettier/prettier/pull/2470#discussion_r143339577). If we're okay with that behavior, then we can `.trim()` the last line.

File: src/printer.js [hunk 14]
```diff
@@ -1907,19 +1907,17 @@ function genericPrintNoParens(path, options, print, args) {
...
-            size = util.getAlignmentSize(
-              // All the leading whitespaces
-              value.slice(index + 1).match(/^[ \t]*/)[0],
-              tabWidth
-            );
-          }
+          const indentSize = util.getIndentSize(
+            childPath.getValue().value.raw,
+            tabWidth
+          );
```
Comment (lydell) [inline src/printer.js]: Is this change needed for this PR? What does it do?

Comment (maxdeviant) [reply src/printer.js]: @lydell I had refactored out `getIndentSize` because I was using it previously with `align`, but I can revert it since it's no longer needed (although I don't think it hurts to leave it factored out into its own function).

File: src/comments.js (hunk 13 above)
Comment (lydell) [reply src/comments.js]: Sorry, I missed that comment. Then you are correct – we should not trim the right side on the last line!

File: src/printer.js (hunk 14 above)
Comment (lydell) [reply src/printer.js]: I see. It’s a nice cleanup so we can keep it refactored out. 👍

File: src/comments.js (hunk 12 above)
Comment (maxdeviant) [reply src/comments.js]: @lydell Done.

**Comment by lydell** [comment]
This looks really good now!

I just came up with one more test case.

```jsx
function Foo() {
  return <div>
    {/**
   * JSDoc-y comment in JSX. I wonder what will happen to it?
  */}
  </div>
}

**Comment by maxdeviant** [comment]
@lydell It almost gets it.

Comes out looking like this:

```jsx
function Foo() {
  return (
    <div>
      {/**
       * JSDoc-y comment in JSX. I wonder what will happen to it?
       */}
    </div>
  );
}
```

I'll see if I can get it working for that case.

**Comment by lydell** [comment]
Here’s one more case:

```jsx
function Foo({onClick}) {
  return <div
    /**
   * Good ol’ onClick.
  */}
  onClick={onClick}
  />
}
```

**Comment by maxdeviant** [comment]
@lydell It seems like the issue might be somewhere in the JSX printer, which I am not familiar with.

Perhaps this would be a good candidate for a separate PR? I think that JSDoc comments appearing in JSX is a more unlikely scenario. I'd be happy to look at it, but I'd also like to see this PR merged since it fixes a very real issue for myself and lots of others.

**Comment by lydell** [comment]
@maxdeviant I totally agree. Would you mind adding the test cases, though? Then everything looks good to me.

**Comment by maxdeviant** [comment]
@lydell Yea, I can add them. You want them failing, correct?

**Comment by lydell** [comment]
No, I would like them passing. It's fine to make a PR that updates the tests later.

**Comment by maxdeviant** [comment]
@lydell Anything else you would like to see done?

**Comment by azz** [comment]
Awesome! This has been an issue with prettier for ages. Thanks!

**Comment by maxdeviant** [comment]
@azz I encounter the issue multiple times a day, so no one will be happier than me that it's fixed.

Cheers 🎉

**Comment by alexjlockwood** [comment]
Nice! Can't wait to format all my comments. :D

**Comment by lydell** [comment]
> Can't wait to format all my comments.

All _JSDoc-style_ comments.

**Comment by crittelmeyer** [comment]
This doesn't appear to be working for me. Running v1.7.4:
screenshot 2017-10-20 11 57 25
screenshot 2017-10-20 11 57 38

**Comment by vjeux** [comment]
I just wanted to say that this is not what I was thinking about: I wanted to maintain the original indentation. It is even better, it is fixing a ton of mis-indented comments on the fb codebase :)
