### PR TITLE
Fix unstable pair of comments between class methods 

### LINKED ISSUE #8323: Constantly changing comments when formatting.
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwFkBDTANVTgHcAFHCTAZ3wF98AzR9fAchxxSYGAFoopGKgBucUenLM+AbnwB6AFQAdKJHToEBAIwAWfDo1r1G-HoOwjOowAYLVzVbuH8RgMz5LHU0dWwh9bwBOEI0YwKgMbDwA-FJWGFZuMP4YAE9MOGYwHFRMGBUQABoQJiloZmRQUhxGeiaEepRSABsaUhz6qoAjHGEAazgYAGVMYVQoAHNkGBwAVzgqgAsYdC6AdQ3UeGYZsDhJ9sOZQ5zkcGYBtChmODwGUnmFZE5u56qAK2YAA8AEIjMDjKakAwAGTmcC+P3WIABgMmc3mXTgAEUVhB4Aiur8QDMcM8cLdBqRBnAupVicVYLtUAATGAbZAADmcVUwjGeuxGmFuvIKL1kdIAjrj4AwmB0QKlxHA4MyVXTBFLUII3h9SASic90Kglqskcx0ZicXj4UhvoSkTAqUzWeykAAmKrLUioLrogDCYU+KAKAFY6StngAVKkdO1E6RrACSUFVsEmRRKMAAginJrlMfq4Gw2EA)
```sh
--parser babel
```

**Input 1:**
```jsx
import { MapViewProps } from 'react-native-maps'; /*
comment 14 
*/ /* comment1
10
*/ /*/ comment 13 */
/*
 comment 9
 ****/
import * as ts from 'typescript';
```

**Output 1:**
```jsx
import { MapViewProps } from "react-native-maps"; /*/ comment 13 */ /*
comment 14 
*/ /* comment1
10
*/
/*
 comment 9
 ****/
import * as ts from "typescript";

```

**Input 2:**
```jsx
import { MapViewProps } from "react-native-maps"; /*/ comment 13 */ /*
comment 14 
*/ /* comment1
10
*/
/*
 comment 9
 ****/
import * as ts from "typescript";

```

**Output 2:**
```jsx
import { MapViewProps } from 'react-native-maps'; /*
comment 14 
*/ /* comment1
10
*/ /*/ comment 13 */
/*
 comment 9
 ****/
import * as ts from 'typescript';
```

**Expected behavior:**
The outputs should be the same as inputs.

### LINKED ISSUE #8718: Unstable pair of comments between class methods
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgMI7AA6UOZOAtugBQCUhAvjgPQBUOAIjq8y+wKLdmJcpQBGdRiQYkQAGhAQADjACW0TMlDoATjogB3AAq6EmlOlQH0AT00KxO9GADWcGAGUlz1VADmyDA6AK5wCgAWMBSoAOrhqvCY3mBwHmYJqgBuCTbI4NjyIL6YcDowRk5+VMgAZpYlCgBWmAAeAEJOru4e6BRwADK+cLX1YSDNLR6+fqhwAIrBEPAjqA0g3jolOnli6GJwqIVKOr4wMaoAJjDhyAAcAAwKxxAlMU5KecdwW5nDCgCOi3gFWU5hAWAAtFA4HALrDCjo4IDVIiKugqugVmsShRVIEQmNMNNZgslsMkHVVmMYHtzlcbkgAEwKILoVSoaZ4CAUaoob4AVkKwRKABU9uZKWtMqEAJJQOGwDxgE4qACC8o8MBssyxcAYDCAA)
```sh
--parser babel
```

**Input:**
```jsx
class C {
    ma() {} /* D */ /* E */
    mb() {}
}

```

**Output:**
```jsx
class C {
  ma() {} /* E */ /* D */
  mb() {}
}

```

**Expected behavior:**
```jsx
class C {
    ma() {} /* D */ /* E */
    mb() {}
}

```

Note:
- this also applies when `D` and `E` are multi-line comments, as long the comment ends and beginning are on the same line
- if there are more than 2 comments, then they "roll": the last is brought at the beginning each time prettier is run
- this bug looks a bit similar to #5900

### PR DESCRIPTION
**Pull request by fisker**
Fixes #8718
Fixes #8323

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/main/comments.js [hunk 1]
```diff
@@ -342,6 +342,14 @@ function breakTies(tiesToBreak, text, options) {
     }
   });
 
+  for (const node of [precedingNode, followingNode]) {
+    if (node.comments && node.comments.length > 1) {
+      node.comments = node.comments.sort(
```
Comment (thorn0) [inline src/main/comments.js:347]:
```suggestion
      node.comments.sort(
```
`sort` muates the array.
