### PR TITLE
Fix interface extends with long type parameters

### LINKED ISSUE #8941: Ugly formatting for interface extends with long type parameters
from: https://github.com/sosukesuzuki/typescript-eslint/pull/1/files#diff-9d24728f5005799a507ba4b6eba78863R60-R64

**Prettier pr-8821(Current master)**
[Playground link](https://deploy-preview-8821--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgDEIIAeAHSkMIBszGnmXXWoBzAGmtobYGCWnagD5CcAB7woAEwDOhAMoQAtnAAqATwAORYL0LYySQvJiZ0HANzUAvtRBcQEHTFTR5yULkyYIAO4ACr4IXii4dAG4Wl7OAEaY+ADWcDBKOvhWyBYArnDOcKrxcLKypQAyuJy5uBxwpJiquDDunMgguLkwEE4gABYwqnQA6v2o8PKZBEphE6gAbhNaHWDycWhQ8lgwQUkczch4dNvOAFbykgBCSWCp6bjqFehwR5GnIBeSSlZ0cACKuQg8DeJwKIEymG2mA6MF0cHkYEsbj6OkssBGqFkMH6yAAHAAGZxoiDbEZJHQdNEIrALV7OACOQPge1c4U68gAtFA4KVSn1MHAmahBXs6ockMcPttVKgcph8s55L8AczXpL3uCYLh4pjsbikAAmZwWXCoOhWADCaglIARAFY+rlthodeEpeCFvkAJJyBDpJGoNwAQTkSjhf1B2zsdiAA)
```sh
--parser typescript
```

**Input:**
```tsx
interface Foo<
  loooooooooooooooooooooooooooooooooong,
  loooooooooooooooooooooooooooooooooong
> extends SomeType {
  foo: string;
}

```

**Output:**
```tsx
interface Foo<
    loooooooooooooooooooooooooooooooooong,
    loooooooooooooooooooooooooooooooooong
  >
  extends SomeType {
  foo: string;
}

```

**Expected behavior(2.0.5 output):**

```tsx
interface Foo<
  loooooooooooooooooooooooooooooooooong,
  loooooooooooooooooooooooooooooooooong
> extends SomeType {
  foo: string;
}

```

### PR DESCRIPTION
**Pull request by sosukesuzuki**
~~This is based on #8967. We should merge it at first.~~
Fixes #8941

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-js/printer-estree.js [hunk 1]
```diff
@@ -2628,9 +2636,22 @@ function printPathNoParens(path, options, print, args) {
...
+                )
+              )
+            )
+          );
+        } else {
+          parts.push(group(indent(concat(partsGroup.concat(printedExtends)))));
+        }
       } else {
-        parts.push(...partsGroup);
+        parts.push(...partsGroup.concat(extendsParts));
```
Comment (fisker) [inline src/language-js/printer-estree.js:2654]:
```suggestion
        parts.push(...partsGroup, ...extendsParts);
```

**Review by evilebottnawi — APPROVED** [review]

**Comment by fisker** [comment]
Add changelog?

**Comment by sosukesuzuki** [comment]
> Add changelog?

I think no, because it is a change to prevent regression.

**Review by fisker — APPROVED** [review]

**Review by evilebottnawi — APPROVED** [review]
