### PR TITLE
Fix printing of CSS selector() function

### LINKED ISSUE #10291: scss mixin breaks on format if name is "selector"
If a SCSS mixin is named "selector" (maybe other keywords also) and has a default value for a parameter, each format removes the last character of the default value.

**Prettier 2.2.1**

```sh
# Options:
--single-quote
--trailing-comma all
--no-semi
--print-width 120
```

**Input:**

```scss
@mixin selector($param: 'value') {
}
```

**Output:**

```scss
@mixin selector($param: 'value) {
}
```

**Expected behavior:**
Don't remove the last character of the default value...

### PR DESCRIPTION
**Pull request by duailibe**
## Description

Fixes #10291, this is an improvement on #8707

What happens here is that when there's a newline before the closing `)`, the parser reports the `endOffset` of that close group is equal to `startOffset + 1`, which is why the code using `locEnd(node.end) - 1` worked. But when there's no newline the parser reports `startOffset == endOffset`, so using `locEnd(node.end) - 1` gets part of the content of the selector.

The fix is to simply use `locStart(node.end)` which works and is also what we really want (get the slice of original text until the *start* of the close group)

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-css/printer-postcss.js [hunk 1]
```diff
@@ -493,8 +493,8 @@ function genericPrint(path, options, print) {
         grandParent.type === "value-func" &&
         grandParent.value === "selector"
       ) {
-        const start = locStart(parentNode.open) + 1;
-        const end = locEnd(parentNode.close) - 1;
+        const start = locEnd(parentNode.open) + 1;
```
Comment (duailibe) [inline src/language-css/printer-postcss.js:496]: This wasn't really necessary but I think it makes sense to align `locEnd(open)` and `locStart(close)`

**Review by sosukesuzuki — APPROVED** [review]
