### PR TITLE
Fix printing comment for the last operand of union types

### LINKED ISSUE #11910: Last indented list item inline comment is being moved to outer comment and combined with existing comment
**Prettier 2.5.0**
[Playground link](https://prettier.io/playground/?source=post_page---------------------------#N4Igxg9gdgLgprEAuEB6VACAKgTwA5wDKYATgJZ4wZmxwkBmAhmHADpQ3wPNzYAWNAOYBGDMHasYjaUgwAKCTEkAfDAHIYAqCLUZ0GAMIQAtsYQxhiles1CATLv1HT5u4oCUAbQC6Abj2YAGI0jAA2GJAusOwAviAANCAQlGTQAM7IoIwkJBAA7gAK2QgZKGF5jDgZiQBGJMwA1nAwhIxmADI0cMhMoWlwtfVgTS14zELIMCQArgMgcMY1cAAmyyvtjNrTjIJwgRAkxowwMBNl0zAQCSB8MMahAOoC8GljLIQlZKcAbl84yOA0tUQDR+iQYAV6oIjj0wv1EgArNIAD0IQlCcAAitMIPBYX05mMSGCATVGEtQtc8ORYA8yMtNMgABwABkS1Ig-Qe9TwAOpcDB326iQAjjj4JDkqUQIw0gBaKBwFYra4kOBishqyE7GFIXrwkD9YxkSYzOZpdFY8XdPVwuZSGp0hl8ZB2RJTRhkUJCZy6+ZpACs12m-Sw5NK+rm31mAEkoGtYMRyJQAILxwgwHAY-H9GIxIA)

```sh
--parser babel
```

**Input:**

```ts
// TypeScript interface
interface Thing1 {
	aaa: (
		| 'thing1' // Comment1
		| 'thing2' // Comment2
	)[]; // Final comment
}
```

**Output:**

```ts
// TypeScript interface
interface Thing1 {
  aaa: (
    | "thing1" // Comment1
    | "thing2"
  )[]; // Comment2 // Final comment
}

```

**Expected behavior:**
```ts
// TypeScript interface
interface Thing1 {
  aaa: (
    | "thing1" // Comment1
    | "thing2" // Comment2
  )[]; // Final comment
}
```

The placement of `Comment2` in the sample output is the point of concern.

Curiously, using 'flow', 'babel', 'babel-flow' and 'typescript' parsers, the same incorrect output is obtained.

But: when using `babel-ts` as the parser, it seems to generate the expected output.

So, I'm thinking this is a bug in Prettier rather than in the parsers?

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #11910

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-js/comments/handle-comments.js [hunk 1]
```diff
@@ -887,6 +888,44 @@ function handleSwitchDefaultCaseComments({
...
+function handleLastUnionElementInExpression({
+  comment,
+  precedingNode,
+  enclosingNode,
+  followingNode,
+}) {
+  if (
+    precedingNode &&
+    (precedingNode.type === "TSUnionType" ||
+      precedingNode.type === "UnionTypeAnnotation") &&
```
Comment (fisker) [inline src/language-js/comments/handle-comments.js:916]: I don't think tests are using flow parsers. Please add more parsers in the tests.

Comment (sosukesuzuki) [reply src/language-js/comments/handle-comments.js:916]: Thank you, added [9cd628f](https://github.com/prettier/prettier/pull/15409/commits/9cd628f95046a0bc544783331d5313272abc8195)

**Review by fisker — APPROVED** [review]
