### PR TITLE
Use `resolve` if `require.resolve` is overridden

### LINKED ISSUE #8047: Uncaught TypeError: createRequire is not a function
**Environments:**

- Prettier Version: 2.0.4
- Running Prettier via: atom-prettier
- Runtime: ?
- Operating System: Linux, macOS, windows

**Steps to reproduce:**

Please see https://github.com/prettier/prettier-atom/issues/725

Thanks!

### PR DESCRIPTION
**Pull request by fisker**
~This reverts #7508 & #7951~

Fixes #8047

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
No, we shouldn't revert it. Let's just use it if `require.resolve` is broken. Otherwise we'll break https://github.com/prettier/prettier/issues/7407.

**Comment by fisker** [comment]
I missed that.

**Comment by fisker** [comment]
I need go out for couple hours now.

File: src/common/resolve.js [hunk 1]
```diff
@@ -4,9 +4,14 @@ let { resolve } = eval("require");
 
 // In the VS Code extension `require` is overridden and `require.resolve` doesn't support the 2nd argument.
 if (resolve.length === 1) {
-  const Module = eval("require")("module");
-  const createRequire = Module.createRequire || Module.createRequireFromPath;
-  resolve = createRequire(__dirname).resolve;
+  resolve = (id, options) => {
+    let baseDir;
```
Comment (thorn0) [inline src/common/resolve.js:8]: It's all-lowercase: `basedir`

File: src/common/resolve.js [hunk 2]
```diff
@@ -4,9 +4,14 @@ let { resolve } = eval("require");
...
+    if (options && options.paths && options.paths.length === 1) {
+      baseDir = options.paths[0];
+    }
+
+    return require("resolve").sync(id, { baseDir });
```
Comment (thorn0) [inline src/common/resolve.js:13]: With this conditional `require` call, we might face the problem you mentioned [here](https://github.com/prettier/prettier/pull/8036#issuecomment-614620428). We should check how it will look in the bundle, or better think of a way to test this fallback.

File: src/common/resolve.js (hunk 1 above)
Comment (fisker) [reply src/common/resolve.js]: Thanks.

File: src/common/resolve.js (hunk 2 above)
Comment (fisker) [reply src/common/resolve.js]: Don't know, need check dist.

Comment (fisker) [reply src/common/resolve.js]: I was trying to wrote a test couple days ago, but failed.

I tried to override `require.resolve` function before test, and restore after test.

Comment (thorn0) [reply src/common/resolve.js]: Overriding is too complicated. I suggest that we simply use an environment variable to trigger the fallback: `resolve.length === 1 || process.env.PRETTIER_FALLBACK_RESOLVE`.

**Comment by fisker** [comment]
I'm going to disable length check to run a test , so it will always use `resolve`, just make sure we are not breaking things.

File: src/common/resolve.js (hunk 2 above)
Comment (fisker) [reply src/common/resolve.js]: Yes, let's use env to run the test, but before that. I'm going to refactor production test first.

File: .github/workflows/prod-test.yml [hunk 3]
```diff
@@ -131,3 +131,10 @@ jobs:
       - name: Run Tests (standalone) (Linux and Windows)
         if: matrix.os != 'macos-latest'
         run: yarn test:dist-standalone --maxWorkers=2
+
+      # #8073 test
+      - name: Run Tests (PRETTIER_FALLBACK_RESOLVE)
```
Comment (thorn0) [inline .github/workflows/prod-test.yml:136]: We need to change the order of the steps. The coverage report from this run is uploaded to Codecov.

Comment (fisker) [reply .github/workflows/prod-test.yml:136]: I thought they can merge.

Comment (thorn0) [reply .github/workflows/prod-test.yml:136]: Seems like [they can](https://docs.codecov.io/docs/merging-reports) if you upload them separately: run test1, upload report1, run test2, upload report2.

Comment (fisker) [reply .github/workflows/prod-test.yml:136]: Sorry, I know codecov can, I mean jest should.

Comment (thorn0) [reply .github/workflows/prod-test.yml:136]: No, it doesn't do that.

**Comment by fisker** [comment]
@thorn0 I checked the `index.js` file in `dist`,  on L24254

```js
let {
  resolve: resolve$1
} = eval("require");
```

I remember this eval can't run in atom? 

[Link](https://github.com/prettier/prettier/issues?q=is%3Aissue++sort%3Aupdated-desc+atom+eval)

**Comment by fisker** [comment]
`eval('require').cache` used in `third-party.js` because https://github.com/prettier/prettier/blob/ea8330a22fb944bb6a0ccb0ec1546d842db7a97f/scripts/build/config.js#L173

File: src/common/resolve.js [hunk 4]
```diff
@@ -2,11 +2,16 @@
 
 let { resolve } = eval("require");
```
Comment (thorn0) [inline src/common/resolve.js:3]:
```suggestion
let resolve = eval("require").resolve;
```

Comment (fisker) [reply src/common/resolve.js]: I've tried this,  won't work , this will replaced by babel https://github.com/prettier/prettier/blob/master/scripts/build/babel-plugins/transform-custom-require.js
to `require.resolve` , then rollup replace it to `commonJsRequire.resolve`

Comment (fisker) [reply src/common/resolve.js]: I'm not sure, but `global.require.resolve` seems a  good solution.

Comment (thorn0) [reply src/common/resolve.js]: Are you sure? I tested it too locally and it stays this way in `dist/index.js`:
```js
let resolve$1 = require.revolve; // In the VS Code and Atom extension `require` is overridden and `require.resolve` doesn't support the 2nd argument.

if (resolve$1.length === 1 || process.env.PRETTIER_FALLBACK_RESOLVE) {
```

Comment (thorn0) [reply src/common/resolve.js]: `global.require` exists only in the REPL.

Comment (thorn0) [reply src/common/resolve.js]: Strangely. locally ESLint doesn't issue a warning for this line for me. 🤔

Comment (fisker) [reply src/common/resolve.js]: Hmm, I guess I tried `let { resolve } = require;` and`let resolve = eval("require").resolve;`. 

Eslint didn't warn on my machine either, we need add comments and disable the rule on it anyway.

**Comment by thorn0** [comment]
@fisker I think everything is good here. Could you please re-check?

File: src/common/resolve.js [hunk 5]
```diff
@@ -1,12 +1,18 @@
 "use strict";
 
-let { resolve } = eval("require");
+// eslint-disable-next-line prefer-destructuring
+let resolve = eval("require").resolve;
```
Comment (fisker) [inline src/common/resolve.js:4]: We should add comment explain why this is disabled, because this can't understand `/scripts/build/babel-plugins/transform-custom-require.js` 

I'm not near my laptop, can you do this?

**Comment by fisker** [comment]
Everything should be good, thanks. Will you fix this https://github.com/prettier/prettier/pull/8072#issuecomment-616482737 ?

**Comment by thorn0** [comment]
Is it broken? I thought that replacement happens for a reason.

File: src/common/resolve.js (hunk 5 above)
Comment (thorn0) [reply src/common/resolve.js:4]: ok

**Comment by fisker** [comment]
I remember you  add it ? I don't know if it can run in atom , I just saw it in `third-party.js`

**Comment by thorn0** [comment]
It wasn't me. I fixed only this thing: https://github.com/prettier/prettier/pull/7820

**Comment by fisker** [comment]
#5558 add it, if  it's true  that atom  can't run  eval , we  need fix it.

**Comment by thorn0** [comment]
Okay. I'm downloading Atom. :D

**Comment by fisker** [comment]
Can you also check if it support `new Function("return this")()`? 

I believe it's also used.

**Comment by fisker** [comment]
I'm  going to sleep, good luck!

**Comment by fisker** [comment]
@thorn0 I tested in atom, both prettier files and `prettier.config.js` file can run `eval`.

**Comment by thorn0** [comment]
I haven't been able to reproduce problems with `eval` and `new Function` in Atom. However, I confirmed that the fallback from this PR works there.

**Comment by fisker** [comment]
And I logged `console.log({global, require})` in our source, and played with it in console

```js
temp2.global.require
ƒ require(path) {
    try {
      exports.requireDepth += 1;
      return mod.require(path);
    } finally {
      exports.requireDepth -= 1;
    }
  }


temp2.require
ƒ require(e){return n.require(e)}


temp2.global.require.resolve
ƒ resolve(request, options) {
    if (typeof request !== 'string') {
      throw new ERR_INVALID_ARG_TYPE('request', 'string', request);
    }
    return Module._resolveFilename(request, mod, false, op…


temp2.require.resolve
ƒ (e){return get_Module()._resolveFilename(e,n)}
```

`global.require.resolve` looks like the native `require.resolve`

**Comment by thorn0** [comment]
The native `require.resolve` should have 2 parameters.

**Comment by thorn0** [comment]
It's not native. `Module._resolveFilename` that it calls has `length === 2` and ignores `options`. Execute `debugger; global.require.resolve('a', {paths:['b']})` to explore that function in the debugger.
