### PR TITLE
JavaScript: Support Smart and F#-style Pipeline

### LINKED ISSUE #6162: Pipeline operator: support Smart & F# proposals
**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBWABAHwHzoMToBU6ATCADQgQAOMAltAM7KgCGATuxAO4AKHCZilYA3CHQAmFEACN2rMAGs4MAMrUFdKAHNkMdgFc4lABYwAtgBsA6ibrxGGsHFWD7dEfYCeycI2aUWoxw7DC88trmrMgAZqyWwZQAVowAHgBC8koqqqzmcAAyWnCx8YkgKamqWtqWcACKBhDwpQnGIBrswey+MqwyXpbQ0tTsWjDWkjAmyAAcAAyUoxDB1vLUvqNw3SIllACOTfDhNEIgrIwAtFBwcBJ30uxwh3RP4ayR0UhxbZTB5nQ9IZ2owanVGs0St8yu0YP1JhJpsgSJR9Kw6JYagBhCDmKK+KDQPYgAzBAAq-SEP2CAF8aUA)
```sh
--parser babylon
```

**Input:**
```jsx
5 |> # * 2
```

**Output:**
```jsx
SyntaxError: Unexpected character '#' (1:6)
> 1 | 5 |> # * 2
    |      ^
```

**Expected behavior:**
The minimal proposal is supported, not the smart one (which is far more convenient)

image

### PR DESCRIPTION
**Pull request by sosukesuzuki**
Fix #6162 

Support [Smart Pipeline](https://github.com/js-choi/proposal-smart-pipelines) and [F#-style Pipeline](https://github.com/valtech-nyc/proposal-fsharp-pipelines).

[More about those proposals ("What's Happening With the Pipeline (`|>`) Proposal?")](https://babeljs.io/blog/2018/07/19/whats-happening-with-the-pipeline-proposal).

**Smart Pipeline:**
```js
// Input
5 |> # * 2

// Output (Prettier Stable)
SyntaxError: Unexpected character '#' (1:6)
> 1 | 5 |> # * 2
    |      ^

// Output (Prettier master)
5 |> # * 2
```

**F#-style Pipeline:**
```js
// Input
promises |> await;

// Output
SyntaxError: Unexpected token (1:18)
> 1 | promises |> await
    |                  ^

// Output (Prettier master)
promises |> await;
```

ref: #7953

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-js/parser-babylon.js [hunk 1]
```diff
@@ -52,19 +51,59 @@ function createParse(parseMethod, extraPlugins) {
     const combinations = [
       babelOptions(
         { strictMode: true },
-        ["decorators-legacy"].concat(extraPlugins)
+        [
+          "decorators-legacy",
+          ["pipelineOperator", { proposal: "minimal" }]
+        ].concat(extraPlugins)
```
Comment (duailibe) [inline src/language-js/parser-babylon.js]: This is bad. I added that as an escape-hatch until I could figure out a decent way to detect which decorator plugin to apply.

This is likely cause a noticeable performance degradation, when there's a simple syntax error.

Comment (thorn0) [reply src/language-js/parser-babylon.js]: @sosukesuzuki Why not always use `proposal: 'smart'`?

Comment (sosukesuzuki) [reply src/language-js/parser-babylon.js]: The `smart` is compatible with `minimal`, but it is coincidental. For example, the same problem will occur again when we try to support `fsarp`.

So, I considered generally solution...

File: CHANGELOG.unreleased.md [hunk 2]
```diff
@@ -261,6 +261,24 @@ useEffect(
 
 This version updates the TypeScript parser to correctly handle JSX text with double slashes (`//`). In previous versions, this would cause Prettier to crash.
 
+#### JavaScriot: Support Smart Pipeline ([#6319] by [@sosukesuzuki])
```
Comment (fisker) [inline CHANGELOG.unreleased.md]:
```sugestion
#### JavaScript: Support Smart Pipeline ([#6319] by [@sosukesuzuki])
```

File: src/language-js/parser-babylon.js (hunk 1 above)
Comment (thorn0) [reply src/language-js/parser-babylon.js]: As far as I understand, we'll need to check **only** `smart` and `fsharp` then. Why check `minimal`?

**Comment by evilebottnawi** [comment]
In theory we can use babel api to detect plugin, if no plugins found use `minimal`

**Comment by thorn0** [comment]
Or we can suppress reparsing attempts if the file doesn't contain the substring `|>`.

**Comment by duailibe** [comment]
@thorn0 That would be ideal

**Comment by mAAdhaTTah** [comment]
I helped implement the Smart & F# proposals in Babel. Is there anything I can do to help this land?

**Comment by thorn0** [comment]
@mAAdhaTTah Is there a quick and dirty way (like a regex) to detect which proposal was used in given code without full parsing?

**Comment by mAAdhaTTah** [comment]
@thorn0 Not that I can think of. Does prettier read the Babel config? That's probably the most reliable source of which pipeline operator is in use.

File: src/language-js/parser-babylon.js (hunk 1 above)
Comment (mAAdhaTTah) [reply src/language-js/parser-babylon.js]: `smart` is not compatible w/ `minimal`, so that's not a safe assumption. `x |> foo()` is invalid in `smart` but valid in `minimal`.

**Comment by thorn0** [comment]
That's the problem, it doesn't read it. And we'd like to avoid that as Prettier's configuration story is already complicated enough.

File: src/language-js/parser-babylon.js (hunk 1 above)
Comment (thorn0) [reply src/language-js/parser-babylon.js]: Oh, I see now. That's really unlucky.

Comment (thorn0) [reply src/language-js/parser-babylon.js]: Oh, I see now. That's really unlucky. Hopefully Babel's error recovery might help here.

If it doesn't help, I'm going to make Prettier try using each proposal until the input parses. To avoid overhead, this logic will be used only if the input contains the substring `|>`.

**Comment by mAAdhaTTah** [comment]
@thorn0 How was this resolved for decorators? Similar approach, or was there something about the various decorator proposals that make this not an issue?

**Comment by thorn0** [comment]
@mAAdhaTTah The error recovery works really beautifully for decorators. Previously, we had to iterate through different option combinations to find the working one, but now (since v1.19) Prettier even supports different decorator variants within one file.

**Comment by mAAdhaTTah** [comment]
@thorn0 Cool alright, if there's anything I can do to adjust the error handling in Babel, let me know, but it might works as-is for this.

**Comment by thorn0** [comment]
`foo |> bar()` works ([playground][1]), even though `proposal` is set `smart`.
But it doesn't recover from `f#` proposal syntax: `foo |> await |> bar` ([playground][2]) and `foo |> bar => bar` ([playground][3]).


[1]: https://deploy-preview-6319--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAzCEAEAfAfJgIwEMAnACgEoQAaECABxgEtoBnZUUkiAdwAVSCdiiIAbHkQCe7WgRJEwAazgwAyvQVMoAc2QwSAVzi0AFjAC2ogOomm8VhrBxVQu0wBudycnCsZILVY4Ehg+eW1zImRUMSDaACtWAA8AIXklFVUiczgAGS04aNjjEESk1S1tUTgARQMIeCLROJANEiCSH2ICOFEaVpItGCsmABMYE2QADgAGWnpuIKt5eh8FuA73QtoAR3r4MIZhECJWAFooODhR6-6SOD2me7CiCKikGOaSoPMmPUNvpVqnUGoUPsVaDAiAQRuNJkgAEyQ+RMUSVADCEHMkR8GwArP0DEEACrQ4SfFruIwASSgN1gqjAg0YAEE6aoYJJqk0ggBfXlAA
[2]: https://deploy-preview-6319--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAzCEAEAfAfJgQwHcCBLGHfAIwICcQAaECABxlOgGdlQ7aIiABToJuKAgBsSAT25MqtAmADWcGAGUWS0lADmyGLQCucJgAsYAWwkB1M+TictYOOtHlSAN3LTk4TnIgOpxwtDCCirqWBMiokiFMAFacAB4AQooqauoElnAAMjpwsfGmIMkp6jq6EnAAikYQ8CUSCSBatCH0KDRUcBKM7bQ6MDakACYwZsgAHAAMTCz8ITaKLH5LjqGexUwAjo3wEaxiIAScALRQcHDjt4O0cAekjxEEUTFIca1lIZakBmMv2qtQaTWKX1KTBgBCoY0m0yQACZoYpSBJqgBhCCWaJ+RwAVkGRhCABVYWJvm1PCYAJJQO6wdRgYZsACCDPUMGktRaIQAvvygA
[3]: https://deploy-preview-6319--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAzCEAEAfAfJgIwEMAnTAXn2JJABoQIAHGAS2gGdlRSSIB3AAqkEnFEQA2fIgE9O9AiSJgA1nBgBlRkpZQA5shgkArnHoALGAFtxAdTMt47LWDjqRDlgDcH05OHZyIDrscCQwAoq6lkTIqBIh9ABW7AAeAEKKKmrqRJZwADI6cLHxpiDJKeo6uuJwAIpGEPAl4gkgWiQhNCjEBHDidO0kOjA2LAAmMGbIABwADPSMvCE2iox+S3BdnsX0AI6N8BFMoiBE7AC0UHBw47eDJHAHLI8RRFExSHGtZSGWLAZjL9qrUGk1il9SvQYEQCGNJtMkAAmaGKFjiaoAYQglmifi2AFZBkYQgAVWGib5tTwmACSUDusHUYGGzAAggz1DBpLUWiEAL78oA

**Comment by thorn0** [comment]
@mAAdhaTTah Could make those errors recoverable, please?

**Comment by mAAdhaTTah** [comment]
@thorn0 I will look into that!

File: src/language-js/needs-parens.js [hunk 3]
```diff
@@ -561,6 +570,16 @@ function needsParens(path, options) {
 
     case "ArrowFunctionExpression":
       switch (parent.type) {
+        case "PipelineTopicExpression":
+          return !!(node.extra && node.extra.parenthesized);
+
+        case "BinaryExpression":
+          return !!(
+            node.operator === "|>" &&
```
Comment (thorn0) [inline src/language-js/needs-parens.js:578]:
```suggestion
            parent.operator === "|>" &&
```

**Comment by thorn0** [comment]
The memory problem happens because `resolvePluginsConflict` repeatedly modifies the same array, so it becomes huge.

File: src/language-js/needs-parens.js [hunk 4]
```diff
@@ -561,6 +579,20 @@ function needsParens(path, options) {
...
+        case "BinaryExpression":
+          if (node.extra && node.extra.parenthesized) {
+            return (
+              parent.operator === "|>" ||
+              (parent.operator !== "|>" &&
+                node.body.type === "BinaryExpression" &&
+                node.body.operator === "|>")
+            );
+          }
+          return false;
```
Comment (thorn0) [inline src/language-js/needs-parens.js:594]: This leads to a bug:

**Prettier pr-6319**
[Playground link](https://deploy-preview-6319--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAKVAPAlAAgLwB8O2OA1DgOQUDcIANCBAA4wCW0AzsqAIYBOfCAHcACvwRcUPADZCeATy4MARnx5gA1nBgBlJutZQA5shh8ArnAYALGAFtpAdWut4HfWDg6Jr1gDdXeWRwDiUQQw44PhgRNSM7HmQAMxlIhgArDgwAITVNbR0eOzgAGUM4ZNSrEEyMHUMjaTgARXMIeErpNJB9Pki+YJh5JjgOMD5WFnoeidhHVgATGGtkAA4ABgYmQUjHNSZg7dGovwqGAEc2+FjmSRAeDgBaKDg4BbfpvjhL1i-YnniiSQKS61UidlYpgsYIaTVa7QqwKqDBgPGU8yWKyQACYUWpWNIGgBhCB2BLBUYAVmm5kiABU0ZIQd0-JYAJJQd6wHTjSYwACCnJ0QyanUiAF9xUA)
```sh
--parser typescript
```

**Input:**
```tsx
((x) => x) + '';
```

**Output:**
```tsx
(x) => x + "";

```

File: src/language-js/parser-babel.js [hunk 5]
```diff
@@ -44,16 +43,41 @@ function babelOptions(extraPlugins = []) {
...
+) {
+  const combinations = [...pluginCombinations];
+  if (condition) {
+    for (const combination of pluginCombinations) {
+      for (const plugin of conflictPlugins) {
+        combinations.push([...combination, plugin]);
+      }
+    }
+  }
+  return combinations;
```
Comment (thorn0) [inline src/language-js/parser-babel.js:59]: Let's say the input combinations are `[["jsx", "typescript"], ["typescript"]]`, in that case the output will be:
```js
[
  ["jsx", "typescript"],
  ["typescript"],
  ["jsx", "typescript", ["pipelineOperator", { proposal: "smart" }]],
  ...
]
```
Why do we need the first two elements in this list?

**Comment by sosukesuzuki** [comment]
CI have been failed since merge this PR(https://github.com/prettier/prettier/actions/runs/72609997). It caused by that `tests_integration/__tests__/piped-output.js` test failing. I'm not sure why it happens...

**Comment by kachkaev** [comment]
Hey folks sorry for a late comment here. Just a question on:

```
- [Link to the 'smart' pipeline proposal](https://github.com/js-choi/proposal-smart-pipelines)
```

Any reason to link to the fork (67 stars) instead of https://github.com/tc39/proposal-pipeline-operator (4.8K stars)? If no specific reasons, WDYT of changing the link in the [2.1 blog post](https://prettier.io/blog/2020/08/24/2.1.0.html)? while it's fresh?

**Comment by thorn0** [comment]
@kachkaev There are three different pipeline operator proposals: "minimal" (the one you linked to), "f#", and "smart".
