### PR TITLE
Fix line break in CSS declaration with comma

### LINKED ISSUE #6024: When box-shadow has multiple values (separated by comma) it'd be prettier to put each value on a separate line
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjCAPAtAZwBYCGAJhAO5IA6UABNQAwAOG1AjE-RwMQBmvANFVqNmAJnZ0ucKQG4qIPiAgMYAS2g5koAgCdtZAAo6EGlAQBuEFUXlptBMAGs4MAMoN7KqAHNkMbQFc4BTwYAFsAGwB1PBV4HHcwOBdjWJUzWIBPZHAcDQVPHDhtGH07L1CCZG4CcMKFACscDAAhO0dnFwJQuAAZTzgqmrqQRowXTy9wuABFfwh4QdqgkHdtQu1ssFybBm1PGEirGDxkAA46BV2IQsi7BmzduHWzAYVtOABHfxV30oJyypIapLBSFUIqXwBZY4CZTWbzAZAobLGAEVCHIjHZAiBR+AgqcITADCEFCFWyUGgrxA-kKABU0SZgYUAL4soA)
```sh
--parser css
```

**Input:**
```css
box-shadow:
  0px 1px 0 0 #fff,
  0px 2px 0 0 #eee;
```

**Output:**
```css
box-shadow: 0px 1px 0 0 #fff, 0px 2px 0 0 #eee;

```

**Expected behavior:**
```css
box-shadow:
  0px 1px 0 0 #fff,
  0px 2px 0 0 #eee;
```

When each value is on a separate line, the whole value feels significantly easier to read.

### PR DESCRIPTION
**Pull request by mvorisek**
## Description

Comma in CSS/LESS declaration/value is used to separate group of multiple values of the same meaning.

Currently line break is enforced in selectors like:
```
h1,
h2 {
    ...
}
```

but not for CSS values like:
```
box-shadow: -1px -1px 2px rgba(0, 0, 0, 0.3), 1px -1px 2px rgba(0, 0, 0, 0.3), -1px 2px 2px rgba(0, 0, 0, 0.3);
```

this PR fixes/unifies the behaviour by enforcing line break after comma in CSS declaration/value.

fix #6024, #7039, #8462
close #13260

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-css/printer-postcss.js [hunk 1]
```diff
@@ -924,12 +924,18 @@ function genericPrint(path, options, print) {
...
+            parentParentParentNode.variable);
+
         const printed = path.map(print, "groups");
-        const res = [];
+        const res = forceHardLine ? [hardline] : [];
 
         for (let i = 0; i < printed.length; i++) {
           if (i !== 0) {
-            res.push([",", line]);
+            res.push([",", forceHardLine ? hardline : line]);
```
Comment (mvorisek) [inline src/language-css/printer-postcss.js:938]: how to fix this lint warning?

Comment (mvorisek) [reply src/language-css/printer-postcss.js:938]: @fisker can you please advise how to fix the lint error?

Comment (fisker) [reply src/language-css/printer-postcss.js:938]: This may work https://github.com/prettier/prettier/blob/310a5b1ba51ad6a3115670058d53a7ecb1dcd25c/src/language-js/printer-estree.js#L193

Comment (mvorisek) [reply src/language-css/printer-postcss.js:941]: Thank you 👍

**Comment by fisker** [comment]
@mvorisek Please check discussion in #6024 and https://github.com/prettier/prettier/issues/6024#issuecomment-1216191051

**Comment by mvorisek** [comment]
I support your https://github.com/prettier/prettier/issues/6024#issuecomment-1209617651 as the wrapping rule should be easy to understand and not dependent on the content IMHO

**Comment by fisker** [comment]
But I agree line breaks in case like [this](https://github.com/prettier/prettier/pull/14208/files#diff-34c9c87dc127dbc18ddefebdc2f51062bb3cace4a73fe78ade1af6ac383c99d0L23) seems unnecessary.

**Comment by mvorisek** [comment]
https://github.com/prettier/prettier/issues/6024#issuecomment-1216191051 proposed to wrap if 2 or more spaces are present in any comma list item.

Where does the 2 spaces come from? What about wrapping when there is at least 1 space?

My reason for 1 space is it will solve the main problem and with zero spaces, any list is well readable on one line/unchanged.

**Comment by mvorisek** [comment]
implemented in 2nd/3rd commit, CSS declarations like `font-family: Arial, sans-serif;` or `$margin: 0, 2em, 0, 1.5em;` are kept on a single line

thank you @fisker for guiding me into the right direction

**Review by fisker — APPROVED** [review]
LGTM

File: src/language-css/printer-postcss.js [hunk 2]
```diff
@@ -924,12 +926,27 @@ function genericPrint(path, options, print) {
...
+          (parentParentParentNode.type === "css-atrule" &&
+            parentParentParentNode.variable);
+        if (forceHardLine) {
+          forceHardLine = false;
+          for (let i = 0; i < node.groups.length; i++) {
+            if (node.groups[i].type === "value-comma_group") {
+              forceHardLine = true;
+            }
+          }
+        }
```
Comment (fisker) [inline src/language-css/printer-postcss.js:941]:
```suggestion
    const forceHardLine =
      parentParentParentNode.type === "css-decl" ||
      (parentParentParentNode.type === "css-atrule" &&
        parentParentParentNode.variable &&
        node.groups.some(
          (node) => node.groups[i].type === "value-comma_group"
        ));
```

Same?

**Comment by mvorisek** [comment]
Hi @fisker, can this PR be merged?

**Comment by fisker** [comment]
Need more reviews.

**Comment by fisker** [comment]
@prettier/core Need review.

**Review by j-f1 — APPROVED** [review]
Nice improvement!

**Comment by mvorisek** [comment]
@fisker there are more review now, would it be possible to merge this PR so it can be part of the next release?

File: tests/format/scss/comments/__snapshots__/jsfmt.spec.js.snap [hunk 3]
```diff
@@ -224,16 +224,23 @@ selector {
 // #8052
 $font-family-rich:
   // custom
-  "Noto Sans TC", "Noto Sans SC", "Noto Sans JP",
+
```
Comment (jerone) [inline tests/format/scss/comments/__snapshots__/jsfmt.spec.js.snap:227]: Empty line intentional?

Comment (mvorisek) [reply tests/format/scss/comments/__snapshots__/jsfmt.spec.js.snap]: Perfect, thank you ❤️

**Comment by fisker** [comment]
Thank you for your hard work!

**Comment by fisker** [comment]
Excluded custom props for now, but it should allow. Not sure how to fix, 

```
:root {
  --box-shadow:
    inset 0 0 10px #555,
    0 0 20px black;
  box-shadow: var(--box-shadow);
}
```

**Comment by mvorisek** [comment]
> Excluded custom props for now, but it's wrong. Not sure how to fix,

Can you link the fix PR here?

I am not entirely sure what the expected result should be for JSON, I would probably expect the same JSON format as in standard JSON/JS.

**Comment by fisker** [comment]
Commit: https://github.com/prettier/prettier/pull/9583/commits/8ddaa4c53645298a327176a479ac497f8ce5e3b7

> what the expected result should be for JSON

Should stay as-it-is.

**Comment by alex-kinokon** [comment]
This seems a bit too aggressive, see #15070.

**Comment by viveleroi** [comment]
We're using the postcss-modules plugin, which apparently doesn't support multiple lines for `composes`. When prettier rewrites this into multi-line it causes postcss to throw an error.

`composes: body-copy, text-ellipsis from global;`

Error: `referenced class name "body-copy" in composes not found`

But with the inline format above, it works fine. Maybe this is something that the modules plugin needs to support? For now I just use `/* prettier-ignore */` above the line
