### PR TITLE
fix(css): comments in selectors

### LINKED ISSUE #2686: SCSS Selector List with Comments loses code, causes syntax error
[Playground Link](https://prettier.io/playground/#%7B%22content%22%3A%22.field%20%7B%5Cn%20%20%26%5Bdata-field-id%3D%5C%221%5C%22%5D%2C%20%2F%2F%20Name%5Cn%20%20%26%5Bdata-field-id%3D%5C%222%5C%22%5D%2C%20%2F%2F%20Email%5Cn%20%20%26%5Bdata-field-id%3D%5C%223%5C%22%5D%2C%20%2F%2F%20Postal%20Code%5Cn%20%20%7B%5Cn%20%20%20%20background%3A%20green%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

Input:

```sass
.field {
  &[data-field-id="1"], // Name
  &[data-field-id="2"], // Email
  &[data-field-id="3"], // Postal Code
  {
    background: green;
  }
}
```

Output:
```sass
.field {
  &[data-field-id="1"],
  // Name &[data-field-id="2"],
  // Email &[data-field-id="3"] {
    background: green;
  }
}
```

This is a serious problem, as it is invalid CSS syntax and comments out many of the selectors.

### PR DESCRIPTION
**Pull request by evilebottnawi**
Fixes #2686

Issue about best comment places https://github.com/prettier/prettier/issues/3905

Also small restructure comments tests

### CODE REVIEW

File: src/language-css/parser-postcss.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ function parseSelector(selector) {
   if (selector.match(/\/\/|\/\*/)) {
     return {
       type: "selector-comment",
-      value: selector
+      value: selector.replace(/^ +/, "").replace(/ +$/, "")
```
Comment (lydell) [inline src/language-css/parser-postcss.js]: Just checking: DO you intentionally only replace spaces, or did you mean to remove other whitespace as well?

Comment (evilebottnawi) [reply src/language-css/parser-postcss.js]: @lydell remove only spaces, it is temporary hack because we don't parse selectors with comments, after we make sure that we do not eat comments and determine their position it will be deleted

Comment (lydell) [reply src/language-css/parser-postcss.js]: I see! 👍

Comment (evilebottnawi) [reply src/language-css/parser-postcss.js]: @lydell approve? :smile:
