### PR TITLE
Fix markdown inserts unexpected newline in lists

### LINKED ISSUE #8004: Markdown inserts unexpected newline in lists
If I insert a newline between two top-level list elements, a newline is also inserted between the first top-level element and its children elements (unexpectedly, to my eye).

```
- Top level item 1
  - Nested item 1
  - Nested item 2
  
- Top level item 2
```

becomes

```
- Top level item 1

  - Nested item 1  // (spurious newline inserted above ^)
  - Nested item 2
  
- Top level item 2
```

I insert the newline between "Nested item 2" and "Top level item 2" intentionally, to keep the the top level items visually distinct, but the effect is slightly ruined by prettier's addition of a newline between "Top level item 1" and "Nested item 1".

That extra insertion doesn't make sense to me, and appears to be a bug.

Playground link is here: [https://prettier.io/playground/#...](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAUQB4Ac5jwAmAOlGQLToAqEu6ANnAG5wPoCW8AtugIxl06KgDk4AZ2Kce-QcPRjJcItLi8ATJRp1GLNqo1kyGAKpQ4eAsSNQqtek1bsua2VCGiJUl7z7oAFACu5paEyujmAO4MHOboAIa4+PEATuIJAEYQrOgAegCUcp5KKj7omu7oWva6TgblIAA0IHQwHNDiyKCpKRCRAAqpCJ0o8QyR8QCenc0ZKfFgANZwMADKuAuxAObIMCmBcM0AFjDcDADqRy7iG2Bwq8NcHMxck8jg4jMgseJwKTD9eZbbjxZAAMzGv2aACtxNgAELzJYrVbxbhwAAysTg4MhhxAsOwq22TAAioEIPBcQwoSANmk-u8QSlFkQ+lAmnSUrEYOcOEQYEdkAAOAAMzVwvV+53muHekokf1YnIAjhT4IC6CMQPFxBRzMplJyUnA1RwTYD4sDQUgITT8b9uBxdvsHSS4OTKTjbXjmjB4hk+QKhUh1H75hwYlAtgBhCDcEHvCQAVk5gV+1ADIzttOYBwAklAiAg1mBubgYABBIurGCTJjU34AXybQA)

### PR DESCRIPTION
**Pull request by byplayer**
## Description

I fix markdown inserts unexpected newline in lists.

This issue is reported the below link.
https://github.com/prettier/prettier/issues/8004

Fixes #8004

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)(not change).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`(not change).
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by barcell1** [comment]
+ 1 on this

File: src/language-markdown/printer-markdown.js [hunk 1]
```diff
@@ -675,7 +675,9 @@ function shouldPrePrintDoubleHardline({ node, previous, parent }, options) {
   const isSequence = previous.type === node.type;
   const isSiblingNode = isSequence && SIBLING_NODE_TYPES.has(node.type);
   const isInTightListItem =
-    parent.type === "listItem" && !isLooseListItem(parent, options);
+    parent.type === "listItem" &&
+    (node.type === "list" ||
+      (node.type !== "list" && !isLooseListItem(parent, options)));
```
Comment (jacksteamdev) [inline src/language-markdown/printer-markdown.js:680]:
```typescript
    parent.type === "listItem" &&
      (node.type === "list" ||
        (node.type !== "list" && // is always true
           !isLooseListItem(parent, options)));
```

The condition can be simplified since the `node.type !== "list"` check is redundant - if the first part of the OR (`node.type === "list"`) is false, then `node.type !== "list"` will always be true. Due to short-circuit evaluation, we can remove this redundant check while maintaining the same logic.

```suggestion
    parent.type === "listItem" &&
      (node.type === "list" || !isLooseListItem(parent, options));
```

I hope this PR can be reviewed and merged soon! 🤞

**Review by jacksteamdev — APPROVED** [review]
LGTM, one minor observation.

File: src/language-markdown/printer-markdown.js (hunk 1 above)
Comment (byplayer) [reply src/language-markdown/printer-markdown.js]: I fix it.
Thank you.

**Comment by jacksteamdev** [comment]
@thorn0 Thanks for helping maintain this project! I noticed that you triaged #8004, is there any possibility this high-quality PR could get reviewed by a Prettier maintainer?

**Review by fisker — APPROVED** [review]

**Review by sosukesuzuki — APPROVED** [review]

**Comment by mikaello** [comment]
It may be a regression when combined with fenced code blocks and nested lists:

Before this PR:

````markdown
1. Some text, and code block below

   ```yaml
   ---
   foo: bar
   ```

   1. Another
   2. List
````

After this PR, notice removed newline after code block:

````markdown
1. Some text, and code block below

   ```yaml
   ---
   foo: bar
   ```
   1. Another
   2. List
````

This is at least in conflict with [MD031](https://github.com/DavidAnson/markdownlint/blob/main/doc/md031.md) for those using markdownlint.

**Comment by fisker** [comment]
Can you open a new issue?

**Comment by mikaello** [comment]
> Can you open a new issue?

Sure: https://github.com/prettier/prettier/issues/17652
