### PR TITLE
Avoid creating node_modules/.cache when --cache is not enabled

### LINKED ISSUE #13032: node_modules/.cache/prettier
I use Yarn PnP and therefore do not usually have a node_modules folder and instead have a .yarn folder. After prettier 2.7, when I run my `prettier --write .` command, I now get a node_modules folder with the only contents being: node_modules/.cache/prettier. Can we move the cache location inside the .yarn folder or somewhere besides node_modules when using pnp?

**Environments:**

- Prettier Version: 2.7.1
- Running Prettier via: CLI
- Runtime: Node.js v17.9.0
- Operating System: macOS
- Prettier plugins (if any): none

**Steps to reproduce:**
run `prettier --write .`

**Expected behavior:**
No node_modules folder and Prettier cache location somewhere in .yarn folder.

**Actual behavior:**
Created a node_modules folder with the following cache: node_modules/.cache/prettier

### PR DESCRIPTION
**Pull request by chiawendt**
## Description

fixes #13032

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: src/cli/find-cache-file.js [hunk 1]
```diff
@@ -8,8 +8,7 @@ import { isJson, statSafe } from "./utils.js";
  * Find default cache file (`./node_modules/.cache/prettier/.prettier-cache`) using https://github.com/sindresorhus/find-cache-directory
  */
 function findDefaultCacheFile() {
-  const cacheDir =
-    findCacheDirectory({ name: "prettier", create: true }) || os.tmpdir();
+  const cacheDir = findCacheDirectory({ name: "prettier" }) || os.tmpdir();
```
Comment (fisker) [inline src/cli/find-cache-file.js]:
```suggestion
  const cacheDir = findCacheDirectory({ name: "prettier" }) ?? os.tmpdir();
```

File: changelog_unreleased/cli/18124.md [hunk 2]
```diff
@@ -0,0 +1,3 @@
+#### Avoid creating node_modules/.cache when --cache is not enabled (#18124 by @chiawendt)
+
+Running `prettier .` without `--cache` no longer creates an empty `node_modules/.cache`.
```
Comment (fisker) [inline changelog_unreleased/cli/18124.md]:
```suggestion
#### Avoid creating `node_modules/.cache/` directory when `--cache` is not enabled (#18124 by @chiawendt)

Run `prettier .` without `--cache` no longer creates an empty `node_modules/.cache/` directory.
```

File: tests/integration/__tests__/cache.js [hunk 3]
```diff
@@ -57,6 +57,18 @@ describe("--cache option", () => {
...
+    await runCliWithoutGitignore(dir, ["--cache", "*.js"]);
+    await expect(fs.stat(defaultCacheFile)).resolves.not.toThrow();
+  });
+
+  it("doesn't create cache directory without --cache", async () => {
+    await runCliWithoutGitignore(dir, ["*.js"]);
+    await expect(
+      fs.stat(path.join(dir, "node_modules/.cache")),
+    ).rejects.toHaveProperty("code", "ENOENT");
+  });
```
Comment (fisker) [inline tests/integration/__tests__/cache.js:70]:
```suggestion
  it("creates cache file with --cache", async () => {
    await runCliWithoutGitignore(dir, ["--cache", "a.js"]);
    await expect(fs.stat(defaultCacheFile)).resolves.not.toThrow();
  });

  it("doesn't create cache directory without --cache", async () => {
    await runCliWithoutGitignore(dir, ["a.js"]);
    await expect(
      fs.stat(path.join(dir, "node_modules/.cache")),
    ).rejects.toHaveProperty("code", "ENOENT");
  });
```

**Comment by chiawendt** [comment]
Thanks

**Comment by fisker** [comment]
@chiawendt Do you think we should avoid calling this function when there is no `--cache`


https://github.com/prettier/prettier/blob/6c92f7ea5412abe443e8c45ca715af83ee24bb6b/src/cli/format.js#L287

**Comment by fisker** [comment]
Closed by accident

**Comment by chiawendt** [comment]
This is still needed when `--cache=false`, because we need to delete the cache directory according to docs:  

https://prettier.io/docs/cli#--cache

> Running Prettier without --cache will delete the cache.

**Comment by fisker** [comment]
Okay, but it doesn't make sense. Since a user can run without `--cache` but give a fake cache location.

I recall I want to remove the cache removal, but a team member said that he will look into it.

**Comment by fisker** [comment]
https://github.com/prettier/prettier/pull/15330

**Comment by chiawendt** [comment]
True
