### PR TITLE
Ignore .git, .svn and .hg directories

### LINKED ISSUE #4895: prettier traverses .git files and tries to format them
**Environments:**
- Prettier Version: 1.13.7
- Running Prettier via: CLI
- Runtime: node v8.9.4, npm v5.6.0, yarn v1.5.1
- Operating System: Linux

**Steps to reproduce:**
- In a git repository with `prettier` installed
- Create a git branch that ends in `.js`
- Run `prettier --write '**/*.js'`

I created a repository with everything ready to reproduce ([link](https://github.com/gillchristian/prettier-report)).

**Expected behavior:**
`.git/` directory should be ignored, `prettier` should run without errors.

**Actual behavior:**
`.git/` directory is traversed in files and `prettier` throws syntax error (obviously because `.git/` files aren't JS files).

---

I'm aware of #2882 but `.git/*` files are still parsed.

Also, I'm up to work on opening a PR solving this issue. But I believe it's better to ask first.

### PR DESCRIPTION
**Pull request by azz**
Don't really see a compelling case for a CLI argument for this.

Fixes #4895

> Note: Can't actually add a `.git` test because git ignores the files 😉

### CODE REVIEW

File: src/cli/util.js [hunk 1]
```diff
@@ -403,6 +403,7 @@ function eachFilename(context, patterns, callback) {
   if (ignoreNodeModules) {
     patterns = patterns.concat(["!**/node_modules/**", "!./node_modules/**"]);
   }
+  patterns = patterns.concat(["!**/.{git,svn,hg}/**", "!./.{git,svn,hg}/**"]);
```
Comment (ikatyang) [inline src/cli/util.js]: It seems the `!./.{git,svn,hg}/**` part is unnecessary, and so does `!./node_modules/**`.

```sh
$ tree test
test
├── dir
│   ├── node_modules
│   │   └── x.js
│   └── x.js
├── node_modules
│   └── x.js
└── x.js

$ node -e 'console.log(
  require("globby").sync(
    ["**/*.js", "!**/node_modules/**"],
    { cwd: "test" }
  )
)'
[ 'dir/x.js', 'x.js' ]
```

Comment (azz) [reply src/cli/util.js]: #2185

Comment (azz) [reply src/cli/util.js]: Try re-running that with `./**/*.js` as the glob.

Comment (ikatyang) [reply src/cli/util.js]: Cool, didn't know that. Can you add a comment for it?

Comment (azz) [reply src/cli/util.js]: Sure.
