### PR TITLE
Print comments for parenthesized TS keyword types

### LINKED ISSUE #11660: TypeScript conditional types: Comment "TEST" was not printed. Please report this error!
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACGATwzjwFUoB3bAQwxIBMAlOAZwFcAbGJiSgHgAqAPjwBePMAA6UPHLwBtAAp4AlrIDWcQhABmeQQF0keABQz5lg8sN508KA1Z4WAR37rdcbHhqiA-GYWViE0wSEAlHgm5rIhVoI2dmgOTngA8hgwHlBePgBGAUFx8fH54aV4UTEVlfIA9PUGAKIAyoK1dXhQcABu3p2Rg1UVEQDcMgC+E1AgADQgEFmq0KzIoDTY2HxKmwhrKDSclDSEawv5tGBaMK0YNGDqAObIMNjscAtwALb5cAwMf4AGRoUCe7BoTzgADEcN8aDAYM9kCAaOwYBB5iAABYwb6cADq2NU8FY9zAcFa+xJql6JMIKLArHOIHUrG8MCUtCe8OQuiO7IWACtWGhWs9OHAAIrsCDwPkCz4ge7YdnYFFEEisMDYVRZLEYXWwAmqBgwbHIACMACYAAwLQ0QdkE2gYFGGtjefpY1yy+BcpYHVGsAC0PX+-yx2DgvtU0a5kN5SH5nEFIHZ31Ur3eStYEulfrgCtTSpgNHyJrNFqQ1oWbxoqk4zwAwhBvknUKwAKxY9jswTlg4ptO9D4ASUcCFuOr1MAAgo5WkRJcX2ZNJkA)

```sh
--parser typescript
--print-width 120
```

**Input:**

```tsx
export type UnwrappedResultRow<T> = {
    [P in keyof T]: (
        T[P] extends Req<infer a> ? (
            a
        ) : (
            T[P] extends Opt<infer b> ? (
                b
            ) : (
                // TEST
                never
            )
        )
    );
};

```

**Output:**

```tsx
Error: Comment "TEST" was not printed. Please report this error!
    at Object.ensureAllCommentsPrinted (https://prettier.io/lib/standalone.js:36:106741)
    at xd (https://prettier.io/lib/standalone.js:36:113165)
    at Nd (https://prettier.io/lib/standalone.js:36:115668)
    at Object.formatWithCursor (https://prettier.io/lib/standalone.js:76:39916)
    at formatCode (https://prettier.io/worker.js:141:21)
    at handleMessage (https://prettier.io/worker.js:78:26)
    at self.onmessage (https://prettier.io/worker.js:36:14)
```

**Expected behavior:**

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #11660

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-js/loc.js [hunk 1]
```diff
@@ -19,10 +35,20 @@ function locStart(node, opts) {
     }
   }
 
+  if (parser === "babel-ts" && tsKeywordTypes.has(node.type)) {
+    return node.start;
```
Comment (sosukesuzuki) [inline src/language-js/loc.js:39]:
```ts
const foo: (
  // comment
  never
);
```

In the above code, `start` and `end` of the `TSNeverKeywordType`  are `9` and `33` but `range` is `[11, 35]`. `range` includes parens. So in this case we should prefer `start`.

However, I'll investigate if this can be fixed in `@babel/parser` side.

File: changelog_unreleased/javascript/12070.md [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+   // comment
+   never
+);
+
+// Prettier stable
+Error: Comment "comment" was not printed. Please report this error!
+
+// Prettier main
+let foo: // comment
+never;
```
Comment (sosukesuzuki) [inline changelog_unreleased/javascript/12070.md:16]: This is still ugly, but at least it can be printed.

**Comment by fisker** [comment]
Can this fixed from here https://github.com/prettier/prettier/blob/2213e1719691b3f2da9dc7f00f1c9f0f8d0ae54a/src/language-js/parse/postprocess/index.js#L19?

File: src/language-js/loc.js (hunk 1 above)
Comment (fisker) [reply src/language-js/loc.js:39]: I think this is not caused by babel,we only use(and modify) `.range`, we must updated the range to wrong value.

File: src/language-js/parse/postprocess/index.js [hunk 3]
```diff
@@ -79,7 +95,9 @@ function postprocess(ast, options) {
       }
       // remove redundant TypeScript nodes
       case "TSParenthesizedType": {
-        node.typeAnnotation.range = [locStart(node), locEnd(node)];
+        if (!tsKeywordTypes.has(node.typeAnnotation.type)) {
+          node.typeAnnotation.range = [locStart(node), locEnd(node)];
```
Comment (sosukesuzuki) [inline src/language-js/parse/postprocess/index.js:99]: This is required for some formatting (See https://github.com/prettier/prettier/blob/main/tests/format/misc/typescript-babel-only/prettier-ignore-nested-unions.ts and https://github.com/prettier/prettier/blob/main/tests/format/misc/typescript-babel-only/prettier-ignore-parenthesized-type.ts). But `TSParenthesizedType` is no longer supported by `typescript-estree`. So we can remove this?

File: src/language-js/parse/postprocess/index.js [hunk 4]
```diff
@@ -6,6 +6,22 @@ const { isTypeCastComment } = require("../../comments.js");
 const visitNode = require("./visitNode.js");
 const { throwErrorForInvalidNodes } = require("./typescript.js");
 
+const tsKeywordTypes = new Set([
```
Comment (fisker) [inline src/language-js/parse/postprocess/index.js:9]: Use a set is good, but I changed print logic to handle future types in printer before, maybe we should reuse the same logic? https://github.com/prettier/prettier/blob/2213e1719691b3f2da9dc7f00f1c9f0f8d0ae54a/src/language-js/print/typescript.js#L61 

I'm not on my laptop, I didn't checked, but I remember we have a function `isSimpleType` or something, maybe should do the same too.

Comment (sosukesuzuki) [reply src/language-js/parse/postprocess/index.js:9]: Yes we have `isSimpleType` function. I know `isSimpleType` but I didn't know about `if(node.type.endsWith("Keyword")) {...}`...

Comment (fisker) [reply src/language-js/parse/postprocess/index.js:9]: Here is the context https://github.com/prettier/prettier/pull/10869#issuecomment-840688577

**Comment by fisker** [comment]
Will it improve the output if we do

```js
expression.extra = { ...expression.extra, parenthesized: true };
```

?

File: src/language-js/parse/postprocess/index.js (hunk 3 above)
Comment (fisker) [reply src/language-js/parse/postprocess/index.js:89]: If we remove this, will it output ugly?

Comment (sosukesuzuki) [reply src/language-js/parse/postprocess/index.js:89]: Maybe yes, in some formats in `babel-ts`

Comment (sosukesuzuki) [reply src/language-js/parse/postprocess/index.js:89]: I reconsidered. Let's keep this. It is possible to remove it in v3, but we shouldn't do it here.

**Review by fisker — APPROVED** [review]
