### PR TITLE
Fix extra semicolon in ambient typescript declaration emit (#2165)

### LINKED ISSUE #2165: Ambient typescript declaration emitting extra semicolon
In an ambient declaration, typescript pretty printing emits an extra, invalid semicolon:

input:
```ts
declare module "classnames" {
  export default function classnames(...inputs: (string | number | false | object | undefined)[]): string;
}
```

output:
```ts
declare module "classnames" {
  export default function classnames(
    ...inputs: (string | number | false | object | undefined)[]
  ): string;;
}
```
live example: https://prettier.github.io/prettier/#%7B%22content%22%3A%22declare%20module%20%5C%22classnames%5C%22%20%7B%5Cn%20%20export%20default%20function%20classnames(...inputs%3A%20(string%20%7C%20number%20%7C%20false%20%7C%20object%20%7C%20undefined)%5B%5D)%3A%20string%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

error in the typescript compiler:
https://www.typescriptlang.org/play/index.html#src=declare%20module%20%22classnames%22%20%7B%0A%20%20%20%20export%20default%20function%20classnames(%0A%20%20%20%20%20%20%20%20...inputs%3A%20(string%20%7C%20number%20%7C%20false%20%7C%20object%20%7C%20undefined)%5B%5D%0A%20%20%20%20)%3A%20string%3B%3B%0A%7D%0A

### PR DESCRIPTION
**Pull request by stephen**
Closes #2165

### CODE REVIEW

File: tests/typescript_ambient/ambient.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
+declare module "classnames" {
+  export default function classnames(...inputs: (string | number | false | object | undefined)[]): string;
```
Comment (vjeux) [inline tests/typescript_ambient/ambient.ts]: Is it possible to have a body {} instead of ; ?

Comment (stephen) [inline tests/typescript_ambient/ambient.ts]: body is not allowed in an ambient declaration. (i.e. `declare module "..."`). here's a [failing ts build](https://www.typescriptlang.org/play/index.html#src=declare%20module%20%22classnames%22%20%7B%0A%20%20%20%20export%20default%20function%20classnames(%0A%20%20%20%20%20%20%20%20...inputs%3A%20(string%20%7C%20number%20%7C%20false%20%7C%20object%20%7C%20undefined)%5B%5D%0A%20%20%20%20)%3A%20string%20%7B%20return%20%22string%22%3B%20%7D%0A%7D%0A): 
```tsx
declare module "classnames" {
    export default function classnames(
        ...inputs: (string | number | false | object | undefined)[]
    ): string { return "string"; }
}
```
> An implementation cannot be declared in ambient contexts.

**Comment by vjeux** [comment]
Awesome, thanks!
