### PR TITLE
Fix comments inside map

### LINKED ISSUE #11918: [SCSS] comments in Map-value mixin arguments break the code
**Prettier 2.5.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AhgcwLQwBZwC2c2ARugDZ7qEAEwAOlLS7QAICWUYFArgCZxaWXAWJlK1QgAomrebVnMFKgGYQATnEwaIvKP2yQKmpLQAkYXgGcYEQtnVadeg0YgmNAGjkqF-Dmt0Ugo4QydtXX1DY1NaKF4KCi9aAHpU2gAVAHkAEWzaa3shSEJiWF8VAEpK2iqAbiYAXxAvEAgABxgOaGtkUHQNXQB3AAVBhD6USmH0AE8+ttINdDAAazgYAGUaOAAZLjhkVUprOCWV9c2tjtWuTGQYDV5zkCJSMMF+PfQoTF4sHAAGKaQjoGDdP7IEDoXh2VogPAwQgUADqeA48GstzAcC2k0xHAAbpi5tCwNZFiAuGcNDBRitMGDjqdXgArawADy291CAEVeBB4CyKGc2rcNLTodYKVSOhouDBURx+PhkAAOAAM4t0Z1RKw60PlcFpRKObQAjoL4AzOlMYdZsFA4GEwgitFaOFoGVhmUgTqLXmdCBxHs8g7y4AKhUd-ay2jBgsrVXhkAAWBMrDgUe4AYXsfre1gArAibHBMsEpgGxSAiS8AJIGBDbMAKroAQQMWxgc1CIrOTSaQA)

```sh
--parser scss
--tab-width 4
```

**Input:**

```scss
.ag-theme-balham {
    @include ag-theme-balham(
        (
            foreground-color: $custom-foreground-color,
            disabled-foreground-color: null, // TODO some comment
        )
    );
}
```

**Output:**

```scss
.ag-theme-balham {
    @include ag-theme-balham(
        (
            foreground-color: $custom-foreground-color,
            disabled-foreground-color: null,
            r: null, // TODO som
        )
    );
}

```

**Expected behavior:**

The code should be untouched, not adding any new entries and keeping the whole content of the comment.

```scss
.ag-theme-balham {
    @include ag-theme-balham(
        (
            foreground-color: $custom-foreground-color,
            disabled-foreground-color: null, // TODO some comment
        )
    );
}

### PR DESCRIPTION
**Pull request by fisker**
## Description

Fixes #11918

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-css/parser-postcss.js [hunk 1]
```diff
@@ -554,7 +554,8 @@ function parseNestedCSS(node, options) {
         // Remove unnecessary spaces in SCSS variable arguments
         params = params.replace(/(\$\S+?)\s+?\.{3}/, "$1...");
         // Remove unnecessary spaces before SCSS control, mixin and function directives
-        params = params.replace(/^(?!if)(\S+)\s+\(/, "$1(");
+        // Move spaces after the `(`, so we can keep the range correct
+        params = params.replace(/^(?!if)(\S+)(\s+)\(/, "$1($2");
```
Comment (alexander-akait) [inline src/language-css/parser-postcss.js:558]: We have very dirty solutions... Bu I agree, it is impossible to fix right now, so let's merge

**Review by alexander-akait — APPROVED** [review]

File: src/language-css/parser-postcss.js (hunk 1 above)
Comment (fisker) [reply src/language-css/parser-postcss.js:558]: The line above this may also cause problems, but let's wait for someone to report 😄 

Hope this trick won't break other cases.

**Review by duailibe — APPROVED** [review]

**Comment by fisker** [comment]
Found a case, so we can also move the spaces after `...`

**Prettier 2.5.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAllMAbArgEzgAIAjAQwCciAKAHSiMaIoHNy6GmBWABiPqZFe-TowB0wgdz6DZ4sWKmMA9MqKQAthoQwpASnp6QAGhAQADjHTQAzslCUKEAO4AFSgjsoy2Z2QCedqYkFGRgANZwMADKZNoAMphwyABmPjZwwaERUdHmYZgsyDAUuJkgcBokcPiE+PFkUCy4ZCxwAGIQFBpkMFZNyCBkuDAQJiAAFjAa2ADqE+jwNvlgcNGei+gAbov+g2A2QSCYGRQwrqEsPanp5QBWNgAe0YXYcACKuBDwN9gZpvkKKdBjYDkdzBRMDBZuh8DAJsgABw8AFODKzULmQYQuCnLbJUwARy+8AuFi8QxsAFooHAajVxhQ4MT0EyLq1rkg0n9yhkNOhiqVea8PiTklzbqYYGQSDC4QikAAWKWhdDYQoAYQgWjIg1xXHGuAyABUZV5uf8QFsygBJKCEWDRMCQywAQXt0Rg-jevwyAF8-UA)

```sh
--parser scss
--tab-width 4
```

**Input:**

```scss
@include bar (
    rgba(
    50 
    50 
    .50 
    50            ...
    // comment
  )
)
```

**Output:**

```scss
@include bar(
    rgba(
        50 50 0.5 50...  // commen
    )
);

```

**Review by sosukesuzuki — APPROVED** [review]

**Review by duailibe — APPROVED** [review]
