### PR TITLE
fix(multiparser): fix markdown error and remove trailing new line

### LINKED ISSUE #3292: Can't use template tag called "markdown"
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbAhgJwNYBMIDuUABgMQAEAFnADY0TEgA0IEADjAJbQDOyo6HjGQAzdDR5wWAI0zow2ODADKbeZygBzZDEwBXKSHxhR4ySw2TMMAApzNGUxMMArHgA8AQnIVLl6VDgAGQ04J3NWPRg2KIAmcMM1TCtkEGl0aQBPeihmEDZMDRgAdU5cGEpkAA4ABhYCiEliuTYdfUNMOABHPU5Ou3QHdASWSVRONoNRjU0aOABFPQh4EZAYDNLyyqRYll10ThoZgGEIVEcUKGgwlj1JABUMviQxZwBfN6A)

**Input:**
```jsx
markdown`# hello`
```

**Output:**
```jsx
TypeError: Cannot read property '1' of null
```

**Expected behavior:**
```jsx
markdown`# hello`
```

### PR DESCRIPTION
**Pull request by ikatyang**
Fixes #3292

### CODE REVIEW

File: src/printer-markdown.js [hunk 1]
```diff
@@ -66,9 +66,10 @@ function genericPrint(path, options, print) {
 
   switch (node.type) {
     case "root":
-      return normalizeDoc(
-        concat([printChildren(path, options, print), hardline])
-      );
```
Comment (ikatyang) [inline src/printer-markdown.js]: The original output did not match the input of `stripTrailingHardline`.
