### PR TITLE
Fix chained logical expressions with objects/array/etc inlined

### LINKED ISSUE #2714: Chained Short Circuit Conditionals in JSX
Just upgraded to 1.6.1 and noticed that chained "short circuit" conditionals no longer get indented. Is this intentional? 

**v1.5.3**
```js
const Foo = (bar, baz) =>
  <div>
    {bar &&
      baz &&
      <span>hello there. make this long enough to wrap to the next line</span>}
  </div>
```

**v1.6.1**
```js
const Foo = (bar, baz) => (
  <div>
    {bar &&
    baz && (
      <span>hello there. make this long enough to wrap to the next line</span>
    )}
  </div>
)
```

### PR DESCRIPTION
**Pull request by duailibe**
Fixes #2714 (though the issue isn't only with JSX expressions)

I believe the heuristics are correct now, but the code got a pretty ugly and I don't have that much experience with this codebase. I hope I can get some guidance on how to improve that huge if expression :-)

### CODE REVIEW

**Comment by vjeux** [comment]
cc @duailibe

**Comment by duailibe** [comment]
Did you mean @suchipi ? :-)

File: src/printer.js [hunk 1]
```diff
@@ -339,18 +339,22 @@ function genericPrintNoParens(path, options, print, args) {
...
+
+      if (
+        willBreakRegardless ||
+        (shouldInlineLogicalExpression(n) && n.left.type !== n.type) ||
+        (!shouldInlineLogicalExpression(n) &&
+          (parent.type === "AssignmentExpression" ||
+            parent.type === "VariableDeclarator" ||
+            parent.type === "ObjectProperty" ||
+            parent.type === "Property"))
       ) {
```
Comment (duailibe) [inline src/printer.js]: Maybe it would be clearer to if written like:

```js
const willBreak =
  parent.type === "ReturnStatement" ||
  (parent.type === "JSXExpressionContainer" &&
    parentParent.type === "JSXAttribute") ||
  (n === parent.body && parent.type === "ArrowFunctionExpression") ||
  (n !== parent.body && parent.type === "ForStatement") ||
  parent.type === "ConditionalExpression";

const wontBreak =
  parent.type === "AssignmentExpression" ||
  parent.type === "VariableDeclarator" ||
  parent.type === "ObjectProperty" ||
  parent.type === "Property";

const shouldGroup =
  willBreak ||
  (shouldInlineLogicalExpression(n) ? n.left.type !== n.type : wontBreak);

if (shouldGroup) {
  return group(concat(parts));
}
```

 Not sure about the naming though =P

**Comment by vjeux** [comment]
Yeahh... oops sorry!

**Comment by suchipi** [comment]
I'll take a look tonight 😄

File: src/printer.js (hunk 1 above)
Comment (suchipi) [reply src/printer.js]: I think what you put in your comment is more readable, so let's update the code to use it, instead.

What do you think of renaming `shouldGroup` to `shouldNotIndent`?

Also, I think we should change `n.type` in your `shouldGroup` declaration to `"LogicalExpression"`. These are equivalent, but using the literal is more clear in my opinion.

I also don't feel like `wontBreak` and `willBreak` are the right names, but I don't quite understand the difference between them. Could you elaborate on that a bit?

File: src/printer.js [hunk 2]
```diff
@@ -339,18 +339,22 @@ function genericPrintNoParens(path, options, print, args) {
       }
 
       // Avoid indenting sub-expressions in assignment/return/etc statements.
```
[the remark this answers is not in the document]
Comment (duailibe) [reply src/printer.js]: You're right. It still avoids indenting sub-expressions but might be valuable to specify when. I'll update it

File: src/printer.js (hunk 1 above)
Comment (duailibe) [reply src/printer.js]: > What do you think of renaming shouldGroup to shouldNotIndent?
>
> Also, I think we should change n.type in your shouldGroup declaration to "LogicalExpression". These are equivalent, but using the literal is more clear in my opinion.

Looks good to me

> I also don't feel like wontBreak and willBreak are the right names, but I don't quite understand the difference between them. Could you elaborate on that a bit?

I'm not sure what the names should be either. What I tried to mean is that the `willBreak` cases don't need to be indented regardless, e.g.:

```js
return (
  condition &&
  condition
);
// "condition &&" will be in a new line regardless of having a inlined logical expression
return (
  condition && [
    element
  ]
);
```

The `wontBreak` cases are the ones where it won't "break" to new lines if they should inline the logical expression, where otherwise it would:

```js
const var =
  foo &&
  bar;
// and when inlining it won't break anymore
const var = foo && [
  element
];```

Comment (duailibe) [reply src/printer.js]: Naming is hard 😅 so I'll happily accept naming suggestions :)

**Comment by duailibe** [comment]
@suchipi I updated according to your suggestions, let me know what you think!

File: src/printer.js [hunk 3]
```diff
@@ -338,19 +338,28 @@ function genericPrintNoParens(path, options, print, args) {
...
+
+      const shouldIdentIfInlining =
+        parent.type === "AssignmentExpression" ||
+        parent.type === "VariableDeclarator" ||
         parent.type === "ObjectProperty" ||
-        parent.type === "Property" ||
-        parent.type === "ConditionalExpression"
+        parent.type === "Property";
+
+      const logicalSubExpressionExists = n.left.type === "LogicalExpression";
```
Comment (suchipi) [inline src/printer.js]: You don't use this variable anywhere; did you mean to use it to replace the `n.left/type !== n.type` [on line 361](https://github.com/prettier/prettier/pull/2770/files#diff-76f26752c3761490942405c0704a8e1dR361)?

File: src/printer.js [hunk 4]
```diff
@@ -338,19 +338,28 @@ function genericPrintNoParens(path, options, print, args) {
...
+      // idented accordingly. We should ident sub-expressions where the first case isn't idented.
+      const shouldNotIdent =
         parent.type === "ReturnStatement" ||
         (parent.type === "JSXExpressionContainer" &&
           parentParent.type === "JSXAttribute") ||
         (n === parent.body && parent.type === "ArrowFunctionExpression") ||
         (n !== parent.body && parent.type === "ForStatement") ||
+        parent.type === "ConditionalExpression";
+
+      const shouldIdentIfInlining =
```
Comment (suchipi) [inline src/printer.js]: :+1: makes sense now. These names + the comment make it a lot easier to understand.

File: src/printer.js (hunk 3 above)
Comment (duailibe) [reply src/printer.js]: Oops my bad!!

Comment (duailibe) [reply src/printer.js]: I'll update this. Are you ok with this name?
