### PR TITLE
Fix loading ESM-style shared config file in Node.js 23

### LINKED ISSUE #16812: ESM Shared Configurations Incompatible with Node v23
**Environments:**

- Prettier Version: 3.3.3
- Running Prettier via: CLI
- Runtime: Node v23 (23.0.0 and 23.1.0 tested)
- Operating System: Linux
- Prettier plugins (if any):
    - `@prettier/plugin-xml`
    - `prettier-plugin-packagejson`
    - `prettier-plugin-organize-imports`
    - `prettier-plugin-sh`

**Steps to reproduce:**

1. Create a basic shared config project as described in ["Sharing Configurations"](https://prettier.io/docs/en/sharing-configurations). The specific configuration or plugins don't matter, but the config object should be exposed via `export default`.
1. Create a stub project, and install your shared config proejct created above. In `package.json` add the `"prettier": "@scope/project"` configuration.
1. Run `npx node@23 node_modules/.bin/prettier --check --log-level debug .`.

**Expected behavior:** Prettier should load the shared config and print errors in project files, as it would with `npx node@22 ...`. 

**Actual behavior:** Prettier fails to load the options from the shared configuration and every file checked emits a warning:

```txt
[debug] loaded options `{"__esModule":true,"default":{"plugins":["@prettier/plugin-xml","prettier-plugin-packagejson","prettier-plugin-organize-imports","prettier-plugin-sh"],"printWidth":100,"tabWidth":4,"singleQuote":true,"proseWrap":"always","vueIndentScriptAndStyle":true,"xmlWhitespaceSensitivity":"ignore","organizeImportsSkipDestructiveCodeActions":true,"overrides":[{"files":"**/*.y?(a)ml?(.dist)","options":{"tabWidth":2}},{"files":["CHANGELOG.md","husky/_/**/*"],"options":{"requirePragma":true}}]}}`
[warn] Ignored unknown option { __esModule: true }.
[warn] Ignored unknown option { default: { plugins: ["@prettier/plugin-xml", "prettier-plugin-packagejson", "prettier-plugin-organize-imports", "prettier-plugin-sh"], printWidth: 100, tabWidth: 4, singleQuote: true, proseWrap: "always", vueIndentScriptAndStyle: true, xmlWhitespaceSensitivity: "ignore", organizeImportsSkipDestructiveCodeActions: true, overrides: [{ files: "**/*.y?(a)ml?(.dist)", options: { tabWidth: 2 } }, { files: ["CHANGELOG.md", "husky/_/**/*"], options: { requirePragma: true } }] } }.
```

**Cause:**

[Node 23 made changes to `require`](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V23.md#2024-10-16-version-2300-current-rafaelgss) and where Node 22 [required a flag to import ESM modules with `require`](https://nodejs.org/docs/latest-v22.x/api/modules.html#loading-ecmascript-modules-using-require), Node 23 [enabled this by default](https://nodejs.org/api/modules.html#loading-ecmascript-modules-using-require).

Since `ERR_REQUIRE_ESM` is no longer thrown without the `--experimental-require-module` flag, we never get down to [explicitly handling ESM modules](https://github.com/prettier/prettier/blob/3e4b452b4a1f93049e2758a83b0eddf6334f180a/src/config/prettier-config/load-external-config.js#L25). Instead, `requireFromFile` ends up returning the ESM module wrapped up as:

```js
{
  __esModule: true,
  default: { /* The actual shared config. */ }
}
```

**Solution:**

- For backwards compatibility, we should leave the existing error handling strategy in.
- For foreward compatibility, we should check if `process.features.require_module` is set to `true` inside the `try` block [here](https://github.com/prettier/prettier/blob/3e4b452b4a1f93049e2758a83b0eddf6334f180a/src/config/prettier-config/load-external-config.js#L17). If so, and `requireFromFile(...).__esModule` is `true`, return `requireFromFile(...).default` instead of the result of `requireFromFile(...)` itself.

**Workaround:**

- Don't use Node 23! :sweat_smile:
- But if you must, pass `--no-experimental-require-module`. You can also add this to your environment's `NODE_OPTIONS` for convenience.

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #16812

I don't add tests for this change due to https://github.com/jestjs/jest/issues/15363, but I was able to test it locally.

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Have you tried esm module with TLA? It should be broken too.

File: src/config/prettier-config/load-external-config.js [hunk 1]
```diff
@@ -15,7 +15,16 @@ async function loadExternalConfig(externalConfig, configFile) {
...
+    // Since Node.js v23 onwards, it is possible to load ESM using require.
+    // If that feature is enabled, it is necessary to return the default.
+    // https://github.com/prettier/prettier/issues/16812
+    // FIXME: We want to add tests but https://github.com/jestjs/jest/issues/15363 blocks
+    // @ts-expect-error
+    if (process.features.require_module && required.__esModule) {
+      return required.default;
+    }
+    return required;
   } catch (/** @type {any} */ error) {
```
Comment (fisker) [inline src/config/prettier-config/load-external-config.js:28]: Maybe simply use `required?.default ?? required`?    https://github.com/babel/babel/issues/16441

**Comment by sosukesuzuki** [comment]
>  Have you tried esm module with TLA? It should broken too.

Thanks, https://github.com/prettier/prettier/pull/16857/commits/3244020856392d6af9d5029fe752830650caf66f addresses the case.

File: src/config/prettier-config/load-external-config.js (hunk 1 above)
Comment (sosukesuzuki) [reply src/config/prettier-config/load-external-config.js:29]: I prefer the current code. Because if the option had a `default` field, it would be used. I know that such a case rarely happens, but it's not that complicated code, so I prefer to be conservative.

**Review by fisker — APPROVED** [review]
