### PR TITLE
Fix multiparser on playground

### LINKED ISSUE #3404: [playground] Parsers not loaded for multiparser
In the playground, we only load the parsers when necessary so that means the `format` may fail when we switch parsers in the playground. For that reason we have the following code:

https://github.com/prettier/prettier/blob/e09359d2428bdac40c30cd6a82c92a627d1e1d05/website/static/worker.js#L98-L104

But after the multiparser refactor in #3370 we no longer have the `parser` property in the exception:

https://github.com/prettier/prettier/blob/e09359d2428bdac40c30cd6a82c92a627d1e1d05/src/printer.js#L125-L137

This fails on the playground ([link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucBnVADDBuEAaECABxgEtpVlQBDAJ1ogHcAFOhSlagNwlIBN8IaqhjIAZtQA2qOAQBGtamADWcGAGUiS0lADmyGLQCuskHwhhxUmQR0zaMZot0BbalemmAVqgAeAIUUVNXVqFzgAGR04DxtCIxgiBIAmWNMtWntkEDlqOQBPSWhBIlodGAB1fhgAC2QADgAGAlKIGQrFImzSuHsuGIJaOABHI1Ihp2pXdyQJTwIZF1IDY1NUHV1JOABFIwh4NIIYPKq+WuRko8VSSQ2AYQgXN2yoaAGQIxkAFTyOOZkAL4AoA)):

```js
css``;
```

If you change the parser to css/less/scss, then go back to babylon, it starts working.

I'm not sure how to fix this with the current architecture of the multiparser. We'd have to have multiple try/catch around the code

### PR DESCRIPTION
**Pull request by duailibe**
Fixes #3404, supersedes #3406

### CODE REVIEW

File: website/static/worker.js [hunk 1]
```diff
@@ -26,7 +26,17 @@ self.require = function require(path) {
...
   }
-  return self[path.replace(/.+-/, "")];
+
+  if (~path.indexOf("parser-")) {
+    var parser = path.replace(/.+-/, "");
+    if (!parsersLoaded[parser]) {
+      importScripts("lib/parser-" + parser + ".js");
+      parsersLoaded[parser] = true;
+    }
+    return self[parser];
```
Comment (azz) [inline website/static/worker.js]: Is this actually defined? If it works it's a good solution

Comment (duailibe) [reply website/static/worker.js]: As I understand the previous code, that's exactly how it was working before. We called `importScripts` below just for this to work `return self[path.replace(/.+-/, "")]`

Comment (duailibe) [reply website/static/worker.js]: It's a bit hackish, since it requires knowledge of the `moduleName` in the rollup config
