### PR TITLE
fix(typescript): properly chain when there is a TSNonNullExpression

### LINKED ISSUE #3999: TS: `!` confuses prettier
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOhhAawQBkIBDAE1wHM4YAKAGwjDPwCcBKHWhrGMuxjcADgFcsaesAC+nANwAdKMvTY8hEuSo86TFmwhcAhLr4ChoiVNkKQAGhAQRMDNCzJQg9hADuABUEEDxQyADcIDAoHEDJ+ZAAzMkYsOEcAI3YyMCIYAGURbIwoamQYdjE0kAoWROTUx2LUoX8s6gBbMjqUqoArLAAPACEsnLo8sna4YmK4boanMRhxGAAmearC9mbkVABPETgsMHYMFxiRU9gAdSj0ZAAOAAZHS4hU66yRXcujuHYwnNHOw4ABHMQYEGtMgdLpIJI9RypdoYMoVKpYYrURhwACKYgg8A2jgE6VuFHuSFWJKyGEYWIAwhB2p1dlBoECQBI4AAVMjpEII1IyGRAA)
```sh
--parser typescript
```

**Input:**
```tsx
this.tokenLoads.get(locator).get(start).push({});

this.tokenLoads.get(locator)!.get(start).push({});
```

**Output:**
```tsx
this.tokenLoads
  .get(locator)
  .get(start)
  .push({});

this.tokenLoads.get(locator)!.get(start).push({});

```

**Expected behavior:**
```tsx
this.tokenLoads
  .get(locator)
  .get(start)
  .push({});

this.tokenLoads
  .get(locator)!
  .get(start)
  .push({});

```

### PR DESCRIPTION
**Pull request by ericanderson**
Fixes #3999

When encountering a `TSNonNullExpression`, don't abort the chain. Just include it with the current group.

### CODE REVIEW

File: src/language-js/printer-estree.js [hunk 1]
```diff
@@ -3800,6 +3800,9 @@ function printBindExpressionCallee(path, options, print) {
   return concat(["::", path.call(print, "callee")]);
 }
 
+function printNonNullExpression() {
```
Comment (j-f1) [inline src/language-js/printer-estree.js]: Why did you abstract this out?

**Comment by ericanderson** [comment]
It seemed like when things were done more than once, they were abstracted. More than happy to just use a string literal.

**Comment by j-f1** [comment]
I think that’s a better idea, given that this is just `"!"`, not something more complicated.

**Comment by duailibe** [comment]
Thanks for contributing! :tada:
