### PR TITLE
Fix binary op as body in arrow expression

### LINKED ISSUE #919: Binary operations as body of an arrow expression need parentheses
Righteously mentioned by @bakkot in https://github.com/prettier/prettier/pull/913#issuecomment-284464885, all of the following test cases should be handled correctly:

```js
a = () => ({} && a);
a = () => ({}() && a);
a = () => ({} && a && b);
a = () => ({} + a);
a = () => ({}()() && a);
a = () => ({}.b && a);
a = () => ({}[b] && a);
a = () => ({}`` && a);
a = () => ({} = 0);
a = () => ({}, a);
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22a%20%3D%20()%20%3D%3E%20(%7B%7D%20%26%26%20a)%3B%5Cna%20%3D%20()%20%3D%3E%20(%7B%7D()%20%26%26%20a)%3B%5Cna%20%3D%20()%20%3D%3E%20(%7B%7D%20%26%26%20a%20%26%26%20b)%3B%5Cna%20%3D%20()%20%3D%3E%20(%7B%7D%20%2B%20a)%3B%5Cna%20%3D%20()%20%3D%3E%20(%7B%7D()()%20%26%26%20a)%3B%5Cna%20%3D%20()%20%3D%3E%20(%7B%7D.b%20%26%26%20a)%3B%5Cna%20%3D%20()%20%3D%3E%20(%7B%7D%5Bb%5D%20%26%26%20a)%3B%5Cna%20%3D%20()%20%3D%3E%20(%7B%7D%60%60%20%26%26%20a)%3B%5Cna%20%3D%20()%20%3D%3E%20(%7B%7D%20%3D%200)%3B%5Cna%20%3D%20()%20%3D%3E%20(%7B%7D%2C%20a)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

### PR DESCRIPTION
**Pull request by yamafaktory**
This should fix #919 🤞.

### CODE REVIEW

**Comment by bakkot** [comment]
I don't think this quite works. One sec, will edit this comment...

**Comment by yamafaktory** [comment]
I can also fix #917.

**Comment by yamafaktory** [comment]
@bakkot thanks for the feedback, I will refactor it in order to fix all these test cases 👍 .

**Comment by bakkot** [comment]
@yamafaktory Added a similar mega-test to #917, which you should check out if you're working on that one too.

**Comment by yamafaktory** [comment]
This is not done yet, there are other cases that need to be handled correctly in order to digest your **mega-tests**.

**Comment by yamafaktory** [comment]
@bakkot now this should be better 🚀.

**Comment by bakkot** [comment]
Progress! But not quite there yet.

----

This is still missing at least

```js
a => ({}().c = 0)
```

and
```js
a => ({}::b())
```
and (re: #917)
```js
({}::b, 0);
```

Possibly other cases as well; those are just from experimenting a little.

----

I'm really uncomfortable with all of these cases statements in `needsParens` falling through :| It makes it really hard to tell if this is the right thing.

e.g., if you have a BindExpression which isn't on an object literal, it falls through to
```js
       return parent.type === "MemberExpression" &&
          name === "object" &&
          parent.object === node;
```

which... doesn't look right for this case?

But a lot of these case statements fall through, and it's not at all obvious to me if they're meant to.

-----

I think your `getCombinedDeepest` can be replaced with

```js
function getCombinedDeepest(node) {
  while (node.left) {
    node = node.left;
  }
  switch (node.type) {
    case "ObjectExpression":
      return true;
    case "MemberExpression":
        return getCombinedDeepest(node.object);
    case "TaggedTemplateExpression":
        return getCombinedDeepest(node.tag);
    case "CallExpression":
        return getCombinedDeepest(node.callee);
    case "ConditionalExpression":
        return getCombinedDeepest(node.test);
    case "UpdateExpression":
        return !node.prefix && getCombinedDeepest(node.argument);
    case "BindExpression":
        return node.object && getCombinedDeepest(node.object);
    default:
      return false;
  }
}
```

It's much simpler (doesn't need `getDeepestCallee`), and also handles `UpdateExpression` and `BindExpression` better. I haven't tested it, mind.

**Comment by vjeux** [comment]
> I'm really uncomfortable with all of these cases statements in needsParens falling through :| It makes it really hard to tell if this is the right thing.

+1. I've seen two bugs because of non intentional fallthrough already fyi.

**Comment by yamafaktory** [comment]
Ok, will try that. I think @jlongster & @vjeux should be involved in that process.

File: src/fast-path.js [hunk 1]
```diff
@@ -583,6 +590,42 @@ function containsCallExpression(node) {
...
+    case "UpdateExpression":
+        return !node.prefix && getCombinedDeepest(node.argument);
+    case "BindExpression":
+        return node.object && getCombinedDeepest(node.object);
+    default:
+      return false;
+  }
+}
+
+function getLeftist(node) {
```
Comment (vjeux) [inline src/fast-path.js]: getLeftMostNode

File: src/fast-path.js [hunk 2]
```diff
@@ -255,13 +255,17 @@ FPp.needsParens = function(assumeExpressionContext) {
       }
       return false;
 
+    case "BindExpression":
+      if (isBinarishOpInArrowFunction(node, parent)) return true;
+
```
Comment (vjeux) [inline src/fast-path.js]: add `return false;` here so it doesn't fall through

File: src/fast-path.js [hunk 3]
```diff
@@ -255,13 +255,17 @@ FPp.needsParens = function(assumeExpressionContext) {
       }
       return false;
 
+    case "BindExpression":
+      if (isBinarishOpInArrowFunction(node, parent)) return true;
```
Comment (vjeux) [inline src/fast-path.js]: please add {}

File: src/fast-path.js [hunk 4]
```diff
@@ -305,14 +309,10 @@ FPp.needsParens = function(assumeExpressionContext) {
...
-      if (
-        node.operator === "instanceof" &&
-        parent.type === "ArrowFunctionExpression"
-      ) {
-        return true;
-      }
+      if (isBinarishOpInArrowFunction(node, parent)) return true;
 
     case "LogicalExpression":
+      if (isBinarishOpInArrowFunction(node, parent)) return true;
```
Comment (vjeux) [inline src/fast-path.js]: don't add this on every single one of those. Instead, add a if condition at the top with

```js
if (parent.type === 'ArrowFunctionExpression' && parent.body === node &&
  // all the conditions where it's true
) { 
  return true;
}

File: src/fast-path.js [hunk 5]
```diff
@@ -583,6 +590,42 @@ function containsCallExpression(node) {
   return false;
 }
 
+function isBinarishOpInArrowFunction(node, parent) {
+  return parent.type === "ArrowFunctionExpression" && getCombinedDeepest(node);
+}
+
+function getCombinedDeepest(node) {
+  while (node.left) {
```
Comment (vjeux) [inline src/fast-path.js]: Use your `getLeftMostNode` function you just wrote below

File: src/fast-path.js [hunk 6]
```diff
@@ -583,6 +590,42 @@ function containsCallExpression(node) {
   return false;
 }
 
+function isBinarishOpInArrowFunction(node, parent) {
+  return parent.type === "ArrowFunctionExpression" && getCombinedDeepest(node);
+}
+
+function getCombinedDeepest(node) {
```
Comment (vjeux) [inline src/fast-path.js]: Should probably be named something like startsWithOpenCurlyBrace

File: src/fast-path.js (hunk 5 above)
Comment (yamafaktory) [inline src/fast-path.js]: Ok, well I reused the code provided by @bakkot.

**Comment by yamafaktory** [comment]
@vjeux / @bakkot I refactored the implementation to be cleaner and to also handle new #917 test cases. Waiting for you feedback, especially @bakkot if you have other cases in mind 👍.

**Comment by bakkot** [comment]
Will check more thoroughly soon, but at a glance I think this misses `({}(), 0);`

**Comment by yamafaktory** [comment]
Your last example seems to already be working.

**Comment by yamafaktory** [comment]
Anyway, thanks, I've added it to the tests.

File: src/fast-path.js [hunk 7]
```diff
@@ -245,6 +245,21 @@ FPp.needsParens = function(assumeExpressionContext) {
     return true;
   }
 
+  if (
+    ((parent.type === "ArrowFunctionExpression" && parent.body === node) ||
+     parent.type === "ExpressionStatement") &&
+      startsWithOpenCurlyBrace(node) &&
```
Comment (vjeux) [inline src/fast-path.js]: can you move this test after all the `node.type === ...`, we first want to make sure we are on the correct node type before doing this expensive logic.

Comment (yamafaktory) [inline src/fast-path.js]: Oh, you're right 👍.

File: tests/flow/arith/__snapshots__/jsfmt.spec.js.snap [hunk 8]
```diff
@@ -162,7 +162,7 @@ let tests = [
     x + \\"\\"; // error
     \\"\\" + x; // error
     x + {}; // error
-    ({}) + x; // error
+    (({}) + x); // error
```
Comment (vjeux) [inline tests/flow/arith/__snapshots__/jsfmt.spec.js.snap]: this seems to be over eager for parenthesis here, but I don't think that it's a big deal. We'll likely never have an expression statement that starts with {} in practice.

**Comment by vjeux** [comment]
This looks good to me, I'll let @bakkot give the final green light and we can ship it. Thanks a lot!

File: tests/flow/arith/__snapshots__/jsfmt.spec.js.snap (hunk 8 above)
Comment (yamafaktory) [inline tests/flow/arith/__snapshots__/jsfmt.spec.js.snap]: Yeah, I noticed it when I was updating the tests and I was clearly unsure on how to deal with it without making it over complex!

File: src/fast-path.js [hunk 9]
```diff
@@ -364,6 +372,12 @@ FPp.needsParens = function(assumeExpressionContext) {
           return false;
 
         case "ExpressionStatement":
+          if (
```
Comment (bakkot) [inline src/fast-path.js]: Tests pass without this addition. It shouldn't be necessary given the `if` at the top, either, if I'm reading them both correctly. Should either get rid of this or, if it's actually necessary, add a test which depends on it.

File: src/fast-path.js [hunk 10]
```diff
@@ -583,6 +597,38 @@ function containsCallExpression(node) {
...
+      return node.object && startsWithOpenCurlyBrace(node.object);
+    case "SequenceExpression":
+      return startsWithOpenCurlyBrace(node.expressions[0])
+    default:
+      return false;
+  }
+}
+
+function getLeftMost(node) {
+  if (node.left) {
```
Comment (bakkot) [inline src/fast-path.js]: Personally I'd write this function as `while (node.left) { node = node.left; } return node;`. It's mainly stylistic, but the loop is probably a little faster. Doesn't much matter though.

File: tests/objects/expression.js [hunk 11]
```diff
@@ -1,3 +1,7 @@
 () => ({}``);
 ({})``;
 a = () => ({}).x;
+({} && a, b);
+({}::b, 0);
+({}::b()``[''].c++ && 0 ? 0 : 0, 0);
+({}(), 0);
```
Comment (bakkot) [inline tests/objects/expression.js]: Could you add `(({} = 0);` and `(({} = 0), 1);`? They pass because of #862, but it'd be good to ensure they continue to.

**Comment by bakkot** [comment]
Looks good to me except for minor comments above!

File: src/fast-path.js [hunk 12]
```diff
@@ -245,6 +245,21 @@ FPp.needsParens = function(assumeExpressionContext) {
...
+    ((parent.type === "ArrowFunctionExpression" && parent.body === node) ||
+    parent.type === "ExpressionStatement") &&
+    startsWithOpenCurlyBrace(node)
+  ) {
+    return true;
+  }
+
   switch (node.type) {
     case "CallExpression":
       if (
```
Comment (bakkot) [inline src/fast-path.js]: This `if` is unnecessary; instead you should have a `|| node.type === "CallExpression"` case a few lines above. And `node.type === "TaggedTemplateExpression"`, come to think, for test case

```js
x => ({}()``)
```

Comment (bakkot) [inline src/fast-path.js]: And also `MemberExpression`, for test case

```js
x => ({}().b)
```

This list of node types should pretty much match the list in `startsWithOpenCurlyBrace`. In fact, now that I say that, a better solution occurs to me: replace this entire `if` with

```js
  if (
    ((parent.type === "ArrowFunctionExpression" && parent.body === node) ||
      parent.type === "ExpressionStatement") &&
    startsWithOpenCurlyBrace(node)
  ) {
    return true;
  }
```

Comment (bakkot) [inline src/fast-path.js]: If you go that route, I think you can then delete all of

```js
    case "ObjectExpression":
      if (parent.type === "ArrowFunctionExpression" && name === "body") {
        return true;
      }
      if (parent.type === "TaggedTemplateExpression") {
        return true;
      }
      if (parent.type === "MemberExpression") {
        return name === "object" && parent.object === node;
      }
```

which, per git blame, looks to me to have been a hack trying to fix the bug which this PR fixes properly.

Comment (yamafaktory) [inline src/fast-path.js]: Ok, let me try that all and let's see how it's going, thanks!.

File: src/fast-path.js (hunk 9 above)
Comment (yamafaktory) [inline src/fast-path.js]: Yeah, I'm going to remove it.

File: src/fast-path.js (hunk 10 above)
Comment (yamafaktory) [inline src/fast-path.js]: I let @vjeux decide on that one. I personally prefer the recursive function, but if the `while` improves execution time why not.

File: tests/objects/expression.js (hunk 11 above)
Comment (yamafaktory) [inline tests/objects/expression.js]: Will do it!

**Comment by yamafaktory** [comment]
@bakkot could you review the latest refactoring, do you see any other missing test case we can add (cc @vjeux)?

**Comment by vjeux** [comment]
as soon as I get the green light from @bakkot, I'll merge it! Thanks a lot both for going through the process!

**Comment by bakkot** [comment]
I think this is correct! If you want to, a couple last cleanup things:

The CallExpression case can just be
```js
    case "CallExpression":
      return false;
```

and you can replace `canBeFirstInStatement` with the below, to get rid of some now-useless parentheses:
```js
FPp.canBeFirstInStatement = function() {
  var node = this.getNode();
  return !n.FunctionExpression.check(node) &&
    !n.ClassExpression.check(node);
};
```

**Comment by yamafaktory** [comment]
@bakkot Thanks a lot for your guidance, everything looks so much better now! The last addition has significantly cleaned up the output which makes it really nice 👍.

**Comment by bakkot** [comment]
Looks good to me!
