### PR TITLE
[RFC] Fix comment location for binary expressions

### LINKED ISSUE #946: Unstable comment in binary expression
```js
a = (
  // Commment 1
  (Math.random() * (yRange * (1 - minVerticalFraction)))
  + (minVerticalFraction * yRange)
) - offset;
```

```js
a = Math.random() * (yRange * (1 - minVerticalFraction)) +
  minVerticalFraction * yRange// Commment 1
   -
  offset;
```

```js
a = Math.random() * (yRange * (1 - minVerticalFraction)) +
  minVerticalFraction * yRange - // Commment 1
  offset;
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22a%20%3D%20(%5Cn%20%20%2F%2F%20Commment%201%5Cn%20%20(Math.random()%20*%20(yRange%20*%20(1%20-%20minVerticalFraction)))%5Cn%20%20%2B%20(minVerticalFraction%20*%20yRange)%5Cn)%20-%20offset%3B%5Cn%5Cna%20%3D%20Math.random()%20*%20(yRange%20*%20(1%20-%20minVerticalFraction))%20%2B%5Cn%20%20minVerticalFraction%20*%20yRange%2F%2F%20Commment%201%5Cn%20%20%20-%5Cn%20%20offset%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

### PR DESCRIPTION
**Pull request by vjeux**
The root cause is that we're calling `printComments` with an empty string, meaning that the leading/trailing comments are not correctly inserted at the right location.

So, the way to fix it is to call `p => concat(parts)` but because we're mutating the array in place, it doesn't work. We need to mutate it and create a copy. But, the root call is actually checking the shape of the parts array which our code is now breaking...

```js
          // Don't include the initial expression in the indentation
          // level. The first item is guaranteed to be the first
          // left-most expression.
          parts.length > 0 ? parts[0] : "",
```

The consequence is that binary expressions are no longer indented correctly if expressions have a comment (but now it places the comment properly!), which seems like an okay trade-off.

I'm not sure if we should merge this one or instead refactor this code such that it doesn't rely on mutation and looking at the shape of the printed tree. `printMemberChain` is a good thing to reference for inspiration.

Fixes #946

### CODE REVIEW

File: src/printer.js [hunk 1]
```diff
@@ -2843,7 +2843,11 @@ function printBinaryishExpressions(path, parts, print, options, isNested) {
     // the other ones since we don't call the normal print on BinaryExpression,
     // only for the left and right parts
     if (isNested && node.comments) {
-      parts.push(comments.printComments(path, p => "", options));
+      parts.splice(
+        0,
+        parts.length,
+        comments.printComments(path, p => concat(parts.slice()), options)
+      );
```
Comment (jlongster) [inline src/printer.js]: I think this code could be a little more readable. Doesn't this do the same thing?

```js
parts = comments.printComments(path, p => concat(parts), optons)
```

?

Comment (vjeux) [inline src/printer.js]: No, parts is an array that's being mutated. You can't just re-assign the variable, you need to clear its contents :(

Comment (jlongster) [inline src/printer.js]: Where else is the instance being mutated that would create an inconsistency? If you reassign the variable any mutations below will continue to work, operating on the new array.

Sorry for the delay; I'll keep this PR open in a tab and check back in so we can get this merged.

Comment (vjeux) [inline src/printer.js]: https://github.com/prettier/prettier/blob/master/src/printer.js#L223

The outer call site creates the part array, passes it as reference and looks at it at the end to do the indentation and to print it.

Comment (vjeux) [inline src/printer.js]: The more I think about it, the more I think we should just refactor this part of the code to avoid doing those mutations.

Comment (jlongster) [inline src/printer.js]: Ah, yep. I remember now. I think I tried to avoid this mutation at some point but it was pretty hard with the recursive call, and I want to land a working implementation. The recursiveness makes it pretty hard, and the resulting code might be a bit more awkward. I forget the details, but feel free to give it a try.

Worst case we can merge this. It's not the best, but oh well..

Comment (vjeux) [inline src/printer.js]: Oh yeah, it's not easy to refactor (I would have done it already :P).

If we've got to chose between two evils, I think that this PR is better. It's not going to indent but at least the comments are going to be stable and at the right place (instead of the crazy way they are now).

Also, this is a very very edge case.
