### PR TITLE
Fix TSMappedType comments

### LINKED ISSUE #4416: Formatting of mapped types in typescript and comments
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAS1jmwDMBDMOPAQT2AB0o88GZyk8oBXAWwCMSAGiYsW-TjwEkmAXyZMYATwzUAQngC89UXgD0evJF68EMXQG0A1oWZW4SiKVoBdSX0HY8AHzwBnGGwiAHM5ECEQCAwYAmg-ZFBybGwIAHcABSSEeJRyADcIAgATcJB+bEp7GABlDEoQ5EDuOAiiPxIYdIrg3nJkCgAbdoiAKz80NQqwKuryUwAZIjh+8iGWkDrsduxkEGVVPzAg6NKMINgAdWKYAAtkAA4ABgiziHaLioxds7htvOWItg4ABHbgEIFdcg9PpIQbDEDtXgERrYZoRPwhAZwACK3Ag8BWawi7H4VyKt2QACZiRUCAMQgBhCAmGEgKDQAEgbjtAAq5H4OThcFksiAA)
```sh
--parser typescript
```

**Input:**
```tsx
export interface A {
  	a: number,
    b: number
}

type B = {
  // comment
  [k in keyof A]: number | string
}
```

**Output:**
```tsx
export interface A {
  a: number;
  b: number;
}

type B = {
  [// comment
  k in keyof A]: number | string
};
```

**Expected behavior:**

**Output:**
```tsx
export interface A {
  a: number;
  b: number;
}

type B = {
  // comment
  [k in keyof A]: number | string
};
```

### PR DESCRIPTION
**Pull request by duailibe**
Closes #4416

### CODE REVIEW

File: tests/typescript_comments/mapped_types.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
+type A = {
+  // commentA
+  [a in A]: string;
+}
```
Comment (j-f1) [inline tests/typescript_comments/mapped_types.ts]: What about this?

```ts
type APrime = {
  [// commentAPrime
    a in A]: string
}
```

Comment (duailibe) [reply tests/typescript_comments/mapped_types.ts]: **Prettier pr-4418**
[Playground link](https://deploy-preview-4418--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAggBQCcBLAWxwF5tgAdKbbAbQHpntJTzYCTy6GGAQ2zF6uALpJsAZxgkoAczoBfEABoQEDDGLRpyUIMKEIAd3xGE+lIIBuEYgBN1IAEaFBYANZwYAZQxPUQVkOQBXOA1RaThCGCJBBVJBZAAzQQAbGI0AK2kADwAhD29fP0FyABlRODTM7JBAwhjCZFRMOGkwEm0XDHkYAHUnGAALZAAOAAYNfogYwY8MNv7O2NtajUI4AEcw4m2EpJSkdKzIkBjSYlDCCI1pYIy4AEUwiHg6840YQVdhxxjZAAJh+HmIGWCAGEIJwTiAoNBNiAwjEACp-axnGLKZRAA)
```sh
--parser typescript
```

**Input:**
```tsx
type APrime = {
  [// commentAPrime
    a in A]: string
}
```

**Output:**
```tsx
type APrime = {
  // commentAPrime
  [a in A]: string
};

```
