### PR TITLE
Go back to babylon beta 13

### LINKED ISSUE #2286: Parsing issue with arrow functions with type specs that returns JSX
This is a regression in 1.5.0.

Here's a minimal repro of the parsing issue:

https://prettier.io/#%7B%22content%22%3A%22const%20pass%20%3D%20()%3A%20X%20%3D%3E%20(%3Cx%20%2F%3E)%3B%5Cnconst%20fail%20%3D%20()%3A%20X%20%3D%3E%20%3Cx%20%2F%3E%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

```javascript
const pass = (): X => (<x />);
const fail = (): X => <x />;
```

```
SyntaxError: Unexpected token, expected , (2:26)
```

Note that if you comment out `fail`, the first run will succeed, but it generates equivalent code to `fail` so a subsequent pass will not succeed.

### PR DESCRIPTION
**Pull request by vjeux**
Fixes #2286

### CODE REVIEW

File: tests/flow_jsx/func_inside_attr.js [hunk 1]
```diff
@@ -1 +0,0 @@
-<bar x={function (x): Array<string> {}} />
```
Comment (vjeux) [inline tests/flow_jsx/func_inside_attr.js]: We should bring back this test on the next babylon upgrade.
