### PR TITLE
Fix a bug: css urls are incorrectly stripped of commas

### LINKED ISSUE #14237: @font-face urls are incorrectly stripped of commas
**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzjAngGzgPgB0oACEgAQDNoYBaSgQzDhOGLI4+tnoYFsAljixISAJwgAjANyc58hYqXKVqxewXoxYUQFcxOABQAlKRBgQAYngAetAGoMxAhpLyWaAfQDixgIIAIgA0ABoAKv5BAJoA8gAKAIrRYX4AyskBAKLJlgCSyQAyAMLJAKolEAAO6ABeQeg4sEEA7gAmMAAWLQDmHTAAdDAwlACU0hokAL5yxKgA9Ji4BBMkIEEgVTAC0OjIoE4SzXFOCLsoDDjNDFi765JiTADWcDCp-HAFAlBwyIw46HA7g8wM9XpUmF9usgYGJdICQHA+JI4K1WiiCgwoN1dAxunAPGI+AwhpDkCAGLoLGsQH0+DgAOodATwdDg5ipU7MgQAN2ZWDJYHQtxAXwBYhgcQe3SJvwuAPWACt0DZUpC8AldOYfkg-vKQOCxGKybScNTKs5YPSBO0OsgABwABnW5ogAPpD0qZPNcDF3J+6wAjpr4JKqmdyehaN8USjqWI4EGBPHJbiZTq5fCAYJobDM2q4H4hs5JJS4HE4GJPt9Zf881j1cHtbr4TBXFabcgAEzrGEMISQooQPhphHoACs1N0ALCrjOzfW3LhuSgaNgqTAzkqMD8K9S2DwNYBk0mQA)

```sh
--parser html
```

**Input:**

```html
<style>
  @font-face {
        font-family: rob;                                                                                
        src: url(RobotoFlex-VariableFont_GRAD,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf);
   }     
</style>
    
```

**Output:**

```html
<style>
  @font-face {
    font-family: rob;
    src: url(RobotoFlex-VariableFont_GRADXTRAYOPQYTASYTDEYTFIYTLCYTUCopszslntwdthwght.ttf);
  }
</style>

```

**Expected behavior:**

Commas in filename should be kept - I don't see why they would be invalid inside a url() CSS function.

### PR DESCRIPTION
**Pull request by seiyab**
## Description
Fix #14237 

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] ~(If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).~
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-css/utils/stringify-node.js [hunk 1]
```diff
@@ -5,7 +5,7 @@ function stringifyNode(node) {
     const open = node.open?.value || "";
     const groups = node.groups
       .map((currentValue) => stringifyNode(currentValue))
-      .join(node.groups[0]?.type === "comma_group" ? "," : "");
+      .join(node.type === "paren_group" ? "," : "");
```
Comment (seiyab) [inline src/language-css/utils/stringify-node.js:8]: Commas had disappeard if the first comma group is flattened.
Groups in paren group should always be separated by comma.

File: src/language-css/parser-postcss.js [hunk 2]
```diff
@@ -85,6 +85,7 @@ function parseValueNode(valueNode, options) {
         (!hasStringOrFunction(groupList) && !isSCSSVariable(groupList[0]))
       ) {
         const stringifiedContent = stringifyNode({
+          type: node.group.type,
```
Comment (fisker) [inline src/language-css/parser-postcss.js:88]: Would it work if we pass node.group directly?

Comment (seiyab) [reply src/language-css/parser-postcss.js:88]: Maybe no.
I think we need to omit open and close.
Maybe `{ ...node.group, open: null, close: null }` works.
I'll see it later.

**Comment by fisker** [comment]
> Fix https://github.com/prettier/prettier/pull/14476

Wrong link

File: changelog_unreleased/css/14476.md [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+}
+// Prettier stable
+@font-face {
+  src: url(RobotoFlex-VariableFont_GRADXTRAYOPQYTASYTDEYTFIYTLCYTUCopszslntwdthwght.ttf);
+}
+// Prettier main
+@font-face {
+  src: url(RobotoFlex-VariableFont_GRAD,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf);
+}
+```
```
Comment (fisker) [inline changelog_unreleased/css/14476.md:19]:
````suggestion
#### Fix a bug that incorrectly strips of commas in some cases (#14476 by @seiyab)

<!-- prettier-ignore -->
```css
/* Input */
@font-face {
  src: url(RobotoFlex-VariableFont_GRAD,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf);
}

/* Prettier stable */
@font-face {
  src: url(RobotoFlex-VariableFont_GRADXTRAYOPQYTASYTDEYTFIYTLCYTUCopszslntwdthwght.ttf);
}

/* Prettier main */
@font-face {
  src: url(RobotoFlex-VariableFont_GRAD,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf);
}
````

File: src/language-css/parser-postcss.js (hunk 2 above)
Comment (fisker) [reply src/language-css/parser-postcss.js:88]: That won't be necessary.

**Comment by fisker** [comment]
Can you try get original text instead of using `stringifyNode`? There are still edge cases broken.

**Prettier pr-14476**
[Playground link](https://deploy-preview-14476--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEABAZtGBadBDMOAAmAB0oiiBnAJzCSIFcaAbACkwgDoYZ0B+AI6M4NAJ4BeTgBoARnhrSAlAG5ylWvSasOEbgHcI6dACZ+nCTQDmstiYCs96Q6cAGJaRCfV5AL4hpEAgABxgAS2gqZFAFGgh9AAUFBCiUPBZ9PDEowNkaAgBrOBgAZTwAWzgAGTCoOGR8Fio4XPywItLgglqrZBgaEUC4ctk4ABMx8aq8KCtGPCs4ADEIGnK8Xh7kEDxGGAgAkAALGHKWAHUjsPgqLsISlOuwgDdrsW2wKhyQWuaaGAS+Ss6wa6WagQAVlQAB4lHosOAARUYEHgoKaLRAXRofw+X0OwRotRg5zCYxgR2QAA5XIFCRBmud8sFtoS4H9nvVAsJUXBASFUjsqNg6uNxocaHBhGFJYCFiCkI1wSBmuUwn0BpiqPC4ABBXhE2R7PmiGp1dHK7WzBHI3kWzEwPCyUnkylIEyBfp4MIsHoAYQg5QVIHZ9kOjGaABUnaklZjniIAJJQSawEpgImhXUpkowMQI+2+XxAA)

```sh
--parser css
```

**Input:**

```css
@font-face {
  src: url(foo.ttf?query=foo,bar,);
  src: url(foo.woff2?foo=rgb(255,255,0)"");
}
```

**Output:**

```css
@font-face {
  src: url(foo.ttf?query=foo,bar);
  src: url(foo.woff2?foo=rgb(255, 255, 0)"");
}

```

**Comment by seiyab** [comment]
Thanks for pointing edge cases.
And throwing error for `@import url(https://example.com/image\).png)` also seems a bug.
> If you choose to write the URL without quotes, use a backslash (`\`) before any parentheses, whitespace characters, single quotes (`'`) and double quotes (`"`) that are part of the URL.

**Comment by seiyab** [comment]
Trying to the original text isn't going smoothly.
- Approach 1. use `text` at `value-root`
    - It contains some texts other than `url()` node such as comment. Reveaing only `url()` seems to be hard.
- Approach 2. use [`toString()` ](https://github.com/TrySound/postcss-value-parser/tree/11a4436e74930f4eaf9cbdb2063656bcce8ebf6a#parsedtostring) of postcss-value-parser
    - It throws in prettier css parser because it removes `nodes` from parsed value.

**Comment by seiyab** [comment]
Following edge case still goes wrong...

https://deploy-preview-14476--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBDABMAOld7KwIxLoCuATgDYAUAFjDAA4DOSA9G3AB6oC2jlOADpIvNliwBKCegnUhAK2bRJAbhwBfEABoQERjACW0ZslCpy5CAHcAChYSmUqStdQBPU7oBG5VGABrOBgAZT44ABlDKDhkADMXZjgfP0DgkMZ-aIBzZBhyUmSQOF5vOAATcoqI1Chs0lRsuAAxCHJeVAYc5DRSGAgdEHpeSgB1WkN4ZkywOBDHScMAN0n3HrBmLxBopPIYWz9sjvjEoqUuEJzBAEVSCHgTyiTdTPJd9c3BxnJomFHDcowWjIAAcAAYXlYkqM-Iwet84LslrFdABHO7wA76JxoZgAWhiFQqg3IcHRhlJB0axyQCSeRSSvEMeQKDKucAAggwft4+nBbHByFEYo9niBmOzbvdYrTTroYKhvP9AcCkAAmeV+QyUHIAYQgvBpxWYAFZBqQkgAVRVOOlipaFACSUCqsBCYB+Bg5LpCMHcglFcA0GiAA

Input
```css
a {
  content: url(https://example.com/\)\ \(.json);
}
```

Output
```css
a {
  content: url(https://example.com/\) \\(.json);
}
```

**Comment by seiyab** [comment]
↑postcss-value-parser seems to go wrong.
Can't we give up this case at least in this PR?
```
nodes: [
  FunctionNode { 
    raws: [Object],
    value: 'url',
    source: [Object],
    sourceIndex: 0,
    nodes: [Array],
    type: 'func',
    unbalanced: 0,
    parent: [Circular *1]
  },
  Parenthesis { 
    raws: [Object],
    value: '(',
    source: [Object],
    sourceIndex: 26,
    type: 'paren',
    parenType: '',
    parent: [Circular *1]
  },
  Word { 
    raws: [Object],
    value: '.json',
    source: [Object],
    sourceIndex: 27,
    type: 'word',
    isHex: false,
    isColor: false,
    parent: [Circular *1]
  },
  Parenthesis { 
    raws: [Object],
    value: ')',
    source: [Object],
    sourceIndex: 32,
    type: 'paren',
    parenType: '',
    parent: [Circular *1]
  } 
],
```

File: src/language-css/parser-postcss.js [hunk 4]
```diff
@@ -197,7 +194,6 @@ function parseNestedValue(node, options) {
         parseNestedValue(node[key], options);
         if (key === "nodes") {
           node.group = flattenGroups(parseValueNode(node, options));
-          delete node[key];
```
Comment (seiyab) [inline src/language-css/parser-postcss.js:200]: I think this is the cause that CI fails. I'm checking.

**Comment by seiyab** [comment]
I'm sorry for annoying commits.
I welcome to change the approach because I'm not sure which approach is good enough.

File: src/language-css/utils/stringify-func-param.js [hunk 5]
```diff
@@ -0,0 +1,18 @@
+"use strict";
+
+const getHighestAncestor = require("./get-highest-ancestor.js");
+
+/**
+ * @param {*} node
+ * @returns {string}
+ */
+function stringifyFuncParam(node) {
```
Comment (seiyab) [inline src/language-css/utils/stringify-func-param.js:9]: We can also use this here.
https://github.com/prettier/prettier/blob/4d4d2a6fc0844f513ea0c6d5316ec7e37b89df66/src/language-css/parser-postcss.js#L54
I'll change it if you want.

**Comment by seiyab** [comment]
Can I rerun CI?

```
[2023-03-13T23:07:46.123Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
Error: Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/v3.1.0/dist/codecov' failed with exit code 255
```

File: tests/format/css/url/__snapshots__/jsfmt.spec.js.snap [hunk 6]
```diff
@@ -11,11 +11,47 @@ div {
...
+  src: url(foo.woff2?foo=rgb\\(255,255,0\\));
+}
+
+a {
+  content: url(https://example.com/\\)\\).jpg);
+  content: url(https://example.com/\\(\\(.jpg);
+  content: url(https://example.com/\\ \\ .jpg);
+  content: url(   https://example.com/\\)\\).jpg   );
+  content: url(   https://example.com/\\(\\(.jpg   );
+  content: url(https://example.com/\\ \\ .jpg);
```
Comment (fisker) [inline tests/format/css/url/__snapshots__/jsfmt.spec.js.snap:53]: Should we trim here?

Comment (fisker) [reply tests/format/css/url/__snapshots__/jsfmt.spec.js.snap:59]: As I tested with in chrome

```
<style>
body {
  background: url(              1.png?_=      )
}
</style>
```

and

```
<style>
body {
  background: url(              1.png      )
}
</style>
```

They all requesting urls without space.

Comment (seiyab) [reply tests/format/css/url/__snapshots__/jsfmt.spec.js.snap:59]: postcss-values-parser throws.
I think it should be a bug.
I'll try newer versions.
```js
const valueParser = require("postcss-values-parser");
valueParser('url(   https://example.com/\\(\\(.jpg   );', {loose: true}).parse()
```

```
Uncaught ParserError: Expected closing parenthesis at line: 1, column 4
    at Parser.error (~/Projects/oss/prettier/node_modules/postcss-values-parser/lib/parser.js:127:11)
    at Parser.parenOpen (~/Projects/oss/prettier/node_modules/postcss-values-parser/lib/parser.js:279:12)
    at Parser.parseTokens (~/Projects/oss/prettier/node_modules/postcss-values-parser/lib/parser.js:235:14)
    at Parser.loop (~/Projects/oss/prettier/node_modules/postcss-values-parser/lib/parser.js:132:12)
    at Parser.parse (~/Projects/oss/prettier/node_modules/postcss-values-parser/lib/parser.js:51:17)
```

Comment (seiyab) [reply tests/format/css/url/__snapshots__/jsfmt.spec.js.snap:59]: v3.2.1 seems good.
```js
const { parse } = require('postcss-values-parser');
parse('url(   https://example.com/\\(\\(.jpg   )');
```

<details>

```
<ref *1> Root {
  raws: { semicolon: false, after: '' },
  type: 'root',
  nodes: [
    Func {
      raws: [Object],
      name: 'url',
      type: 'func',
      isColor: false,
      isVar: false,
      nodes: [Array],
      parent: [Circular *1],
      source: [Object],
      params: '(   https://example.com/\\(\\(.jpg   )'
    }
  ],
  source: {
    input: Input {
      css: 'url(   https://example.com/\\(\\(.jpg   )',
      hasBOM: false,
      id: '<input css 1>'
    },
    start: { line: 1, column: 1 }
  },
  toString: [Function: bound toString]
}
```

</details>

But v3.0.0 is big breaking release. https://github.com/shellscape/postcss-values-parser/releases
Which way do you like?
- Bump postcss-values-parser  on next branch via another PR first, and then work on this bug.
- Leave `'url(   https://example.com/\\(\\(.jpg   )'` and merge this PR first. And then try to bump postcss-values-parser on next branch. Finally, tackle `'url(   https://example.com/\\(\\(.jpg   )'` (or, perhaps it will be resolved by update).

Comment (fisker) [reply tests/format/css/url/__snapshots__/jsfmt.spec.js.snap:59]: > And then try to bump postcss-values-parser

Too hard..

**Review by fisker — APPROVED** [review]
Thank you!

**Comment by fisker** [comment]
Can you fix the conflicts?

**Comment by fisker** [comment]
Good job @seiyab

File: tests/format/css/url/__snapshots__/jsfmt.spec.js.snap (hunk 6 above)
Comment (seiyab) [reply tests/format/css/url/__snapshots__/jsfmt.spec.js.snap:59]: Will it conflict with your work if I'll try to bump postcss-value-parser?
Referring following, I'm asking you.
> I want to make some change to the value-comma_group part

https://github.com/prettier/prettier/pull/14480

Comment (fisker) [reply tests/format/css/url/__snapshots__/jsfmt.spec.js.snap:59]: No. Go a head, but it won't be easy, I've tried few times since 2 years ago.

Comment (fisker) [reply tests/format/css/url/__snapshots__/jsfmt.spec.js.snap:59]: Last attempt by other maintainer. https://github.com/prettier/prettier/pull/11667

Comment (seiyab) [reply tests/format/css/url/__snapshots__/jsfmt.spec.js.snap:59]: Thank you for your replies.
Sounds so hard!
Any way, I'll try it, though I will be likely to give up 🔥

Comment (seiyab) [reply tests/format/css/url/__snapshots__/jsfmt.spec.js.snap:59]: @fisker 
Hi, I have tried migrating postcss-values parser from v2 to v6.
Eventually, I gave up because https://github.com/shellscape/postcss-values-parser/issues/140 prevents us from migrating.
May I summarize what I investigated for migration somewhere (perhaps an issue or a discussion)?
