### PR TITLE
fix: issue #6813 (Zero-based lists are broken)

### LINKED ISSUE #6813: [Markdown] Zero-based lists are broken
As provided by @alexandrtovmach in https://github.com/gatsbyjs/gatsby/pull/18942#issuecomment-549749393, parsing zero-based lists is broken.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAGAdAAgDIEsDOMAOlAIxZ6EkBMFBMIANCBAA4y7T7KgCGATvwgB3AAoCE3FLwBuEXABMmIAEb9eYANZwYAZVYbcUAObIY-AK5xmACxgBbADYB1G7nj4DYOLsnvcMu4Ansjg+NzMRvhw-DCi6sb2vMgAZryO0cwAVvgAHgBC6lo6urz2cHhQcKnpmSA5ubpGxo5wAIoWEPA1GdYgBvzR-KFJ-JoKIlDKrPxGMM6KMDbIAByozDMQ0c7qrKEzcEMy1cwAjp3w8WxSILz4ALRVcArPyvxw57jv8byJyUhpXrMaL2XBmSx9fDNVodLrVAG1PowXgqBYKJbIajMcy8XCOZoAYQg9iSoSg0BOIAs0QAKiipIDogBfJlAA)
```sh
--parser markdown
```

**Input:**
```md
0. List
1. List
2. List
```

**Output:**
```md
0. List
1. List
1. List

```

**Expected behavior:**
```md
0. List
1. List
2. List

```

### PR DESCRIPTION
**Pull request by evilebottnawi**
- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

fixes #6813 + many tests

### CODE REVIEW

File: src/language-markdown/utils.js [hunk 1]
```diff
@@ -162,6 +162,34 @@ function getOrderedListItemInfo(orderListItem, originalText) {
...
+function hasGitDiffFriendlyOrderedList(node, options) {
+  if (!node.ordered) {
+    return false;
+  }
+
+  if (node.children.length < 2) {
+    return false;
+  }
+
+  const startNumber = Number(
```
Comment (j-f1) [inline src/language-markdown/utils.js]:
```suggestion
  const firstNumber = Number(
```

File: src/language-markdown/utils.js [hunk 2]
```diff
@@ -162,6 +162,34 @@ function getOrderedListItemInfo(orderListItem, originalText) {
...
+    getOrderedListItemInfo(node.children[0], options.originalText).numberText
+  );
+
+  const number = Number(
```
Comment (j-f1) [inline src/language-markdown/utils.js]:
```suggestion
  const secondNumber = Number(
```

File: src/language-markdown/utils.js [hunk 3]
```diff
@@ -162,6 +162,34 @@ function getOrderedListItemInfo(orderListItem, originalText) {
...
+    getOrderedListItemInfo(node.children[1], options.originalText).numberText
+  );
+
+  if (startNumber === 0 && node.children.length > 2) {
+    const nextNumber = Number(
```
Comment (j-f1) [inline src/language-markdown/utils.js]:
```suggestion
    const thirdNumber = Number(
```

File: tests/markdown_list/__snapshots__/jsfmt.spec.js.snap [hunk 4]
```diff
@@ -2458,11 +2458,200 @@ proseWrap: "always"
...
+
+0. abc
+1. def
+2. ghi
+
+---
+
+1. abc
+1. def
+1. ghi
```
Comment (j-f1) [inline tests/markdown_list/__snapshots__/jsfmt.spec.js.snap]: Shouldn’t `0`-`1`-`1` be printed as `0`-`1`-`2` just like `1`-`2`-`2` is printed as `1`-`2`-`3`?

Comment (evilebottnawi) [reply tests/markdown_list/__snapshots__/jsfmt.spec.js.snap]: No, we (not only me, it is common practice for many other developers) use `1` for git friendly markers (for example you want to start with `45` and have git friendly markers):
```md
45. list
1. list
1. list
1. list
1. list
```

Same for `0`, you may want start with `0`:
```md
0. list
1. list
1. list
1. list
1. list
```

Comment (evilebottnawi) [reply tests/markdown_list/__snapshots__/jsfmt.spec.js.snap]: `1`-`2`-`2` is git friendly also but it is out of this PR because in out code we use only `1` as git friendly market, you can open an issue about this and i will fix it (it is easy)

Comment (j-f1) [reply tests/markdown_list/__snapshots__/jsfmt.spec.js.snap]: Why not do this then?

```markdown
0. list
0. list
0. list
0. list
0. list
```

Comment (evilebottnawi) [reply tests/markdown_list/__snapshots__/jsfmt.spec.js.snap]: Because @ikatyang use `1.` for git friendly markers (and it is common practice) :smile: I think it is really other issue, developers use `1.` for git friendly markers usually (for example https://docs.microsoft.com/en-us/contribute/how-to-write-use-markdown, i can find more links if it is necessary)

Comment (j-f1) [reply tests/markdown_list/__snapshots__/jsfmt.spec.js.snap]: That makes sense. Thanks! 👍

Comment (j-f1) [reply tests/markdown_list/__snapshots__/jsfmt.spec.js.snap]: That makes sense, thanks! 👍

**Comment by fisker** [comment]
@evilebottnawi

how about

```js
const [firstNumber, secondNumber, thirdNumber] = node.children
  .slice(0, 3)
  .filter(Boolean)
  .map(child =>
    Number(getOrderedListItemInfo(child, options.originalText).numberText)
  );
```

**Comment by evilebottnawi** [comment]
thirdNumber may not exist, also it is unnecessary get third node when list contains only 2 items

**Comment by fisker** [comment]
I used `.filter(Boolean)`

**Comment by evilebottnawi** [comment]
@lydell why 2?

**Comment by evilebottnawi** [comment]
There are a lot of changes for the second version, we should still have an intermediate version 1.20

**Comment by lydell** [comment]
The plan is to release 2.0 early January 2020. I don’t think we’ll be able to jam another release in between. It’s just two months away and there’s Christmas and all.

**Comment by lydell** [comment]
Yes, sounds good.

File: src/language-markdown/utils.js [hunk 5]
```diff
@@ -162,6 +162,34 @@ function getOrderedListItemInfo(orderListItem, originalText) {
   return { numberText, marker, leadingSpaces };
 }
 
+function hasGitDiffFriendlyOrderedList(node, options) {
```
Comment (fisker) [inline src/language-markdown/utils.js]: why not name `hasDiffFriendlyOrderedList`

Comment (evilebottnawi) [reply src/language-markdown/utils.js]: Because it is git diff, not diff, it is original name, so it is out of this PR

File: changelog_unreleased/markdown/pr-6852.md [hunk 6]
```diff
@@ -0,0 +1,19 @@
+#### Markdown: handle zero-based lists correctly ([#6852](https://github.com/prettier/prettier/pull/6852) by [@evilebottnawi](https://github.com/evilebottnawi))
```
Comment (lydell) [inline changelog_unreleased/markdown/pr-6852.md]:
```suggestion
#### Handle zero-based lists correctly ([#6852](https://github.com/prettier/prettier/pull/6852) by [@evilebottnawi](https://github.com/evilebottnawi))
```
