### PR TITLE
JS: Fix multiple-comments-on-same-line format

### LINKED ISSUE #3532: Two comments straight after each other breaks formatting and swaps content by accident
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMAgMxwnXwHIdTy6BuAHSg4HoAqDjbHnwBnGAE8ANnAAm+KjXqMyMALRx0EGKmisOHSFFH4AgsMxxyhElogAhCAA98AXhHip0gHTTUANwAGHPj4AGRISABGcBS4cPjAQcH4BvCwSPS6UEn4AO6o0jAAFukAjJgO7FlJ6CQ4AOaoUCpSFDDpKmUVicEUEhDW6S0wldmFcKh1hW34AAwjSZgk0j5QdSowEJjpACTAmNSYwi4AfPglMzP4XPj7m8KeJGYWMFY2AL4ApPNvelVhSCRWnAcPFulcePgACoQZJSWpyPrWfA8Li8MEpBDTOiZbI+MwSEhidIwEgRKTzYJgOE4dIRTSFb4cfyVFG-AxGUzmSzWbT2JyuAAUCSqjy5Lx5EAANIkwIVUBJpIwoNKqp41bdDhw3gBKE74AWJAA8Pl86IJwmEADkSOg4M5gP4xhMpuk5okIL5gb0IDl0nLlgh5otlo01hstvhdhqjs5TudLtdow8ntz3l9EhEyABrOrUACuUGk6RycvgQYgwlQNig6UYBK0npY-h+VWOYONfmOwFl8sVCDehq4JrbVUHw442sqHDgDkEBGk0RIeYkBE5z1evMclRAkpAm2rwmQoFq1ByAAVaghDygSL4IPkdyBHjBkBQSBJhHBdxEcNm4DAAGVFjAUNkBgHA8y-EBpAgMBX3fT9d0aT88DPX86hqeCPyggArYQHFsX8wCzf8AJtOAABlGjgLDEL3PMYEwBiACZaKgxYcBQ5AQEzCJJGgR99kaGAAHV8iKZAAA4Zl3W5PxE39MG4-Y4BQz1H0YABHPNUEYNCSAwkg2N3T90FQMCIKgytVikABFPNNBopA32w3cSQiMSCkKZBmLc395VDABhGhMJQKBoBo3c80-SFSWvFzPzeN4gA)

**Input:**
```jsx
import React from 'react';

/*
import styled from 'react-emotion';

const AspectRatioBox = styled.div`
  &::before {
    content: '';
    width: 1px;
    margin-left: -1px;
    float: left;
    height: 0;
    padding-top: ${props => 100 / props.aspectRatio}%;
  }

  &::after {
    /* To clear float *//*
    content: '';
    display: table;
    clear: both;
  }
`;
*/

const AspectRatioBox = ({
  aspectRatio,
  children,
  ...props
}) => (
  <div
    className={`height: 0;
  overflow: hidden;
  padding-top: ${props => 100 / props.aspectRatio}%;
  background: white;
  position: relative;`}
  >
    <div>{children}</div>
  </div>
);

export default AspectRatioBox;

```

**Output:**
```jsx
import React from "react"; /*
    content: '';
    display: table;
    clear: both;
  }
`;
*/

/*
import styled from 'react-emotion';

const AspectRatioBox = styled.div`
  &::before {
    content: '';
    width: 1px;
    margin-left: -1px;
    float: left;
    height: 0;
    padding-top: ${props => 100 / props.aspectRatio}%;
  }

  &::after {
    /* To clear float */ const AspectRatioBox = ({
  aspectRatio,
  children,
  ...props
}) => (
  <div
    className={`height: 0;
  overflow: hidden;
  padding-top: ${props => 100 / props.aspectRatio}%;
  background: white;
  position: relative;`}
  >
    <div>{children}</div>
  </div>
);

export default AspectRatioBox;

```

**Expected behavior:**

The comments after `/**/` should not appear at the beginning of the first comment, but at the end of the second original comment.

### LINKED ISSUE #7724: Broken nestled jsdoc comments for overloaded functions
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mAOiAEICGATqQNzFQMD0AVCw5i5gALwC2ABwA2FeJgAqHLtwHUKfTMHEBPAXAC+mGKrhSesqvMXjNANwpCArrqiceVODEtVbwAGoXr6qU1btb0gZGSjqa2mp63A5OLooeVho+DNiWUGAwAJbQmOYJABThcAA0OZ5wAJSKHJgZ2Jh51ADmlnwIMGgAdEIIjTAAFoQERABMlcDVmJjRzrZQcADumADC0GDRcPHWBToludbl9LaYmnBCaHBVR5PTsXOLm3DbagfV3lBvIEUgEAKZ6MigahUCDzAAK1AQaGQIAopggGQAJp8QAAjQxgADWjgAyrIwBkoI1kDAqNYvn0YHwhAB1PoZeBoPFwbGQ+kZUz05TQsBoKFfAnnKgwUGGRp8CjIbAWc5fABWaAAHmR0ViYNj5HAADIEuCS6XFEDyhXYgmNboARUsEHgerOBoMguhKIoKNOyIEVAJMGpiP6yAAHAAGL4eiDnamGATQj1wQWmXVfACOVvgIp+UJQFDQAFo5nAEfnkQ5kxkHCKKGKJUgpXavuc+BliaSDWhTRaU7rq-qvjAXT6EX6kMMe4YMkJTSs+OLoVBoAmQJZzuIXRmazKQKZrABJKAF2DYtYZX4AQV32O03Vt53U6iAA)
```sh
--parser babel
```

**Input:**
```jsx
const foo = "Bar";

/**
 * @template T
 * @param {Type} type
 * @param {T} value
 * @return {Value}
 *//**
 * @param {Type} type
 * @return {Value}
 */
function value(type, value) {
  if (arguments.length === 2) {
    return new ConcreteValue(type, value);
  } else {
    return new Value(type);
  }
}

```

**Output:**
```jsx
const foo = "Bar";
/**
 * @param {Type} type
 * @return {Value}
 */

/**
 * @template T
 * @param {Type} type
 * @param {T} value
 * @return {Value}
 */ function value(type, value) {
  if (arguments.length === 2) {
    return new ConcreteValue(type, value);
  } else {
    return new Value(type);
  }
}

```

**Expected behavior:**
Output identical to input.

### LINKED ISSUE #9671: Unstable format when multiple comments on same line
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDA3AHSgegFQCMeO+ATMdvgMwVQBGWU2GlhtZx1tDIANCBAAOMAJbQAzslCoATjIgB3AAqyEklKgA2C1AE9J-OjNRgA1nBgBlQSZFQA5shgyArnH5wAtnTgATX34AMqgOLqj2cABiEDKeqDCiDshoLjAQfCAAFjCemgDqmSLw4jZgcJZqRSIAbkW6yWDiBiB24nAyMErG9nHIAGZabfwAVuIAHgBCxmYWlqiecIF2cP2D7iCjY5Z29ppwAIouEPCrmkMgNjJtMsl0qD6aGYIydjB5Ir4wmcgAHAAM-GeEDaeWMgmSzzg12qK34AEcjvAukJ1GhxABaKBwPx+DIyOAIkT4rrhXpIAZndZtTwiJyuKk7PaHY4rclrfgwe7vT7fJCkDnGESaHYAYQgnjJIChAFYMi42gAVe7qCnnapuACSUACsEsYBewgAgtrLDBdHtTm0AL5WoA)
```sh
--parser babel
```

**Input:**
```jsx
a;
/*1*//*2*/
/*3*/
b;

a;
/*1*/
/*2*//*3*/
b;
```

**Output:**
```jsx
a; /*2*/
/*1*/ /*3*/
b;

a; /*3*/
/*1*/
/*2*/ b;

```

**Second Output:**
```jsx
a; /*2*/ /*3*/
/*1*/ b;

a; /*3*/
/*1*/
/*2*/ b;

```

**Expected behavior:**

Should be stable

### PR DESCRIPTION
**Pull request by fisker**
Fix #9671
Fix #3532
Fix #7724

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
I just realized that there are similar thing for "RemainingComment" https://github.com/prettier/prettier/blob/ef6a2c5f8a448bb16bcbaeab06f29e2be98a958d/src/main/comments.js#L322, but that logic may not fit this case.

**Comment by thorn0** [comment]
The solution looks good, but I want to test it a bit more.

**Comment by fisker** [comment]
A known issue 

**Prettier pr-9672**
[Playground link](https://deploy-preview-9672--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBDA3AHSgegFQCMeO6+ATMdvgMyVQBG6IANCBAA4wCW0AzsqFQAnIRADuABWEJ+KVABsxqAJ79W9IajABrODADK7LVygBzZDCEBXOKzgBbenAAmzlwBlUZq6lNwAYhBC9qgw3GbIaFYwECwgABYw9vIA6vFc8LxGYHD6MhlcAG4ZypFgvGogJrxwQjASmqYhyABmCjWsAFa8AB4AQpo6evqo9nDuJnCt7bYg3T36JqbycACKVhDw0-IdIEZCNUKR9KhO8nHsQiYwKVzOMPHIABwADKyXEDUpmuyRl3CHQpTVgARw28AaHFkaF4AFooHAXC44kI4GCuKiGr5mkg2jtZjV7FwLNYCUsVutNlNcTNWDBTrd7o8kGQ6ZouPIlgBhCD2HEgAEAVjiVhqABVTrI8btCjYAJJQNywfRgK6cACCiv0MGUK22NQAvgagA)
```sh
--parser babel
```

**Input:**
```jsx
a;
/*1*/;/*2*/
/*3*/
b;
```

**Output:**
```jsx
a; /*2*/
/*1*/ /*3*/
b;

```

**Comment by thorn0** [comment]
A solution for this known issue might be something like this: if any previous comment for the same `precedingNode` was detected as "own-line", then the current comment can't be considered "end-of-line" and should be considered "own-line" instead.

File: src/main/comments.js [hunk 1]
```diff
@@ -306,6 +306,50 @@ function attach(comments, ast, text, options) {
...
+const isAllEmptyAndNoLineBreak = (text) =>
+  !/[\n\u2028\u2029]/.test(text) && /^\s*$/.test(text);
+function isOwnLineComment(comment, text, options, comments, commentIndex) {
+  const { locStart, locEnd } = options;
+  let start = locStart(comment);
+
+  // Find first comment on the same line
+  for (let index = commentIndex - 1; index >= 0; index--) {
+    const previousComment = comments[index];
+    if (!previousComment) {
```
Comment (thorn0) [inline src/main/comments.js:318]: Let's add a check here that `comment` and `previousComment` have the same `precedingNode`. Otherwise, `slice` might return huge strings when the comments are far from each other.

File: src/main/comments.js [hunk 2]
```diff
@@ -306,6 +319,62 @@ function attach(comments, ast, text, options) {
...
+  let start = locStart(comment);
+
+  // Find first comment on the same line
+  for (let index = commentIndex - 1; index >= 0; index--) {
+    const previous = decoratedComments[index];
+    if (!previous) {
+      break;
+    }
+    if (previous.precedingNode !== precedingNode) {
+      continue;
```
Comment (thorn0) [inline src/main/comments.js:336]:
```suggestion
      break;
```

File: src/main/comments.js [hunk 3]
```diff
@@ -306,6 +319,62 @@ function attach(comments, ast, text, options) {
   }
 }
 
+const isAllEmptyAndNoLineBreak = (text) =>
+  !/[\n\u2028\u2029]/.test(text) && /^\s*$/.test(text);
```
Comment (thorn0) [inline src/main/comments.js:323]:
```suggestion
  !/[\S\n\u2028\u2029]/.test(text);
```

**Comment by thorn0** [comment]
**Prettier pr-9672**
[Playground link](https://deploy-preview-9672--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEADAJMAOlAhjgegCoBGIg4gJnMKIGYaoBfVHHfKYsio6g2hvyggANCAgAHGAEtoAZ2ShcAJ2UQA7gAUVCBSlwAbdbgCeCsQCNluMAGs4MAMoSb0qAHNkMZQFc4YuABbCzgAE1CwgBlcDx9cdzgAMQhlQNwYGQ9kEFwfGAhREAALGECDAHUi6Xg5FzA4R11q6QA3apNssDlzEDc5OGUYTWt3NOQAM0N+sQArOQAPACFrOwdHXEC4SLc4Can-EDn5xzd3AzgARR8IeD2DaZAXZX7lbItcEINCiWU3GHLpKEYEVkAAOAAMYh+EH65WsEmyPzgLxauzEAEdrvBhpI9Dk5ABaKBwMJhQrKOCY6QU4bxMZISb3A79QLSLy+Zmnc5XG67Bn7MQwD4AoEgpCUQXWaQGU4AYQggXpIGRAFZCj5+gAVD56RkPFp+ACSUAisEcYF+UgAgibHDATOc7v0mEwgA)
```sh
--parser babel
```

**Input:**
```jsx
`${
a
/*1*//*2*/
/*3*/
}`

a
/*1*//*2*/
/*3*/

```

**Output:**
```jsx
`${
  a /*2*/
  /*1*/
  /*3*/
}`;

a; /*2*/
/*1*/
/*3*/

```

File: src/main/comments.js [hunk 4]
```diff
@@ -306,6 +312,61 @@ function attach(comments, ast, text, options) {
   }
 }
 
+const isAllEmptyAndNoLineBreak = (text) => !/[\S\n\u2028\u2029]/.test(text);
+function isOwnLineComment(text, options, decoratedComments, commentIndex) {
+  const { comment, precedingNode } = decoratedComments[commentIndex];
+  const { locStart, locEnd } = options;
+  let start = locStart(comment);
+
+  if (precedingNode) {
```
Comment (thorn0) [inline src/main/comments.js:321]: I think this condition isn't needed. It's okay if `precedingNode` is falsy. `currentCommentPrecedingNode !== precedingNode` would still do what we need (we might want to replace `!==` with `!=` though).

Comment (fisker) [reply src/main/comments.js:321]: https://github.com/prettier/prettier/pull/9672#issuecomment-732941426 seems not caused by this part.

```js
a; /*2*/
/*1*/
/*3*/
```

The trailing comments part print like this

```json
[
{"type":"line-suffix","contents":{"type":"concat","parts":[{"type":"concat","parts":[{"type":"line","hard":true},{"type":"break-parent"}]},"","/*4*/"]}},
{"type":"concat","parts":[" ","/*5*/"]},
{"type":"line-suffix","contents":{"type":"concat","parts":[{"type":"concat","parts":[{"type":"line","hard":true},{"type":"break-parent"}]},"","/*6*/"]}}
]
```

Because of `line-suffix`, `/*1*/` print after `/*2*/`

Comment (fisker) [reply src/main/comments.js:321]: It seems it's a separate issue, I'll try to fix it

Comment (thorn0) [reply src/main/comments.js:321]: All three comments should be classified as own-line and printed without `line-suffix`. I thought it didn't happen because of the `if (followingNode)` check. Was I wrong?

Comment (fisker) [reply src/main/comments.js:321]: They were attached as trailing even without this PR, because there is no followingNode, problem is in `printTrailingComment`

**Review by thorn0 — APPROVED** [review]
