### PR TITLE
Fix `in` inside of a for in a nested way

### LINKED ISSUE #907: Omitted parentheses in ForStatement with `in` in initializer
The grouping parentheses are necessary in all of the below, but prettier removes them:

```js
for (let a = (b in c);;);
```

```js
for (a && (b in c);;);
```

```js
for (a => (b in c);;);
```

```js
function* g() {
  for (yield (a in b);;);
}
```

```js
async function f() {
  for (await (a in b);;);
}
```

### PR DESCRIPTION
**Pull request by vjeux**
Fixes #907

### CODE REVIEW

**Comment by vjeux** [comment]
@bakkot I'd love if you could review this PR :)

File: src/fast-path.js [hunk 1]
```diff
@@ -280,17 +282,27 @@ FPp.needsParens = function(assumeExpressionContext) {
...
+      const isLeftOfAForStatement = node => {
+        let i = 0;
+        while (node) {
+          let parent = this.getParentNode(i++);
+          if (!parent) {
+            return false;
+          }
+          if (parent.type === "ForStatement" && parent.init === node) {
+            return true;
+          }
```
Comment (bakkot) [inline src/fast-path.js]: If you add
```js
          if (n.Statement.check(parent)) {
            return false;
          }
```
here, you can avoid walking all the way up the tree for every `in`. Not sure how much it would help.

Comment (vjeux) [inline src/fast-path.js]: good idea

**Comment by bakkot** [comment]
Should work. It's a little overzealous, but people probably aren't putting too much complex logic there anyway.

Optionally you could `return false` from `isLeftOfAForStatement` if you hit an ObjectExpression or ArrayExpression, to be a little less overzealous.

File: src/fast-path.js [hunk 2]
```diff
@@ -280,17 +282,27 @@ FPp.needsParens = function(assumeExpressionContext) {
...
+          node = parent;
+        }
+        return false;
+      };
       if (
         node.operator === "in" &&
-        parent.type === "ForStatement" &&
-        parent.init === node
+        (isLeftOfAForStatement(node) ||
+          parent.type === "AssignmentExpression")
```
Comment (bakkot) [inline src/fast-path.js]: Don't need this line. `x = b in c` should codegen without parentheses.

Comment (vjeux) [inline src/fast-path.js]: cool thanks, I'll remove that

File: src/fast-path.js (hunk 1 above)
Comment (vjeux) [inline src/fast-path.js]: Actually, this doesn't work. For some reason VariableDeclaration is considered to be a Statement and therefore

```js
for (let a = (b in c); ; );
```

is no longer parenthesized. I'll leave the optimization off, I don't think it's a big deal going up all the way.

Comment (bakkot) [inline src/fast-path.js]: Oh, right. Ugh, estree, why are you so terrible.
