### PR TITLE
Fix `diff` package import

### LINKED ISSUE #12275: diffArrays deep require breaks Prettier 2.6 in Node.js 17.5.0
**Environments:**

- Prettier Version: 2.6.0-dev
- Running Prettier via: CLI
- Runtime: Node.js v17.5.0, npm 8.4.1
- Operating System: macOS 12.2

**Steps to reproduce:**

1. Install Node.js v17.5.0 and npm 8.4.1
2. Install Prettier 2.6.0-dev
3. Run prettier: `npx prettier --write .`

**Expected behavior:**

Prettier works.

**Actual behavior:**

Prettier breaks:

```sh
node:internal/modules/cjs/loader:488
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/diff/array.js' is not defined by "exports" in /repo/node_modules/diff/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:705:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/repo/node_modules/prettier/src/main/core.js:4:24) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v17.5.0
```

I tracked the problem to this line:

https://github.com/prettier/prettier/blob/92e6f44bbad9b6ee70dff0827f17448d50c72ca7/src/main/core.js#L4

If I change it to:

```js
const { diffArrays } = require("diff");
```

Prettier works.

Alternatively, If I change this line in https://github.com/kpdecker/jsdiff:

https://github.com/kpdecker/jsdiff/blob/d358a573dc38fb89dd5ee296805e29f75c932a58/package.json#L40

To:

```json
"./*": "./*"
```

Prettier works too.

Thanks!

### PR DESCRIPTION
**Pull request by fisker**
## Description

Lucky we only use one method in `cli.js`, `index.js`, and `standalone.js`, so we can easily replace them.
This didn't change the output.

This reverts #12160
Fixes #12275

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: scripts/build/config.mjs [hunk 1]
```diff
@@ -229,6 +243,9 @@ const coreBundles = [
         replacement: "const utilInspect = require('util').inspect",
       },
     ],
+    replaceModule: {
+      ...replaceDiffPackageEntry("lib/diff/array.js"),
+    },
```
Comment (sosukesuzuki) [inline scripts/build/config.mjs:248]: Why copied? Isn't it enough?

```suggestion
    replaceModule: replaceDiffPackageEntry("lib/diff/array.js"),
```

**Review by sosukesuzuki — APPROVED** [review]
