### PR TITLE
fix(js): Object destructuring in method shorthand #6515

### LINKED ISSUE #6515: Object destructuring in method shorthand syntax always breaks into multiple lines
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEEBGArTAXk2AB0pNMAzAVyjAApzLKBLAEwBpmWyKXKOADYQA5khKYYrGELiYAvt36UFPAJQkelAE5wYNHRQ6YA1FJlyA3DyXkFNqCE4gIAB2npkoAIY6dEADuAAp+CGjIID4AbhAcziA4Oj5gANb6AMpuKaxQosgwOjRwLgAWMAC2QgDqpTJwaNlgcBnhMqzRMgCekWBoES65aHA6MMHJohU+yFQ+QsMueGgAHgBCyWmZPhVwADK5cDNzCyBLyxm5onIAijQQ8EfzJSDZOsM6kTg+OF0iTi5uHS5GDVDgwUrIAAcAAYAQFhtVkm5IoCGiNoocXABHO7wcbuCIoHxoAC0UDgcHYlISehxrD04x8k2mSFmTxcwwqrAKRWeaEuN1xhyQhWKLhg31B7HByAATOLkqwhJcAMIQCpTSJQaCYkA0YYAFW+hLZwwUCiAA)
```sh
--parser babylon
--single-quote
```

**Input:**
```jsx
const obj = {
  func(
    id,
    {
      blog: { title },
    }
  ) {
    return id + title;
  },
};

```

**Output:**
```jsx
const obj = {
  func(
    id,
    {
      blog: { title }
    }
  ) {
    return id + title;
  }
};

```

**Expected behavior:**
The result should like the es5 function property of the object.
```javascript
const obj = {
  func: function(id, { blog: { title } }) {
    return id + title;
  },
};
```

### PR DESCRIPTION
**Pull request by ericsakmar**
Adds `ObjectMethod` `ClassMethod`, and `ClassPrivateMethod` to the list of types that should/shouldn't cause line breaks. Now they behave like `ArrowFunctionExpression`.

fixes #6515

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Do we have issue? Also as written above please add changelog information

**Comment by bakkot** [comment]
While you're there can you add `classMethod` as well? [Test case is](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6UOOAZgK5RgAUAlgCYA0hOARqhAOZJsz0YqODgC+YgJSESZMgCc4MSnNJMcAahwChcANwyxJUSRDMQEAA4DomZKHRy5EAO4AFBwlsp0ANwhNTEHY5dDAAa0UAZQtQ+ihuZBg5SjgzAAsYAFtUAHU0wThMGLA4SM9Beh9BAE9kcGxAuMw4ORhXEO5M9GRydFRmswArTAAPACEQ8Kj0TLgAGTi4Hr6BkGGRyLjuYQBFSgh4Zf7UkBi5Zrk69nR2aq4oQIs5OJgcphg05AAOAAYzJ4gzRyIQsdSehRaPiWZgAjvt4O1LF4QFgALRQOBwRhYwIKOH0BTtdCdbpIXrHMzNTL0RLJE6YLa7eFLMkrE4wG5vRgfZAAJjMSXQ9FQWwAwhBMl06lBoNCQJRmgAVG5ecnNUSiIA)

```js
class A {
  func(id, { blog: { title } }) {
    return id + title;
  }
}
```

**Comment by ericsakmar** [comment]
Latest push updates the changelog and adds support for `classMethod`.

File: src/language-js/printer-estree.js [hunk 1]
```diff
@@ -1288,6 +1288,8 @@ function printPathNoParens(path, options, print, args) {
           parent.type !== "FunctionDeclaration" &&
           parent.type !== "FunctionExpression" &&
           parent.type !== "ArrowFunctionExpression" &&
+          parent.type !== "ObjectMethod" &&
+          parent.type !== "ClassMethod" &&
           parent.type !== "AssignmentPattern" &&
```
Comment (thorn0) [inline src/language-js/printer-estree.js]: Please add [`ClassPrivateMethod`](https://deploy-preview-6646--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6UOOAxAGYCuUYAFAJYAmANITgEaoQDmSHGIxio4OAL4SAlIRJkyAJzgxqC0ixwBqHEJFwA3HIklxIViAgAHIdEzJQ6BQogB3AAqOEdlOgBuEFjMQTgV0MABrZQBlSzDGKF5kGAVqOHMACxgAW1QAdXThOExYsDgor2FGX2EAT2RwbCD4zDgFGDdQ3iz0ZEp0VBbzACtMAA8AIVCI6PQsuAAZeLhe-sGQEdGo+N5RAEVqCHgVgbSQWIUWhXrOdE4aniggywV4mFyWGHTkAA4ABnNnhAWrlQpZ6s8iq1fMtzABHA7wDpWbwgLAAWigcDgzGxQSU8MYSg66C6PSQfRO5haWUYSRSp0w2z2COW5NWpxgt3ezE+yAATOZkuhGKhtgBhCBZbr1KDQGEgagtAAqt28FLWvlSAEkoDjYFEwC9rHhdVEYPdWeq4OJxEA).

Comment (ericsakmar) [reply src/language-js/printer-estree.js]: Done!

**Comment by ericsakmar** [comment]
Latest push adds support for ClassPrivateMethod.

**Comment by lydell** [comment]
@thorn0 Feel free to merge this if all looks good to you now!

**Comment by evilebottnawi** [comment]
@thorn0 can you open issue (maybe we already have issue)?

**Comment by thorn0** [comment]
@evilebottnawi Do you really think something should be done about it? Nested destructuring is not really readable when squeezed into a single line.

**Comment by thorn0** [comment]
Turns out it is intended, see https://github.com/prettier/prettier/pull/4267

**Comment by evilebottnawi** [comment]
@thorn0 I probably would still have opened issue and would like to receive feedback from other developers

For me this look better:
```js
const obj = {
  func(id, [{ blog: { title } }]) {
    return id + title;
  },
  func2(id, { foo: { blog: { title } } }) {
    return id + title;
  },
};
```

more heuristic

**Comment by thorn0** [comment]
@evilebottnawi It breaks if there is more than two levels of nested destructuring. E.g. if it has only two levels, it won't break:
```ts
const obj = {
  func(id, [{ blog: title }]) {
    return id + title;
  }
};
```
I think this heuristic is good enough.

Anyways, the issue is open: #2550
