### PR TITLE
Fix empty file error in json and graphql

### LINKED ISSUE #4448: Empty JSON/graphql file throws error
If a JSON file is empty or just has whitespace, Prettier throws an error. I think we should just output an empty file in this case. This issue causes https://github.com/azz/pretty-quick/issues/28.

**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACEAaEEAOMCW0AzsqAIYBOFEA7gAqUIkpkBuE+AJpiAEYVkwAazgwAyjkH4oAc2QwKAVzhZpROBRh0BMgLZlkAMzIAbdVgBWRAB4AhAcNFiyuuABlpcI6fMhJFdQpkECtoHhwKaRgAdS4YAAtkAA4ABiwIiHVogRxgiLhA1i8sCjgAR0V8Uu0yPQMkYzMVEHVdfHklZqJpGRM4AEVFCHhvJqwYMl5YzgTkACZxgXwTHoBhCF19YKhoYpBFdQAVSeZG9QBfc6A)
```sh
--parser json
```

**Input:**
```json
 
```

**Output:**
```json
SyntaxError: Unexpected token (1:2)
> 1 |  
    |  ^
```

### PR DESCRIPTION
**Pull request by ad1992**
Fixes #4448

### CODE REVIEW

**Comment by duailibe** [comment]
Can't we just do a check here? 
https://github.com/prettier/prettier/blob/fda7bf59f482c83a9db94bdc1111689a3e4ff474/src/main/core.js#L229

```js
if (!text) {
  return { formatted: "" };
}
```

**Comment by ad1992** [comment]
The spec for `graphql_empty_file` and `json_empty_file` are passing in local but not in travis. I am not sure why. Can someone rerun the specs.

**Comment by j-f1** [comment]
It looks like they’re still failing after a re-run @ad1992.

**Comment by duailibe** [comment]
> are passing in local but not in travis

Are you running with `AST_COMPARE=1` ?

**Comment by ad1992** [comment]
@duailibe yes you were right it was due to `AST_COMPARE=1`. Its fixed now.

File: tests_config/run_spec.js [hunk 1]
```diff
@@ -63,14 +63,15 @@ function run_spec(dirname, parsers, options) {
       if (AST_COMPARE) {
         const compareOptions = Object.assign({}, mergedOptions);
         delete compareOptions.cursorOffset;
-        const astMassaged = parse(input, compareOptions);
+        const astMassaged =
+          input && input.trim().length ? parse(input, compareOptions) : {};
```
Comment (duailibe) [inline tests_config/run_spec.js]: This might no be the correct fix for this either... maybe we should handle that in `prettier.__debug.parse`

File: tests/graphql_empty_file/__snapshots__/jsfmt.spec.js.snap [hunk 2]
```diff
@@ -0,0 +1,11 @@
+// Jest Snapshot v1, https://goo.gl/fbAQLP
+
+exports[`empty-file.graphql 1`] = `
+~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Comment (duailibe) [inline tests/graphql_empty_file/__snapshots__/jsfmt.spec.js.snap]: Let's keep these tests in `tests/empty/`.

Just edit `tests/empty/jsfmt.spec.js` to add `graphql` and `json` to the parsers

File: tests_config/run_spec.js (hunk 1 above)
Comment (ad1992) [reply tests_config/run_spec.js]: I reverted this as it got fixed when I rebased with master.

**Comment by ad1992** [comment]
@suchipi @duailibe can this be merged ?

**Comment by duailibe** [comment]
Can you fix the lint failure?

**Comment by ad1992** [comment]
@duailibe I had already run `yarn lint --fix` so there should not be any lint issue.
`size = size + tabWidth - (size % tabWidth);` got converted to this when I ran yarn lint --fix 
`size = size + tabWidth - size % tabWidth;`
should I revert it back ?

**Comment by lydell** [comment]
Well, Travis says that the parens should be there: https://travis-ci.org/prettier/prettier/jobs/387448061#L489

Perhaps your local node_modules is out of date? Try running `yarn` to update. Then I would guess `yarn lint --fix` would do the right thing.

**Comment by ad1992** [comment]
Yes `node_modules` was out of date. Its fixed now.

**Comment by ad1992** [comment]
@duailibe please review.
