### PR TITLE
Don't print an extra line break for arrow function with type parameter in assignment

### LINKED ISSUE #16067: Unstable formatting when placing comment before higher order generic TypeScript arrow function
**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzKmC8AOnpgPSmbGaYA8AKgDQB8AFAJQFObueYCMAbhAMQEAA4wAlumSgAhgCcFEAO4AFRQjTIQcgDYq5AT20iARgrlgA1nBgBlOQFs4AGUlQ4ybPrRxzljZ29mJWHgDmyDAKAK7+IH5OklGx8XAAHmJwCpIusPp02VCKknDaSD56fiJoEXpwAIoxEPDevvEAVmjp9nWNza0V7SIAjgNwaspi5bpoALSecAAmy8Ig0XKSehEAwhBOTnI6+nprtVDh9QCCMNGSZjHwatnunm1V8QAWME56AOqfSTwNChMBwexaIGSABuQKMOjAaFMIGhcQAklAVrB7GAchIrpj7DAjPV3tUQGJlH4-pYxDpKWVstCvCIPH4FDBJnJwocyfFQgp2TpiVk0LjJBI1pSPDA-pIljBPsgABwABhECjgY0kmq5PKOQw+IhgcjMcoVSqQACYRDE-HRTeVKuS4E4zMsVktXHILjFuXAAGIQBSHW4RY6PCAgAC+0aAA)

```sh
--parser typescript
```
and

```sh
--parser babel-ts
```

**Input:**

```tsx
const fn =
  // 
  <T,>() => () => 1;
```

**Output:**

```tsx
const fn =
  //

    <T,>() =>
    () =>
      1;

```

**Second Output:**

```tsx
const fn =
  //


    <T,>() =>
    () =>
      1;

```

**Expected output:**

```tsx
const fn =
  //
  <T,>() =>
  () =>
    1;

```

**Why?**

When formatting `const fn = <T,>() => () => 1;`, the output is:

```tsx
const fn =
  <T,>() =>
  () =>
    1;

```

so this would match that. Ideally though I would prefer

```tsx
const fn =
  //
  <T,>() => () => 1;

```

since it does fit on one line.

This also happens if the `//` is changed to a `/* */`.

Weirdly though, if the comment begins on the same line as the `=` operator, there is a difference between the comment type. A line comment is stable but also produces unexpected output, whereas a block comment is unstable for two formats but also produces unexpected output.

### Block comment on same line

**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzKmC8mA9AFQlEA6emAPACoB8AFAJQEOavuYCMA3CAA0ICAAcYAS3TJQAQwBO8iAHcACgoRpkIWQBtlsgJ5bhAI3mywAazgwAyrIC2cADISocZNj1o4Zi9a2dqKW7gDmyDDyAK5+IL6OEpExcXAAHqJw8hLOsHp0WVAKEnBaSN66vsJo4bpwAIrREPBePnEAVmhpdrUNTS3lbcIAjv1wqkqiZTpoALQecAAmS0IgUbISuuEAwhCOjrLaerqrNVBhdQCCMFESptHwqlluHq2VcQAWMI66AOofEngaBCYDgdk0gIkADdAYZtGA0CYQFDYgBJKDLWB2MDZcSXDF2GCGOpvKogURKXy-CyibQU0pZKGeYTuXzyGATWRhA6kuIheRs7REzJoHEScSrCnuGC-CSLGAfZAADgADMJ5HBRhINZzuYdBu9hDBZKZZfLFUgAEzCaK+OgmsoVMlwRymJbLRYuWTnaJcuAAMQg8gON3CRweEBAAF8o0A)

```sh
--parser typescript
```

**Input:**

```tsx
const fn = /**/
  <T>() => () => 1;
```

**Output:**

```tsx
const fn =
  /**/

    <T,>() =>
    () =>
      1;

```

**Second Output:**

```tsx
const fn =
  /**/


    <T,>() =>
    () =>
      1;

```

## Line comment on same line

**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzKmC8mA9EQDp6YA8AKgHwAUAlAbZky5gIwDcIANCAgAHGAEt0yUAEMATjIgB3AAqyEaZCCkAbBVICe6gQCMZUsAGs4MAMpSAtnAAyoqHGTZtaOMdMWr1oTMXAHNkGBkAV28QLztRMMjouAAPITgZUQdYbWp0qFlROHUkDy0vATQQrTgARQiIeHdPaIArNGTrKtr6xpLmgQBHHrgleSFizTQAWlc4ABN5-hBwqVEtEIBhCDs7KQ1tLSXKqGDqgEEYcNEjCPgldOdXJrLogAsYOy0AdVfReDRAmA4NY1H9RAA3P56DRgNCGEDgqIASSgC1g1jAGREZ1R1hgemqz3KICE8i8X1MQg0pKK6XBbgELi8MhgoykwV2ROigRkzI0+LSaExohES1JLhgX1Ecxgr2QAA4AAwCGRwIaiVVsjl7PovAQwKRGKUyuVIABMAgiXmohuKpWJcDsRnmCzmjikJwi7LgADEIDJdpcQvtbhAQABfcNAA)

```sh
--parser typescript
```

**Input:**

```tsx
const fn = //
  <T>() => () => 1;
```

**Output:**

```tsx
const fn = //

    <T,>() =>
    () =>
      1;

```

**Second Output:**

```
✓ Second format is unchanged.
```

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #16067

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-js/print/arrow-function.js [hunk 1]
```diff
@@ -119,15 +120,23 @@ function printArrowFunction(path, options, print, args = {}) {
     signatureDocs,
     shouldBreak: shouldBreakChain,
   });
-  let shouldBreakSignatures;
+  let shouldBreakSignatures = false;
```
Comment (sosukesuzuki) [inline src/language-js/print/arrow-function.js:123]: Jus refactoring: set the default value.

**Review by fisker — APPROVED** [review]
