### PR TITLE
fix(markdown): print multiline content correctly in footnoteDefinition

### LINKED ISSUE #3786: Markdown: Footnotes should be treated as blocks
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBlCBbOACeAPGAOgG0A9AMygF0AdKOsyqpbACTgCccBLAZ2wCG2chAgwoYnAHcAFtzAzs3KGAA2AVwAmcfpG2E6dbMewADcx15GTlbBgHKAFAEpswayZMAHDspiqoAEJHGhAYOX4+bF5MHAAldV4YQNDnAG4PbABfTPNTOhAAGhAILxhuaF5kUAEODggpAAVahCqUAQA3CG5NIpABJORyAVVeOGKAIw4BMABrOBhULxnlAHNkGA51cZBNCDAhkbHi5TGOGEbp1ftD0Z2AK148ACFpuYXUASwAGWU4W+OJXUMC8wIATACdstLJxkCB7BxZnspFA+j4-AB1HrhZAADgADMUfBAxhjpl44T4dJwOv9ilwAI7qbhcS4Ca4CSHFMYYbgbLY7XhrVRwACK6kkXLCAgmWM0OKQABZipsHKo1gBhTA3FASKB0kCJOAAFRlbWGdyyWSAA)
```sh
--parser markdown
--tab-width 4
```

**Input:**

````markdown
Some text.[^fn]

[^fn]: Here is a footnote which includes code.

    ```rs
    fn main() {
        println!("this is some Rust!");
    }
    ```
````

**Output:**

````markdown
Some text.[^fn]

[^fn]: Here is a footnote which includes code.

```rs
fn main() {
    println!("this is some Rust!");
}
```
````

**Expected behavior:**

The original block is unchanged:

````markdown
Some text.[^fn]

[^fn]: Here is a footnote which includes code.

    ```rs
    fn main() {
        println!("this is some Rust!");
    }
    ```
````

### PR DESCRIPTION
**Pull request by ikatyang**
Fixes #3786 

---

**Prettier pr-3787**
[Playground link](https://deploy-preview-3787--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBlCBbOACeAPGAOgG0A9AMygF0AdKOsyqpbACTgCccBLAZ2wCG2chAgwoYnAHcAFtzAzs3KGAA2AVwAmcfpG2E6dbMewADcx15GTlbBgHKAFAEpswayZMAHDspiqoAEJHGhAYOX4+bF5MHAAldV4YQNDnAG4PbABfTPNTOhAAGhAILxhuaF5kUB8-AHVuTXDkAA4ABmKYAQAjBqaZZAAWYt5lAHNVOABFdUlkcgFVXjhOjgdVcYBhTHtkEAkoOCKQbrWwAGs4GFQvATBx5BgOdRWQACtePAAhM8vrgSwABllEckAslq9bpZOHt7BxzpoIFIoMdlhhuI9nq9EnAACo9KpgxbLYrKZYcGAABTWY12RIhxS4AEd1NwuNSBLSBPNiZCOBBlnU1l49j4dJwAG5HYoCDj8qSU2UIQkgAQSiCNY6IsA8hmqpK6kkldQwLwmgBMhrgWSyQA)
```sh
--parser markdown
--tab-width 4
```

**Input:**
````markdown
Some text.[^fn]

[^fn]: Here is a footnote which includes code.

    ```rs
    fn main() {
        println!("this is some Rust!");
    }
    ```

````

**Output:**
````markdown
Some text.[^fn]

[^fn]: Here is a footnote which includes code.

    ```rs
    fn main() {
        println!("this is some Rust!");
    }
    ```

````

### CODE REVIEW

File: src/language-markdown/printer-markdown.js [hunk 1]
```diff
@@ -295,13 +292,35 @@ function genericPrint(path, options, print) {
...
+                        concat([
+                          ifBreak(concat([line, line]), ""),
+                          childPath.call(print)
+                        ])
+                      )
+                    : childPath.call(print)
+              })
+            ),
+            nextNode && nextNode.type === "footnoteDefinition"
+              ? ifBreak(line, "")
```
Comment (j-f1) [inline src/language-markdown/printer-markdown.js]: Can this be a `softline`?

Comment (ikatyang) [reply src/language-markdown/printer-markdown.js]: There's no actual differences between `line` and `softline` in this context since it's only printed if break, and I found it's also used in other printer this way, so I think it should be fine? 

https://github.com/prettier/prettier/blob/ea5bfb44e4faa52d9ad0b7ccf992a185de851d8d/src/language-js/printer-estree.js#L2295

Comment (j-f1) [reply src/language-markdown/printer-markdown.js]: @ikatyang From what I’ve seen, `softline` is equivalent to `ifBreak(line, "")`. Is that incorrect?

Comment (ikatyang) [reply src/language-markdown/printer-markdown.js]: Oops, I thought you meant `ifBreak(line)` -> `ifBreak(softline)`. Fixed.

File: tests/markdown_footnoteDefinition/__snapshots__/jsfmt.spec.js.snap [hunk 2]
```diff
@@ -3,7 +3,121 @@
...
+[^a]: a
+[^a]: a
+
+---
+
+[^a]: a
+[^a]: a
+[^a]: a
+[^a]:
+
```
Comment (azz) [inline tests/markdown_footnoteDefinition/__snapshots__/jsfmt.spec.js.snap]: This blank line looks odd to me.

Comment (ikatyang) [reply tests/markdown_footnoteDefinition/__snapshots__/jsfmt.spec.js.snap]: I personally think it'd better to have leading blank line there as it's a block-level node, what do you think?

1. leading + trailing
    ```md
    [^something]:

        ~~~
        hello world
        ~~~

        > blah blah blah blah blah blah blah blah
        > blah blah blah blah blah blah blah blah

    [^something]:

        ~~~
        hello world
        ~~~

        > blah blah blah blah blah blah blah blah
        > blah blah blah blah blah blah blah blah

    ```
    ```md
    [^something]:

        > blah blah blah blah blah blah blah blah
        > blah blah blah blah blah blah blah blah

    [^something]:

        > blah blah blah blah blah blah blah blah
        > blah blah blah blah blah blah blah blah

    ```
2. trailing
    ```md
    
    [^something]:
        ~~~
        hello world
        ~~~

        > blah blah blah blah blah blah blah blah
        > blah blah blah blah blah blah blah blah

    [^something]:
        ~~~
        hello world
        ~~~

        > blah blah blah blah blah blah blah blah
        > blah blah blah blah blah blah blah blah

    ```
    ```md
    [^something]:
        > blah blah blah blah blah blah blah blah
        > blah blah blah blah blah blah blah blah

    [^something]:
        > blah blah blah blah blah blah blah blah
        > blah blah blah blah blah blah blah blah

    ```

Comment (azz) [reply tests/markdown_footnoteDefinition/__snapshots__/jsfmt.spec.js.snap]: Ah, ok. lgtm then.
