### PR TITLE
Fix flow union params

### LINKED ISSUE #1249: Flow functions with union params
It looks like flow function types lose necessary parens with overloaded params.

#### Before
```js
(Grip | Function) => ObjectClient,
```

#### After
```js
Grip | Function => ObjectClient,
```

#### test case

```diff
diff --git a/tests/flow/union/__snapshots__/jsfmt.spec.js.snap b/tests/flow/union/__snapshots__/jsfmt.spec.js.snap
index db4de98..4cf1f37 100644
--- a/tests/flow/union/__snapshots__/jsfmt.spec.js.snap
+++ b/tests/flow/union/__snapshots__/jsfmt.spec.js.snap
@@ -421,6 +421,8 @@ type Bar = () => (C | string); // workaround
 function f() { return ""; }
 function bar(x:Bar) { }
 bar(f);
+
+type Foo = ( string | number ) => number
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 var C = require("test-lib");

@@ -443,6 +445,8 @@ function f() {
 function bar(x: Bar) {}
 bar(f);

+type Foo = string | number => number;
+
 `;

 exports[`test-lib.js 1`] = `
diff --git a/tests/flow/union/test.js b/tests/flow/union/test.js
index 5acbee0..d44d566 100644
--- a/tests/flow/union/test.js
+++ b/tests/flow/union/test.js
@@ -16,3 +16,5 @@ type Bar = () => (C | string); // workaround
 function f() { return ""; }
 function bar(x:Bar) { }
 bar(f);
+
+type Foo = ( string | number ) => number
```

### PR DESCRIPTION
**Pull request by jasonLaster**
Resolves #1249

My guess is that my fix is probably too specific. I wanted to share it early for feedback.

### CODE REVIEW

**Comment by jasonLaster** [comment]
Also, for what it is worth I found it helpful to use the `docs/index.html` as a debugging environment because i could quickly add a breakpoint and debug. I don't if it would be nice to add this strategy in the README as well.

File: tests/flow/union/issue-1249.js [hunk 1]
```diff
@@ -0,0 +1 @@
+type Bar = ( number | string ) => number;
```
Comment (existentialism) [inline tests/flow/union/issue-1249.js]: Probably want to move this outside of the flow folder, as these tests are directly imported from flow and will be sync'd in the future.

Maybe as a fixture under `flow_parens`?

(We can also move `flow_return_arrow/parens` as a fixture into that)?

File: src/printer.js [hunk 2]
```diff
@@ -2291,6 +2291,7 @@ function printFunctionParams(path, print, options, expandArg) {
       parent.type === "TypeAlias") &&
     fun[paramsField].length === 1 &&
     fun[paramsField][0].name === null &&
+    fun[paramsField][0].typeAnnotation.type !== "UnionTypeAnnotation" &&
```
Comment (existentialism) [inline src/printer.js]: Will want to cover `IntersectionTypeAnnotation` too?

File: tests/flow/union/issue-1249.js (hunk 1 above)
Comment (vjeux) [inline tests/flow/union/issue-1249.js]: Yes, please add them outside of the flow folder. I don't really care where :)

File: src/printer.js (hunk 2 above)
Comment (vjeux) [inline src/printer.js]: I've been looking at the list and I think it makes more sense to have a whitelist rather than blacklist. Do you mind updating your code with the list below? Then we can merge it. Thanks!

Those are all the ones I could find that are just raw strings. Flow appears to not need parenthesis for a lot more but I think we should err on the safe side and add parenthesis for the rest.

```js
case "NullLiteralTypeAnnotation":
  return "null";
case "ThisTypeAnnotation":
  return "this";
case "NumberTypeAnnotation":
  return "number";
case "VoidTypeAnnotation":
  return "void";
case "NullTypeAnnotation":
  return "null";
case "EmptyTypeAnnotation":
  return "empty";
case "AnyTypeAnnotation":
  return "any";
case "MixedTypeAnnotation":
  return "mixed";
case "BooleanTypeAnnotation":
  return "boolean";
case "BooleanLiteralTypeAnnotation":
  return "" + n.value;
case "StringLiteralTypeAnnotation":
  return nodeStr(n, options);
```

Comment (jasonLaster) [inline src/printer.js]: Do you mean something like this?

```js
const typeAnnotationType = fun[paramsField][0].typeAnnotation.type;
["UnionTypeAnnotation", "NullLiteralTypeAnnotation", "ThisTypeAnnotation"].includes("ThisTypeAnnotation")
```

File: tests/flow/union/issue-1249.js (hunk 1 above)
Comment (jasonLaster) [inline tests/flow/union/issue-1249.js]: ahh - that's cool.

File: src/printer.js (hunk 2 above)
Comment (vjeux) [inline src/printer.js]: yeah:

```js
["...", ... all that list ..., "..."].includes(typeAnnotationType)
```

**Comment by vjeux** [comment]
If you have time to send an update in the next few hours that would be awesome. I'd like to do a 1.1.0 today with all the fixes that have been reported.

**Comment by jasonLaster** [comment]
doing it now

**Comment by jasonLaster** [comment]
Updated. I'm not sure if there is a better place to list out the flow whitelist. Also, a couple of other snapshots changed, but I believe that's the desired behavior.

File: src/printer.js [hunk 3]
```diff
@@ -2285,12 +2285,29 @@ function printFunctionParams(path, print, options, expandArg) {
...
+    "NumberTypeAnnotation",
+    "VoidTypeAnnotation",
+    "NullTypeAnnotation",
+    "EmptyTypeAnnotation",
+    "AnyTypeAnnotation",
+    "MixedTypeAnnotation",
+    "BooleanTypeAnnotation",
+    "BooleanLiteralTypeAnnotation",
+    "StringLiteralTypeAnnotation",
+  ];
```
Comment (vjeux) [inline src/printer.js]: This is perfect

File: src/printer.js [hunk 4]
```diff
@@ -2285,12 +2285,29 @@ function printFunctionParams(path, print, options, expandArg) {
   }
 
   const parent = path.getParentNode();
+
+  const flowTypeAnnotations = [
+    "UnionTypeAnnotation",
```
Comment (vjeux) [inline src/printer.js]: We don't want UnionTypeAnnotation here, right?

File: src/printer.js [hunk 5]
```diff
@@ -2285,12 +2285,29 @@ function printFunctionParams(path, print, options, expandArg) {
...
+    "NullLiteralTypeAnnotation",
+    "ThisTypeAnnotation",
+    "NumberTypeAnnotation",
+    "VoidTypeAnnotation",
+    "NullTypeAnnotation",
+    "EmptyTypeAnnotation",
+    "AnyTypeAnnotation",
```
Comment (vjeux) [inline src/printer.js]: any is there

File: src/printer.js [hunk 6]
```diff
@@ -2285,12 +2285,29 @@ function printFunctionParams(path, print, options, expandArg) {
...
+    "MixedTypeAnnotation",
```
Comment (vjeux) [inline src/printer.js]: and mixed as well. Something seems wrong with your logic.

Comment (jasonLaster) [inline src/printer.js]: oh, i was doing a whitelist, this looks like a blacklist :)

**Comment by jasonLaster** [comment]
hmm, I'm not happy with the direction this is going. It seems like we'll need to add more types to types to the exclude list :)

**Comment by jasonLaster** [comment]
Wow, check it out! a tidy diff

**Comment by vjeux** [comment]
The flow team is adding new types regularly, I'm feeling much better about having a whitelist rather than a blacklist that will fail for new new types...

**Comment by vjeux** [comment]
Looks like includes doesn't work on node 4 :( can you use indexOf instead? Then we're good to go, thanks a ton for the fix.

**Comment by vjeux** [comment]
Thanks!
