### PR TITLE
Fix closing parens on multi-line intersection/union type

### LINKED ISSUE #3403: Closing parenthesis of multi-line intersection/union type
**Prettier 1.9.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAyjAQ3mwF5tgAdKbG7AZwAsCAnOAEwAVmItn0lsBKGioBfbADJsACiq1sAH3LY2ASzphmqgLaqoQmAIogAYgHkzxgNzYAZhAgChabKLm0lwFes069BoxAAIQBBACVrbAAjFidhV3caT28NLV19WEDQgC1ImIAvOJdxKgBKKyoQABoQHhhVaDpkUBZuAHcOFgQmlAIANwhVNmqQAjoYZFsCABs6OBqo5gIwAGs4GFwMZb0Ac2QYZgBXeZA2CDBJmbmavTm+LgId7QJL2ZOAKzoADyCl1fXcARtHAADJ6OCva61Q4wDAwgBMkJOW2Yd2QqEwcFSqgwExqGC0sAA6kMYAxkAAOAAM+O4cyJSww6IJWLgzD6EJqrAAjodVKwHk8Xkgpm8anNdPsjic6LtpnAAIqHCDwJE1QhRElsMnIAAs6qWqmmuwAwhBtM90VBoJyQIc5gAVAhRHqiuaiURAA)
```sh
--parser typescript
--tab-width 4
```

**Input:**

```tsx
type State = {
    sharedProperty: any;
} & (
    | { discriminant: "FOO"; foo: any }
    | { discriminant: "BAR"; bar: any }
    | { discriminant: "BAZ"; baz: any } 
);
```

**Output:**

```tsx
type State = {
    sharedProperty: any;
} & (
    | { discriminant: "FOO"; foo: any }
    | { discriminant: "BAR"; bar: any }
    | { discriminant: "BAZ"; baz: any });
```

**Expected behavior:**

```diff
type State = {
    sharedProperty: any;
} & (
    | { discriminant: "FOO"; foo: any }
    | { discriminant: "BAR"; bar: any }
-   | { discriminant: "BAZ"; baz: any });
+   | { discriminant: "BAZ"; baz: any }
+);
```

### PR DESCRIPTION
**Pull request by existentialism**
Fixes #3403.

### CODE REVIEW

File: src/printer.js [hunk 1]
```diff
@@ -2324,6 +2325,27 @@ function genericPrintNoParens(path, options, print, args) {
         join(concat([line, "| "]), printed)
       ]);
 
+      let hasParens;
+
+      if (n.type === "TSUnionType") {
```
Comment (existentialism) [inline src/printer.js]: Not really happy with this, but it seemed better to keep this logic here than spread it into `TSParenthesizedType`?

Comment (suchipi) [reply src/printer.js]: Feels about the same either way to me personally
