### PR TITLE
Fix flow union comments

### LINKED ISSUE #849: Comments in flow union are not displayed correctly
Prettier 0.19
The following 

```js
// TODO: Not sure that all of these are actually needed. Remove some?
type UploadState<E, EM, D>
    // The upload hasnt begun yet
    = {type: "Not_begun"}
    // The upload timed out
    | {type: "Timed_out"}
    // The reset timed out
    | {type: "Reset_timed_out"}
    // Still uploading to aws3
    | {type: "Uploading_AWS3"}
    // Completed uploading to aws3
    | {type: "Completed_AWS3"}
    // Canceled the upload to aws3
    | {type: "Canceled_AWS3"}
    // Paused the upload to aws3
    | {type: "Paused_AWS3"}
    // The upload to aws3 is waiting
    | {type: "Waiting_AWS3"}
    // Starts procedure of creating a post with mutations and such
    | {type: "Creating_post"}
    // Failed somewhere on the line
    | {type: "Failed", error: E, errorMsg: EM}
    // Uploading to aws3 and CreatePostMutation succeeded
    | {type: "Success", data: D}
```

Gives different output when you save and then save again. 

first save 
```js
// TODO: Not sure that all of these are actually needed. Remove some?
type UploadState<E, EM, D> = /* The upload hasnt begun yet*/

    | { type: "Not_begun" }
    | /* The upload timed out*/
    { type: "Timed_out" }
    | /* The reset timed out*/
    { type: "Reset_timed_out" }
    | /* Still uploading to aws3*/
    { type: "Uploading_AWS3" }
    | /* Completed uploading to aws3*/
    { type: "Completed_AWS3" }
    | /* Canceled the upload to aws3*/
    { type: "Canceled_AWS3" }
    | /* Paused the upload to aws3*/
    { type: "Paused_AWS3" }
    | /* The upload to aws3 is waiting*/
    { type: "Waiting_AWS3" }
    | /* Starts procedure of creating a post with mutations and such*/
    { type: "Creating_post" }
    | /* Failed somewhere on the line*/
    { type: "Failed", error: E, errorMsg: EM }
    | /* Uploading to aws3 and CreatePostMutation succeeded*/
    { type: "Success", data: D };
```

second save 
```js
// TODO: Not sure that all of these are actually needed. Remove some?
type UploadState<E, EM, D> /* The upload hasnt begun yet*/ =
    | { type: "Not_begun" } /* The upload timed out*/
    | { type: "Timed_out" } /* The reset timed out*/
    | { type: "Reset_timed_out" } /* Still uploading to aws3*/
    | { type: "Uploading_AWS3" } /* Completed uploading to aws3*/
    | { type: "Completed_AWS3" } /* Canceled the upload to aws3*/
    | { type: "Canceled_AWS3" } /* Paused the upload to aws3*/
    | { type: "Paused_AWS3" } /* The upload to aws3 is waiting*/
    | {
          type: "Waiting_AWS3",
      } /* Starts procedure of creating a post with mutations and such*/
    | { type: "Creating_post" } /* Failed somewhere on the line*/
    | {
          type: "Failed",
          error: E,
          errorMsg: EM,
      } /* Uploading to aws3 and CreatePostMutation succeeded*/
    | { type: "Success", data: D };
```

### PR DESCRIPTION
**Pull request by vjeux**
The comments infra has been architected with trailing operators and fails for leading `|`. Instead of having leading comments, we can put trailing comments on the previous one and use the same technique as assignment to deal with the indentation.

Fixes #849

### CODE REVIEW

**Comment by vjeux** [comment]
cc @cpojer, this was also an issue on the jest run.

File: tests/comments/flow_union.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+type UploadState<E, EM, D>
+  // The upload hasnt begun yet
```
Comment (vjeux) [inline tests/comments/flow_union.js]: Notice that it also works with comments being before the `=` sign!

Comment (jlongster) [inline tests/comments/flow_union.js]: I feel like it's better that we encourage this:

```js
type UploadState<E, EM, D> =
  // comment
  | { type: "etc" }
  // comment
  | { type: "etc etc"}
```

That seems a lot more consistent and would make the code in this PR simpler, right?

Comment (vjeux) [inline tests/comments/flow_union.js]: I didn't add any code to handle this case (and wasn't going to). I just implemented the fix for your example and as a happy coincidence it also fixed this one.

File: src/printer.js [hunk 2]
```diff
@@ -1610,15 +1610,21 @@ function genericPrintNoParens(path, options, print) {
...
+      const token = isIntersection ? "&" : "|";
+      const printed = concat([
+        ifBreak(concat([shouldIndent ? line : "", token, " "])),
+        join(concat([line, token, " "]), types)
+      ]);
+
+      if (!shouldIndent) {
+        return group(printed);
+      }
+      return group(indent(options.tabWidth, printed));
```
Comment (jlongster) [inline src/printer.js]: You could keep the code more like it was before and just do `indent(shouldIndent ? options.tabWidth 0, ...)`. I think it reads better when the doc is all one expression

Comment (jlongster) [inline src/printer.js]: Can you explain how the parent is doing the indentation if there's a comment?

Comment (vjeux) [inline src/printer.js]: Will do

File: src/printer.js [hunk 3]
```diff
@@ -1698,8 +1704,13 @@ function genericPrintNoParens(path, options, print) {
         "type ",
         path.call(print, "id"),
         path.call(print, "typeParameters"),
-        " = ",
-        path.call(print, "right"),
+        " =",
+        hasLeadingOwnLineComment(options.originalText, n.right)
+          ? indent(
```
Comment (vjeux) [inline src/printer.js]: Okay, so this is a bit tricky, the comments are printed around the node. So from this code perspective, `printed` is `// comment \n | type` so we need to indent here and put a \n so that it goes to the next line.

If we try to put the indent inside the node, then it would look

```js
type X =
// comment
  | type
```

notice that the `// comment` is not indented because outside.

Now, if you don't have any comments, then you are not sure if the node is going to be expanded or not, so you can't force a hardline and want to let the child decide how to indent itself, if needs be.

Comment (jlongster) [inline src/printer.js]: I see. Yeah, that makes sense. Unfortunate complexity, but I'm hoping once all this works, we'll never need to touch this code again haha

Comment (vjeux) [inline src/printer.js]: Yeah, that's definitely the plan! :p

File: src/printer.js [hunk 4]
```diff
@@ -1614,15 +1614,18 @@ function genericPrintNoParens(path, options, print) {
...
+      const shouldIndent = !(parent.type === 'TypeAlias' &&
+        hasLeadingOwnLineComment(options.originalText, n));
+
+      const token = isIntersection ? "&" : "|";
+      const printed = concat([
+        ifBreak(concat([shouldIndent ? line : "", token, " "])),
+        join(concat([line, token, " "]), types)
+      ]);
+
+      return group(shouldIndent ? indent(options.tabWidth, printed) : printed);
```
Comment (jlongster) [inline src/printer.js]: I was talking about something like this. It's nice to keep is all a single expression as I think it's more clear how it's laid out:

```js
return group(
  indent(
    shouldIndent ? options.tabWidth : 0,
    concat([
      ifBreak(concat([line, isIntersection ? "&" : "|", " "])),
      join(concat([line, isIntersection ? "&" : "|", " "]), types)
    ])
  )
);
```

I copied the code from before your PR so if you've tweaked this it may not have your updates, but I don't see why this shouldn't work.

Comment (vjeux) [inline src/printer.js]: Sure, I can do that
