### PR TITLE
Throw errors for invalid `TSEmptyBodyFunctionExpression` node

### LINKED ISSUE #12963: Prettier parses `({ methodName() })` incorrectly
**Prettier 2.6.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKYACAtnGALCAEwDkBDHVASgwF9KQAaECABxgEtoBnZUUgJ34QA7gAUBCHilIAbYaQCePJgCN+pMAGtcAZXJwAMuyhxkAM1lc4q9Vt0sNxgObIY-AK7WQcLCriFCfwNSKCd3Uic4ADEIfixSGA5Q5BBSdxgIRhA8GCwZAHU8dnguBzA4HUli9gA3YoUUsC5lEGMrfhhRdSd480svACsuAA8dZxk4AEV3CHg+mSsmB352lJgFFjguMH52NiyWXdh89kJ8ZAAOAAYloSt89RYUw624fhrTJgBHGfgu1ikqS4AFoTP5-Fl+HAfuwoV0Ir0kBYFl4rFh2K4PKjxlNfqYkf0mDBSCoTmc8MgAExE9TsGTOADCECwiO8XAArFl3FYACokqTIxYgGqeACSUECsB0Oz2MAAghKdOsJvMrDQaEA)

```sh
--parser typescript
```

**Input:**

```tsx
({ methodName() })
```

**Output:**

```tsx
({ methodName(); });

```

**Expected behavior:**
The code inputted is invalid and shouldn't be parsed. Prettier recognizes this as an object because it can be turned into a multiline object and Prettier still has invalid output.

**Prettier 2.6.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKYAdKACbBbOGACwgBMA5AQwNQEosBfWkAGhAgAcYBLaAZ2ShKAJ2EQA7gAURCASkoAbcZQCeAtgCNhlMAGtCAZWpwAMtyhxkAM0V84m7XsMcd5gObIYwgK72QcPA04UlJgk0ooN29KNzgAMQhhPEoYHkjkEEpvGAhWECIYPAUAdSJueD4XMDgDWXLuADdylQywPnUQczthGEltN2TrWz8AKz4ADwN3BTgARW8IeCGFOzYXYW6MmBUOOD4wYW4uPI5D2GLuUmJkAA4ABjWxO2LtDgzTvbhhBss2AEcFvA+pw5Jk+ABaCzBYJ5YRwAHcOF9GKDJA2FZ+Ox4bieHyY6ZzQGWNHDNgwSgaC5XIjIABMZO03AU7gAwhA8Kj-HwAKx5bx2AAqFLk6NWIAavgAklBQrADAcjjAAIIygzbGbLOwMBhAA)

```sh
--parser typescript
```

**Input:**

```tsx
({
  methodName()
})
```

**Output:**

```tsx
({
  methodName();,
});

```

### PR DESCRIPTION
**Pull request by fisker**
## Description

Fixes #12963

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-js/parse/postprocess/typescript.js [hunk 1]
```diff
@@ -73,9 +73,10 @@ function throwErrorForInvalidNodes(ast, options) {
...
       return;
     }
+
     throwErrorForInvalidDecorator(tsNode, esTreeNode, tsNodeToESTreeNodeMap);
     throwErrorForInvalidAbstractProperty(tsNode, esTreeNode);
   });
 }
 
-module.exports = { throwErrorForInvalidNodes };
+module.exports = { throwErrorForInvalidNodes, throwSyntaxError };
```
Comment (sosukesuzuki) [inline src/language-js/parse/postprocess/typescript.js:82]: Can we move `throwSyntaxError` to other file like a `parse/postprocess/throw-syntax-error.js`?

Comment (sosukesuzuki) [inline src/language-js/parse/postprocess/typescript.js:82]: Can we move `throwSyntaxError` to other file like a `parse/postprocess/throw-syntax-error.js`?

**Review by sosukesuzuki — APPROVED** [review]
