### PR TITLE
Fix printing of Flow type number literals (#1128)

### LINKED ISSUE #1128: Hexadecimals are replaced with decimals
It appears that numbers written in hexadecimal where the value is below some threshold are replaced with decimals, while others are left as hexadecimal. For example I had `const FOO = 0x01;` and it was replaced with `const FOO = 1;`. While the conversion in this example is straightforward, ideally numbers would *always* be left in their original form. In this case I'm implementing a protocol and it's helpful to be able to copy-paste hex values and grep for them in the protocol specification.

### PR DESCRIPTION
**Pull request by josephsavona**
Fixes #1128.

### CODE REVIEW

File: src/printer.js [hunk 1]
```diff
@@ -1746,7 +1746,11 @@ function genericPrintNoParens(path, options, print) {
     case "NumberLiteralTypeAnnotation":
       assert.strictEqual(typeof n.value, "number");
 
-      return "" + n.value;
+      if (n.extra != null) {
+        return printNumber(n.extra.raw);
+      } else {
+        return printNumber(n.raw);
+      }
```
Comment (josephsavona) [inline src/printer.js]: Running the existing tests shows that sometimes `n.extra` is undefined, sometimes not, hence the two cases here.

Comment (vjeux) [inline src/printer.js]: Yeah, that's a difference between babylon and flow parsers.

**Comment by vjeux** [comment]
Thanks!
