### PR TITLE
fix: css variables and scss interpolation

### LINKED ISSUE #4470: SCSS parser adds space before SCSS variable in `var(--#{item})` construction
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKACDABOBDMACwwBIYBPABzgwEtMBnAVzDDgYYBoMATPKAOZwATtwDueYVHoDu9AGYQMwdFiwAyALSaAxMDJU4AX2Wq1WbQCMBSDADdJACm16D1IwEoA3GaxH0vhhauvoU7kiEEHYippjmGFY29k4uoYZG2gA2tAKEMN6B-lCBwa5hxkiKYEwMsfEJmta2DsLOIW7GWTl5BXF+AX1BqR1GSAQwtNF18YnNKe3lnj6DJmpmRSCcIBCUE9AMyKCSwhBiAAqSCAcoeHYQtDybIJbCBADWcDAAypQEMsgwYRMOBbegMEQwM6vAQAWzwyHkeEy4K2ACsGAAPABCrzAH2+eBhcAAMvQ4AikSiQL9hODhMgQAwwBwnpRhPQYAB1B4wQjIAAcAAYtmyIODOa9KAy2ewRNEnsI4ABHJi0RVQvCw+GVSkgxlwGG0AFAvUMGSZOAARSYEHgFORepgeEs3J4vOQACYtoC8LRsoIAMIQGFwhlQaDkrY1OAAFWd10RDqMRiAA)
```sh
--parser scss
```

**Input:**
```scss
  @each $type in success, danger, warning, info {
    &--#{$type} {
      --bg: var(--#{$type});
    }

    &--#{$type}:hover {
      --bg: var(--#{$type}--light);
    }

    &--#{$type}:focus {
      --bg: var(--#{$type}--light);
    }

    &--#{$type}:active {
      --bg: var(--#{$type});
    }    
  }

```

**Output:**
```scss
@each $type in success, danger, warning, info {
  &--#{$type} {
    --bg: var(-- #{$type});
  }

  &--#{$type}:hover {
    --bg: var(-- #{$type}--light);
  }

  &--#{$type}:focus {
    --bg: var(-- #{$type}--light);
  }

  &--#{$type}:active {
    --bg: var(-- #{$type});
  }
}

```
**Expected behavior:**
As you may not probably noticed prettier adds space before the `#{type}` when it's inside the var CSS properties accessor function. Making `var(-- success)` etc.
This leads to code that is not working properly.
So to be 100% explicit:
Before: `--bg: var(--#{$type});`
After: `--bg: var(-- #{$type});`

### PR DESCRIPTION
**Pull request by evilebottnawi**
fixes #4470

### CODE REVIEW

File: src/language-css/printer-postcss.js [hunk 1]
```diff
@@ -452,7 +452,7 @@ function genericPrint(path, options, print) {
         const isNextRightCurlyBrace =
           iNextNode.type === "value-word" && iNextNode.value === "}";
 
-        // Ignore interpolation in SCSS (i.e. ``#{variable}``)
+        // Ignore interpolation in SCSS (i.e. `#{variable}`)
```
Comment (evilebottnawi) [inline src/language-css/printer-postcss.js]: Just fix double '`'
