### PR TITLE
Handle CSS selectors with comment-like strings

### LINKED ISSUE #7850: Incorrect format in css when selector attribute value is a URL
**Prettier 2.0.1**

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDA2gCwE5wGYC8AOiJjDAA5ID01cAHqgLYUA2cAdJEyQLoAEwfgBMAlgGc2qAJ5J+UaHH4BfEABoQECjFHRxyUKmzYIAdwAKRhPpSpWpmfo0AjbKjABrODADKFd6JQAObIMNgArnAaZEysAOqYovCS7nA+1kmiAG5J0sjg4k4ggeJw2DDmbkFMqMh4dqUaAFbi9ABCbp7ePsxwADKBcHUNUSAt9D6BQewAiuEQ8MOsjSD+2KXY+WCF6qvYgTBxosIwmMgAHAAMGhQmpXFuFPm3cBtZQxoAjvPwlVo2aHEAFooHA4MJwbtcN9RLhKqhqrUkPVlqNSkxRKEImiprMfkNkSMNDBUM4jiczkgAEzEtyiVhTADCECYNXyrwArLtwqUACqkmwolZZSIASSgENgPjA+20AEEJT4YNJ2EtSsplEA)

```sh
# Options (if any):
--single-quote
```

**Input:**

```css
a[href="http://example.com"] { display: none }
```

**Output (v2.0.1):**

```css
a[href="http://example.com"]
{
  display: none;
}
```

**Output (v1.19.1):**

```css
a[href="http://example.com"] {
  display: none;
}
```
**Expected behavior:**

The double quotes should have been changed to single quotes and the opening brace should have been left in the same line as the selector.

In v1.19.1 the bug with the quotes was present but the bug with the opening brace is new in v2.0.1.

**Expected output:**
```css
a[href='http://example.com'] {
  display: none;
}
```

### PR DESCRIPTION
**Pull request by kovsu**
## Description

ref: https://github.com/prettier/prettier/issues/7850#issuecomment-603259143

Strip quoted content before testing selectors for `//` so comment detection skips attribute values like `href="//"`.

Fixes #7850

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: src/language-css/parse/parse-selector.js [hunk 1]
```diff
@@ -2,11 +2,18 @@ import PostcssSelectorParser from "postcss-selector-parser/dist/processor.js";
 import { addTypePrefix } from "./utils.js";
 
 function parseSelector(selector) {
+  // Clean the content in quotes,
+  // avoid the next regex to match quotes content
+  const cleanContent = selector.replaceAll(
+    /"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'/gu,
```
Comment (fisker) [inline src/language-css/parse/parse-selector.js]: This is confusing. Do you understand this regexp?

Comment (kovsu) [reply src/language-css/parse/parse-selector.js]: 😂 I just ask copilot to do this.

Comment (kovsu) [reply src/language-css/parse/parse-selector.js]: replace it with `/"[^"]*"|'[^']*'/gu` ?

Comment (fisker) [reply src/language-css/parse/parse-selector.js]: Better.

**Comment by fisker** [comment]
Please add changelog, and don't forget to do so in future PRs.

**Review by fisker — APPROVED** [review]
