### PR TITLE
Typescript: Fix `prettier-ignore`d mapped types

### LINKED ISSUE #9550: prettier-ignore breaks mapped types
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAhgXm2AB0ptzsB6S7DAJzhhgEs46BaZgcyggdIrYA2gEFszMgCEAukmwBhcgB9yAEQHYAviAA0ICBhbQAzslC46dCAHcAChYSmUuADbXcaU3oBGdXGABrRgBlDH8JLmQYOgBXOD04AFtvOAATVLSAGVwoLhjcLjgAMT5E3CYI5BBcGJgIXRAACxhElwB1RuZ4YzCwOGDHLuYANy60KrBjLxAJYzYYWz8uMuQAM1c5vQArYwAPST9AkNxEuEyJODWN+JAd3eCIlzgARRiIeCuXTZAwujm6KroLDGMB0ZiGBr0CQwNrMVIwRrIAAcAAY9PQIHM2n4MFV6HB-sNLnoAI5veCLAxOarGdhQOBpNINBhk5gMRYFFZIdZfG5zRLMKKxPmPF7ky7c656GC4byw+GIpAAJmlfmYLgi8ggiS5IAJAFYGjE5gAVWVOHnfYZxACSUAysGCoPBMBE9uC6Cenzmmk0QA)
```sh
--parser typescript
```

**Input:**
```tsx
type a= {
    // prettier-ignore
    [A in B]: C  |  D
  }
```

**Output:**
```tsx
type a = {
  // prettier-ignore
  A in B: C | D;
};

```

**Second Output:**
```tsx
SyntaxError: Property or signature expected. (3:3)
  1 | type a = {
  2 |   // prettier-ignore
> 3 |   A in B: C | D;
    |   ^
  4 | };
  5 | 
```

### PR DESCRIPTION
**Pull request by fisker**
I think we have to ignore the whole `TSMappedType`, there is no other node contains `[` and `]`.

Fixes #9550

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-js/comments.js [hunk 1]
```diff
@@ -905,25 +919,37 @@ function handleTSFunctionTrailingComments(
   return false;
 }
 
-function handleTSMappedTypeComments(
+function handleIgnoredComments(
```
Comment (thorn0) [inline src/language-js/comments.js:922]:
```suggestion
function handleIgnoreComments(
```

Comment (thorn0) [reply src/language-js/comments.js:922]: Comments aren't ignored. They're "ignore comments". Nodes with such comments are ignored.

**Comment by fisker** [comment]
I did  something  wrong, setting to draft, will  check later.

**Review by thorn0 — APPROVED** [review]
