### PR TITLE
Fix inconsistent assignment format

### LINKED ISSUE #17437: Non consistent line break for multiple assignment between Babel and TS
**Prettier 3.5.3**

**Input:**

```tsx
didScheduleRenderPhaseUpdateDuringThisPassFoo = didScheduleRenderPhaseUpdate = true
```

**[Babel output](https://prettier.io/playground#N4Igxg9gdgLgprEAuEATAlqgymAFnVAVwBs4AlBVOAJwAVcBDAZzgFUAHVB+AEUOvRQA5gBVc6JrWZMAYhAgACALwKM2PARLlKNeszaducZQpjVCcEABoQEdjHTQmyUA2rUIAdynUEzlAzEngwAns42AEbUDGAA1nAwWAwAtnAAMoKWSABmgSw2EBEAVnBgMADq0ezIIOy+LNQAbpaR0XEJWOwxgkLIZhY2LMnofeZwNnAAHuw06KmwgQDyM9EwEHQQTOgO0DWU1iBTK3MIMIEiNFBu6HD+ucT5IFvCpACKhBDwyPePRUyTWB6bw+XxyeXGIAAjiC4LQPOx-CBmABaKBwAgEA5mBjoYg9ADCEGSyQYNUCxAOzyEpAAgjAzOgIoR4LQaBk0d9wTZcDBksRyuJ4EwumA4Fg-Nt0I1tiEamAmOEQI0LABJKBUWA4AT2GnqrAwEKkTkPCF1TZwSoMaooOq3GjNA6CBowOEMIQk42PLrUBo1CIMCJwCk2OqCCqYGC4ZAADgADDZfND0L5Xe7SWCTTYzhFyhGo0gAEw2QgsEQBu5cw7JQOoKioNIMYSEN1wOTUEn0npk5kQEAAXz7QA)**

```tsx
didScheduleRenderPhaseUpdateDuringThisPassFoo =
  didScheduleRenderPhaseUpdate = true;
```

**[TS output](https://prettier.io/playground#N4Igxg9gdgLgprEAuEATAlqgymAFnVAVwBs4AlBVOAJwAVcBDAZzgFUAHVB+AEUOvRQA5gBVc6JrWZMAYhAgACALwKM2PARLlKNeszaducZQpjVCcEABoQEdjHTQmyUA2rUIAdynUEzlAzEngwAns42AEbUDGAA1nAwWAwAtnAAMoKWSABmgSw2EBEAVnBgMADq0ezIIOy+LNQAbpaR0XEJWOwxgkLIZhY2LMnofeZwNnAAHuw06KmwgQDyM9EwEHQQTOgO0DWU1iBTK3MIMIEiNFBu6HD+ucT5IFvCpACKhBDwyPePRUyTWB6bw+XxyeXGIAAjiC4LQPOx-CBmABaKBwAgEA5mBjoYg9ADCEGSyQYNUCxAOzyEpAAgjAzOgIoR4LQaBk0d9wTZcDBksRyuJ4EwumA4Fg-Nt0I1tiEamAmOEQI0LABJKBUWA4AT2GnqrAwEKkTkPCF1TZwSoMaooOq3GjNA6CBowOEMIQk42PLrUBo1A0zJhgbUwA51QQVTAwXDIAAcAAYbL5oehfK73aSwSabGcIuVI9GkAAmGyEFgiBgRO5cw7JCIEKioNIMYSEN1wOTUEn0npk5kQEAAXwHQA)**

```tsx
didScheduleRenderPhaseUpdateDuringThisPassFoo = didScheduleRenderPhaseUpdate =
  true;
```

**Why?**

Renaming a file from JS to TS should not change its formatting.

### PR DESCRIPTION
**Pull request by fisker**
## Description

Fixes #17437

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by sosukesuzuki — APPROVED** [review]

File: src/language-js/print/assignment.js [hunk 1]
```diff
@@ -180,7 +181,7 @@ function chooseLayout(path, options, print, leftDoc, rightPropertyName) {
     (hasShortKey ||
       rightNode.type === "TemplateLiteral" ||
       rightNode.type === "TaggedTemplateExpression" ||
-      rightNode.type === "BooleanLiteral" ||
+      isBooleanLiteral(rightNode) ||
```
Comment (aovchinn) [inline src/language-js/print/assignment.js:184]: I guess this caused https://github.com/prettier/prettier/issues/17883

Comment (fisker) [reply src/language-js/print/assignment.js:184]: Do not comment on old prs, locking.
