### PR TITLE
HTML: Fix crash on reading `Node.sourceSpan`

### LINKED ISSUE #9368: Crash in forceNextEmptyLine
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzjATtA5gPgENUB6THKAgWgDJcYBuDbPfAI1PNdvoZABoQEAA4wAltHTJQhLDgDuABVkIpKQgBt5hAJ5TBbLITABrODADKw42MrJsAVziC4AWzZwAJp68AZQpQOhLhwAGIQWK6EMOJ26g4wEAIgABYwrhoA6ili8OjWYHAWqrliAG65Osjg6PogtuhwWDCKRrhRyABmmo2CAFboAB4AQkam5haErnC+tnBdPc4gA4MWtrgacACKDhDwCxq9INZYjVjVaRnJwli2MJlinjApyAAcAAyCNxCNmUbC1RucDOZXmggAjrt4K0RGoQIR0FQoHAvF5klg4JCxBjWsEOkhuoclo1XGJ7FgnIJ0OtNjs9vMCYtBDBCGwHk8XkgAEzMoxiDTrADCEFc+JAwIArMkHI0ACqstSEo5lJwASSgPlgFjAt1EAEENRYYDpNgdGgBfc1AA)
```sh
--parser html
```

**Input:**
```html
<strong>a</strong>-&gt;<strong>b</strong>-&gt;
```

And even simpler:
```html
<strong>a</strong>-<strong>b</strong>-
```

**Output:**
```html
TypeError: Cannot read property 'line' of undefined
    at forceNextEmptyLine (https://prettier.io/lib/standalone.js:15:348165)
    at https://prettier.io/lib/standalone.js:15:361385
    at Ci.map (https://prettier.io/lib/standalone.js:15:107094)
    at Mv (https://prettier.io/lib/standalone.js:15:361045)
    at Object.print (https://prettier.io/lib/standalone.js:15:365539)
    at Ni (https://prettier.io/lib/standalone.js:15:109060)
    at https://prettier.io/lib/standalone.js:15:108522
    at Object.printComments (https://prettier.io/lib/standalone.js:15:104815)
    at e (https://prettier.io/lib/standalone.js:15:108503)
    at ki (https://prettier.io/lib/standalone.js:15:108568)
```

**Expected behavior:**

### PR DESCRIPTION
**Pull request by fisker**
Somehow, `Node.sourceSpan.constructor` became `Object`, use `ParseSourceSpan` directly from `angular-html-parser`.

Fixes #9368

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-html/parser-html.js [hunk 1]
```diff
@@ -273,17 +278,19 @@ function _parse(text, options, parserOptions, shouldParseFrontMatter = true) {
...
   };
 
   if (frontMatter) {
-    frontMatter.sourceSpan = {
-      start: { offset: 0 },
-      end: { offset: frontMatter.raw.length },
-    };
+    const start = new ParseLocation(file, 0, 0, 0);
+    const end = start.moveBy(frontMatter.raw.length);
+    frontMatter.sourceSpan = new ParseSourceSpan(start, end);
```
Comment (fisker) [inline src/language-html/parser-html.js:293]: This is not related to linked issue, but improves the `sourceSpan` of "root" and "front-matter" Node

**Review by thorn0 — APPROVED** [review]

**Comment by fisker** [comment]
Do you think we need figure why the `Node.sourceSpan.constructor` is not `ParseSourceSpan`? Or maybe @ikatyang know the reason behind it?

**Review by sosukesuzuki — APPROVED** [review]

**Comment by thorn0** [comment]
I don't think it's really necessary The bug is there since 1.15 when HTML support was added, so it's not a regression. My guess is that the node is cloned without preserving the prototype chain at some point .

**Review by evilebottnawi — APPROVED** [review]
