### PR TITLE
Remove `require` from UMD bundles

### LINKED ISSUE #12338: Regression TypeScript parser: "Critical dependency: the request of a dependency is an expression"
Looks like a regression of #11269 and #11076

**Environments:**

- Prettier Version: 2.5.1
- Running Prettier via: webpack browser
- Runtime: webpack v5
- Operating System: macOS
- Prettier plugins (if any): parser-typescript

**Steps to reproduce:**

Add this line of code to repo that has webpack:

```ts
return () => import("prettier/parser-typescript");
```

**Expected behavior:**
No warnings

**Actual behavior:**
Big webpack warning about "Critical dependency: the request of a dependency is an expression"

### PR DESCRIPTION
**Pull request by fisker**
## Description

Fixes #12338

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: scripts/tools/bundle-test/index.js [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+  for (const { displayName, name, file } of files) {
+    console.log(`${displayName || name}: `);
+
+    const stats = await runWebpack({
+      mode: "production",
+      entry: file,
+      output: {
+        path: TEMPORARY_DIRECTORY,
+        filename: getRandomFileName(name),
+      },
```
Comment (fisker) [inline scripts/tools/bundle-test/index.js:63]: @alexander-akait Do you know how to prevent webpack write file to dist?

**Review by Chrobob-777 — APPROVED** [review]

**Comment by fisker** [comment]
Merging this, so I can work on #12493.
