### PR TITLE
#6151 -- Allow plugin to specify option with type `string`

### LINKED ISSUE #6151: Allow plugin to add option with string type
**Environments:**
- Prettier Version: 1.17.1
- Running Prettier via:  CLI
- Runtime:  Node.js v10
- Operating System:  Linux

**Steps to reproduce:**

The `options` parameter that a plug in provides only accept the following types: `int`, `choice`, `boolean`, `flag`, `path`. I'd like the user to be able to provide a generic `string` type, which is not possible at the moment, see this check [here](https://github.com/prettier/prettier/blob/a9fd8e2cf42cd696aa1fb489ea7a374beb45b338/src/main/options-normalizer.js#L152).

Some background information: I'm developing a Prettier plugin for the [Apex language](https://github.com/dangmai/prettier-plugin-apex), and I'd to use a standalone server that does the parsing. Right now, I have to default making calls to `localhost` for the server, but I'd like to give the user the ability to specify this in case they have that server listening on a different interface or on a different network altogether.

**Expected behavior:**

Prettier allows me to specify a `string` type for option.

**Actual behavior:**

Prettier exits with error: `Unexpected type string`.

### PR DESCRIPTION
**Pull request by dangmai**
This PR allows plugins to specify option with type `string`. Currently (as can be seen in #6151), Prettier only accepts option types `int`, `choice`, `boolean`, `flag`, `path`, and rejects type `string`.

Fixes #6151.

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by duailibe** [comment]
This is a breaking change, I believe. I’ll include this in 2.0 with other changes planned. 

1.19 should be out before though

**Comment by dangmai** [comment]
I don't think this breaks any backwards compatibility with plugins - right now a `string` option gets rejected by Prettier core, so no plugin can use that anyway.

File: src/main/options-normalizer.js [hunk 1]
```diff
@@ -118,6 +118,9 @@ function optionInfoToSchema(optionInfo, { isCLI, optionInfos }) {
         parameters.preprocess = value => Number(value);
       }
       break;
+    case "string":
```
Comment (ikatyang) [inline src/main/options-normalizer.js]: I think it'd be better to have a way to specify a user-friendly type name in the help message, it should display `--server <url>` instead of `--server <string>` for example, but this is not a requirement so it could be done in the future.

Comment (dangmai) [reply src/main/options-normalizer.js]: I agree that it'd be nicer UX for the user. However, right now, `int` type shows `<int>` in the CLI so this change would be in line with that. A cursory glance at `vnopts` doesn't show me an obvious way to change that option either, so I'd prefer to keep this PR small, and change the type name in the future.

**Comment by shellscape** [comment]
@duailibe can we get another look at this? It doesn't _appear_ to be something that would cause a traditional breaking change, so some more information would be very much appreciated. This is blocking plugin authors pretty badly.
