### PR TITLE
Keep trailing-comma for `var` function

### LINKED ISSUE #13202: [CSS] Prettier removes trailing comma inside `var` function
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCACYAdKbbAWmICMBDAJyWwDdqAKUygLwBoBKAbgIF8Q7EBAAOMAJbQAzslDUqEAO4AFaghkoKAG0UUAnjKFkqFMAGs4MAMoUAtnAAy4qHGTptUuEZPnLVkabOAObIMFQArl4gcLZkcAAm8QkOFFBB4RRBcABiEFS2FDASacggFOEwEIIgABYwtloA6jXi8FIBYHBW6q3idK16pWBShiDOnlQwyiZBBW4eUQBWUgAeVsFacACK4RDw81qeQgFUE0Mj1SJUzjCN4vEwNcgAHAAMxwqejSYipVdwEzoriEAEddvBpqINGUpMQXAkEtUqHAweJkdNMnMkO5DlFPLZxKEIniNttwa5sQshDAKGQ7g8nkgAEzUkziLTBADCEFsWOiUgArNVwp4ACq0jQ4o4gOiRACSUCSsCsYGuYgAgoqrDA9JsDp4+HwgA)

```sh
--parser css
```

**Input:**

```css
.foo {
  --bar: var(--baz,);
}
```

**Output:**

```css
.foo {
  --bar: var(--baz);
}

```

**Expected behavior:**

The bare comma, which indicates "fallback to nothing," remains.

```css
.foo {
  --bar: var(--baz,);
}
```

## Spec

https://www.w3.org/TR/css-variables-1/#using-variables

> In an exception to the usual [comma elision rules](https://www.w3.org/TR/css-values-4/#comb-comma), which require commas to be omitted when they’re not separating values, a bare comma, with nothing following it, must be treated as valid in [var()](https://www.w3.org/TR/css-variables-1/#funcdef-var), indicating an empty fallback value.
> Tests
> 
> Note: That is, var(--a,) is a valid function, specifying that if the --a custom property is invalid or missing, the [var()](https://www.w3.org/TR/css-variables-1/#funcdef-var) should be replaced with nothing.

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #13202

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-css/printer-postcss.js [hunk 1]
```diff
@@ -915,7 +917,17 @@ function genericPrint(path, options, print) {
...
                 const isLast = index === node.groups.length - 1;
-                const printed = [print(), isLast ? "" : ","];
+                const hasComma = () =>
+                  Boolean(
+                    child.source &&
+                      options.originalText
+                        .slice(locStart(child), locStart(node.close))
+                        .trimEnd()
+                        .endsWith(",")
+                  );
```
Comment (sosukesuzuki) [inline src/language-css/printer-postcss.js:927]: Ideally we need to use `getNextNonSpaceNonCommentCharacterIndexWithStartIndex` like this:

```js
                const hasComma = () => {
                  const index =
                    child &&
                    getNextNonSpaceNonCommentCharacterIndexWithStartIndex(
                      options.originalText,
                      locEnd(child)
                    );
                  return index && options.originalText[index] === ",";
                };
```

But, `locEnd` for `--baz` in `var(--baz,)` returns unexpected value

**Review by fisker — APPROVED** [review]

File: src/language-css/printer-postcss.js (hunk 1 above)
Comment (fisker) [reply src/language-css/printer-postcss.js:927]: https://github.com/prettier/prettier/pull/13321 is also blocked by it.
