### PR TITLE
fix(playground): no unnecessary import

### LINKED ISSUE #4652: [bug] prettier playground compiles too slow when it came across syntax it doesn't know
**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTAAwB0oATASzQAcAbbATyUwDNa4APAblICNswAawDmAJwgBXcs1FwyPKADpsvMJmCZKNek0y9aEIQsx6BI8VLLMA7gAsK8BQF9ShLiAA0ICNRgV0yKDYouLWAArBCGjIINgAbhAUZJ4gvKJmcDAAytQCFFDCyDCiEnBe+WhwojBh6cIAttjILNi0lV4AVmgcAELpQplZ2PVwADL5cM2t7SC5opWiMWwQ1inUovkwAOpJMLbIABwADF7rEJVb6dQx63ALcZNesgCOEhSytdgNTUgtbWUgSr1ChFEoAtD5YTsACKEgg8Cm-y8MBUOzIe2QACZkekKLRIQBhCD1RoxKDQR4gCSVAAqKmiv2mcCcTiAA)
```sh
--parser flow
```

**Input:**
```jsx
const a = `
display: flex;
background: red;
.abc { display: block;
  background: white;
}
`;
```

**Output:**
```jsx
const a = `
display: flex;
background: red;
.abc { display: block;
  background: white;
}
`;

```

**Expected behavior:**

When I change the code at left, the right part compiles too slow....

beside, how can I format a code block using a specific syntax like less/scss

### PR DESCRIPTION
**Pull request by ikatyang**
Fixes #4652

### CODE REVIEW

File: website/static/worker.js [hunk 1]
```diff
@@ -2,65 +2,73 @@
 /* eslint no-var: off, strict: off */
 /* globals prettier prettierPlugins */
 
+var imported = {};
+function importScriptOnce(url) {
+  if (!imported[url]) {
+    imported[url] = true;
```
Comment (j-f1) [inline website/static/worker.js]: Perhaps use an array, `Object.create(null)`, or a set here to avoid bugs we’ve encountered with using an object as a map on the past?

Comment (ikatyang) [reply website/static/worker.js]: I'll change it to use `Object.create(null)`, though I think it's almost impossible to encounter the same issue since we probably won't have some parser named something like `hasOwnProperty`.
