### PR TITLE
TypeScript: temp fix for missing readonly keyword

### LINKED ISSUE #1845: TypeScript: `readonly` modifier gets removed
Version: v1.4.0-beta

Input:

```js
class Foo {
  public readonly foo = 'string';
}
```

Actual Output:

```js
class Foo {
  public foo = 'string';
}
```

Expected Output:

```js
class Foo {
  public readonly foo = 'string';
}
```

### PR DESCRIPTION
**Pull request by azz**
Fixes #1845

Not sure if the regex is too easy to pass?

### CODE REVIEW

File: src/printer.js [hunk 1]
```diff
@@ -1666,6 +1666,9 @@ function genericPrintNoParens(path, options, print, args) {
       if (n.type === "TSAbstractClassProperty") {
         parts.push("abstract ");
       }
+      if (n.readonly || hasReadonly(n, options)) {
```
Comment (vjeux) [inline src/printer.js]: I think that it would be safer to check from `start(n)` to `start(n.key)` instead of the entire node, which could be big.

File: src/printer.js [hunk 2]
```diff
@@ -4174,6 +4178,13 @@ function shouldInlineLogicalExpression(node) {
   return false;
 }
 
+function hasReadonly(n, options) {
+  // Temp. Remove after https://github.com/eslint/typescript-eslint-parser/pull/303
+  return /\breadonly\b/.test(
```
Comment (vjeux) [inline src/printer.js]: The regex sounds good if we restrict the range a bit more.

**Comment by vjeux** [comment]
Thanks for working on this! If we restrict the range, it should be safer and good to go!

**Comment by vjeux** [comment]
Actually, for this one, looks like there's a PR up for it https://github.com/eslint/typescript-eslint-parser/pull/303, we could change the hash to use it.

**Comment by azz** [comment]
Ok, will do

**Comment by vjeux** [comment]
Awesome! thanks :)
