### PR TITLE
Fix css-modules composes breaking with long line width

### LINKED ISSUE #2189: Formatting CSS breaks when using css-module's `composes`
# Background & Context

When using `css-modules` with `composes` formatting the source code using prettier's defaults seem to cause an error in the `css-loader`. 

## Example

```css
.button {
  composes: button-base from './base-button.css';
  background: red;
}
```

will be formatted to

```css
.button {
  composes: button-base 
      from './base-button.css';
  background: red;
}
```

This yields the following type of error 

screen shot 2017-06-18 at 17 23 04

stating that the "referenced class name 'x' in composes could not be found" using the `css-loader` in a webpack@2 context.

### PR DESCRIPTION
**Pull request by tdeekens**
# Background & Context

When using `css-modules` with `composes` formatting the source code using prettier's defaults seem to cause an error in the `css-loader`. 

## Example

```css
.reference {
  composes: selector from "a/long/file/path/exceeding/the/maximum/length/forcing/a/line-wrap/file.css";
}
```

will be formatted to

```css
.reference {
  composes: 
      selector 
      from "a/long/file/path/exceeding/the/maximum/length/forcing/a/line-wrap/file.css";
}
```

This pull request attempts to fix that by detecting the use of composition and by passing the normal formatting flow.

Closes #2189

### CODE REVIEW

File: src/printer-postcss.js [hunk 1]
```diff
@@ -69,13 +69,19 @@ function genericPrint(path, options, print) {
...
 
       return concat([
         n.raws.before.replace(/[\s;]/g, ""),
         n.prop,
         ":",
         isValueExtend ? "" : " ",
-        path.call(print, "value"),
+        isComposed
+          ? n.value.group.group.groups.join("")
+          : path.call(print, "value"),
```
Comment (vjeux) [inline src/printer-postcss.js]: Can you use removeLines?

Comment (tdeekens) [inline src/printer-postcss.js]: The doc at that point with all its definitions never contains a `type` of `line` or `if-break` to my knowledge. Hence, the `removeLines` would change much from what I can tell from reading here [here](https://github.com/tdeekens/prettier/blob/fix/css-modules-composes/src/doc-utils.js#L161). Is there another way of achieving the same or am I missing something?

Comment (azz) [inline src/printer-postcss.js]: Its more about not assuming the shape of the doc too much. `removeLines` does that for you.

File: src/printer-postcss.js [hunk 2]
```diff
@@ -69,13 +69,19 @@ function genericPrint(path, options, print) {
...
+        n.prop === "composes";
 
       return concat([
         n.raws.before.replace(/[\s;]/g, ""),
         n.prop,
         ":",
         isValueExtend ? "" : " ",
-        path.call(print, "value"),
+        isComposed
+          ? n.value.group.group.groups.join("")
```
Comment (vjeux) [inline src/printer-postcss.js]: You want to do

```js
concat(path.map(print, "value", "group", "groups"))
```

Otherwise it doesn't go through the normal print mechanism.

It's not ideal that we have to reach into one level deep but without being on a computer I can't really troubleshot.

@azz, if you have a better idea, please let me know, otherwise i'll merge with my suggestion.

File: src/printer-postcss.js (hunk 1 above)
Comment (vjeux) [inline src/printer-postcss.js]: Have you actually tried removeLines? If it did nothing, well too bad, otherwise that's an elegant-ish solution.

Comment (tdeekens) [inline src/printer-postcss.js]: Sorry, hopefully used it correctly now and it seems to do the trick. Got a bit "confused" by the line location of the comment as I would expect that we'd want to keep "normal" formatting without removing lines in case it's not a 'composes'?

File: src/printer-postcss.js (hunk 2 above)
Comment (tdeekens) [inline src/printer-postcss.js]: Seems not to be needed anymore. Please check the last commit.

**Comment by vjeux** [comment]
Thanks!

**Comment by TrySound** [comment]
Guys. there're two equal keywords. `composes` and `compose-with`.

**Comment by tdeekens** [comment]
Thanks for spotting. I'll add a PR for `compose-with` then.

**Comment by tdeekens** [comment]
Can you share a reference to the spec using `composes-with` I am having trouble finding it.

**Comment by TrySound** [comment]
There's no spec for syntax features. There's a few plugins and ICSS (extension) spec.
https://github.com/css-modules/postcss-icss-composes#local-class-composition
