### PR TITLE
Playground: Fix "Report issue" 414 bug

### LINKED ISSUE #6297: Playground tooltips appear below scrollbars (and “Report issue” button causes a 414 in Playground)
Edit: The 414 issue has been fixed. See the next comment for the remaining problem.

Using the “Report issue” button can result in a `414 Request-URI Too Large` response from GitHub. This was discovered attempting to report a [small issue](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzOMwAWAKgIYA2A1gMoEQDuamAvJgBRq0MA0mJADgEsA0nACePMiQwAJCAFcATmgCUzAHyZgAHSiZMCvIt0AFBRAC2AtHAB05Mu05ob5-q0IkoUOGXWadepBQGJiKviwABgQwMHxoSAD0CXQpNgDmEBBpZHD8VjaQ5gmi8jByAEZwCQBuAMwJ1iQKhAD8FGJMACTAeSKiAL4AZB5ePgCSACZdwCPeZEN8TTBMaFACfHx4XAITgxAKE3AKTBMk8IOuAB4ASnBocmQwaEwATAAMEQDcOgH6hgq6XD4AisMLKX56PQ2GAEBCsAxoPjoOB+BFI4K2ABWaGgrGU4N0kKhMLh2Ogfm0hKJRIMZQBmDJUBsAng5jQEOpnJs2AEjyOrBZcHMFI5nLFmCCISg9GYmG8dEwABEznA8d8qeKxZKsCTdCx5UqVQLWTZVutNjAbHwKmQrLCJgBBGDKdWazXazAwATmOCKgTYbBjKCyRSMFiLJRwIMwVisaUKgC0nthUFUCUwAEY3tm05gAGxvTDpguut1i2lGT3e33+wPB+RKTAAHkwkhkDbQpbLmH6BO7UNcfGNQpFGv7fzpukp4-FOyQmEF5mZExs1R2cAgky4opnei9MBy88XprWGzw0JZOW3Y93mEOaDACnWXugR5NZrPlvvj+fAmg19valTngN8hRPc1z2tcpbQ4OBHRgADAMhb0SDSOBQKXD8LWhAg5HMcooBIXlnAIAQ0gIGwwkQ3d+i7Mtex3cU6L0Xt1V7ZQcLhDh6DDDRuIYblJBjfE2M+EAuBACA+BfYJkFAJozDoYwmgQNBkBAEhqggHZxJAcoFBIMB2hgKhFjAAQoDSZAYAUOQ4Ak6JzDIAB1Uj4ERQy4CoVSWQENcYFEdSwDQNSJIs6wFBgUxUNcZBsHIawJOxS4ACEDKMvAqBIH0ABkLLgOKEvskBkqoCzsjgABFOQIHgQqyESkAIwi9TsDIehdL4J9YGcnYYWQDMJK6iBrGcgy+HUrq7iOaoCokgBHGr4FMKS1JQKQE28OC4N0gxFoEAxorSWKkHihriusSxrNsi7ypyaraoKpAbLsiSYBIcpeomfqkBeN6DN5cqAGELBOkBpW8XS5GsUhyjWs7rH6fogA) (which seems to be resolved) where the print width was hidden and defaulting to 1.

### PR DESCRIPTION
**Pull request by Drapegnik**
Fix #6297

Check if report url is too long (>8000), change report url to _short report_ and copy full report to clipboard.

Screen Shot 2019-08-22 at 15 09 45

Example: [report issue](https://github.com/prettier/prettier/issues/new?body=%3C!--%20The%20full%20report%20is%20copied%20to%20your%20clipboard%2C%20paste%20it%20here.%20---%3E%0A%0A%3C!--%20Short%20report%3A%20---%3E%0A**Prettier%201.18.2**%0A%5BPlayground%20link%5D(http%3A%2F%2Flocalhost%3A3001%2Fplayground%2F%23N4Igxg9gdgLgprEAuc0DOMAEAzOMwAWAKgIYA2A1gMoEQDuamAvJgBRq0MA0mJADgEsA0nACePMiQwAJCAFcATmgCUzAHyZgAHSiZMCvIt0AFBRAC2AtHAB05Mu05ob5-q0IkoUOGXWadepBQGJiKviwABgQwMHxoSAD0CXQpNgDmEBBpZHD8VjaQ5gmi8jByAEZwCQBuAMwJ1iQKhAD8FGJMACTAeSKiAL4AZB5ePgCSACZdwCPeZEN8TTBMaFACfHx4XAITgxAKE3AKTBMk8IOuAB4ASnBocmQwaEwATAAMEQDcOgH6hgq6XD4AisMLKX56PQ2GAEBCsAxoPjoOB%2BBFI4K2ABWaGgrGU4N0kKhMLh2Ogfm0hKJRIMZQBmDJUBsAng5jQEOpnJs2AEjyOrBZcHMFI5nLFmCCISg9GYmG8dEwABEznA8d8qeKxZKsCTdCx5UqVQLWTZVutNjAbHwKmQrLCJgBBGDKdWazXazAwATmOCKgTYbBjKCyRSMFiLJRwIMwVisaUKgC0nthUFUCUwAEY3tm05gAGxvTDpguut1i2lGT3e33%2BwPB%2BRKTAAHkwkhkDbQpbLmH6BO7UNcfGNQpFGv7fzpukp4-FOyQmEF5mZExs1R2cAgky4opnei9MBy88XprWGzw0JZOW3Y93mEOaDACnWXugR5NZrPlvvj%2BfAmg19valTngN8hRPc1z2tcpbQ4OBHRgADAMhb0SDSOBQKXD8LWhAg5HMcooBIXlnAIAQ0gIGwwkQ3d%2Bi7Mtex3cU6L0Xt1V7ZQcLhDh6DDDRuIYblJBjfE2M%2BEAuBACA%2BBfYJkFAJozDoYwmgQNBkBAEhqggHZxJAcoFBIMB2hgKhFjAAQoDSZAYAUOQ4Ak6JzDIAB1Uj4ERQy4CoVSWQENcYFEdSwDQNSJIs6wFBgUxUNcZBsHIawJOxS4ACEDKMvAqBIH0ABkLLgOKEvskBkqoCzsjgABFOQIHgQqyESkAIwi9TyhIcpRDIaBdL4J9YGcnYYWQDMJN6iBrGcgy%2BHU3q7iOaoCokgBHGr4FMKS1JQKQE28OC4N0gwVoEAxorSWKkHihriusSxrNs67ypyaraoKi6iokmB2oGiYhqQF4PoM3lyoAYQsc6QGlbxdLkaxSHKTbLusfp%2BiAA)%0A%60%60%60sh%0A--parser%20babylon%0A--print-width%201%0A%60%60%60)

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: website/playground/markdown.js [hunk 1]
```diff
@@ -1,4 +1,4 @@
-function formatMarkdown(
+export default function formatMarkdown(
```
Comment (lydell) [inline website/playground/markdown.js]: As far as I remember, this file cannot have `export` syntax in it, because it is also run through Node.js in some script to update the issue templare.

Comment (Drapegnik) [reply website/playground/markdown.js]: @lydell, where?

Comment (Drapegnik) [reply website/playground/markdown.js]: Could I change it to named export? (I haven't found the script and use cases of this file)

```js
module.exports = {
  formatMarkdown,
  getHeader,
  prettify
};
```

Comment (lydell) [reply website/playground/markdown.js]: I can't find it either. I think it has been removed.

Comment (Drapegnik) [reply website/playground/markdown.js]: @lydell, I leave it as it is.
so, could you merge it?

**Comment by lydell** [comment]
I quickly played around with playground here: https://deploy-preview-6409--prettier.netlify.com/playground

But with the following test input I still got an 414 after clicking the "Report issue" button.

<details>
<summary>Test input</summary>

````````````````````````````````````md
**Prettier pr-6409**
[Playground link](https://deploy-preview-6409--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAqVAFATnGMCWcWABAA5YC0AbACwAMAnOgDpQDaGANgIYCeA5lggBXKABNinfFADWAXQAUACzykAzkgD0msXFKcIvCuTgA3QgHdq9BhWM48hLADoouKQDNezyAFtN+nyCIuKaAMQAcjQAkvwAHvwM-GL8ADL85ACiAILCOQCOAGrZAGLZACpQAOIAsgDCAOpgDdkAQtnZAKwAmnV02QBG2XUW2TXZUADy-AAipACKM9xV2RH80b1wXZz8-K0AGgDSbRHSHmUzLfvz2QCqwwBevDLZDzKzdL5q+yWHYNGmOrCcr8bIAZnm-AAEmJ8gxWkoGjUaAAOJSpbIzCAiQ6LCJwJ6lGARADUUF4dWiwkO3GyACkAMpqDoDABK3Bk+TUsPKzSqpEycTaVTBVV8KNanFarLofDUVGGDNuh3KdRqmX4aluESqrNKAC18m0qGoofk6XsIjMcq06RYoNlutkqEpWt1qtFDhZonbhBFUiihXVAzULPwGQArOhVEbZOhxSaTGhgW0PbKTeYYuinOoAdlMWG45jAdRmdQecVaubAUDqUCw-TqvGi+BeKPy+sy+QsdRJ3TA5Q6C26EcyHmycFaN3mMgATK06vwKGXRmALPgLBZDvwLJwqBhRmDMnV5uUIzAajc6lhTB18LnePM4nU6XQSrOAIyzzKHBrRBpVDQNC7KYUoWHaND4NEWCtJKs7CPkkz6mAs5wGCrThr4YBQvwNT8LO0SLiU8zCGADA1Pqpj8LcFAfk+HQRm0eozPcULdBYag0N07RjBAFipK05StLcvCmPMKI1K0FitAy3D6hGFG8LOajlPkDzlDQHgRjB3SpHUhw9CUdDodENA5FCo4kiUNRxDM2QYCx3CgmAMBxB4ULZPqWAwMIDbRNEYhKN5+DZPM3R0mA+pqK0sStBEmTlJkdJ2iOWGdFQMj4CiMCHKQHQyBYVQApM0QYHQ+AYARqQPHAYCZCSrJVA8Az6qQULcCSDStCSmKdCpEYUA0EARmI3XRJMVAMHU6g0B+JR0qk8ykPgUKsh+ahYPgMxwvMrSFLcraxI6DQ0LihRxFChRVHEFgyB+Sgoii+yFMIhS+MBbQyNEbozHQRAeCiHimLmESJuiMxKAwVCnjGKLdPsND6hYmTWhE8xkt6twlJcMwfiF2QeFAviZK0MglTUMhxHQDLdCUcSzrwkxrCsDKYiMNScAwvj9vqcDvlCNBKA8DT6nUpgPLc5QzK0dADOUnCsg8-D7HEFCzt0Kz6rO2S5vqVQRLwKymHE3QUCiYC7XUhRvMIXUYAymQyI7-5wHQ8x1N0EAMo+DR1JkJRKCSmQWwyFDRBEiVQqkmSmPtVCkCi+AMKNYJQIcNQQIc+D5PyVD4NwxwNPg-ARAnzqsqSMhVN0+qsvg3SzmI3SssIbpSOUkwzKYDRKAMSf8EhDwRkodw0L48X5DQAwRq3QElA0dKWCSHgwA0Mw9ZkvgCXUtwQC0HYUDI7R1B4rL8BgH5UA8rIgmIdKtPbW9xDODLlHSdQyBA03dEoBKkKTz59QlBkB4fY+oMS+EmJ0aI+ROqekKEoQoJQ6iwRkJweYCDCicBKFgTotwkG3BoFUD8cByj4BKB+OMEYK51AZAONG0ROBxBgJMOgUIGRiA8A9GYYhJgMkWHUdhvgaisk7HScovgLBrAeL4J2FheAYHTt0IerR9RQkmOUXSYJyjPEyDUXgDwoQRBRN+eYagUypHHLwMEJQmTcG1vsGQvgHh0F4OUBoAhCidFdrmASwg4iQxgMmJQUASitApuYukDwKDcCoGAVm9d5iTFMOOTgH4fiFFzHEMEGAwBqEyBgbotgIwYDEA8eY0R9jRCgAMMEpg6RPToKQGAKISiFFZBAcoBc4j5DAGAAYcReAMHmBgbIvAsSHFuL7RYG5cwFMmFDC2Is6hgA8CSDm4VOYMioNEfUP81CHBJMINQapdT8JmFSI4kwoTNG4JMCgcByFgE6J0CMDQMCdB6nETIFByi7VSJ0fAqReicF8AyToAwPydH4ZkGAEYQRgg6bmTkrR+RxH1MMGS7VjgfiqPMe4mVjwWHqHpDAR9BhKEHPwcccQqgzBgHSKgg5dTYQ-KyaIPZfAYreZkBoqQA7KwTDMKgdIOnpAiPsVI+wPztCUksGYcA6jlGZNEWcwr8UbiqK0NQgEuEeEAvqVoEA1BwBJqkaI2R-wPDBJMboUIZVUChLOMm2RWQUGEDUDwqQL6HHAaCVkDRjytCIfsLeCDXV0kyj6SYSgqCFXmENA5GEw7cDCouNQ8xEQ3HTIUMAEYqD+2iGSUgtx+AyE6DUKEwhTARikpamguYwQl2opMGQYBbitBwhAQCAwG4JCAu0Dw0JsgUFGrmGYj5DgYBqNSVkHgZhENSDsW4whIYPA3PgMERpSBwBjF4ph-BI2shJA8FELxhj6hmJ0MUNBWhgEON0EkY9WQTvltkWkDIGDCoYFAOIkaGStF8DMYVvgSipHwLca40UGBn31lUDy2R+DCGiPMOgkwSgMBoAKCA56ACUrAAAGRG1BKFYHYUg3AsAmpIL4SjMgxB8SgIRojrBWDoGqaQYQMAkAsCgERojtGsD0cY2xzADgCBEDIJQWgjBeMcB4AIIQogJBSFkIoFQMB1BaB0HoAwRgTDmDgFYGTth7C4Aky4NwMBPDeD8AEBTwRlOaHw3x4jpGoDkco9R4gAxuADF4AYJjrmCOsagOxqAnHuO8f4xGNQcRWAeFEC5fA0BiBQjgJwAwQ0sCcDEAoYAgg4C4GkPwYgABeYgzAQC-0yxAKrAAaYghXcBwAkBVgA5FV7LuWqvtca2ofAnAEAwHK8QDw3BOAmsa9ADOxy4DJKIPVgAvrh4gwBQvEGIPgDwCgACEzWCBQH4Lh4ADhfJQGIFAYQmWlsAG4Nubc29oYgHcZiTCQMQLEUB2sjbm8QQs4gIC+C2xdnA4giCsE20NkbV3gcVZqNwGAShnAeAMBAEgCgEdI+cADhjvgFCrdQMQD89Vcy4ecDAL2MBNpHYJzj3T3AwBwAUJoZgzBnBs7ECSTQxdGtVaqy5yH-3cDneIAAHjEPgUwxAwA8DUGoCI3BfBwDK+19LtXutiHa8QAg1mVfAAI57YQxBKNwGIOYAblOSCw4GJJgAJMAS7whgdLYI0t4gM2RAmoW1gMrwBPdzZ90tgAfA9zbYu1DU+gPwYPjuDslecGoKQTOFDEDoI1j8xByeU9uKQHdWA6jcBNQT4gJIms4GK0dxPyfmcfmzxAVIfEiCF+L6tpbYvNCR6EEd0PF3HsFYr4d-gzgEBiDUEXJHCgGsC+IAAfkqyABfxAPsR4oxdyPAX9fAEgAYLAH3OvMEK7wdrS2Q8NYXx3tQa-g-ECW0L8PcBfC9+YDAOPg-Wu39YzADvj-e+PbW8QAoANkNrAC5v-ptvPlVhziAPfo9h9lVrtlVnfkFv-h3pLqYMHvdkFsgfxqFugJMFxpFjxqgMxgRrFvFlAIllAMlqlurllujrlvlkLvHkdqNlVjVgYNPn3gdh-h1l1gwWIL1vVkLsAcNqNuNpNnAMIX3gHt7qYBDlACtmtkLttoAftoPiVqtutn3ptmdlgBdldpllgZtsgULs9q9u9p9tAD9sQH9rjkDiDsLuDlgELtDk7nDsQFjsjqjtiFgJjojsjvYfjoTsTnAGTrARTlTjTvwAThETgIECnqzuzpztzvwPgHzjASALhlgULnoRdlPjoeLugbAZtrLkXgrkrirlVnQXvAIfzoUZtrrkNn7obiICbjgObvgJbuju4bbiQA7rDq7sgeAR7lALNnIUQH7rIfNvIVgMMY9n-uARHlHj3iUf3iwcPknvgCnunsTvXrnvni3szqtmXhsdXtsbXvXo3hYM3kXscfMagZ3isTHmsQPkVkPiPuIOPvgJPtPlkXPoAWsZtlVgvmsath9gUSMeHlftwOvjAJvn7o7jvujvASAEfiCafqHiABkZftfmCQ8Y9mLr-m8S1mIO3poL-q8aIbAACVASCaiYgSAASWgVLosdkawKYcFqQSFkFvgYQVxsQdyYJsJvaKJtgOZk4FJtYLJiQewFwEEEpuIJINIPIMoKoBoNoLoPoIYGZoZsZjYORuJk4K4O4NtrZkDvZgqSEGIM5qFvxiRmRsYF5pJr5v5oFqQXgagBxgKbxqQeQQlklgQLQRlvQTlnltoZthsWwdViGXVticwe-m1sQJ1iAJrkISIYNmIRVhIVNkLtMT7hyVoSoR4GoRsUWYUXkU7kYULpyU9poC9p3JYV9jYXYbCXjo4WDroC4X3m4bDqNl4Sjmjn4QOUESXkTiQuEYUZEQyNTiVrEVOfETwIkWzhzswFzpoGkRkQLjkX3pWZCYScUQ0TLnLhUcrmVtUbGWmTAUeU0frq0cbqbp0d0dbs7n0cQAMc7kMWsfmbMVMWMV7jMUQASYsagV3tHiBeASSR8VsTsRnvsXnrca3qXuXu8QnjBZcZEdcYhfcWsZfs8RBZtlBQnqPt8b8fGf8fPvuSMSCfUSMeCYCUedCWvsQBvs0cAEiRALvqieiYvpieflVribCQRVngSQ-k-lBa1uSZSUecANSSNpASANAcvgvoycyToKyULuyYoR6byagAQZpj6bKX6XFgGdQUGRdjUZrkwdwRoawRVuwbGVwZGYmaNimVeX1hmSASNtmRNrmTIf+YHrMYWcoX3qoXtmWSFf-pWYYZwMYZ-igcQOYY2R9s2b9iav9m2Q4dIE4V2a4bgO4f2QEYOb4f4djqOSEROWAY9tObObTlVZtvTgkczkkaueuZuaCVkTuboSLvoQxagYeSMWUfLormeReRrnUdeSMbeS0Ubu0Wbhbj8T0TbvbsAIMW7t+QFRMb7v7ptYBXMbAcJcsd3i8YxWtmcehQoLsXXpEQcdhSXqcbZZsTXgoNdZTlhQXncQTqJeLk8cdcJURVXiRRPkoFPuRatpRUCUvrReAfRVRUsTCXCQiexTLpxSiQvjxbfmftiRfp3niUebht9USeJTwWST-k-lSZmTSQpUpQyUgbASyRgZpVgTgSxkFvxgRtiSABAM0illAGoMgKAJRkIBYBgKbnzcgCAEWBAPgGIJzQMIWGADILgAyBRmACVsgNTsIFIdVjAL4JwD3D8XADCUzgyAgJblLj8bwBLXkvzfViANINRjANgE5LRsgDmdreQa0ArUrTALJMruBm4G7b5R7XFgyCVkNiRBAPAEHZIXbRRlRkQBLcKQxvaJzeQNIKvDLUjsgCiOniAOQManAA0IWKQBLSYNRvIZzfkMIFHXANgNzfzSgEXhQG4K1q1pzTgNXfgDgM7fwK7UgO7XbSar4PgBrVgFrUPeHXAJHdHQPcHXbTAH5kXGINnUgLOAvYWINiVnUEDv3SAFANAHAJzXNl0gMI3YPSAKYFrdUroLAHQptM0hMGIDOZvjHSaqfkAA)
```sh
--parser markdown
```

**Input:**
`````markdown
**Prettier pr-6409**
[Playground link](https://deploy-preview-6409--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAqVAFATnGMCWcWABAA5YC0AbACwAMAnOgDpQDaGANgIYCeA5lggBXKABNinfFADWAXQAUACzykAzkgD0msXFKcIvCuTgA3QgHdq9BhWM48hLADoouKQDNezyAFtN+nyCIuKaAJSsAAbRakqsdqTcWGpExABG3Gm8BlBR0ays6ACSUKTCMEgsUNGRAFZqAB6sHqJgBNDEABJwnAYA6hBYnGIKwIJwuNL8xAC8xMwgSj0GCwA0xOO4cBJzAOQLA0NiC7vravicCDCzxB7cnCnr0ACyIikA8qZEqwC+YcTAApQYjEfAeBQAQk2BCg-DCwAcwiwwKgwl6PwA3ECQTjtMQACrvAAi7yQxCJ0F212EKWIWG44ggvlBwJw4iIrBBl2uqOZc2e3BgSmcHgMg2ICgFQuc9MZvgU-1QxAAjABRADUAHYws4YBAAMowLBTBUyvQ8MBwBSaZjMZy2sTqzT4fjrBYLCK5YF03BI4EAHjE+FMxDAPDUagActxfHAZrtur0IIdhrtiAQYJcZsBIgBNETEJJwYjmc56ki8tKpAAkwGIvOIP0iP2ILzecE+RGzbZpHa+WB+AD5sTj-WojdB+IO69Cps41FJLQpiHR1sriDq9QBVUikIgAYW4KQVxHVGxwk1h88XVuVm4gABkIBYD0erf8fv7NOOhLDh96QTGC8YX4ZwEDENQ+nwIUFDWD1iAAfnmEBkOIMkx0SYFx2yONgGASADCwMl9mYcZeF2H4hzWZCvzUTDB0bTlRzgXx-2YGAZ2A7ZGNyGAvxY-8cQBCVzkuWBPSEkEkIWe0QCYoSyQWCEFh+EcQS-INTEHLEvVU6p8i9dB3nKMoKiqGp6iaKAWigNp8A6RN+kGYZRiY2dYRuBYliTODvWhbi9gOZzjhAU4mNEq4bjuB44FWJiew+ftWD+AEmLBCUoWAqZ-kBACfRgP16zRTgdJBPSmLxQkSTJCkoCpYhezpBkxCZFkfXZLAmO5Iq+WIKVhVFCBBklQVhVlFr5UVFU4G1eTiF1A0jRNCScTNQIlxtO0HSdfh8DdOSQDCHSmMRZEJTmwNgzmkEwyPKMYzjBZHOTYL3TykEMyzHN82EQscBLfAy3FSsa2AXkmz0yTWygV5e07LBuxh9t4chnFBMkscJz-a6cSAiYQOvfAl1XFV7x3PcsEPY9-jPdzQIXInb3vJ8X0pt8FVRoTaKxqccbxy9QPAyDoKUWCQDiw7EPO96cQWZCcf+MlYJl9S6IZYhsK+usCMGRSQDIuXKOHcWaO-eiFc55jWP5+AxE-TQBL5iLYClmS5b15SQEtjTg3Ro7kqBGpxZACBSHaKA1GQUAkiECwMCLCPkBAbhTAgfAxGDtJ6TAGRcH1RIwCmZAjWEWLFhgXxOD6JRoLgNXLX1BAy2DaDeCTsAI2D6QUiwGBsG4fhfG4ZBoseEBLIAIWz3OYH1B6H2kOAR-uMfLP1KZLgARWECB4GXmLVhARJkiIJOh6wGQWosKBg-IaQYCgsQhWQAAOVcj6EFI+npUgk5MHuvjBwAI473gNgUOkcUBHgoG4bY2xg44BAfgHA-dB7DyQKPMuKRfD4GLlgUuh9ziwi3qApeGCV5lxgJkR+z8kAACZD5Gm4BcKY+4mRDyTlAaAS9D69nxJkSBmDD6mFLiUXQsB9RgGNGHAAguIQ0OF94pEokAA)
```sh
--parser markdown
```

**Input:**
````markdown
**Prettier pr-6409**
[Playground link](https://deploy-preview-6409--prettier.netlify.com/playground/)
```sh
--parser babylon
```

**Input:**
```jsx
function HelloWorld({greeting = "hello", greeted = '"World"', silent = false, onMouseOver,}) {

  if(!greeting){return null};

     // TODO: Don't use random in render
  let num = Math.floor (Math.random() * 1E+7).toString().replace(/\.\d+/ig, "")

  return <div className='HelloWorld' title={`You are visitor number ${ num }`} onMouseOver={onMouseOver}>

    <strong>{ greeting.slice( 0, 1 ).toUpperCase() + greeting.slice(1).toLowerCase() }</strong>
    {greeting.endsWith(",") ? " " : <span style={{color: '\grey'}}>", "</span> }
    <em>
	{ greeted }
	</em>
    { (silent)
      ? "."
      : "!"}

    </div>;

}
```

**Output:**
```jsx
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver
}) {
  if (!greeting) {
    return null;
  }

  // TODO: Don't use random in render
  let num = Math.floor(Math.random() * 1e7)
    .toString()
    .replace(/\.\d+/gi, "");

  return (
    <div
      className="HelloWorld"
      title={`You are visitor number ${num}`}
      onMouseOver={onMouseOver}
    >
      <strong>
        {greeting.slice(0, 1).toUpperCase() + greeting.slice(1).toLowerCase()}
      </strong>
      {greeting.endsWith(",") ? (
        " "
      ) : (
        <span style={{ color: "grey" }}>", "</span>
      )}
      <em>{greeted}</em>
      {silent ? "." : "!"}
    </div>
  );
}

```
````

**Output:**
````markdown
**Prettier pr-6409**
[Playground link](https://deploy-preview-6409--prettier.netlify.com/playground/)

```sh
--parser babylon
```

**Input:**

```jsx
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver
}) {
  if (!greeting) {
    return null;
  }

  // TODO: Don't use random in render
  let num = Math.floor(Math.random() * 1e7)
    .toString()
    .replace(/\.\d+/gi, "");

  return (
    <div
      className="HelloWorld"
      title={`You are visitor number ${num}`}
      onMouseOver={onMouseOver}
    >
      <strong>
        {greeting.slice(0, 1).toUpperCase() + greeting.slice(1).toLowerCase()}
      </strong>
      {greeting.endsWith(",") ? (
        " "
      ) : (
        <span style={{ color: "grey" }}>", "</span>
      )}
      <em>{greeted}</em>
      {silent ? "." : "!"}
    </div>
  );
}
```

**Output:**

```jsx
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver
}) {
  if (!greeting) {
    return null;
  }

  // TODO: Don't use random in render
  let num = Math.floor(Math.random() * 1e7)
    .toString()
    .replace(/\.\d+/gi, "");

  return (
    <div
      className="HelloWorld"
      title={`You are visitor number ${num}`}
      onMouseOver={onMouseOver}
    >
      <strong>
        {greeting.slice(0, 1).toUpperCase() + greeting.slice(1).toLowerCase()}
      </strong>
      {greeting.endsWith(",") ? (
        " "
      ) : (
        <span style={{ color: "grey" }}>", "</span>
      )}
      <em>{greeted}</em>
      {silent ? "." : "!"}
    </div>
  );
}
```

````
`````

**Output:**
`````markdown
**Prettier pr-6409**
[Playground link](https://deploy-preview-6409--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAqVAFATnGMCWcWABAA5YC0AbACwAMAnOgDpQDaGANgIYCeA5lggBXKABNinfFADWAXQAUACzykAzkgD0msXFKcIvCuTgA3QgHdq9BhWM48hLADoouKQDNezyAFtN+nyCIuKaAJSsAAbRakqsdqTcWGpExABG3Gm8BlBR0ays6ACSUKTCMEgsUNGRAFZqAB6sHqJgBNDEABJwnAYA6hBYnGIKwIJwuNL8xAC8xMwgSj0GCwA0xOO4cBJzAOQLA0NiC7vravicCDCzxB7cnCnr0ACyIikA8qZEqwC+YcTAApQYjEfAeBQAQk2BCg-DCwAcwiwwKgwl6PwA3ECQTjtMQACrvAAi7yQxCJ0F212EKWIWG44ggvlBwJw4iIrBBl2uqOZc2e3BgSmcHgMg2ICgFQuc9MZvgU-1QxAAjABRADUAHYws4YBAAMowLBTBUyvQ8MBwBSaZjMZy2sTqzT4fjrBYLCK5YF03BI4EAHjE+FMxDAPDUagActxfHAZrtur0IIdhrtiAQYJcZsBIgBNETEJJwYjmc56ki8tKpAAkwGIvOIP0iP2ILzecE+RGzbZpHa+WB+AD5sTj-WojdB+IO69Cps41FJLQpiHR1sriDq9QBVUikIgAYW4KQVxHVGxwk1h88XVuVm4gABkIBYD0erf8fv7NOOhLDh96QTGC8YX4ZwEDENQ+nwIUFDWD1iAAfnmEBkOIMkx0SYFx2yONgGASADCwMl9mYcZeF2H4hzWZCvzUTDB0bTlRzgXx-2YGAZ2A7ZGNyGAvxY-8cQBCVzkuWBPSEkEkIWe0QCYoSyQWCEFh+EcQS-INTEHLEvVU6p8i9dB3nKMoKiqGp6iaKAWigNp8A6RN+kGYZRiY2dYRuBYliTODvWhbi9gOZzjhAU4mNEq4bjuB44FWJiew+ftWD+AEmLBCUoWAqZ-kBACfRgP16zRTgdJBPSmLxQkSTJCkoCpYhezpBkxCZFkfXZLAmO5Iq+WIKVhVFCBBklQVhVlFr5UVFU4G1eTiF1A0jRNCScTNQIlxtO0HSdfh8DdOSQDCHSmMRZEJTmwNgzmkEwyPKMYzjBZHOTYL3TykEMyzHN82EQscBLfAy3FSsa2AXkmz0yTWygV5e07LBuxh9t4chnFBMkscJz-a6cSAiYQOvfAl1XFV7x3PcsEPY9-jPdzQIXInb3vJ8X0pt8FVRoTaKxqccbxy9QPAyDoKUWCQDiw7EPO96cQWZCcf+MlYJl9S6IZYhsK+usCMGRSQDIuXKOHcWaO-eiFc55jWP5+AxE-TQBL5iLYClmS5b15SQEtjTg3Ro7kqBGpxZACBSHaKA1GQUAkiECwMCLCPkBAbhTAgfAxGDtJ6TAGRcH1RIwCmZAjWEWLFhgXxOD6JRoLgNXLX1BAy2DaDeCTsAI2D6QUiwGBsG4fhfG4ZBoseEBLIAIWz3OYH1B6H2kOAR-uMfLP1KZLgARWECB4GXmLVhARJkiIJOh6wGQWosKBg-IaQYCgsQhWQAAOVcj6EFI+npUgk5MHuvjBwAI473gNgUOkcUBHgoG4bY2xg44BAfgHA-dB7DyQKPMuKRfD4GLlgUuh9ziwi3qApeGCV5lxgJkR+z8kAACZD5Gm4BcKY+4mRDyTlAaAS9D69nxJkSBmDD6mFLiUXQsB9RgGNGHAAguIQ0OF94pEokAA)

```sh
--parser markdown
```

**Input:**

````markdown
**Prettier pr-6409**
[Playground link](https://deploy-preview-6409--prettier.netlify.com/playground/)

```sh
--parser babylon
```

**Input:**

```jsx
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver
}) {
  if (!greeting) {
    return null;
  }

  // TODO: Don't use random in render
  let num = Math.floor(Math.random() * 1e7)
    .toString()
    .replace(/\.\d+/gi, "");

  return (
    <div
      className="HelloWorld"
      title={`You are visitor number ${num}`}
      onMouseOver={onMouseOver}
    >
      <strong>
        {greeting.slice(0, 1).toUpperCase() + greeting.slice(1).toLowerCase()}
      </strong>
      {greeting.endsWith(",") ? (
        " "
      ) : (
        <span style={{ color: "grey" }}>", "</span>
      )}
      <em>{greeted}</em>
      {silent ? "." : "!"}
    </div>
  );
}
```

**Output:**

```jsx
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver
}) {
  if (!greeting) {
    return null;
  }

  // TODO: Don't use random in render
  let num = Math.floor(Math.random() * 1e7)
    .toString()
    .replace(/\.\d+/gi, "");

  return (
    <div
      className="HelloWorld"
      title={`You are visitor number ${num}`}
      onMouseOver={onMouseOver}
    >
      <strong>
        {greeting.slice(0, 1).toUpperCase() + greeting.slice(1).toLowerCase()}
      </strong>
      {greeting.endsWith(",") ? (
        " "
      ) : (
        <span style={{ color: "grey" }}>", "</span>
      )}
      <em>{greeted}</em>
      {silent ? "." : "!"}
    </div>
  );
}
```
````

**Output:**

````markdown
**Prettier pr-6409**
[Playground link](https://deploy-preview-6409--prettier.netlify.com/playground/)

```sh
--parser babylon
```

**Input:**

```jsx
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver
}) {
  if (!greeting) {
    return null;
  }

  // TODO: Don't use random in render
  let num = Math.floor(Math.random() * 1e7)
    .toString()
    .replace(/\.\d+/gi, "");

  return (
    <div
      className="HelloWorld"
      title={`You are visitor number ${num}`}
      onMouseOver={onMouseOver}
    >
      <strong>
        {greeting.slice(0, 1).toUpperCase() + greeting.slice(1).toLowerCase()}
      </strong>
      {greeting.endsWith(",") ? (
        " "
      ) : (
        <span style={{ color: "grey" }}>", "</span>
      )}
      <em>{greeted}</em>
      {silent ? "." : "!"}
    </div>
  );
}
```

**Output:**

```jsx
function HelloWorld({
  greeting = "hello",
  greeted = '"World"',
  silent = false,
  onMouseOver
}) {
  if (!greeting) {
    return null;
  }

  // TODO: Don't use random in render
  let num = Math.floor(Math.random() * 1e7)
    .toString()
    .replace(/\.\d+/gi, "");

  return (
    <div
      className="HelloWorld"
      title={`You are visitor number ${num}`}
      onMouseOver={onMouseOver}
    >
      <strong>
        {greeting.slice(0, 1).toUpperCase() + greeting.slice(1).toLowerCase()}
      </strong>
      {greeting.endsWith(",") ? (
        " "
      ) : (
        <span style={{ color: "grey" }}>", "</span>
      )}
      <em>{greeted}</em>
      {silent ? "." : "!"}
    </div>
  );
}
```
````

`````
````````````````````````````````````

</details>

**Comment by Drapegnik** [comment]
@lydell, fixed.

**Comment by lydell** [comment]
Nice!

One question – what is the purpose of the “short report”? I'm thinking that it'll be easier for the user to paste the full report if the text box is as empty as possible. So maybe it's better to always have only the comment pre-filled?

I also wonder if we can come up with better copy for the comment?

Here's an attempt at helping the user _where_ to paste. (They can't paste _inside_ the comment, or immediately to the right of it.)

```md
<!-- The report has been copied to the clipboard. Please paste it after this line! -->

```

Maybe users don't know what "report" means here? Is "playground" a better word? I also tried an alternate "paste" copy here:

```md
<!-- The playground has been copied to the clipboard. Paste it to get started with your issue! -->

```

Yet another version. Maybe too long?

```md
<!--
The playground has been copied to the clipboard.
Remove this comment and paste!
(Your code is too long for GitHub's autofill feature.)
-->

```

**Comment by Drapegnik** [comment]
@lydell, how about [this one](https://github.com/prettier/prettier/issues/new?body=%3C!--%20The%20issue%20body%20has%20been%20saved%20to%20the%20clipboard.%20Please%20paste%20it%20after%20this%20line!%20%F0%9F%91%87%20--%3E%0A)?

File: website/playground/Playground.js [hunk 2]
```diff
@@ -42,6 +42,10 @@ const ENABLED_OPTIONS = [
   "requirePragma",
   "vueIndentScriptAndStyle"
 ];
+const ISSUES_URL = "https://github.com/prettier/prettier/issues/new?body=";
+const MAX_LENGTH = 8000 - ISSUES_URL.length; // it seems that GitHub limit is 8195
+const COPY_MWSSAGE =
```
Comment (lydell) [inline website/playground/Playground.js]:
```suggestion
const COPY_MESSAGE =
```

File: website/playground/Playground.js [hunk 3]
```diff
@@ -135,131 +139,144 @@ class Playground extends React.Component {
...
+                      <ClipboardButton
+                        copy={() =>
+                          this.getMarkdown(formatted, debug.reformatted)
+                        }
+                      >
+                        Copy markdown
+                      </ClipboardButton>
+                      <a
+                        href={getReportLink(
+                          showFullReport ? fullReport : COPY_MWSSAGE
```
Comment (lydell) [inline website/playground/Playground.js]:
```suggestion
                          showFullReport ? fullReport : COPY_MESSAGE
```

File: website/playground/buttons.js [hunk 4]
```diff
@@ -41,16 +37,16 @@ export class ClipboardButton extends React.Component {
   }
 
   render() {
+    const { children } = this.props;
```
Comment (lydell) [inline website/playground/buttons.js]:
```suggestion
    const { children, copy, ...rest } = this.props;
```

Comment (lydell) [reply website/playground/buttons.js]: This should allow for removing the three `rest` lines below, right?

Comment (Drapegnik) [reply website/playground/buttons.js]: @lydell, yep, but it falls with:
```bash
[1] SyntaxError: Unexpected token (40:31)
[1]
[1]   38 |
[1]   39 |   render() {
[1] > 40 |     const { children, copy: _, ...rest } = this.props;
```

there is no [`proposal-object-rest-spread`](https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread) plugin

**Comment by lydell** [comment]
Thanks! Great job! Would you like to fix the other part of #6409 too?

**Comment by Drapegnik** [comment]
@lydell, you are about [tooltips](https://github.com/prettier/prettier/issues/6297#issuecomment-511137776)?

**Comment by lydell** [comment]
Yes, that’s correct! If you feel like it, fixing that little annoyance would be awesome.
