### PR TITLE
Make JSON parser stricter

### LINKED ISSUE #10333: Markdown code-block with wrong language yields garbage
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdArAztAOlABwEMwBrIgczi11xgAs4BaegVwCNawBPAgJ2o1cAMwCWADxisBQin1EATAMLQxFaURijoAOmx4o6VPhAAaEBAJboWZKCJ8+EAO4AFBwlsoiAG2dFuW3N2PhJSOBgAZWIwUSgKZBg+VjhzOABbdjgFBWyAGSJ41ko4ADEIPnTNLXjkECJWGAgzEHoYdJ8AdXpReCwYuEjPXtEAN17uOrAsIJA4rDg+GFdQiirkYV8F82xxACFQsgjIonS4PLi4Da3UkF3IuIofOABFVgh4a59tkGI+Bb4dSqfFIChcUBa-DiME6igYyAAHAAGcz8CALTqhAh1fjURajK7mACO73gK0sXnqWCYUDg2WyLQEJNEAhWlHWSE231uC3SokSyR5j2ebw+V05N3MMCI7FhCnhSAATFLQqIfI8VOkOSBqABWFqsBYAFRlXi5P1GKQAklBcrBImB5FYAIK2yIwbjPL4LAC+PqAA)

**Input:**

Markdown document with:
<pre>
```json
packages\the-hub\cypress\fixtures\gridConfiguration.json
```
</pre>

**Output:**

<pre>
```json
packagespackages\the -
  hubhub\cypresshub\cypress\fixtureshub\cypress\fixtures\gridConfiguration.json
```
</pre>

**Expected behavior:**

If the content cannot be parsed as the requested language, throw.

### PR DESCRIPTION
**Pull request by fisker**
## Description

Make JSON parser stricter, I don't think we should allow all expressions.
And we don't need all the `plugins` and `errorRecovery`.

Fixes #10333

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-js/parser-babel.js [hunk 1]
```diff
@@ -179,15 +180,32 @@ function shouldRethrowRecoveredError(error) {
   return messagesShouldThrow.has(message);
 }
 
-function parseJson(text, parsers, opts) {
-  const ast = parseExpression(text, parsers, opts);
+function createJsonParse(options) {
+  // @ts-ignore
+  const { allowComments } = { allowComments: true, ...options };
```
Comment (thorn0) [inline src/language-js/parser-babel.js:185]:
```suggestion
  const { allowComments = true } = options;
```

**Review by thorn0 — APPROVED** [review]

**Review by sosukesuzuki — APPROVED** [review]

**Comment by thorn0** [comment]
Oops, we broke JSON5! https://spec.json5.org/#numbers

**Prettier pr-10346**
[Playground link](https://deploy-preview-10346--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEwBmEJIJJTQSynxgE8BfEAGhAgAcZ9oBnZUAQwCcOIB3ABU4IWKNgBsebEi2oAjDmzABrODADKtBYQDmyGBwCucanAC2MuABMLlgDJsoW-Wy1wAYhA4m2MBg+Qg2fRgIKhAACxgTUQB1MOI4Jg0wOFUhYnwAN2ISfzAmaRBCJjgOGD55LS9kNDFi6gArJgAPACF5JRVVNhM4G0I4atqjEEam1W1ROABFfQh4QdE6kA0OYo5-RugAVlDaDkIYaPwLGDDkAA4ABmo9iGLo+Vp-PYSSjIHqAEdZ+HK6YQCTAAtFA4JZLKEOHBvvgoeVnFUkDVFsNiiZ8LoDKiJtMfgMkUNqDA2DIjiczkgAExE+T4UTaADCEBMiJACR21H0xQAKiThMilhlDLhrLBVGB9vQAIJQCyqUiTBbFMhkIA)

```sh
--parser json5
```

**Input:**

```json5
{foo:Infinity}
```

**Output:**

```json5
SyntaxError: Identifier is not allowed in JSON. (1:6)
> 1 | {foo:Infinity}
    |      ^
```

**Comment by fisker** [comment]
I'll fix
