### PR TITLE
Fix HTML AST JSON serializer for debugging

### LINKED ISSUE #12609: Playground: Errors when displaying HTML AST
スクリーンショット 2022-04-07 10 06 01

Printing works well.

**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmpaEAqc2+8AzmXgE5xkBmEbGB8ACasWAdzg4cAOhmoA9NVLzMuAnBJRSpEABoQELDACW0JslDs2EUQAV2CMyjw5ReAJ5m9AIzZ4wAazgYAGU8DDgAGSMoOGQuZyY4b18AoOCsP2iAc2QYNgBXJJB6LzhBQTKIvCgs-LwsuAAxXn4YYxrkEDx8mAhdEAALGAwcAHUBo2YMsDhgh0mjADdJt06wJk8QaMS2GBtfLP44hKKAKyYAD2DsnDgARXyIeGOcRL0Mth3OoZH+rDZojBRkZBDABsgABwABneVkSo18WE6-zgO0WsT0AEdHvB9gZHF0mABaGJlMr9DjYowcfb1I5IeKvIqJDBGXIFZk3e442IMk56GB4LzA0HgpAAJgFviMOGyAGEIBh6cUmABWfr5RI0IWORlvECLQoASSgFVgwTAAMMAEFTcEYG5bi9EgBfF1AA)

```sh
--parser html
```

**Input:**

```html
<template>
  <p>Templates are formatted as well...</p>
</template>



```

**Output:**

```html
<template>
  <p>Templates are formatted as well...</p>
</template>

```

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #12609 

## Checklist

- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Can you open another PR to try set `.parent` non-enumerable with this https://github.com/prettier/prettier/blob/f98c197b66db7491021f5d1cb65d137aa5d7ac68/src/language-html/ast.js#L180?

**Comment by fisker** [comment]
Or maybe it should work if we add `.parent` to the prototype?

**Comment by fisker** [comment]
If it doesn't work, we can also add `.toJSON` method. I think better fix in the html parser.

**Comment by sosukesuzuki** [comment]
I've addressed your review with using `setNonEnumerableProperty` [38f59b0](https://github.com/prettier/prettier/pull/12611/commits/38f59b00e4f42b178805b5a007884ce2a0689830)

File: src/language-html/ast.js [hunk 1]
```diff
@@ -16,6 +16,8 @@ class Node {
     for (const [key, value] of Object.entries(props)) {
       if (key in NODES_KEYS) {
         this._setNodes(key, value);
+      } else if (key === "parent") {
+        setNonEnumerableProperty(this, "parent", value);
```
Comment (fisker) [inline src/language-html/ast.js:20]: I think this will break `Node#clone()`, but it seems already broken before since properties like `.prev` is also non-enumerable

**Comment by fisker** [comment]
There is another one in `cloneAndUpdateNodes`.
Let's fix this with https://github.com/prettier/prettier/pull/12611#issuecomment-1091162767? I think it's a better approach.

File: src/language-html/ast.js (hunk 1 above)
Comment (sosukesuzuki) [reply src/language-html/ast.js:20]: Hmm, I just want to output the html AST with `--debug-print-ast` for other work, so what do you think about merging once the first implementation that specify the replacer function in the `JSON.stringify`?  I think other issues can be addressed later.

**Comment by fisker** [comment]
Turns out setting `.parent` as non-enumerable did break the `clone()` and `new Node()`, but we can always clone `.parent` when calling `.clone()`.

- I added a new `.setProperty()` to replace the old `clone()`/`new()`/`_setNodes()` logic, I think it's more clear.
- I also turn `. attrMap` from non-enumerable property to a `getter`, so we don't need to copy it when cloning.

**Comment by fisker** [comment]
Feel free to merge, if you are fine with those changes.

File: src/language-html/ast.js [hunk 2]
```diff
@@ -8,33 +8,40 @@ const NODES_KEYS = {
...
     }
+
+    Object.defineProperty(this, property, {
+      value,
+      enumerable: false,
+      configurable: true,
+    });
   }
 
   map(fn) {
```
Comment (fisker) [inline src/language-html/ast.js:47]: This may need an update in future, seems overcomplicated.

**Comment by sosukesuzuki** [comment]
Thanks
