### PR TITLE
Fix exports comment formats.

### LINKED ISSUE #12750: Inconsistent between comments inside export and import specifiers
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACYAHSjzwDMIIAaY02vAIwENs8mBnUgei70gFt+CGMUIj8zAF40oAX3LYI-PAHIKEFaKjosuAvXUy6JRizac8PPkqGxR409OKytAS3678RE4fr1mrBzcvAK2IlBiYo4y8mSKymqUKiBUIBAYMK7Q7MigLIoA7gAKLAg5KEwANgVMAJ45qQzYTGAA1nAwAMpMQgAyrtrIZFXscI3NbR2dGC0DAObIMNgArmOo-AxwACZb271MUHPLTHNwAGI4-EwwmYfIIEzLMBApIAAWMPyVAOpvrvDsGZgOCdMr-VwAN3+tXuYHYDRAA1GuCKzTmVyGIzWACt2GhOvNKnAAIrLCDwTGVUapGbYZH3ZibSqvDDYAYwb6uLYwN7IAAcAAYaYpRt9mhh7qy4MiIXBXgBHMnwVHpcoPdgAWm0222r2wcEVrn1qJOGKQwypa1G-FcixWVsJJKVcvNWNSMCYDE53N5SAATO7mq5KvMAMI2Jj3aUAVley1GABVPeULdSQBDVgBJKC7WCdMBsjIAQRznRgtSJlNGslkQA)

```sh
--parser babel
```

**Input:**

```jsx
export {
  foo,
  
  bar as  // comment
		 baz,
} from 'foo'

export {
  foo,
  
  bar as  // comment
		 baz,
}

import {
  foo,
  
  bar as  // comment
		 baz,
} from 'foo'
```

**Output:**

```jsx
export {
  foo,
  bar as baz, // comment
} from "foo";

export {
  foo,
  bar as baz, // comment
};

import {
  foo,
  // comment
  bar as baz,
} from "foo";

```

**Expected behavior:**

This is edge case, but worth to investigate where the difference is.

[#12746](https://deploy-preview-12746--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACYAHSjzwDMIIAaY02vAIwENs8mBnUgei70gFt+CGMUIj8zAF40oAX3LYI-PAHIKEFaKjosuAvXUy6JRizac8PPkqGxR409OKytAS3678RE4fr1mrBzcvAK2IlBiYo4y8mSKymqUKiBUIBAYMK7Q7MigLIoA7gAKLAg5KEwANgVMAJ45qQzYTGAA1nAwAMpMQgAyrtrIZFXscI3NbR2dGC0DAObIMNgArmOo-AxwACZb271MUHPLTHNwAGI4-EwwmYfIIEzLMBApIAAWMPyVAOpvrvDsGZgOCdMr-VwAN3+tXuYHYDRAA1GuCKzTmVyGIzWACt2GhOvNKnAAIrLCDwTGVUapGbYZH3ZibSqvDDYAYwb6uLYwN7IAAcAAYaYpRt9mhh7qy4MiIXBXgBHMnwVHpcoPdgAWm0222r2wcEVrn1qJOGKQwypa1G-FcixWVsJJKVcvNWNSMCYDE53N5SAATO7mq5KvMAMI2Jj3aUAVley1GABVPeULdSQBDVgBJKC7WCdMBsjIAQRznRgtSJlNGslkQA) didn't change output.

### PR DESCRIPTION
**Pull request by HosokawaR**
## Description

Fixes #12750

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-js/comments.js [hunk 1]
```diff
@@ -61,7 +61,7 @@ function handleOwnLineComment(context) {
     handleWhileComments,
     handleTryStatementComments,
     handleClassComments,
-    handleImportSpecifierComments,
+    handleImportAndExportSpecifierComments,
```
Comment (fisker) [inline src/language-js/comments.js:64]:
```suggestion
    handleModuleSpecifierComments,
```

Comment (HosokawaR) [reply src/language-js/comments.js]: Thank.
It's the best naming.
I fixed.

File: src/language-js/comments.js [hunk 2]
```diff
@@ -623,8 +623,11 @@ function handleLastFunctionArgComments({
   return false;
 }
 
-function handleImportSpecifierComments({ comment, enclosingNode }) {
-  if (enclosingNode?.type === "ImportSpecifier") {
+function handleModuleSpecifierComments({ comment, enclosingNode }) {
```
Comment (fisker) [inline src/language-js/comments.js:626]: Sorry, I thought this was the function added in #12746, can we move this part of logic into `handleModuleSpecifiersComments` function?

Comment (HosokawaR) [reply src/language-js/comments.js]: Sound good. 
I fixed.

File: tests/format/js/comments/export.js [hunk 3]
```diff
@@ -20,3 +20,21 @@ export {
...
+} from 'foo'
+
+const fooooo = ''
+const barrrr = ''
+export {
+  fooooo,
+
+  barrrr as  // comment
+		 bazz,
+}
```
Comment (fisker) [inline tests/format/js/comments/export.js:40]: Can we add `import` test here too? Or maybe in other better place? So we can notice the change between import/export in one place.

Comment (HosokawaR) [reply tests/format/js/comments/export.js:40]: Thank !

> Can we add import test here too? Or maybe in other better place?

I created `export-and-import.js` and added tests to compare comment formats in `export` and `import` in it.
Because I thought `export.js` should only content about `exports`.

**Review by fisker — APPROVED** [review]
Thanks for working on this.

**Review by sosukesuzuki — APPROVED** [review]
Thank you!!
