### PR TITLE
fix: newline between front-matter and comment

### LINKED ISSUE #4687: [CSS] newlines/spaces between front-matter and comment
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdKBnCBbOGACwEsoBzLdVLLAegCoACSPA2JhurAOlwOJlyTYFgC+IADQgIABxglo2ZKACGAJ3UQA7gAUNCZSlUA3CCQAmUkACN1qsAGtCAZVkOhyGOoCucaWTYcOowuvbkeKrIAGaqADZB0gBW2AAeAEL2Tq6qBAAyZHAx8Ykg7upB6sjg2MrSsupkMADqlsTIABwADPVaQc32stUNcJUmRdLqcACOPiRTYaoRUUixCf4gQXgkXr4b2EJxcACKPhDwxevSMKo2rRbtSABM1-YkcUIAwviR1VDQExAPiCABVbkY1kExGIgA)
```sh
--parser css
```

**Input:**
```css
---
something
---

/* comment */
.something {
}
```

**Output:**
```css
---
something
---
 /* comment */
.something {
}

```

**Expected behavior:**
Same as input.

### PR DESCRIPTION
**Pull request by evilebottnawi**
fixes #4687

### CODE REVIEW

File: src/language-css/printer-postcss.js [hunk 1]
```diff
@@ -828,15 +828,16 @@ function printNodeSequence(path, options, print) {
...
           )) ||
-        (node.nodes[i + 1].type === "css-atrule" &&
-          node.nodes[i + 1].name === "else" &&
-          node.nodes[i].type !== "css-comment")
+          (node.nodes[i + 1].type === "css-atrule" &&
+            node.nodes[i + 1].name === "else" &&
+            node.nodes[i].type !== "css-comment"))
       ) {
         parts.push(" ");
       } else {
```
Comment (ikatyang) [inline src/language-css/printer-postcss.js]: There's a potential bug in:

https://github.com/prettier/prettier/blob/56af3d621d6890819d65d4c3604425f187e7643a/src/language-css/printer-postcss.js#L842-L849

where `isNextLineEmpty` _could_ be `true` for `front-matter`, but it's currently always `false` since there's no loc info in `front-matter`:

https://github.com/prettier/prettier/blob/56af3d621d6890819d65d4c3604425f187e7643a/src/language-css/parser-postcss.js#L500-L503

Two wrongs make the thing right, I think we should fix it somehow? (maybe in another PR)

Comment (evilebottnawi) [reply src/language-css/printer-postcss.js]: @ikatyang can you give example where potential we have bug?

Comment (ikatyang) [reply src/language-css/printer-postcss.js]: I meant, if we fix the bug that there's no loc info in `front-matter`, then it'll become a bug.

```diff
 result.nodes.unshift({
   type: "front-matter",
   value: frontMatter,
+  source: {
+    start: { line: 1, column: 1 },
+    end: {
+      line: frontMatter.split("\n").length,
+      column: frontMatter.split("\n").pop().length
+    },
+    input: { css: frontMatter }
+  }
 });
```

```diff

 ---
 ---
 
 /** @prettier */
 
 .class {    display: none;    }
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ---
 ---
 
+
 /** @prettier */
 .class {
   display: none;
 }
```
