### PR TITLE
Fix vue self-closing tags

### LINKED ISSUE #3692: Vue self-closing tags cause double-printing
Was running vue on gitlabhq and ran into this:

**Input:**

```vue
<script>
</script>

<template>
  <br />
</template>
```

**Output:**

```vue
<script>
</script>

<template>
  <br />
</template><script>
</script>

<template>
  <br />
</template>
```
  
/cc @vjeux

### PR DESCRIPTION
**Pull request by azz**
Looks like the way the parsing works doesn't add `end` properties to self-closing tags and their parents (all the way up?). Couldn't figure out a nice way to fix it in the parser so just did it in the printer for now.

Copied in an example component from GitLabHQ.

Fixes #3692

### CODE REVIEW

**Comment by azz** [comment]
https://deploy-preview-3693--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAzmATgSwA4wB8AOlAARkBmEEZAFGQJSmoD0muBJ5L8AtngA2AQ3jcKqAEZYyrcWVTUI8LPIpLSFCdLmaFrJSu5t+Q0XG4gANCAgEc0dMlDCsWCAHcACq4ROUwgBuEDgAJtYgwugwyJTCguhwNtLCYADWcDAAynipOFAA5sgwWACuSSChEGCx8Yk2+YlYMF5YwgV8wrUJFQBW6AAeAEJt6ZlZwnxwADL5cN31tqUweMsATAsVuVhNyCCB5RF4uLAA6mEwABbIABwADDbHEImnbXh7x3BNgfM2WHAAR1KOH+rXanU2NkSfBwxTKFXQ+QKgjgAEVSsp5kg4j0bDBhJJzqErsg1ni2jhBEiAMIQPgQlBQaC-EClRIAFQJ-hxiQAvrygA

File: src/language-vue/printer-vue.js [hunk 1]
```diff
@@ -3,19 +3,33 @@
...
   }, "children");
-  res.push(options.originalText.slice(index, n.end));
+
+  if (printParent) {
+    res.push(options.originalText.slice(index, n.end));
+  }
+
+  // Only force a trailing newline if there were any contents.
+  if (n.tag === "root" && n.children.length) {
+    res.push(hardline);
```
Comment (vjeux) [inline src/language-vue/printer-vue.js]: What happens if there’s already a trailing (or more) new line, is it going to add one more?

Comment (azz) [reply src/language-vue/printer-vue.js]: It does... I tried to do a right trim on the content but it didn't work.

Comment (vjeux) [reply src/language-vue/printer-vue.js]: I also tried to normalize this but figured it would not be worth it. I think that the best way forward is to pretty print the first depth of html for vue files. This way we clean up the code a bit more and will handle this newline.

Comment (azz) [reply src/language-vue/printer-vue.js]: Actually no, it works just fine as is.
