### PR TITLE
Fix `ifBreak` check in `fits`

### LINKED ISSUE #12352: Unnecessary line breaks caused by `ifBreak` with group id nested in `group` with the same id
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEmBmEBOmAFJFAM4yZn5gAKAhjABaYQ6YDaAjAEwDMAGky8+AfRHj+QiTP7jpYiXyVdRAFj48AugEpM6LJgC+GIyAEgIABxgBLaGWSh6+fBADuDfAkcp6AG3d6AE9HCwAjfHowAGs4GABlegBbOAAZWyg4ZBwAsjgIqNj4hKtozIBzZBh8AFcCkDhk8LgAE1a2tPooCtr6CrgAMQJkxjse5BB6WpgIcxAmGGT-AHUmW3gyMrA4BJ8N2wA3DeDJsDIwkEz8-BhaKIrRnLyGgCsyAA8Eyv84AEVahB4M9-PkLGV8DdJuF6C1-PMrPhMjAVrZWsxkAAOAAM4Lc+RWUSsk0RcBuh2yFgAjoD4PdrL4pmQALRZNptebeGm2bz3fpPJC5UENfLJWzVOoin7-WnZQUvCwwWGo9FMZA8RVRWz+SoAYQgyQFjTIAFZ5rV8gAVWG+IVgkCHeoASSgHVgCTASJsAEFXQkYMFfiD8kYjEA)

```sh
--parser babel
```

**Input:**

```jsx
{
  for (const srcPath of [123, 123_123_123, 123_123_123_1, 13_123_3123_31_432]) {
  }
}
```

**Output:**

```jsx
{
  for (const srcPath of [
    123, 123_123_123, 123_123_123_1, 13_123_3123_31_432,
  ]) {
  }
}

```

**Expected behavior:**

Should format as input.

Found this when playing with the "doc", in this case, the input is exactly 80 width. I think there should be bug in the doc print.

The test code from https://github.com/prettier/prettier/blob/2cde2dbf9d280260f8c499039d89419b21fa4dc0/tests/format/js/arrays/issue-10159.js#L3

@thorn0 You may interest.

### PR DESCRIPTION
**Pull request by fisker**
## Description

Fixes #12352

I tried different logic, this one seems working.
In this version, don't trust `group.break = false`, and assume `MODE_FLAT` when calling `fits()`.

I couldn't understand why we inherit "mode" from parent group? Shouldn't we always measure width in flat mode?

Another question about `group.break`, shouldn't is "undefined" by default? And we should add another "mode" and have different logic, I can image how hard this will be, break can be decided by other things, will be huge measure call or even circular.

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
I remember I played with this too, but I don't remember my conclusions. I hope I'll find some time to look into this to distract myself from what's going on here in my country.

File: src/document/doc-printer.js [hunk 1]
```diff
@@ -203,7 +203,8 @@ function fits(next, restCommands, width, options, hasLineSuffix, mustBeFlat) {
               : doc.contents,
           ]);
 
-          if (doc.id) {
+          // `doc.break = false` can't be trusted
+          if (doc.id && doc.break) {
```
Comment (thorn0) [inline src/document/doc-printer.js:207]: I didn't look deeply into this yet, but this doesn't look right. Groups can be broken not only because of `doc.break`. Dynamically broken groups, those that are broken because they don't fit, don't have `doc.break`.

Comment (fisker) [reply src/document/doc-printer.js:207]: I know, I don't really understand this function.

> I couldn't understand why we inherit "mode" from parent group? Shouldn't we always measure width in flat mode?

This is my question.

Comment (fisker) [reply src/document/doc-printer.js:207]: I tried, a) always MODE_FLAT, b) add 'undefined' mode, c) #12359. They all breaking things.

Comment (fisker) [reply src/document/doc-printer.js]: I removed this part... Seems the same, decide `groupMode` here is wrong, even if `doc.break = true`, `fits()` printed doc is not the final output, maybe we can just remove this line?

Comment (fisker) [reply src/document/doc-printer.js]: I guess I'm right about this, this is wrong at the first place, it happened not using ifBreak inside the group with same id. https://github.com/prettier/prettier/pull/4563/files#diff-6ffe0e63f15d2bde411262c9dd7a96802e2a5ac2dbc5f4732f03c12dce6e5b7bR313

**Comment by fisker** [comment]
@thorn0 Got time to review?

File: src/document/doc-printer.js (hunk 1 above)
Comment (thorn0) [reply src/document/doc-printer.js]: > I couldn't understand why we inherit "mode" from parent group? Shouldn't we always measure width in flat mode?

Is this question about this line:

```js
          const groupMode = doc.break ? MODE_BREAK : mode;
```

?

Comment (fisker) [reply src/document/doc-printer.js]: Yes, but that.

Comment (thorn0) [reply src/document/doc-printer.js]: Consider sibling groups like this:
```js
[
  group(["(GROUP1-a", line, "GROUP1-b)"]),
  " ",
  group(["(GROUP2-a", line, "GROUP2-b)"]),
]
```
([doc explorer playground][doc1])

When the first group is printed, the second group is measured in `MODE_BREAK` inside the `fits` call. It means the group doesn't have to fit fully, only its part before the first line break. If these groups had nested groups, the same measurement rules would need to be used for them as for their parent groups. That's why `mode` is inherited.

Everything is good as long as only groups and line breaks are involved. `ifBreak` is a problem. A group measured in `MODE_BREAK` doesn't necessarily break, but `case "if-break"` in `fits` is implemented as if it were the case. This leads to [buggy results][buggy]. In fact, when `case "if-break"` is reached, it's not known yet if the group fits or breaks, so choosing between `doc.flatContents` and `doc.breakContents` can't be done fully correctly without introducing a lot of complexity (nested `fits` calls?). However, this problem somehow isn't noticeable in practice. I guess Prettier never uses `ifBreak` before line breaks inside groups, and we should consider this a known design limitation.

Similarly, your solution in this PR might be not 100% strict (`fits` doesn't really know yet whether the ancestor group with the given id breaks), but it might be good enough. I'd like to play with it a little more though.

[doc1]: https://deploy-preview-10183--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBtAOlABFg5gJwgFcAHACgxDIHEAlAeQFUAFARgFoBDdEAGiwA2ASyhx+POkzbsARgEoeAXTm9MOHlh6rseQqQo8aDFgCYuWwSLGaQk07IUhl2xXxAQSMIdADOyUJz4hADuzIEIfiicAsGcAJ5+vCAy+JxgANZwMADKnAC2cAAyVsgAZtE+YsmpGVnZJGkiuMgw+ERVcHkycAAmPb2FnFC4RJy4cABiEPh5nDBew8ggnEQwEG4AFjB5AgDqG0LwPg1gcNkRh0IAbodxS2A+iSAilfgwzKm4s2UVVQBWPgAHtkmgI4ABFIgQeA-ASVJINfCvJY9CBgdhwQEkATTOD4NwkfAiGC7IQ9GAbZAAZgAHAjCJVdqkSEtCXBXlc4G4AI5Q+AfDyRZY+diiXq9Nz4OC8oRSj5jb5IcpwqqVPJCFptVWgiF8rlK35JGCcGSk8mUpAmI2pITCYYAYQgeUVIHZAFY3ERKgAVE2RZXwkBXdoASSg-Vg2TARM8AEFw9kYHEwbDAwDAQAhGqZHL5IolA0qgC+RaAA
[buggy]: https://deploy-preview-10183--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBtAOlABFg5gJwgFcAHACgxDIHEAlAeQFUAFARgFoBDdEAGiwA2ASyhx+POkzbsARgEoeAXTm9MOHlh6rseQqQo8aDFgCYuWrEIBmAIXxxOAazIbJp2XIDUPFYJFjNEDdmM3klFUxFPhAIEhghaABnZFBOfEIAd2Y0hGSUTgEMzgBPZN4QGXxOMEc4GABlTgBbOAAZf2QrAsSxCqqauvqSapFcZBh8Il64Jpk4ABN5hdbOKFwiTlw4ADEIfCbOGHi15BBOIhgIaIALGCaBAHVroXhE4bA4etyXoQA3F+KpzAiTKIBEPXwMGYVVwB063V6ACtEgAPeqjARwACKRAg8HhAh65WG+Ahp3mEDA7DgKJIAj2cHw0RI+BEMAeQnmMGuyAAzABOYmEHoPKokU4suAQ35waIAR1x8GhsTyZ0S7FECwW0XsCqE9mhmzhSC6hN6PSaQnGk3NGOxitlJoR5RgnBkHK5PKQJhdVSEwjWAGEIE1jSApQBWaJEHoAFTdeVNRJAvymAEkoEtYPUwKy4gBBTP1GDFTEE5PIlF2aq1BrNNodJ1mgC+zaAA

Comment (fisker) [reply src/document/doc-printer.js]: Thanks!

**Review by thorn0 — APPROVED** [review]
Looks good!

**Comment by fisker** [comment]
Thank you for your time.
