### PR TITLE
Fix class implements with long type parameters

### LINKED ISSUE #8943: Ugly formatting for class implements with long type parameters
This is regression on master. I found this when work on #8941.
**Prettier pr-8931(Current master)**
[Playground link](https://deploy-preview-8931--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgEpzqqoCeBRpAMtAOYBy6AtnAEwA8AOlDjgCokAHOAEEATjQCuzWHSkAjOKIDyUOABouPfkLGTpMWYwWjeAdwgbufQSPFSEB+Yt4ALUXDhcAfDgCWjAVQ4fVwAISw4AElYRQAzdDA4HGAAXy4QNRAIARhfaExkUHRRUQhTAAVihAKUIlN0EgLMuVEEgGs4GABlAQTfKBpkGFEJdRBghQATSbhJynQBiXQaOAAxCFFGdBhcgeQQdAkYCAyQFxhGVAB1F194TF7Eruq73wA3O5J9sGxT-sxFDByq0aFtkPFUADMgArTAAD1CrTAHW6TDglH6cHBRChIFhcK6-RoQQAihIIPBsZCxr1RADRPsYDZMGBRL4cqcBGzYFdfJMYC5kAAOAAMmS5EABV1aAn2XLg9LeWMyAEdyfBgdkagdMABaVSzWandxq3zuYHLMFICG4gGMXxDEZjTBE0nqrHWnFjGDoOS8-mCpAsTLDdC+VBEgDCEEYVvGmAArKcJADeL6ajaxm9RtEZrAuqz2TBhFBJl0mUEqQCUikgA)
```sh
--parser typescript
```

**Input:**
```tsx
class ReallyReallyLongName2<
  TypeArgumentNumberOne,
  TypeArgumentNumberTwo,
  TypeArgumentNumberThree
> implements BaseInterface {}

```

**Output:**
```tsx
class ReallyReallyLongName2<
    TypeArgumentNumberOne,
    TypeArgumentNumberTwo,
    TypeArgumentNumberThree
  >
  implements BaseInterface {}

```

**Expected behavior(2.0.5 output):**

```tsx
class ReallyReallyLongName2<
  TypeArgumentNumberOne,
  TypeArgumentNumberTwo,
  TypeArgumentNumberThree
> implements BaseInterface {}

```

### PR DESCRIPTION
**Pull request by sosukesuzuki**
Fixes #8943

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
**Prettier pr-8967**
[Playground link](https://deploy-preview-8967--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQA8eA8uRZVddQDRk2NPm04B8OAlgLYAOqcbghi4CEHMAC+IWiAi8YnaJmSh0AJ3UQA7gAUNCFSnSpt6AJ4rZAI3XowAazgwAyr3ucoAc2Qx1AVzhZQWs4ABMw8IAZdG9-dC84AnVudBhFb2QQdH8YCBkQAAsYblQAdULOeEx3MDgXQyrOADcq8yywbALPTDh1GF07L1TkADMTXtkAK0wADwAhO0dnF3QhKM84MYmgkBnZl08vAQBFfwh4bdRJkHd1XvUsmHNeOEwwdU4FAt5P2DLOGEYIVkAAOAAMsl+EF6ZTsvCyvzefWaW1kAEdzvBBvIjNlMABaKBwcLhArqOCYzgUwYJEZIcbXXa9bicXwBZlHU5YrYMnayGDoawAoEgpAAJgFdk4qCOAGEINx6SA3gBWAr+XoAFSFRkZN2agQAklBIrAXB8vjAAIKmlzPARXXqSSRAA)
```sh
--parser typescript
```

**Input:**
```tsx
class Foo<FOOOOOOOOOOOOOOOOOOOOOOOOOOO,FOOOOOOOOOOOOOOOOOOOOOOOOOOO, > implements Foo {}
```

**Output:**
```tsx
class Foo<FOOOOOOOOOOOOOOOOOOOOOOOOOOO, FOOOOOOOOOOOOOOOOOOOOOOOOOOO>
implements Foo {}

```

**Expected:**

```tsx
class Foo<FOOOOOOOOOOOOOOOOOOOOOOOOOOO, FOOOOOOOOOOOOOOOOOOOOOOOOOOO>
  implements Foo {}

```

File: src/language-js/printer-estree.js [hunk 1]
```diff
@@ -4111,6 +4111,10 @@ function printTypeScriptModifiers(path, options, print) {
   return concat([join(" ", path.map(print, "modifiers")), " "]);
 }
 
+function getTypeParametersGroupId(node, options) {
+  return Symbol.for("prettier.typeParameters" + options.locStart(node));
+}
```
Comment (fisker) [inline src/language-js/printer-estree.js:4116]: This mean to use different Symbol for different Node?

This work?

```js
const typeParametersGroupIds = new WeakMap();
function getTypeParametersGroupId(node, options) {
  if (!typeParametersGroupIds.has(node)) {
   typeParametersGroupIds.set(node, Symbol());
  }
  return typeParametersGroupIds.get(node);
}
```

Comment (sosukesuzuki) [reply src/language-js/printer-estree.js:4116]: Yes, your suggestion looks good. Thank you.

File: tests/typescript/class/__snapshots__/jsfmt.spec.js.snap [hunk 2]
```diff
@@ -151,6 +178,34 @@ class ExtendsAbstractClassAndImplementsInterfaces5
...
+  TypeArgumentNumberTwo,
+  TypeArgumentNumberThree
+> implements BaseInterface {}
+
+class ImplementsInterfaceClassWithComments1<
+    TypeArgumentNumberOne,
+    TypeArgumentNumberTwo,
+    TypeArgumentNumberThree
+  > // comments
+  implements BaseInterface {}
```
Comment (evilebottnawi) [inline tests/typescript/class/__snapshots__/jsfmt.spec.js.snap:207]: Why not:
```ts
class ImplementsInterfaceClassWithComments1<
  TypeArgumentNumberOne,
  TypeArgumentNumberTwo,
  TypeArgumentNumberThree
> 
  // comments
  implements BaseInterface {}
```

or
```ts
class ImplementsInterfaceClassWithComments1<
  TypeArgumentNumberOne,
  TypeArgumentNumberTwo,
  TypeArgumentNumberThree
> // comments
  implements BaseInterface {}
```
```

Comment (sosukesuzuki) [reply tests/typescript/class/__snapshots__/jsfmt.spec.js.snap:207]: Because to follow test for similar behavior: https://github.com/prettier/prettier/blob/master/tests/typescript/interface/__snapshots__/jsfmt.spec.js.snap#L170-L175

Comment (sosukesuzuki) [reply tests/typescript/class/__snapshots__/jsfmt.spec.js.snap:207]: But I don't know it was intended.

**Review by evilebottnawi — APPROVED** [review]
I think we can improve implements and extends in future, related https://github.com/prettier/prettier/issues/5156, here only types
