### PR TITLE
Fix formatting error on optional call expression and member chain

### LINKED ISSUE #15916: TypeError: Cannot read properties of undefined (reading 'type')
**Prettier 3.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdrJQM41QJwEMoATCAWwDEBXKMAS2lQF5UAKAN0IBtq4BKJKg4R6JFgD5UwADpQMC1PQBm7LrzgA6Qv2lzFB1MtpgAgm32GrMkDYA0lqweN0AQhflOvJQgE8AVticPHzaAPyaMBAAyjD49FAA5mz8-I5eijIwWdokJGwAjHaoNj6+NmmeGZnZMJEQAJLRAPKx8Ukp6dWV3QDcXRgAvumD-VAgdiAQAA4wjDjIoIT4+BAA7gAKywjYyCA8a367kwBGRGAA1nAw0YTkcAAyCXDIyjzYcKfnVzfThAxJZBxPiTD7kehA-AgkBwAAe0zg8XusB4ABVEVBlvQ4LskG9uB9QQlEtw4ABFagQeCvd6fECBWHRYmkilUl542mTACOlPgG1W01x+2wAFooHA4CRJRMQHFCPRuMSAMIUciEPY8bgy7DMuCmGBxegnah8xFPcU0gl0gAWMHI3AA6tb6PBsH8wHBojsXfQOC7fHswNhjiAOHwGqQEDcwPFZqZSLFfKTLYSQNNVh8HURpnt0zjERwXpMEh98DB+YREmqU3S-vhS3sYL4EdgY-RZjL0wkYA6xDBrcgABwABkm+DgPPo44rVfVHKtkxghBOvZI-eQACZJtQPqjl7j8am4OQTpKpSQHsREtRK3BKBB8GqDcSNSaICBBoMgA)

```sh
--parser typescript
```

**Input:**

```tsx
    const randomFuncion = (value): void => {
        if (value.a) {
            funcA(
                "",
                funcB(
                    dayjs(value.a?.toString())
                  		.add(1, "day")
                  		.toISOString()
                )
            );
        }
    };

```

**Output:**

```tsx
TypeError: Cannot read properties of undefined (reading 'type')
    at Jn (https://prettier.io/lib/plugins/estree.js:7:16595)
    at be (https://prettier.io/lib/plugins/estree.js:9:605)
    at be (https://prettier.io/lib/plugins/estree.js:10:209)
    at https://prettier.io/lib/plugins/estree.js:36:14282
    at Array.every (<anonymous>)
    at https://prettier.io/lib/plugins/estree.js:36:14273
    at Array.some (<anonymous>)
    at Oi (https://prettier.io/lib/plugins/estree.js:36:14252)
    at Kr (https://prettier.io/lib/plugins/estree.js:36:14852)
    at da (https://prettier.io/lib/plugins/estree.js:36:58423)
```

**Expected output:**

```tsx
const randomFuncion = (value): void => {
  if (value.a) {
    funcA(
      "", 
      funcB(dayjs(value.a?.toString())
        .add(1, "day")
        .toISOString()
      )
    );
  }
};
```

**Why?**
That was not an Error in 3.1.1 here the error in version 3.2.0 which should be fixed in #15912

If I remove the question mark behind the `funcB(dayjs(value.a? ...` the error is gone.

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #15916 

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
@fisker I think #15916 is a high priority bug, so we will merge it without review. Please leave a review later.

File: src/language-js/utils/index.js [hunk 1]
```diff
@@ -779,8 +785,8 @@ function isSimpleCallArgument(node, depth = 2) {
 
   if (isMemberExpression(node)) {
     return (
-      isSimpleCallArgument(node.object, depth) &&
-      isSimpleCallArgument(node.property, depth)
+      isSimpleCallArgument(getChainProp(node, "object"), depth) &&
+      isSimpleCallArgument(getChainProp(node, "property"), depth)
```
Comment (fisker) [inline src/language-js/utils/index.js:789]: We can add  `if (node.type === "ChainExpression") { node = node.expression }` to `isSimpleCallArgument` like other functions do.

Comment (fisker) [reply src/language-js/utils/index.js:789]: Or add to L801
