### PR TITLE
Fixup getSupportInfo for babylon parser prior to 1.16.0

### LINKED ISSUE #5822: getSupportInfo misinform about babel/babylon
Since 1.16 and the name change babylon -> babel, getSupportInfo returns "babel" as a valid parser for JS, Flow, JSX language. Of course, babel is not a valid parser with prettier < 1.16.
This appeared in prettier-vscode.
We have a current workaround, sadly it doesn't work with prettier < 1.8 (where getSupportInfo doesn't exist)
Changing `prettier.getSupportInfo(otherPrettier.version)` to `otherPrettier.getSupportInfo()`

context: 
prettier/prettier-vscode#705
prettier/prettier-vscode#706

**Environments:**
- Prettier Version: 1.16.3
- Running Prettier via: API
- Runtime: Node 8+ 
- Operating System: ALL

**Steps to reproduce:**

```js
require("prettier").getSupportInfo("0.0.0").languages.find(l=>l.name === "JavaScript").parsers
```

**Expected behavior:**
`[ 'babylon', 'flow' ]`

**Actual behavior:**
`[ 'babel', 'flow' ]`

### PR DESCRIPTION
**Pull request by azz**
This undoes an accidental breaking change where `prettier.getSupportInfo('1.0.0')` would report supporting the `babel` parser instead of `babylon`.

Fixes #5822 

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If not an internal change) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: tests_integration/__tests__/__snapshots__/support-info.js.snap [hunk 1]
```diff
@@ -444,19 +445,18 @@ exports[`API getSupportInfo() with version 1.8.2 -> undefined 1`] = `
...
       \\"JavaScript\\": Array [
-@@ -25,10 +37,16 @@
+-       \\"babylon\\",
++       \\"babel\\",
         \\"flow\\",
       ],
       \\"Less\\": Array [
         \\"less\\",
       ],
-+     \\"Lightning Web Components\\": Array [
```
Comment (azz) [inline tests_integration/__tests__/__snapshots__/support-info.js.snap]: I assume this is correct as it is unreleased?

**Comment by azz** [comment]
Any idea why I'm getting build failure emails from CircleCI? Is Circle even in use anymore?

image

**Comment by ikatyang** [comment]
Circle was removed in #5611, but it seems we forgot to remove their webhooks.

**Comment by azz** [comment]
Thanks! Azure pipelines look pretty neat. Are there any issues I should read through to catch up on current state of CI?

**Comment by ikatyang** [comment]
Azure Pipelines was introduced in #5410 and then tweaked in #5611/#5498, these 3 PRs should include everything about our current CI state. Basically, it's just migrated from Circle/Travis to Azure Pipelines with the same test steps, the docs for Azure Pipelines could be found [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema).
