### PR TITLE
Fix plugin loading in `prettier.getFileInfo()`

### LINKED ISSUE #17488: `prettier.getFileInfo()` doesn't load plugin
**Environments:**

- Prettier Version: 3.5.3
- Running Prettier via: 
- Runtime: 
- Operating System: 
- Prettier plugins (if any): 

**Steps to reproduce:**

```json
{
  "plugins": {"prettier-plugin-x"}
}
```

When `prettier-plugin-x` defines `languages`,

```
prettier --file-info foo.xxx
```

**Expected behavior:**

should load the plugin first, and return parser defined by that plugin.

**Actual behavior:**

It's not works as expected.

### PR DESCRIPTION
**Pull request by fisker**
## Description

Fixes #17488

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: src/common/get-file-info.js [hunk 1]
```diff
@@ -13,10 +19,9 @@ import inferParser from "../utils/infer-parser.js";
  * @returns {Promise<FileInfoResult>}
  *
  * Please note that prettier.getFileInfo() expects options.plugins to be an array of paths,
- * not an object. A transformation from this array to an object is automatically done
- * internally by the method wrapper. See withPlugins() in index.js.
+ * not an object.
  */
```
Comment (fisker) [inline src/common/get-file-info.js:18]: The original comment is incorrect, `withPlugins` doesn't support object type of `plugins`, only standalone version does, but `getFileInfo` is not supported in standalone version.
