### PR TITLE
Fix extra parens for update expressions

### LINKED ISSUE #794: Extra parenthesis for ++ inside of CallExpression
This

```js
const uuid = String(this._uuidCounter++);
```

gets converted into this:

```js
const uuid = String((this._uuidCounter++));
```

which doesn't make much sense.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20uuid%20%3D%20String(this._uuidCounter%2B%2B)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

### PR DESCRIPTION
**Pull request by yamafaktory**
This should fix #794.

### CODE REVIEW

File: src/fast-path.js [hunk 1]
```diff
@@ -258,7 +258,6 @@ FPp.needsParens = function(assumeExpressionContext) {
           return name === "object" && parent.object === node;
 
         case "TaggedTemplateExpression":
-        case "CallExpression":
         case "NewExpression":
```
Comment (vjeux) [inline src/fast-path.js]: do we need it for newExpression as well?

Comment (yamafaktory) [inline src/fast-path.js]: No, I don't think so. I tried it and it looks fine 👍.
