### PR TITLE
Fix CI detection to avoid unwanted TTY behavior

### LINKED ISSUE #5801: list-different (and check) log every file in CI, instead of just changed files
**Environments:**
- Prettier Version: 1.16.1
- Running Prettier via: CLI
- Runtime: Node.js 10 (and probably every version)
- Operating System: Linux

**Steps to reproduce:**

- Use [this reproduction repo](https://github.com/DSchau/prettier-check-repro) and specifically [this PR](https://github.com/DSchau/prettier-check-repro/pull/1) for an illustration of the issue

**Expected behavior:**

`prettier --list-different` (and `prettier --check`) should _only_ log the different files in CI

**Actual behavior:**

`prettier --list-different` logs _every_ file in a CI server, tested with TravisCI and CircleCI.

**More information**

Prettier v1.16.1 tweaked the behavior of `--list-different` (and additionally `--check`). It appears to now log all files that are being checked, rather than just the files that differ. In a local, non-CI environment this works well because the shell is wiped with each new file, and the end result ends up being _just_ the files that are changed. In CI, this behavior is **not** present, and so the output becomes incredibly challenging to read and it's not clear which files are different and should be updated.

It appears that [this PR](https://github.com/prettier/prettier/pull/5629) may have been the cause of the regression, specifically with relying on only `process.stdout.isTTY` which seems to log _every_ file being accessed in CI.

### PR DESCRIPTION
**Pull request by kachkaev**
Fixes #5801

- [x] I’ve added tests to confirm my change works.
- [ ] ~~(If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)~~
- [x] (If not an internal change) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by kachkaev** [comment]
What can we do with the code coverage?

**Comment by SimenB** [comment]
`jest.mock('is-ci', () => true)`?

**Comment by kachkaev** [comment]
`is-ci` returns a value, not a function, which makes its mocking problematic. Besides, all mocked modules have to be done via [third-party.js](https://github.com/prettier/prettier/blob/7345a38e645193926d66ef09ce5e7d754265c8bb/src/common/third-party.js) – otherwise, they can't be mocked in prod tests.

https://github.com/prettier/prettier/blob/18b03a31cc76209a2810c30819e04d659cc940f0/tests_integration/runPrettier.js#L71-L73

**Comment by SimenB** [comment]
Ah, didn't know about the issue when bundling

**Comment by SimenB** [comment]
Won't make a difference, `require('ci-info')` will still give you an object

**Comment by lydell** [comment]
Yeah, I didn’t mean it would help the tests. I guess I was mostly wondering if anybody else was surprised by the seemingly pointless wrapper package :)

File: src/cli/util.js [hunk 1]
```diff
@@ -54,7 +54,7 @@ function diff(a, b) {
 
 function handleError(context, filename, error) {
   if (error instanceof errors.UndefinedParserError) {
-    if (context.argv["write"] && process.stdout.isTTY) {
+    if (context.argv["write"] && process.stdout.isTTY && !thirdParty.isCI()) {
```
Comment (ikatyang) [inline src/cli/util.js]: Since `process.stdout.isTTY` and `!thirdParty.isCI()` are always used together, it'd be better to extract them to be a new function.

Comment (kachkaev) [reply src/cli/util.js]: Sounds like a reasonable idea, but how would you call it? I could not come up with a good name.

Comment (ikatyang) [reply src/cli/util.js]: How about calling it `isTTY` directly?

Comment (lydell) [reply src/cli/util.js]: Yes – calling `isTTY` plus adding a comment explaining it would be nice

File: src/utils/is-tty.js [hunk 2]
```diff
@@ -0,0 +1,10 @@
+"use strict";
+
+const thirdParty = require("../common/third-party");
+
+// Some CI pipelines incorrectly process.stdout.report isTTY status,
```
Comment (lydell) [inline src/utils/is-tty.js]: Looks like some words have been scrambled out of order?

Comment (kachkaev) [reply src/utils/is-tty.js]: 😅 true

**Comment by ikatyang** [comment]
@kachkaev Thanks!

@DSchau Today or tomorrow if everything goes well.

File: tests_integration/runPrettier.js [hunk 3]
```diff
@@ -74,6 +76,9 @@ function runPrettier(dir, args, options) {
   jest.spyOn(require(thirdParty), "getStream").mockImplementation(() => ({
     then: handler => handler(options.input || "")
   }));
+  jest
+    .spyOn(require(thirdParty), "isCI")
+    .mockImplementation(() => process.env.CI);
```
Comment (j-f1) [inline tests_integration/runPrettier.js]: Should this be mocked to a specific value so results are consistent?

Comment (kachkaev) [reply tests_integration/runPrettier.js]: We want to test both CI and non-CI modes and I’m setting env: { CI: true } in a couple of integration tests to make sure the behavior changes.
