### PR TITLE
fix(flow,ts): consistent interface and remove unnecessary indent for extends

### LINKED ISSUE #5431: Extra indentation in generic parameter
**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAS1jmwDMBDMOPAMQggB0o8914oATAZzwCFzsAHiYsWAZQgBbOABloAcwAqATwxwANCNGKIvbHHIBrGUQ1aAfHmBbSBOABsOSPFACukgEYkA3EwC+IOogEBgwBNBcyKAC2BAA7gAKAgiRKOQAbhAEHIEgHtiUhnAwYhiURPLIMNiuGiAAFjCS9gDq9QTwXGVUYikdBOkdysjgXJFBRFwkMAkF8pLkyBT2U0EAVlxoeoXFYuTSJlBwS+QrdRtoYhX2cACKrhDwJ2dBZdhT2CMe5B7K9tC5DDYIgwFrZGD1ZAAFgADK9YlMWgUMCMgXAPuljkF9ABHVwEfSzcjzRZIZarEBTSQEKo1Opca53B5PMmnCkwH5gjgQ5AAJiC1XIBHsFQAwlIFiMoNAsSBXFNFD9UuS4H4-EA)
```sh
--parser babylon
--print-width 40
```

**Input:**
```jsx
export interface Foo
  extends Bar<
    SomeLongType,
    ToBreakLine,
  > {
  field: number;
}
```

**Output:**
```jsx
export interface Foo
  extends Bar<
      SomeLongType,
      ToBreakLine
    > {
  field: number;
}

```

**Expected behavior:**
The input was formatted with prettier 1.14.3, the extra indentation that 1.15.1 adds seems unnecessary.

### PR DESCRIPTION
**Pull request by ikatyang**
Fixes #5431

+ force-break Flow interfaces to be consistent with TS interfaces
+ do not indent interface `extends` if there's only one extend member
+ correctly distinguish `module` and `namespace` for `TSModuleDeclaration`
  (`module X {}` was printed as `namespace X {}`)

- [x] I’ve added tests to confirm my change works.
- (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-js/printer-estree.js [hunk 1]
```diff
@@ -2707,7 +2711,10 @@ function printPathNoParens(path, options, print, args) {
               concat([
                 line,
                 "extends ",
-                indent(join(concat([",", line]), path.map(print, "extends")))
+                (extendsDoc =>
+                  n.extends.length === 1 ? extendsDoc : indent(extendsDoc))(
+                  join(concat([",", line]), path.map(print, "extends"))
+                )
```
Comment (j-f1) [inline src/language-js/printer-estree.js]: How do you feel about creating a helper function for this?

```js
const indentIf = (condition, doc) => condition ? indent(doc) : doc;
```

This would eliminate the need for an IIFE and make the code a little clearer IMO.

Comment (ikatyang) [reply src/language-js/printer-estree.js]: A general `identity` would be better I guess:

```js
(condition ? identity : indent)(doc)

function identity(x) {
  return x;
}
```
