### PR TITLE
Fix: Always preserve frontmatter, remove dependency

### LINKED ISSUE #4162: Strips empty Jekyll front-matter blocks
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdK7VawIwgBMBPYPGQgJyLiqQAIBGABwA8GBnCAGwEsiDKnCIBuLAF8QAGhAQWMPtE7JQAQypUIAdwAKGhCpRqAbhAEyQazjGQAzNT05xZ+KmrABrODADKLDz4oAHNkGCoAVxcQIggwe0dnWSDnKhhdd2CAWzUEp2iAK042ACF3Lx9fNSy4ABkguDykuQiYFlaAJibogKpU5BBOME4VWRYqIJgAdQEYAAtkAA4ABjGtZyn3FgHxuFSTRtlhAEcIvmEMtWzcpAd82WcsvjDI6M4g4J44AEUIiHhurIYGp8DMiPNkB0ge4+PwQgBhCBZHIDKDQQ4gCLOAAqIKMd2cEgkQA)
```sh
--parser scss
```

**Input:**
```scss
---
---

body{
	border: 1px solid red;
}
```

**Output:**
```scss
body {
  border: 1px solid red;
}

```

I noticed prettier will retain Jekyll-style front matter blocks if they have content but remove them if they are empty. I believe this to be incorrect behavior as Jekyll requires the front-matter block to be present to process the file, even if that block has no content. Specifically this is happening with a .scss file in Jekyll with empty front-matter. 

See #3321 & #3802

### LINKED ISSUE #4390: Preserve comments in YAML front matter
The fixes for #3321 in #3802 only work if the YAML front matter block actually contains variable content.

As noted in #4162:

> I noticed prettier will retain Jekyll-style front matter blocks if they have content but remove them if they are empty. I believe this to be incorrect behavior as Jekyll requires the front-matter block to be present to process the file, even if that block has no content. Specifically this is happening with a .scss file in Jekyll with empty front-matter.

Many Jekyll projects use comments in the YAML front matter for SCSS files to ensure the front matter is preserved and explain its purpose:

```yaml
---
# Keep this YAML front matter block to trigger Jekyll processing
# See https://jekyllrb.com/docs/frontmatter for more information
---
```

However, Prettier strips these comments, so the resulting front matter block is effectively empty and thus discarded.

Discussion in https://github.com/jonschlinkert/gray-matter/issues/65 and #4243 suggests efforts are underway to preserve empty front matter, but it would be helpful to retain any comments in the process.

**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdKBiABAaTjgAdcYALASwGdcBNAQQFkAZXAMwCdoZcBbAIYx4nXACMANhDABrMhDKdKAc2VxRAKTgyAnhIm5i3MHGrVKUZVjwBlIrnLDi1JAHpXAK216JnMQDpIPlcAE2lqVy4eQWF1DghRPgS4XAt2BJjKaCx0VCwsAAFKPmIE3gByADcBJQFJU3KAbkLi0s4KsQFqOCaWkrLcDBAYHWI4IeaoIv723HKJAR0IAFcYXqnWgfLIWAQ1yZAAGhAIYhgsqGpkUBruAHcABRqEK5QBSohKEKOQMU4BWRwGA2YgAizKZAwTjLODHCzddoPf7KQTIdgCCTdY4eagADwAQv9AcCBHw4CwLHA0RisSBQZwEcgQNQwGYfkYLDAAOpfCjIAAcAAZjkYIN0uf9iEyjKZ1JUqcdOHAAI7LShKpECFECamY2HMuB8SiQ6H68yWCRwACKywg8BNMOOMDqPJCfKQACYnf9KBJwQBhCB8VEoKDQBUgZbdAAqdVe6L1xy6MF1tLCYFT+pWMGIqw9mYAvgWgA)
```sh
--parser scss
--single-quote
```

**Input:**
```scss
---
# Keep this YAML front matter block to trigger Jekyll processing
# See https://jekyllrb.com/docs/frontmatter for more information
---

@import 'variables';
@import 'base';
@import "type";
@import 'layout';
@import 'content';

```

**Output:**
```scss
@import 'variables';
@import 'base';
@import 'type';
@import 'layout';
@import 'content';

```

**Expected behavior:**

The YAML front matter block — _including comments_  — should be preserved:

```scss
---
# Keep this YAML front matter block to trigger Jekyll processing
# See https://jekyllrb.com/docs/frontmatter for more information
---

@import 'variables';
@import 'base';
@import 'type';
@import 'layout';
@import 'content';
```

### PR DESCRIPTION
**Pull request by eliasmeire**
👋 

This fixes #4390, fixes #4162

### CODE REVIEW

**Comment by duailibe** [comment]
Looking good!! Always glad to remove a dependency :)

I don't think the regex check is correct though, it's matching this as frontmatter:

**Prettier pr-4392**
[Playground link](https://deploy-preview-4392--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBadAdKBDX2sBG6qWWAdNgATBaV12QA2EATpUpQMSUAMfA3FgC+IADQgIABxgBLaAGdkobCxYQA7gAUVCRSmwA3CDIAmYkARbYwAazgwAypOsyoAc2QwWAVzjjX8nAsMJpWbgC22MgAZtiMgeIAVvIAHgBCVrb2DtjhcAAyrnAxcQkgziyBLMjg8orikiyuMADqpjAAFsgAHDwNaoEtVpI1jXBVBsXiLHAAjt4yM6HYEVFIsfF+IIHhMp4+W-KuboxwAIreEPAlm+Iw2ARtJp3IAEx3VjKMxwDCEOGRGpQaBTEDeQIAFQeeg2gSEQiAA)
```sh
--parser css
```

**Input:**
```css
---
aaaa
b---

.a {
     color : # 000;
}
```

**Output:**
```css
---
aaaa
b
---

.a {
  color: #000;
}

```

(You can test it out in the preview playground: https://deploy-preview-4392--prettier.netlify.com/playground/)

File: src/language-css/parser-postcss.js [hunk 1]
```diff
@@ -438,21 +437,27 @@ function parseNestedCSS(node) {
   return node;
 }
 
-function parseWithParser(parser, text, frontMatter) {
+function parseWithParser(parser, text) {
   let result;
+  const frontMatterMatches = text.match(/^---\n([\s\S]*)---/);
```
Comment (duailibe) [inline src/language-css/parser-postcss.js]: Maybe `/^---(\n[\s\S]*)?\n---/` ??

Comment (eliasmeire) [reply src/language-css/parser-postcss.js]: Might work, will try it out :)

**Comment by eliasmeire** [comment]
Updated it, your regex works better indeed.

**New output:**

```
---b aaa --- .a {
  color: #000;
}
```

Which I guess makes sense because it's being handled as a CSS selector?

**Comment by duailibe** [comment]
Thank you!

**Comment by evilebottnawi** [comment]
@eliasmeire Great work! Thanks!

**Comment by eliasmeire** [comment]
No problem :) thanks for maintaining prettier, great work!

File: src/language-css/parser-postcss.js (hunk 1 above)
Comment (jonschlinkert) [reply src/language-css/parser-postcss.js]: fwiw, this will fail on this:

```
---
foo: bar
---

This is content.

---

and more content...
```

Since the regex will match up to the last `---`.

Try changing the regex to this: `/^---\n([\s\S]*?)---/` (add a `?`, to match lazily instead of greedily).

Comment (eliasmeire) [reply src/language-css/parser-postcss.js]: Hey Jon, I tried those 2 cases and the output is the same. But indeed the current regex matched up to the second `---` so it's probably still better for it to match lazily. Making a small follow up PR. Nice catch 👍
