### PR TITLE
Invalidate outdated cache file

### LINKED ISSUE #17092: [3.5 regression] `[error] Cannot read properties of undefined (reading 'length')`
# Workaround
(edited by a maintainer)

Please remove `node_modules/.cache/prettier/.prettier-cache` and re-run.

---

**Environments:**

- Prettier Version: 3.5.0
- Running Prettier via: CLI
- Runtime: Node.js 22
- Operating System: Ubuntu
- Prettier plugins (if any): N/A

**Steps to reproduce:**

```
npm exec -- prettier --cache --write src/background.ts
```

**Expected behavior:**

Formats the code.

**Actual behavior:**

`[error] Cannot read properties of undefined (reading 'length')`

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #17092

Prettier 3.5 uses a different cache format than previous versions.
Since loading an old cache file in Prettier 3.5 would cause a runtime error outdated cache files are removed.

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
@fisker What do you think about this approach?

**Comment by fisker** [comment]
When does it fails? `createFromFile` or `getFileDescriptor` can't we `try/cache`?

**Comment by sosukesuzuki** [comment]
`createFromFile` fails. Of course, we could do a try-catch. But that would mean that the error would be thrown after all cache files have been read. We chose this approach for performance reasons.

**Comment by fisker** [comment]
> We chose this approach for performance reasons.

I have to say that it's not better, current approach reads the cache file every time, and the odds of invalid cache file is low(even almost impossible after first update from old version), but if we choose `try/catch` it will only reload if it's from old version.

**Comment by sosukesuzuki** [comment]
@fisker I've updated to just use `try-catch`

File: src/cli/format-results-cache.js [hunk 1]
```diff
@@ -44,10 +45,24 @@ class FormatResultsCache {
...
-    );
+    try {
+      this.#fileEntryCache = fileEntryCache.createFromFile(
+        /* filePath */ cacheFileLocation,
+        useChecksum,
+      );
+    } catch {
+      // https://github.com/prettier/prettier/issues/17092
+      // Prettier 3.5 uses a different cache format than previous versions.
+      // If the cache file is not in the expected format, delete it and retry.
```
Comment (fisker) [inline src/cli/format-results-cache.js:56]:
```suggestion
      // If `createFromFile` fails, it's probably because the format of cache file changed, it happened when we release v3.5
```

File: changelog_unreleased/cli/17100.md [hunk 2]
```diff
@@ -0,0 +1,4 @@
+#### Invalidate outdated cache file (#17100 by @sosukesuzuki)
+
+Prettier 3.5 uses a different cache format than previous versions.
+Since loading an old cache file in Prettier 3.5 would cause a runtime error outdated cache files are removed.
```
Comment (fisker) [inline changelog_unreleased/cli/17100.md:4]: This should be improved, maybe something like

```
#### Fix CLI crash when cache for old version exists (#17100 by @sosukesuzuki)

Prettier 3.5 uses a different cache format than previous versions, Prettier stable crashes when reading existing cache file, Prettier main fixed the problem.
```

**Review by fisker — APPROVED** [review]
The logic looks good to me, two comments.
