### PR TITLE
Scss: fix scss variable string concatenation removing spaces

### LINKED ISSUE #4691: Scss variable string concatenation removing spaces
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6ADgQwOZwLQBGEMMEAtnmDJgATAA6U9MBmYA1tgE4QCuUAEzwBLMjjhIavLgBsAFABJMAZ2VwYyvFhgALGgGoaAcmXUYwsAHoZmQcKjYt45ZYBmEYnC4ixuPMpwuTAFMfzJUACt0bCMASgBuRmZWDm4+QTwuOHQ4TBhJKAhM7NyYRKgAXxAAGhAIdHNoZWRQTC4eAHcABTaEZpRMADcIYQEakAIgjnUAZSwwe2xkGC5eOFr7NS4YLqDsMWRXTBk1WojlAA8AISn2WcwyOAAZezhD49OQLC4t5BBlMCqcboLj2GAAdVGumQAA4AAy1EEQNTgoLoP4guBbQZvWpZACOvGEWV2OAOSCOJ3W-zgZGEy1W1OUixkcAAirxPO8qbVqARIQJoUgAEy8oLCGSLADC5HJIEKUFxIF4agAKpgCP1KWoKhUgA)
```sh
# Options (if any):
--parser scss
```

**Input:**
```scss
.page-bottom-cta {
	background-image: url($assets-path + 'static/landing-pages/footer-image-sagrada-sm.jpg');
	background-repeat: no-repeat;
}
```

**Output:**
```scss
.page-bottom-cta {
  background-image: url($assets-path+"static/landing-pages/footer-image-sagrada-sm.jpg");
  background-repeat: no-repeat;
}
```

**Expected behavior:**
When doing string concat in scss files, the space around the ` + ` is being removed.
Is this by design or a bug?

### PR DESCRIPTION
**Pull request by sasurau4**
fix #4691

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-css/printer-postcss.js [hunk 1]
```diff
@@ -458,16 +458,23 @@ function genericPrint(path, options, print) {
...
         const iPrevNode = node.groups[i - 1];
         const iNode = node.groups[i];
         const iNextNode = node.groups[i + 1];
         const iNextNextNode = node.groups[i + 2];
 
+        if (insideURLFunction) {
+          if (
+            (iNextNode &&
+              iNextNode.type === "value-operator" &&
+              iNextNode.value === "+") ||
```
Comment (evilebottnawi) [inline src/language-css/printer-postcss.js]: In theory we can have more operators (for example `-`, `*` and `/`), i think we should handle them too

Comment (sasurau4) [reply src/language-css/printer-postcss.js]: I think the additional operator is special because it is used for concatenation of string inside URL function.
So, we shouldn't handle `-`, `*`, `/`.
