### PR TITLE
fix(markdown): allow more cases that `_`-style emphasis is available

### LINKED ISSUE #3170: Markdown: Not all `*` is converted into `_`
**Prettier 1.8.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAqVARCACAnhAV2wHcBDWbGHAJzgEcC4BnGbU7VAMzlJgNtTYI1bLQAOw1u1QAjAgHNUAfnQgANCAhiYAS2hNkoUi2SdSAGyZwNM6qTABrODADKY+zqjzkMaow0AJhBgphZWGgBWTAAeAEJ2js4upAC2cAAynnChltaaBDBiBQBMOeEg7tRW1MggKaTUDkHEUOoV1J4wAOo6ATAAFsgAHAAMGlYpOj5+eUye8uZwAIoEEPBleTCkMj19g0jFGr6kOubzAMIQKfW1UNDZGgRWACrbBkhmuQC+X0A)
```sh
--parser markdown
```

**Input:**
```markdown
**Do you want to request a *feature* or report a *bug*?**
```

**Output:**
```markdown
**Do you want to request a _feature_ or report a *bug*?**

```

**Expected behavior:**
Both `*feature*` and `*bug*` should be converted

### PR DESCRIPTION
**Pull request by ikatyang**
Fixes #3170

### CODE REVIEW

File: src/printer-markdown.js [hunk 1]
```diff
@@ -11,6 +11,12 @@ const fill = docBuilders.fill;
 const align = docBuilders.align;
 const docPrinter = require("./doc-printer");
 const printDocToString = docPrinter.printDocToString;
+const escapeStringRegexp = require("escape-string-regexp");
+
+// http://spec.commonmark.org/0.25/#ascii-punctuation-character
+const ascii_punctuation_pattern = escapeStringRegexp(
```
Comment (azz) [inline src/printer-markdown.js]: Why snake_case here? :wink:

**Comment by azz** [comment]
Thanks for these quick fixes!

File: src/printer-markdown.js (hunk 1 above)
Comment (ikatyang) [reply src/printer-markdown.js]: 😅
