### PR TITLE
Keep comments in mapped type inline

### LINKED ISSUE #18730: Inline block comment in mapped type incorrectly moved to separate line
**Prettier 3.8.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAQtgXm2AB0ptsB6AKm0gFt6EZ9rLsBtAI2wEtzcAXSTYAzjABO-AOZkAvmTLos2ACoBlVZjgAZXvAkBDADaFiZCjWzH9cI6bbYuI8VKjSA3PJAAaEBAwYXmhRZFBDCQkIAHcABQiEUJQTaMM0UL8uIzAAazgYdUMmPSg4ZAAzE1E4PwguACs4MBgAdSMMZBAMCThqiQA3MszsvIKMQzAZZEkAVxqQavpeaYk5vzgADywpJlgTAHltwxgICViIUX1gqE6EABNfEE3t3l2YE1U7KAjeXoqq+aXdzGOAARRmEHg-2M1T89VEG3UMhB4MhZSQlRh8wAjhD4LEohgkiBDKIALSlOB3KmPSSGXg2dwAYQgjEMnRMxkeQOkIIAgjBJLwuDN8XYSujMbCQAALGD0YwtGW2UTjMBwdSJK79fRoTpgUQZED9OYASSg1Ng6jAUkCfIt6nQIOh0u6FzgbUMHRQ3V6dkGj3u+3KEs6xnKj34fRgBMM0no7IxAL84wkfU6yl6Nt4gUe3X4rV4dxgMuQAA4AAx+Hq43g9WPxxNS+bvLgtIsl5AAJj8M2qqkMXCSzfW9C4VOpdx0hncMzjcAAYqcE4KpslRRAQHI5EA)

```sh
--parser typescript
```

**Input:**

This is a Prettier test
https://github.com/prettier/prettier/blob/812a4d0071270f61a7aa549d625b618be7e09d71/tests/format/typescript/comments/mapped_types.ts#L6-L8

```tsx
type B = {
  /* commentB */ [b in B]: string
}

type TSTypeLiteral = {
  /* literal */ b: string;
}
```

**Output:**

```tsx
type B = {
  /* commentB */
  [b in B]: string;
};

type TSTypeLiteral = {
  /* literal */ b: string;
};

```

**Expected output:**

```tsx
type B = {
  /* commentB */ [b in B]: string;
};

type TSTypeLiteral = {
  /* literal */ b: string;
};

```

**Why?**

Prettier handles inline block comments inconsistently between mapped types and regular type literal properties:

- `TSTypeLiteral` with property signature: comment stays inline ✓
- `TSMappedType`: comment is moved to a separate line ✗

Both cases have the same structure—a block comment preceding a type member—so they should be formatted consistently. The comment in the mapped type should remain on the same line as the member it annotates.

### PR DESCRIPTION
**Pull request by fisker**
## Description

Fixes #18730

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: tests/format/typescript/comments/mapped-types.ts [hunk 1]
```diff
@@ -44,3 +44,24 @@ type MakeBrand<T extends string> = {
...
+}
+
+type M4  = {
+  /* a long long long long long long long long long long long long long long comment */ [b in B]: string
+}
+
+type M5  = {
+  /* Multi
+line */ [b in B]: string
+}
```
Comment (fisker) [inline tests/format/typescript/comments/mapped-types.ts:67]: @Dunqing I think these two should on own line, oxfmt currently not.

Comment (Dunqing) [reply tests/format/typescript/comments/mapped-types.ts:67]: Thank you! I will follow it up in the Oxfmt.
