### PR TITLE
fix spacing issue in postcss simple vars

### LINKED ISSUE #4348: postcss-simple-vars: computed variable names broken
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjAhmA1gcwE4QCuUAJgLSQA2EeSABACQMAUAzjAJ6VwCUAwhGp4A3AB0oIADQgIABxgBLaK2Sh0eAgHcACuoQqU6AG4QFJKSHTtkAM3SVWcaajyYscGAGVZmBVBzIMHiETiAkEGC29o7Sfo54MNquOAC26FEOoQBWrAAeAEKu2B6e6ClwADJ+cBkxMoQwsg0ATLWhPnjxyOCsKtKyeH4wAOpmMAAWyAAcAAz9BI7DrrLdA3DxRjXSeHAAjoQKO0noqelIdpnSjikKgcGhrH443ACKhBDwbdIw6KijJBNkM1vq4FJQngIUmlulBoFsQIRHAAVX4GC6OAC+GKAA)
```sh
--parser css
```

**Input:**
```css
background-color: $$(style)Color;

```

**Output:**
```css
background-color: $$(style) Color;

```

**Expected behavior:**
Output should be same as input, i.e. no additional space should be introduced.

### PR DESCRIPTION
**Pull request by ad1992**
Fixes #4348

### CODE REVIEW

**Comment by ad1992** [comment]
@evilebottnawi made the change.

File: src/language-css/printer-postcss.js [hunk 1]
```diff
@@ -409,6 +410,12 @@ function genericPrint(path, options, print) {
         const iNextNode = node.groups[i + 1];
         const iNextNextNode = node.groups[i + 2];
 
+        if (
+          iNode.type === "value-func" &&
+          hasNoSpaceBeforeValueNode(iNextNode)
```
Comment (evilebottnawi) [inline src/language-css/printer-postcss.js]: Better add helper `isPostcssSimpleVar` and move all check inside this util function.

**Comment by evilebottnawi** [comment]
@ad1992 yes, just need add tests when word have other value

**Comment by ad1992** [comment]
@evilebottnawi I have added some specs but these specs are already covered in other files so I am not sure if its needed here for example `@@var` is already in `less.css`

File: src/language-css/utils.js [hunk 2]
```diff
@@ -211,6 +211,14 @@ function hasParensAroundValueNode(node) {
   );
 }
 
+function isPostcssSimpleVar(currentNode, nextNode) {
```
Comment (lydell) [inline src/language-css/utils.js]: The check in here is a bit hard to understand. At a glance it feels too generic. Is it? Could his have unintended consequences? For example, do we need to check that the name of something is `$`?

Comment (evilebottnawi) [reply src/language-css/utils.js]: /cc @ad1992

Comment (lydell) [reply src/language-css/utils.js]: Perhaps the function logic is fine, but the name `isPostcssSimpleVar` is misleading? Because that's not what it checks?

Comment (ad1992) [reply src/language-css/utils.js]: initially the code was
```js
iNode.type === "value-func" &&
hasNoSpaceBeforeValueNode(iNextNode)
```
and then changed it to isPostcssSimpleVar. Yes its not explicitly checking whether is `PostcssSimpleVar`. 
should it be isLeadingSpaceInPostCssSimpleVar ? Please suggest some better name :)

Comment (evilebottnawi) [reply src/language-css/utils.js]: @ad1992 just add check on `$` in your utils function and all

File: src/language-css/utils.js [hunk 3]
```diff
@@ -211,6 +211,14 @@ function hasParensAroundValueNode(node) {
...
+  return (
+    currentNode.type === "value-func" &&
```
Comment (evilebottnawi) [inline src/language-css/utils.js]: `currentNode.name === '$$'`

Comment (evilebottnawi) [reply src/language-css/utils.js]: /cc @ad1992

Comment (ad1992) [reply src/language-css/utils.js]: @evilebottnawi if I add the check  `currentNode.value === '$$'` then it will only work for functions with name `$$`, etc. Is that the correct behaviour ? Then I should also add test where function name is something else other than `$$`

Comment (evilebottnawi) [reply src/language-css/utils.js]: @ad1992 postcss simple var have `$$(name)` syntax and it is normal, yes add test where we have `@@(name)`, maybe other tests too

Comment (ad1992) [reply src/language-css/utils.js]: got it. Made the changes.

**Comment by evilebottnawi** [comment]
@vjeux sorry, accidentally mentioned you :smile:

**Comment by ad1992** [comment]
@j-f1 please review

**Comment by j-f1** [comment]
I don’t know the CSS printer that well, so I’m not really qualified to review.

**Comment by ad1992** [comment]
@evilebottnawi @lydell can this PR be merged if there are no more pending reviews ?
