### PR TITLE
Fix wildcard syntax in `@forward` (#11482)

### LINKED ISSUE #11482: [scss] Wildcard syntax in `@forward` broken
Using the latest prettier wildcard syntax is broken when using `@forward` pattern.
It worked as desired in v2.3.2.

**Prettier 2.4.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZhATgdwIZYAmABAOQB0A9AA54wAWpxeAzsbQwLQBUA3ADpQM2fETJVIAG2xNWxKdh4ChmXARIVKcSXAC2CGLLba9BpYJAAaEBGowAltBbJQBLBBwAFAgmco8kvgAns7WAEZYeGAA1nAwAMp4+gAy9lBwyOgBLHDhkTFx8bRgaQDmyDBYAK65IHphcISEjcl4UKVVeKVwAGLYunQO7cggeFUwEFYg9DC6kgDq9PbwLMVw8b7L9gBuy0EjYCyhIGk5WDCekaUDmdm1AFYsAB7xZToAilUQ8LeSOda0LBnEYsQ7HahYNIweb2QgMZAADgADAD3Dl5pFqCMIXAztsMtYAI5feCXWx+UYsTjpRqNKZYODE+wMy5dG5ILJ-Wo5XT2CrVblvOCfb4ZDl3awwPBhGFw+jIABMksi9kkZQAwhBdOy6iwAKxTKo5AAq0r8nP+IG2NQAklBmrB4mBIXYAIL2+IwII6X45AC+fqAA)

```sh
--parser scss
```

**Input:**

```scss
@forward './path' as path-*;
@forward './color' as color-*;
@forward './element' as element-*;

```

**Output:**

```scss
@forward "./path" as path- *;
@forward "./color" as color- *;
@forward "./element" as element- *;

```

**Expected behavior:**

Wildcard syntax should be preserved.

```scss
@forward "./path" as path-*;
@forward "./color" as color-*;
@forward "./element" as element-*;

```

### PR DESCRIPTION
**Pull request by niksy**
## Description

Fixes #11482.

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-css/printer-postcss.js [hunk 1]
```diff
@@ -550,6 +550,22 @@ function genericPrint(path, options, print) {
...
+          insideAtRuleNode(path, "forward") &&
+          iNode.type === "value-word" &&
+          iNode.value &&
+          iNode.value.endsWith("-") &&
+          iPrevNode.type === "value-word" &&
+          iPrevNode.value &&
+          iPrevNode.value === "as" &&
+          iNextNode.type === "value-operator" &&
+          iNextNode.value &&
+          iNextNode.value === "*"
```
Comment (sosukesuzuki) [inline src/language-css/printer-postcss.js:564]: @alexander-akait Could you check if this condition works file? Sorry I'm not familiar with SCSS...

Comment (alexander-akait) [reply src/language-css/printer-postcss.js:564]: I think fine

Comment (alexander-akait) [reply src/language-css/printer-postcss.js:564]: Ideally we need special logic for `@use`/`@forward`, but it will require parser for this, postcss-values-parser violate spec in many places, to solve it in right way we need another parser, so I think we can safely merge it

Comment (niksy) [reply src/language-css/printer-postcss.js:564]: @sosukesuzuki @alexander-akait check is based on [official documentation on prefixes](https://sass-lang.com/documentation/at-rules/forward#adding-a-prefix). `@forward` is available only for Sass files.

**Review by sosukesuzuki — APPROVED** [review]
Thanks for your quick PR!

**Comment by sosukesuzuki** [comment]
@fisker Can you review this? If you approve this, I'll release new patch version.

**Comment by fisker** [comment]
Is this valid? 

**Prettier pr-11487**
[Playground link](https://deploy-preview-11487--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEABAZhATgdwIZYAmABADogA2AlgEZYECe5xeAzsTTFALQBU3ADwDcIADQgIABxhVorZKAJYIOAAoEE8lHgr4G88XTxgA1nBgBlPAFs4AGSpQ4ydDtZxD9U+YuTjjgHNkGCwAVw8QOGsaOEJCWLs8KADQvAC4ADFsazwYGWTkEDxQmAgxEAALGGsKAHUKqnhWPzA4C01GqgA3RoZCsFYDEEd3LBhVegCclzcIgCtWAQtAijgARVCIeBmKd3E-LFHC1gGhySxHGFqqQhgK5AAOAAZ95Xda+klC87hRrudxABHTbwCZSLRFVjcJyxWLlLBwYFUBETNLTJCuXYRdzWKjBMLYlbrEHODGzcQwPA0a63e5IABMFPoVGoyQAwhBrOjIqwAKzlULuAAqVK0mL2IC64QAklB4rALGALtIAIJyiwwBirHbuAC+uqAA)

```sh
--parser scss
```

**Input:**

```scss
@forward "library" as btn-*-x;
```

**Output:**

```scss
@forward "library" as btn-* -x;

```

**Comment by fisker** [comment]
This should not related to this PR, but somehow cross the printWidth

**Prettier pr-11487**
[Playground link](https://deploy-preview-11487--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEABAZhATgdwIZYAmABAOQA2AlgEZYECepxOlMAFsQBQA6UxxAEmrk8YANZJiAYgBMc4gEJCcdHgCu5GABpe-IdmVYAtHUKU1AZ0kAGAHQBGLHAC2i5ao0xeASgDcILRAIAAcYSmgLZFACLAgcAAUCBEiUPHJ8ekjA2lExOBgAZTxnOAAZSig4ZFVyCzhsunF8guDRCoBzZBgsNXqQF2o4QmVCUrwodrU8drgAMWxnPBgwieQQdRgIAJA2GGdyAHU2VjgLVrA4AuTWSgA3Vno1sAsskAq6rBh4unbF6rS6oEAFYWAAeBQ65DgAEU1BB4P9an1WlgPmsLM9XsEsBUYAdKIR2MgABzWQLYiB1A50YJrbGnOBYW5VQIARzh8G+IRS6wsRkqQyG2yc7MoTm+0z+SBqgJAdWclC6PT6FkhMI5VWlAL6MDw1HxhLYyBkgW6eEoVAmAGEIM4pf0LABWbaWOAAFT1KRlfVuvQAklBlLACmAcaEAIKBgowehQxF1AC+CaAA)

```sh
--parser scss
```

**Input:**

```scss
@forward 'library' with (
  $black: #222 !default,
  $border-radius: 0.1rem !default
);
```

**Output:**

```scss
@forward "library" with ($black: #222 !default, $border-radius: 0.1rem !default);

```

**Comment by niksy** [comment]
@fisker 

> **Input:**
>
>```css
>@forward "library" as btn*;
>@forward "library" as btn-*-x;
>@forward "library" as btn*-*;
>```

Only the first is valid, and I’ve made changes to reflect that. Other two are invalid Sass syntax for `@forward` rule.

**Comment by niksy** [comment]
> This should not related to this PR, but somehow cross the printWidth
> 
> **Prettier pr-11487**
> [Playground link](https://deploy-preview-11487--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEABAZhATgdwIZYAmABAOQA2AlgEZYECepxOlMAFsQBQA6UxxAEmrk8YANZJiAYgBMc4gEJCcdHgCu5GABpe-IdmVYAtHUKU1AZ0kAGAHQBGLHAC2i5ao0xeASgDcILRAIAAcYSmgLZFACLAgcAAUCBEiUPHJ8ekjA2lExOBgAZTxnOAAZSig4ZFVyCzhsunF8guDRCoBzZBgsNXqQF2o4QmVCUrwodrU8drgAMWxnPBgwieQQdRgIAJA2GGdyAHU2VjgLVrA4AuTWSgA3Vno1sAsskAq6rBh4unbF6rS6oEAFYWAAeBQ65DgAEU1BB4P9an1WlgPmsLM9XsEsBUYAdKIR2MgABzWQLYiB1A50YJrbGnOBYW5VQIARzh8G+IRS6wsRkqQyG2yc7MoTm+0z+SBqgJAdWclC6PT6FkhMI5VWlAL6MDw1HxhLYyBkgW6eEoVAmAGEIM4pf0LABWbaWOAAFT1KRlfVuvQAklBlLACmAcaEAIKBgowehQxF1AC+CaAA)
> 
> ```shell
> --parser scss
> ```
> 
> **Input:**
> 
> ```css-scss
> @forward 'library' with (
>   $black: #222 !default,
>   $border-radius: 0.1rem !default
> );
> ```
> 
> **Output:**
> 
> ```css-scss
> @forward "library" with ($black: #222 !default, $border-radius: 0.1rem !default);
> ```

You’re right, this is not related to this PR, but I can push it in this one or create new one with adjustments?

**Review by sosukesuzuki — APPROVED** [review]

File: src/language-css/printer-postcss.js [hunk 2]
```diff
@@ -550,6 +550,21 @@ function genericPrint(path, options, print) {
           continue;
         }
 
+        // Ignore SCSS @forward wildcard suffix
+        if (
+          insideAtRuleNode(path, "forward") &&
+          iNode.type === "value-word" &&
+          iNode.value &&
+          iPrevNode.type === "value-word" &&
+          iPrevNode.value &&
```
Comment (thorn0) [inline src/language-css/printer-postcss.js:559]:
```suggestion
```
`iPrevNode.value && iPrevNode.value === "as"` is the same thing as just  `iPrevNode.value === "as"`.

File: src/language-css/printer-postcss.js [hunk 3]
```diff
@@ -550,6 +550,21 @@ function genericPrint(path, options, print) {
...
+          iPrevNode.value === "as" &&
+          iNextNode.type === "value-operator" &&
+          iNextNode.value &&
```
Comment (thorn0) [inline src/language-css/printer-postcss.js:562]:
```suggestion
```

**Review by thorn0 — CHANGES_REQUESTED** [review]

**Review by thorn0 — APPROVED** [review]

**Comment by sosukesuzuki** [comment]
I'll release new patch version includes this.

**Comment by sosukesuzuki** [comment]
done
