### PR TITLE
Vue: improve parsing custom blocks with `angular-html-parser@1.5.0`

### LINKED ISSUE #6325: Incorrectly parsing vue custom block as HTML
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJhMBnAfAHSgBUALAS2wAJIBbAB2gRkpgEMBrOK1qSgAzLwa2PpToAnCHUoAKPgEFx41gE9UAeQBGAKzhgYuPgEoAdIUqUI4wqQrUI9RrEqa4YgDaswcdJTJRsMnQ3Vn5UGhUAWloGKCZDMyhUAHpMHAIoQlRsMHEyOgNzSmTkyjgYMCzknLyC3BAAGhApGDJobGRQViUIAHcABW6EDpRWADcIIMaQTWUwThgAZTovfwBzZBhxAFc4JpIYGncAdXJ4bBXvReHBMjHBFWRwbA6m-2w4cRh+5TWaVmQADNWO4Pk1tNgAB4AITmC0WrBocAAMv44ECQWCQBDIYt1u44ABFbYQeAY0F7EArcQfcRPMa7aYSfwwY5BGAkZAADgADE0JBAPsdlHQnhIuJ8xuimgBHEnwH5SEYgVjYSJxHw+abiOBysg6n6sP4ApDAilND40MibHaUwJQNYE4mk9GmzGUtiaNnoDnIABMTS2rDI7nWAGEHP8nlBGNNth8iKxNCMzR8AL5poA)
```sh
--parser vue
```

**Input:**
```vue
<docs>
This component takes an `items` prop (`Array<Object>`).
  or
This component should be placed inside a `<my-component>`.
</docs>

<script>
  // etc
</script>
```

**Output:**
```vue
SyntaxError: Unexpected closing tag "docs". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (5:1)
  3 |   or
  4 | This component should be placed inside a `<my-component>`.
> 5 | </docs>
    | ^
  6 | 
  7 | <script>
  8 |   // etc
```

**Expected behavior:**

My team has written a custom vue SFC webpack plugin that generates documentation via a `<docs>` tag. This tag contains markdown comments. Prettier tries to parse this block as HTML, which fails due to unclosed "element tags". Some examples of the syntax that cause problems are shown above. Prettier should not be running an HTML parser over these custom blocks, as there are no guarantees what type of content they will contain.

I'd expect that prettier would just ignore custom blocks it doesn't understand. Per #5448 prettier won't _format_ custom blocks. But if we're not gonna format them, why parse them at all?

### LINKED ISSUE #6503: [Vue] Unexpected closing tag "template" – support same HTML parsing strategy as the Vue compiler
My Vue code file uses Pug in `<template>`.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwAE+UA5gLwA6IWArqdQHyVSGEDEkseAllHACcWbSjADOEDHAC0kbNAQwAFDDwUA5KglTpq0o3UBKFqgD0mXATiMQAGhAQsMHtDHJQeAQIgB3AAqeCG4oeABuEDwAJnYgAEYCeGAA1nAwAMpYiXykyDACtHD2ABYwGDgA6kU88GKZYHBpQdU8odUAnsjgYm72fGKCMH4JpBh4yABmeDj99gBWYgAeAEIJyalpeFIAMnxwE1MzIPMLadk4cACKtBDw+9OFNJ79Ap2hBTFYAnww5VEwRcgABwABnsnwg-XKCSwnU+cGeoT29gAjtd4ENHMEQHgxNJ+HBIgSYgI4KieCShmpRndDv0MDxcvkHmIzpc0XskJN7vZVLFfpF-sgAEw8hI8HDZADCkmpKCgChitH6ABU8LFglz+gBfLVAA)
```sh
# Options (if any):
--parser vue
```

**Input:**
```vue
<template lang="pug">
  #container
  	some-component(tag='<some-tag>')
</template>
```

**Output:**
```vue
SyntaxError: Unexpected closing tag "template". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (4:1)
  2 |   #container
  3 |   	some-component(tag='<some-tag>')
> 4 | </template>
    | ^
```

**Expected behavior:**

Get formatted Vue file (with Pug template) without error.

### LINKED ISSUE #7975: Use `vue-eslint-parser` parse `.vue` file first?
So the invalid html won't pass to html parser, maybe can fix #6525 #6503 #6325 ?

Update: we should also try [`vue-component-compiler`](https://github.com/vuejs/vue-component-compiler)/[`@vue/component-compiler-utils`](https://github.com/vuejs/component-compiler-utils).

### LINKED ISSUE #8108: Improve `.vue` parse with `angular-html-parser@1.5.0`
Details: https://github.com/ikatyang/angular-html-parser/pull/12#issuecomment-616167534

### PR DESCRIPTION
**Pull request by sosukesuzuki**
Fixes #8108
Fixes #6503
Fixes #6325

Close #7975

```html
<!-- Input -->
<custom lang="javascript">
const foo =    "</";
</custom>

<!-- Prettier stable -->
SyntaxError: Unexpected character """ (2:19)
[error]   1 | <custom lang="javascript">
[error] > 2 | const foo =    "</";
[error]     |                   ^
[error]   3 | </custom>

<!-- Prettier master -->
<custom lang="javascript">
const foo = "</";
</custom>
```

- [x] I’ve added tests to confirm my change works.
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: tests/html_vue/template-lang.vue [hunk 1]
```diff
@@ -13,3 +13,8 @@
     #foo
   .bla
 </template>
+
+<template lang="pug">
```
Comment (fisker) [inline tests/html_vue/template-lang.vue:17]:
```suggestion
<template lang="unknown">
```

We may support `pug` someday.

**Comment by fisker** [comment]
I think we support [this](https://deploy-preview-8153--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAdKAeAhAEQPIDCAKgJoAKAogAQAWMAtgDYB8GdTz6VVGARhABMAnpyjduGAQEsAblSkCAvKhABDAA7qVo9BgD00maPE8AzmABOU9TFFQ4AdyoA1AK5wAFMDiMkVAOQAxBrq-gC+AJRc4vrmVjbGPHr8wqL67CwgADQgEDZS0KbIoKoWFhAOZKUIRSiqjA6qQkU5vBaqYADWcDAAyuodUlAA5sgwFu45cPS8cAICcwAyqiOuqsNwAGIQFvSqMDBDo3WuMBDZIBkA6jRS8KYDYHC9NXeyd0LI4KYtIEOmcAsMDI7WGe2QADN6gCcgArUwADwAQu0uj1eqp6HBFkM4JDoXA4YjekdGHAAIquCDwfGMGEgAYWAEWL4ydwXdRWWBXBQwGjIAAcAAYcpyIACru11F9OXBmTI8TkAI5U+AgvK1NSmAC09jmcwuFjgKqkRpB63BSChdMJIAB9CkYwmttMpIpqrxVoJORgql4PIEfOQACYfe0pIwjgQIPRLSA5QBWC6uAFEP21a30tlwACSUAWsF6lmsMAAgvnejAhGTaQCwmEgA) before

File: src/language-html/parser-html.js [hunk 2]
```diff
@@ -288,6 +339,11 @@ module.exports = {
     vue: createParser({
       recognizeSelfClosing: true,
       isTagNameCaseSensitive: true,
+      getTagContentType: (tagname) => {
+        if (tagname !== "template") {
```
Comment (fisker) [inline src/language-html/parser-html.js:343]:
```suggestion
        if (tagname.toLowerCase() !== "template") {
```

**Comment by sosukesuzuki** [comment]
@fisker 
> I think we support this before. stable

Does it need to be supported by the vue parser? It is supported by the HTML parser([Playground](https://deploy-preview-8153--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAdKAeAhAEQPIDCAKgJoAKAogAQAWMAtgDYB8GdTz6VVGARhABMAnpyjduGAQEsAblSkCAvKhABDAA7qVo9BgD00maPE8AzmABOU9TFFQ4AdyoA1AK5wAFMDiMkVAOQAxBrq-gC+AJRc4vrmVjbGPHr8wqL67CwgADQgEDZS0KbIoKoWFhAOZKUIRSiqjA6qQkU5vBaqYADWcDAAyuodUlAA5sgwFu45cPS8cAICcwAyqiOuqsNwAGIQFvSqMDBDo3WuMBDZIBkA6jRS8KYDYHC9NXeyd0LI4KYtIEOmcAsMDI7WGe2QADN6gCcgArUwADwAQu0uj1eqp6HBFkM4JDoXA4YjekdGHAAIquCDwfGMGEgAYWAEWL4ZC7qKywK4KGA0ZAADgADDkORAAVd2uovhy4MyZHicgBHKnwEF5WpqUwAWnsczmFwscGVUkNIPW4KQULphJAAPoUjGExtplJFJVeMtBJyMFUvG5Al5yAATN72lJGEcCBB6BaQLKAKwXVwAoi+2pW+kydwASSgC1gvUs1hgAEE870YEIybSAWEwkA)), I think which is sufficient. (We don't have a vue parser tests for it.)

**Comment by fisker** [comment]
I don't know, but people can use `--vue` to parse `.html` to support `v-if`.

**Comment by thorn0** [comment]
I'm not a Vue user, but the name of "single file components" implies that there are "multiple file components" that have their templates in separate files. I skimmed through the Vue docs, found some mentions of "in-DOM templates", but there doesn't seem to be a separate page about this.

File: src/language-html/parser-html.js (hunk 2 above)
Comment (sosukesuzuki) [reply src/language-html/parser-html.js:343]: I'm not sure if this is necessary. I haven't seen template tag written with upper case. I also can't find any such mention in [the specification](https://vue-loader.vuejs.org/spec.html) or in the source code of the [sfc-compiler](https://github.com/vuejs/vue-next/tree/master/packages/compiler-sfc).

**Comment by sosukesuzuki** [comment]
I forgot about directives. I cannot find about vue app written in only one html file in documentations, but the below code works fine. It would be good that Prettier support this.  I'll fix.
```html
<html>
  <body>
    <div id="example">
      <p v-if="hello === 'Hello World!'">{{ hello }}</p>
    </div>
    <script src="https://unpkg.com/vue"></script>
    <script>
        new Vue({
            el: '#example',
            data: { hello: 'Hello World!' }
        })
    </script>
  </body>
</html>
```

File: src/language-html/parser-html.js [hunk 3]
```diff
@@ -340,7 +340,7 @@ module.exports = {
       recognizeSelfClosing: true,
       isTagNameCaseSensitive: true,
       getTagContentType: (tagname) => {
-        if (tagname !== "template") {
+        if (tagname !== "template" && tagname !== "html") {
```
Comment (fisker) [inline src/language-html/parser-html.js:343]: I'm not sure about `template`, but I'm sure about `html`, it can be uppercase :)

Comment (sosukesuzuki) [reply src/language-html/parser-html.js:343]: stable prettier does not support it...([Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHyoAS+AsgDIMA6U55qAEYQAJgE8effgJEBLAG7l5AWlkAzALzcQaiBHIbD08gHJdEE9sm9UAejnzJx1AGcwAJ1kAHGJKhwAd3IANQBXOAAKYDg6JFMAYgBDLy8TAF8ASl5nWzdPHycBW2FxSTtWTkkQABoQCB9ZaBdkUET3dwgA4jaEZpREugDEsWbawXdEsABrOBgAZS9J2SgAc2QYd3Da6noAdUpZeBdFsDg53sOFQ7FkcBdRkGWXOHcYYgmVmkTkNQHn2oAVi4AB4AIQm01mc0SNDgHGWcB+fzggJBc2WKzocAAiqEIPAkXR-iBFu5nu5bvJwjUSZ5YLtZCIYJRkAAOAAMtS8HWeuwmXlu3Lg5PkiNqAEc8fB3vU+iBEi5lP44CIVTT3HBJbINe9Ep9vkhfkSUSBnjRZOtNiaXBisbj8YjDcjajBEoIGUyWUgAEwuiayOgY3AQGhfW7CgCsNNCz3wbr6RuJVLgAEkoKrYHMPN4YABBdNzGBiLGE55pNJAA)). We should open new issue.
```
parser=vue
```
**Input:**
```html
<!DOCTYPE html><HTML>
  <body>
    <div v-if="foo ===    'foo'">

</div>
    <script>
new Vue({el: '#app'})
    </script>
  </body>
</HTML>
```
**Output:**
```html
<!DOCTYPE html
>><HTML>
  <body>
    <div v-if="foo ===    'foo'">

</div>
    <script>
new Vue({el: '#app'})
    </script>
  </body>
</HTML>
```

Comment (fisker) [reply src/language-html/parser-html.js:343]: We should.

Comment (fisker) [reply src/language-html/parser-html.js:343]: I don't use angular, angular does not support it too

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHyoAS+AsgDIMA6U55qAEYQAJgE8efAQHph4yammtOkkABoQEAA4wAltADOyUAEMATmYgB3YuYRGUJulZNijGwWZNgA1nBgAylreulAA5sgwZgCucBrU9ADqlLrwBsFgcAH2qboAbqliyOAG7iChBnBmMMReYTQmyABmTpUaAFYGAB4AQl6+-gEmNHAcoXDNrXEgnV0BoWF0cACK0RDwk3RtIMFmlWbFJuHRdObqO2ahMIm6IjCUyAAcAAwaWpaViV5axe9w+3kJhoAI5reC1bQOEAmAwAWigcDgIiR5zMcFBujRtRM9UaSBaW2mlRoukiMSJCyWq3WE3xUw0MBMghudweSAATAyvLo6AtcBAaA1iv8AKznaKVfBMhwE7Z5WIASSgyNgATAlx0AEFlQEYGIlptKgBfI1AA)

Comment (sosukesuzuki) [reply src/language-html/parser-html.js:343]: #8162

**Comment by fisker** [comment]
@sosukesuzuki [NOOOO](https://deploy-preview-8153--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG4nkXPpzb5GnPeW0OoB6Pox6UBmXATgie1ejNGKAIhDJQIMMgHNVEAK4wANGQCe+gOQ4c2jaf0AnAM5wcAMzJgc0OFTIAjE388Xz9gsiw4CFw4ADouWSF5eMFhUkEJDmlSEEMQKJgaaEdkUDx7ewgAdwAFMoRilDwcSrwTYty-ezwwAGs4GABlLG6aKC1kGHs9OFy2Px8qHwAZPDG9PC04ADEIewwCArHkEDwDCByQAAsYDBwAdUuaeEdhsDgB+qf6J5NjsEd2iBRs57DBql0tPtkK4ms5cgArRwADwAQl1ev0BngMHAlqM4NDYTMQIikQNRlocHAAIp6DQEpAwnBwkDDJxwezHOjTC5YeyjGB3GhUGCXZAADgADLk+RBnHculhjny4CC6ATcgBHOnwcFRBonRwAWigcB8Pgu9jg2poVvBGyhjKJuWcGBoEymxMcFKptPphOZxJgeD8QpFYqQACZcpM8DQcBSAMIQDCOkCqgCsFz0zgAKiGGkyWdy4ABJKCLWADMD8rAwACCFYGMBMVIDzgAvh2gA)

**Comment by sosukesuzuki** [comment]
ooops, I'll fix..

**Comment by fisker** [comment]
Seems `angular-html-parser` parser problem

```text
require('angular-html-parser').parse('<template><div><template><div></div></template><div></div></div></template>', {getTagContentType:() => 0})
ParseTreeResult {
  rootNodes: [
    Element {
      name: 'template',
      attrs: [],
      children: [Array],
      sourceSpan: [ParseSourceSpan],
      startSourceSpan: [ParseSourceSpan],
      endSourceSpan: [ParseSourceSpan],
      nameSpan: [ParseSourceSpan],
      i18n: null
    },
    Element {
      name: 'div',
      attrs: [],
      children: [],
      sourceSpan: [ParseSourceSpan],
      startSourceSpan: [ParseSourceSpan],
      endSourceSpan: [ParseSourceSpan],
      nameSpan: [ParseSourceSpan],
      i18n: null
    }
  ],
  errors: [
    TreeError {
      span: [ParseSourceSpan],
      msg: 'Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags',
      level: 1,
      elementName: 'div'
    },
    TreeError {
      span: [ParseSourceSpan],
      msg: 'Unexpected closing tag "template". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags',
      level: 1,
      elementName: 'template'
    }
  ]
}
```

**Comment by fisker** [comment]
Exactly as I thought 

```text
require('angular-html-parser').parse('<div><div></div></div>', {getTagContentType:() => 0})
ParseTreeResult {
  rootNodes: [
    Element {
      name: 'div',
      attrs: [],
      children: [Array],
      sourceSpan: [ParseSourceSpan],
      startSourceSpan: [ParseSourceSpan],
      endSourceSpan: [ParseSourceSpan],
      nameSpan: [ParseSourceSpan],
      i18n: null
    }
  ],
  errors: [
    TreeError {
      span: [ParseSourceSpan],
      msg: 'Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags',
      level: 1,
      elementName: 'div'
    }
  ]
}
```

**Comment by sosukesuzuki** [comment]
@fisker Sorry, I don't understand the above problem properly, so could you open new issue in [angular-html-parser repo](https://github.com/ikatyang/angular-html-parser)?

**Comment by fisker** [comment]
Sure, I will.

**Comment by fisker** [comment]
@sosukesuzuki see https://github.com/ikatyang/angular-html-parser/issues/11#issuecomment-620560801

**Comment by fisker** [comment]
Seems everything is working, I'll run it on my vue projects later.

**Comment by sosukesuzuki** [comment]
I tried it with my company's vue project, there is no problem

**Comment by thorn0** [comment]
This should be a `SyntaxError`.

**Prettier pr-8153**
[Playground link](https://deploy-preview-8153--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmpaEAqc2+8AzmXgE5xkBmEbGB8ACasWAdzg4cAOhmkKFVAHpSSzLgJwSUEABoQELDACW0JslDs2EUQAV2CMyjw5ReAJ5m9AIzZ4wAazgYAGUsPyMoAHNkGDYAVzg9ei84QUFUgBk8KLi8SLgAMV5+GGMo5BA8OJgIXRAACxgMHAB1eqNmMLA4YIcOowA3DrcKsCZPEAimODYYG19I-mQuZ2m9ACsmAA8AIV8AoOC8DDgMiLhl1cSQTa3giMicOABFOIh4S5w1kDC2abYKgMEnUsGwIjAWkZBDB6sgABwABj0oIg0xaviwFVBcH+AwuegAjm94PMDI5KkwALRQOCpVJ1DhEowceZ5JZIFZfa7TDBGGLxbkPJ6vd4XDlXPQwPBeSHQ2FIABMkt8RhwDwAwhAMOyQDiAKx1OLTGjSxyc75AuAASSg6VgwTAYMMAEFbcEYG4np9pgBfH1AA)
```sh
--parser vue
```

**Input:**
```vue
<template>
  <p>Templates are formatted as well...
    </
</template>

```

**Output:**
```vue
TypeError: Cannot read property 'start' of null
    at Ln (https://deploy-preview-8153--prettier.netlify.app/lib/parser-html.js:113:1846)
    at e (https://deploy-preview-8153--prettier.netlify.app/lib/parser-html.js:113:3991)
    at Object.parse (https://deploy-preview-8153--prettier.netlify.app/lib/parser-html.js:113:4470)
    at Object.parse (https://deploy-preview-8153--prettier.netlify.app/lib/standalone.js:13771:21)
    at coreFormat (https://deploy-preview-8153--prettier.netlify.app/lib/standalone.js:17226:27)
    at format (https://deploy-preview-8153--prettier.netlify.app/lib/standalone.js:17461:77)
    at formatWithCursor (https://deploy-preview-8153--prettier.netlify.app/lib/standalone.js:17477:14)
    at https://deploy-preview-8153--prettier.netlify.app/lib/standalone.js:33653:14
    at Object.format (https://deploy-preview-8153--prettier.netlify.app/lib/standalone.js:33662:14)
    at formatCode (https://deploy-preview-8153--prettier.netlify.app/worker.js:233:21)
```

File: src/language-html/parser-html.js [hunk 4]
```diff
@@ -39,11 +43,56 @@ function ngHtmlParser(
...
+          const endOffset = node.endSourceSpan.start.offset;
+          for (const error of _errors) {
+            const { offset } = error.span.start;
+            if (startOffset < offset && offset < endOffset) {
+              errors.push(error);
+              break;
+            }
+          }
+        }
+        rootNodes[i] = _rootNodes[i];
```
Comment (fisker) [inline src/language-html/parser-html.js:92]: Isn't `rootNodes` and `_rootNodes` the same array?

**Comment by fisker** [comment]
#6525 Different now [Stable](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8qAJgJYBuxA9OVatZrgXIQDpSoDOYATmVhiE4ADywReMAAQk4AMzwBXHNOBSAvgx79B7KNWpTUeAEZg93GAE8crLdduEQAGhARBZaF2Sg8vXhAA7gAKfgjeKHgUEGQkLiAmvHhgANZwMADKWMlkUADmyDC8inCuABYwGDgA6mVk8FzZYHAZ4fWU9VbI4FzerrlccJLBSXkYeMgKOIOuAFZcIgBCSanpGXgYcAAyuXCTeNOlIPMiGbl5tgCKihDw+4eu2byDvN0UJfFY-LDVsTBlyAAHAAGR4BQbVJJYbpfOAvCh7VwARxu8BG7giIDwXAAtFA4HBZHFXLw4CiyKSRngxhMkFMZiBBhgyIVikcuOcrqi9nSDgyYKZfiR-sgAEyuIp4Mg4c4AYQgGHG3Sg0ERIEUgwAKqYIvS4Op1EA) [This PR](https://deploy-preview-8153--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8qAJgJYBuxA9OVatZrgXIQDpSoDOYATmVhiE4ADywReMAAQk4AMzwBXHNOBSAvgx79B7KNWpTUeAEZg93GAE8crLdduEQAGhARBZaF2Sg8vXhAA7gAKfgjeKHg4gXhW3q4mvHhgANZwMADKWMlkUADmyDC8inCucBgmcCSyJAAyePmKeHlwAGISGAQwuQWRijAQLiAAFjAYOADqw2TwXNlgcBnhM5QzVsjgXPEguVxwksFJeZ3ICjh7rgBWXCIAQkmp6Rl4GHC1uXCnURcg1yIZPVsAEVFBB4F9zqUQNleHteBsKCUhlh+LAJmQSDBhsgABwABlcKIgewmSSwGxRcDhFE+rgAjqD4Id3BEQHguABaKBwKpVIa8OAMsgCw7NE5IM4-PYYMiFYpQriAuAgsGfCXfKEwUzozHYpAAJlcRTwZBwPQAwhAMOKQFSAKxDRR7AAqpgikqhiLgAEkoLJYBk+AIYABBP0ZBxqj3qdRAA)

**Comment by sosukesuzuki** [comment]
@fisker I think it isn't needed to support JavaScript style comments in Vue SFC because it is not spec (ref: https://github.com/ikatyang/angular-html-parser/pull/12#issuecomment-616304945)

**Comment by fisker** [comment]
I know that but [this](https://deploy-preview-8153--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEB6VACAPAQwEZgB8AOlFvALYAOANjvIVgCYCWAbo6qx1qpbfTgkyAZzAAnFlRiE4ADyoRxMDEzgAzHAFcaK4BgC+vMZOnCsImAE8aQ49duEQAGhARpLaCOSgc48RAA7gAKfgjeKDg0gThW3q544jhgANZwMADKVMksUADmyDDiWnCucBR4cExqTAAyOPlaOHlwAGJKFPQwuQWRWjAQLiAAFjAUNADqwyzwItlgcBnhM+wzVsjgIvEguSJwysFJeZ3ImjR7rgBWInIAQkmp6Rk4FHC1uXCnURcg13IZPVsAEUtBB4F9zqUQNlxHtxBs2CUhlRJLAJiwmDBhsgABwABlcKIgewmSSoGxRcDhbE+rgAjqD4Id3BEQDgRABaKBwKpVIbiOAMlgCw7NE5IM4-PYUFiFYpQkSAuAgsGfCXfKEwfDozHYpAAJlcRRwLBoPQAwhAKOKQFSAKxDLR7AAq+AikqhiLgAEkoGpYBkJFIYABBP0ZBxqj0GAxAA) seems unacceptable, you wipe my whole file, just because I put a `// <a>` above.

Can we do this way? If it's Vue SFC, we already have the root elements(maybe also need check comments), we can loop the root elements find the text before/between/after, and print them when printing root children. 

I don't know if it's possible, just a idea.

**Comment by fisker** [comment]
@sosukesuzuki I think you didn't handle [unclosed element correctly](https://deploy-preview-8153--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UAygBYQCuANugARQQw2UQDOcNMJ7ksCMhIADQgIABxiZoLZKACGAJ3kQA7gAUFCaSlmVlsgJ7ThAI3mywAazgwio85igBzZDHnk4wuAFtjcdOj8AGVkncllHOAAxCHkvWRgJJ2QQWXIYCCEQEhgvSgB1Ekx4FjswOCJNIpwi-WSwFiMQBzZ5GFUzRzjkADMdNmEAKxYADwAhM0trIlkvOECHOB6+jxAh4aIHR0o4AEVyBkWkXsp+kDt5FuTsd0zReQcYPMx0TmQADgAGYTvWODyzUTJO5wFrYRbCACO+3g7TEWhSLAAtFA4H4-Jl5HAoZhMe1wl0jsthGwvJgXG4VixNts9gclicVjBZMYni8SMgAEzCVyyTCUTYAYQgXgJIBBAFZMuQ2AAVZlaY6na5wACSUACsCIYHu4gAguqiDB9Nt6WwAL5moA), the `// <a>` problem I mentioned above should be the same problem, if this handled,  that one should only format wrong, but not lost content.

File: src/language-html/parser-html.js [hunk 5]
```diff
@@ -39,11 +42,56 @@ function ngHtmlParser(
...
+      });
+      const secondParseRootNodes = secondParseResult.rootNodes;
+      const secondParseErrors = secondParseResult.errors;
+
+      errors = [];
+
+      for (let i = 0; i < rootNodes.length; i++) {
+        const node = rootNodes[i];
+        const { endSourceSpan, startSourceSpan } = node;
+        const isUnclosedNode = endSourceSpan === null;
```
Comment (fisker) [inline src/language-html/parser-html.js:76]: [1](https://deploy-preview-8153--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4gDQgQAOMm0AzsqAIYBOtEA7gAp0KUrUA2j1AnpQIAjWtTABrODADKRMZigBzZDFoBXOATgBbIXHTp9AGWpK11RXABiEWtuoxSS5CGpqYEfCAAWMbVwB1b0x4cjkwOGl2EJwQvhcwckEQBXI4WhhmUUV7ZAAzbjSCACtyAA8AIVEJKWlqbTgjBTh8ws0QUrLpBUUuOABFNQh4Vq4ikDlaNNoXbA0vIloFGADMdBhvZAAOAAYCRYg0gNEiF0W4aewWggBHIfgs4g5XcgBaKDh9fS9aODvMX5ZCy5JAFMbtNLaTAqdQQnp9QbDFqgtoEGDUISrdabJAAJjRokwXB6AGEINoQSALgBWLxqNIAFQxHDB4zmcAAklBDLBpGAliQAILc6QwPh9UZpAC+UqAA) [2](https://deploy-preview-8153--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEB6VACAPAEwJYBuIANCBAA4x7QDOyoAhgE5MQDuACswnSgwDZsGATzqkARkwZgA1nBgBlctLxQA5shhMArnFJwAtuLg4cJgDIN12hmrgAxCEwMMYVdchANtMCCRAAFjAG-ADqAXjwNMpgcAo8kYSRwp5gNGIgqjRwTDAcUmouyABmAtmkAFY0AB4AQlKy8goMBnDmqnAlZXogVdUKqmr8cACK2hDwXfzlIMpM2UyeBLr+5EyqMKF4ODAByAAcAAykaxDZoVLknmtwCwSdpACO4-D5FLxeNAC0UHAmJv4mHBnnggflbEUkKVpj1sgY8JodLDBsMxhNOlDuqQYAxxFsdnskAAmbFSPD8QYAYQgBkhIFuAFZ-NpsgAVXG8aEzZZwACSUDMsAUYHWlAAggKFDBhMMptkAL7yoA)

**Comment by fisker** [comment]
Have you seen [this](https://github.com/ikatyang/angular-html-parser/issues/15#issuecomment-626105430)?

**Comment by sosukesuzuki** [comment]
@fisker 
> Have you seen this?

Yes. Isn't it enough? https://github.com/prettier/prettier/pull/8153/files#diff-b9175c570626e1f7f11d277df8272fcbR345-R346

**Comment by thorn0** [comment]
@sosukesuzuki It's needed to implement e.g. https://github.com/prettier/prettier/issues/6298. The content of `<template>` is not necessarily HTML. And when it's not, it shouldn't parsed as such.

**Comment by sosukesuzuki** [comment]
@thorn0 I know. Is [this formatting for pug](https://deploy-preview-8153--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwAE+UA5gLwA6IWArqdQHyVSGEB08AzjC22wGIAZhAh8OAI3wtUAeky4CcRiAA0ICFhgBLaF2Sg8AJyMQA7gAVjCfSjw4zeAJ771Eo3jABrODADKWJ7aZMgwRrRw6nAYEnAAJnHxADJ4ZLR4pHAAYhBGGAQ6IXa0MBBqIAAWMBg4AOoV2tyBYHB+No3aAG6NTsjgXK4gwVxwRjAWHqT5yEL2I+oAVlwAHgBCHt6+fngYcEnBcDNzkSBLy37BpDhwAIq0EPBHOPM0xiNGfZ0R5VhGwTC1bRxGAVZAADgADOpfhARrUPFg+r84O9Ood1ABHe7wCaaWwgPBcAC0UDg8Xi5SMcCx2ipEwy0yQs2eJxGGG0oXCrMu1zuD0OTOO6hgeAkgOBoKQACZhR5tDhLgBhCAYRkgFEAVnKtBGABVRbZmS8vnAAJJQRKwPxgP5aACCFr8MCc1yeIwAvu6gA) incorrect?

**Comment by thorn0** [comment]
It's good. I didn't notice you'd already updated the parser.

File: src/language-html/parser-html.js [hunk 6]
```diff
@@ -39,11 +42,54 @@ function ngHtmlParser(
...
+    const langValue = langAttr && langAttr.value;
+    const shouldParseAsHtml =
+      langValue == null || getParserName(langValue, options) === "html";
+
+    if (shouldParseAsHtml) {
+      const secondParseResult = parser.parse(input, {
+        canSelfClose: recognizeSelfClosing,
+        allowHtmComponentClosingTags,
+        isTagNameCaseSensitive,
+      });
```
Comment (fisker) [inline src/language-html/parser-html.js:67]: @sosukesuzuki 

Is this secondParse still need with attrs info? I'm okay with this, just double checking with you.

If it's still needed, I think we can optimalize this a little bit, because it's not alway needed, so we can do the second parse when it's needed. Something like 

```js

const getSecondFormat = () => secondResult ? secondResult : (secondResult = doSecondFormat())

if (isUnclosedNode) {
  rootNodes[i] = getSecondFormat().rootNodes
  // ...
} else if (node.name === "template" || node.name === "html") {
  // handle getSecondFormat().errors
}
```

Better?

**Comment by fisker** [comment]
[This seems not right](https://deploy-preview-8153--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwAEMAnlnALwA6IArlANZQQDuUNAfFVFt4YRUIByACoALAJYBnQpAAmcQtMKo4UsHnJyOAQiHdUAeky4CcDiAA0ICFhgToU5KDwAnV6wAKbhE5R4cFjwSJ2sAI1c8MAY4GABlLCiJKABzZBhXWjhrOAwwuDkFOQAZPFTaPBS4ADEIVwwCe1TkEDxaGAgrEDEYDBwAdUl4KUSwODjfCXsANymSFrApUJBkqThXGE9IlIbkADMAtesAKykADwAhSOjYuLwMOGLkuH3D7JBTs7jklJw4AEVaBB4K8cEcQIlXGtXC1plkulhXMkYP0JHIYGJkAAOAAM1kREDW-UiWBaiLU62mL2sAEcgfAtrY-K0pABaKBwAoFLquOB0iS8raVXZIA5g95rDASdKZCU-P6A4EvUVvawwPBhVHozFIABMasiEhwPwAwhAMCKQGoAKxdWhrEQavxi8FwuAASSgClgcTASLsAEEvXFSH9QWsAL4RoA), code from [pug site](https://pugjs.org/language/code.html#buffered-code)

**Comment by thorn0** [comment]
> code from pug site, but

Hm... I thought I tested code like that and it worked.

>  I guess we can improve later

It's directly related to this PR, so would be better to fix now.

**Comment by fisker** [comment]
I feel this going to getting harder to parse correctly, because sosukesuzuki also trying to support html files with vue syntax, how about make this a new parser `vue-sfc` only work for `.vue` file.

@sosukesuzuki  do you think this will be easier to parse?

**Comment by fisker** [comment]
> Hm... I thought I tested code like that and it worked.

Because there is `=` in  my  case.

**Comment by thorn0** [comment]
Ah, I tested `<template lang=...>`, not `<template type=...>`.

**Comment by thorn0** [comment]
`vue` should remain for SFCs as they're more common. "HTML with Vue" could be called `vue-html`.

Some alternatives I can think of:

- parse top-level standard HTML elements (`div`, `span`, etc) as HTML
- add a suboption to the `html` parser via `--embedded-language-formatting`

On the other hand, even now Prettier supports "HTML with Vue" only if the file has a top-level `html` tag, right? And the fact that nobody complains about that means that either nobody uses this feature or everyone is okay with using the `html` tag. So let's keep it like that maybe? Isn't it implemented like that in this PR any way?

**Comment by fisker** [comment]
Hmmm... in that case, this is expected,.only lang checked?

**Comment by fisker** [comment]
[vue only check lang too](https://github.com/vuejs/vue-next/blob/74ed7d1d6bc259b60ffec6775fe64245db857519/packages/compiler-sfc/src/parse.ts#L107), we are good, sorry for bring the wrong case.

**Comment by fisker** [comment]
Let's fix this https://github.com/prettier/prettier/pull/8153#discussion_r423421953 ? then we can merge.

File: src/language-html/parser-html.js (hunk 6 above)
Comment (sosukesuzuki) [reply src/language-html/parser-html.js:67]: What means "second format"? is not "second parse"?

Comment (fisker) [reply src/language-html/parser-html.js:67]: Second parse, sorry, it's not always needed, right?

Comment (sosukesuzuki) [reply src/language-html/parser-html.js:67]: Yes, I'll fix:+1:

**Comment by fisker** [comment]
I know vue  don't support multiple `<template>`,  what  [this](https://deploy-preview-8153--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8qA9JrgXIQDpTpzb7wAE+UA5gLwCuUA1lAgB3KDTp4xpckyq16jSsTIMKLMSAA0ICFhgBLaAGdkoPACczwgArmExlHhxC8AT2NaARmbxg+cGADKWD56HMgwZtxwWgwecAAm8QkAMngc3HjscABiEGYYBPphDtwwEJogABYwGDgA6pV68IbBYHABdk16AG5NLsjghu4goYZwZjBW3uwFyABmjmNaAFaGAB4AQt6+-gF4GHDJoXDzi9Egq2sBoew4cACK3BDwpzhLIMFmY2YD3VEVWDMoRgdT08RglWQAA4AAxaQEQMZ1bxYAaAuDfbonLQARye8CmOnsIDwhgAtFA4AkEhUzHA8Xo6VNMrMkAs3ucxhg9OFIpybndHs8TmyzloYHgPKDwZCkAAmcXePQ4G4AYQgGFZIAxAFYKtwxgAVSX2dnvP5wACSUCSsACYCBugAgjaAjAXHdXmMAL7eoA) should be

**Comment by fisker** [comment]
[Another multiple templates case](https://deploy-preview-8153--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8qA9JrgXIQDpTpzb7wAE+UA5gLwCuUA1lAgB3KDTp4xpckyq0wOaHAAmAOlogANCAhYYAS2gBnZKDwAnM8IAK5hMZR4cQvAE9jWgEZm8YPnBgAylg+ehzIMGbccFoMHspKygAyeBzceOxwAGIQZhgE+mEO3DAQmiAAFjAYOADq5XrwhsFgcAF2DXoAbg0uyOCG7iChhnBmMFbe7HnIAGaOI1oAVoYAHgBC3r7+AXgYcImhcLPz0SDLKwGh7DhwAIrcEPDHOAsgwWYjZn2dUWVYZqEYDU9EoYOVkAAOAAMWn+EBGNW8WD6-zgn06Ry0AEcHvAJjp7CA8IYALRQODKZRlMxwHF6GkTdLTJBzF6nEYYPThSLsq43e6PI4sk5aGB4DzA0HgpAAJlF3j0OCuAGEIBhmSA0QBWMrcEYAFXF9lZrx+cAAklAErAAmAAboAIJWgIwFw3Z4jAC+nqAA)

**Comment by thorn0** [comment]
So what is the second parsing needed for?

**Comment by sosukesuzuki** [comment]
It seems that this can be avoided if the node replacement is based on location info instead of index.

**Comment by fisker** [comment]
Nice!

**Comment by sosukesuzuki** [comment]
I fixed the above problem but for some reason commits are not shown on the PR. We can see these changes in file changes.(why...?)
https://github.com/prettier/prettier/pull/8153/files#diff-b9175c570626e1f7f11d277df8272fcbR81-R95

**Comment by fisker** [comment]
I saw the ci running, then I test those two links. thought it's my problem. The commits are missing on your fork too https://github.com/sosukesuzuki/prettier/commits/8106

**Comment by thorn0** [comment]
I successfully fetched them from the work. Looks like GitHub's UI is out of sync.

**Comment by fisker** [comment]
Screenshot_2020-05-13-23-18-21-899_com chrome canary

**Comment by fisker** [comment]
All issues addressed?

**Comment by sosukesuzuki** [comment]
Yes all issues were probably fixed. Can we merge this? Should I fix commits history?
(I've pushed these commits from the new machine so maybe something was wrong with my Git config. I'll look into this.)

**Comment by fisker** [comment]
I'm good.

**Comment by fisker** [comment]
I didn't bring this case  here   https://github.com/prettier/prettier/issues/8162#issuecomment-619684156, but you  should know.

I  try to throw SyntaxError in https://github.com/prettier/prettier/pull/8280, but  this PR keeps it  as it is , I  think it's  better.

**Comment by thorn0** [comment]
I reported this situation to GitHub. The commits still aren't visible on the UI. Not sure what happens if we do a merge.

BTW, a question on SO relevant to this PR:  https://stackoverflow.com/q/61742084/76173

**Comment by fisker** [comment]
I  use this `script`(and  `textarea`) template before, for  browsers  don't support `template`. I don't think we should format it as  html , if  it can format as  html why  not put in a  hidden `<div>`?

**Comment by fisker** [comment]
Try  close and  reopen ?

File: src/language-html/parser-html.js [hunk 7]
```diff
@@ -65,6 +141,7 @@ function ngHtmlParser(
     } else if (node instanceof Text) {
       node.type = "text";
     } else {
+      console.log(node);
```
Comment (sosukesuzuki) [inline src/language-html/parser-html.js:144]: oops, I'll remove this

**Comment by thorn0** [comment]
@fisker Prettier formats `script type="text/markdown"`. Why not format `script type="text/html"`?

**Comment by sosukesuzuki** [comment]
@fisker 
> I try to throw SyntaxError in ~~#8280~~ #8281, but this PR keeps it as it is , I think it's better.

I think so too but the behavior is happened by [stable Prettier](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAEQPIGEAqAmgAoCiABABYwC2ANgHwA6Uq19zrlcAhgCadUAem79BAIwh8Anp3LlUfAJYA3ckr4BeJiB4AHPTrnyF6ALRnyAd25RyKgK5xyengCcAzs4dfyAMwg3Klo6ABpyAEkoPQcYcg9KCAc6PnIoCDiYN144ng9ySBo9aAQ4i2N5VCiYmAZgYBUeOicAXxbhatjjYWUVQSFJGW6PMDclPTiPNzBtEGoYPQ8kISEHaIBrAHMAOkKhRzghZQ8YfadtgCsPI2ERsYnh0fHalhM0uCtyADUnAApgV5vchwOhIcgAcgAxPo9ODQoC3nweDAeGC-GswDAlNBfgBKcgAuxA+TZGAONx2YD2JpOMHggCM4PILQRJhZRPkLVxgNuTweLGE7EYIFCIAgE2xUA8yFA7jcECsxHcCGlKCaVh40mlovEbh4YHWcBgAGVXGAlFBNsgsk5RUKAOqUJTwDxmuDGlXO1TO6TIcAebUgC1eNwwYh6zY0HjIPxNLyiq4ADwAQnqDUbjTwaHAADIWuAxuNwBMeRPGi2bOhwACKDgyBaQsbo8ZArk8cDcfoOItbY1g9o0MEoyAAHAAGUV6eVee16vR+qdwEMqAuigCOdfg4fFqt0HjMUDgcD4x572Q3Smy4Z4kejjaLoq8NCU1rctpAHgrVdr9cLzeLIAouIA58EOyAAEyilkPBKHQFa4BANBRn6S4AKw9j4cD4Dw4iqk2LYHFEJ6wMafIwAAglAfDGjA0hVn+XhtEAA). So we can fix this in other PR.

**Comment by sosukesuzuki** [comment]
I think we should open new issues for https://github.com/prettier/prettier/pull/8153#issuecomment-628082830 and https://github.com/prettier/prettier/pull/8153#issuecomment-628081977 , should not fix in this PR.

File: src/language-html/parser-html.js (hunk 7 above)
Comment (fisker) [reply src/language-html/parser-html.js]: This done?

Comment (sosukesuzuki) [reply src/language-html/parser-html.js]: yes

Comment (fisker) [reply src/language-html/parser-html.js]: GO!

File: src/language-html/parser-html.js [hunk 8]
```diff
@@ -39,11 +42,84 @@ function ngHtmlParser(
...
+          }
+          if (
+            node.startSourceSpan.start.offset ===
+            _node.startSourceSpan.start.offset
+          ) {
+            return true;
+          }
+          return false;
+        });
+      };
```
Comment (fisker) [inline src/language-html/parser-html.js:95]:
```suggestion
      const getSameLocationNode = (node) =>
        getSecondParse().rootNodes.find(
          ({ startSourceSpan }) =>
            startSourceSpan &&
            startSourceSpan.start.offset === node.startSourceSpan.start.offset
        );
```

`node` can't be false, right?

File: src/language-html/parser-html.js [hunk 9]
```diff
@@ -39,11 +42,84 @@ function ngHtmlParser(
...
+      const doSecondParse = () =>
+        parser.parse(input, {
+          canSelfClose: recognizeSelfClosing,
+          allowHtmComponentClosingTags,
+          isTagNameCaseSensitive,
+        });
+      const getSecondParse = () =>
+        secondParseResult
+          ? secondParseResult
+          : (secondParseResult = doSecondParse());
```
Comment (fisker) [inline src/language-html/parser-html.js:80]:
```suggestion
      const getSecondParse = () =>
        secondParseResult || (secondParseResult = doSecondParse());
```

File: src/language-html/parser-html.js [hunk 10]
```diff
@@ -39,11 +42,84 @@ function ngHtmlParser(
...
+            const { offset } = error.span.start;
+            if (startOffset < offset && offset < endOffset) {
+              errors = [error];
+              break;
+            }
+          }
+          const replaceNode = getSameLocationNode(node);
+          if (replaceNode) {
+            rootNodes[i] = replaceNode;
+          }
```
Comment (fisker) [inline src/language-html/parser-html.js:118]:
```suggestion
      rootNodes[i] = getSameLocationNode(node) || rootNodes[i];
```

File: src/language-html/parser-html.js [hunk 11]
```diff
@@ -288,6 +366,16 @@ module.exports = {
     vue: createParser({
       recognizeSelfClosing: true,
       isTagNameCaseSensitive: true,
+      getTagContentType: (tagName, prefix, hasParent, attrs) => {
+        if (
+          tagName !== "html" &&
+          !hasParent &&
+          (tagName !== "template" ||
+            attrs.find((attr) => attr.name === "lang" && attr.value !== "html"))
```
Comment (fisker) [inline src/language-html/parser-html.js:374]:
```suggestion
            attrs.some(({name, value}) => name === "lang" && value !== "html"))
```

**Comment by sosukesuzuki** [comment]
@fisker Thank you for your review! I fixed all reviewed points.

**Comment by fisker** [comment]
Great job!
