### PR TITLE
Fix additional empty line switch case comment

### LINKED ISSUE #805: Two blank lines are inserted between a `case` statement and a comment, except on Windows
Input source code:

```javascript
switch (node && node.type) {
  case "Property":
  case "MethodDefinition":
    prop = node.key;
    break;

  case "MemberExpression":
    prop = node.property;
    break;

  // no default
}
```

When formatted, the single blank line before the final comment is turned into two blank lines:

```javascript
switch (node && node.type) {
  case "Property":
  case "MethodDefinition":
    prop = node.key;
    break;

  case "MemberExpression":
    prop = node.property;
    break;


  // no default
}
```

This is unexpected behavior to me. Prettier never uses multiple blank lines in a row anywhere else, and in fact it collapses multiple blank lines into one blank line in other situations.

The extra blank line is inserted in the web tool [prettier.github.io/prettier/][output] (no matter what OS it is viewed with), and is also inserted when I or my coworker on Ubuntu run the `prettier` command-line tool. However, for my coworkers who run Windows, `prettier` keeps only one blank line between the `break;` and the comment instead of inserting an extra one. It's probably related to `\n` vs. `\r\n` line endings.

Some more-minimal input code that [still reproduces the problem][minimal-output]:

```javascript
switch (foo) {
  case "bar":
    doThing()

  // no default
}
```

Deleting the single blank line or deleting the comment avoids this issue.

[output]: https://prettier.github.io/prettier/#%7B%22content%22%3A%22switch%20(node%20%26%26%20node.type)%20%7B%5Cn%20%20case%20%5C%22Property%5C%22%3A%5Cn%20%20case%20%5C%22MethodDefinition%5C%22%3A%5Cn%20%20%20%20prop%20%3D%20node.key%3B%5Cn%20%20%20%20break%3B%5Cn%5Cn%20%20case%20%5C%22MemberExpression%5C%22%3A%5Cn%20%20%20%20prop%20%3D%20node.property%3B%5Cn%20%20%20%20break%3B%5Cn%5Cn%20%20%2F%2F%20no%20default%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

[minimal-output]: https://prettier.github.io/prettier/#%7B%22content%22%3A%22switch%20(foo)%20%7B%5Cn%20%20case%20%5C%22bar%5C%22%3A%5Cn%20%20%20%20doThing()%5Cn%5Cn%20%20%2F%2F%20no%20default%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

### PR DESCRIPTION
**Pull request by yamafaktory**
This one should fix #805.

### CODE REVIEW

File: src/printer.js [hunk 1]
```diff
@@ -1855,7 +1856,17 @@ function printStatementSequence(path, options, print) {
 
     parts.push(stmtPrinted);
 
-    if (util.isNextLineEmpty(text, stmt) && !isLastStatement(stmtPath)) {
+    if (parent.type === "SwitchCase") {
```
Comment (vjeux) [inline src/printer.js]: This function is a generic one. Could you instead try to fix it inside of the implementation of SwitchCase?

Comment (yamafaktory) [inline src/printer.js]: Of course, I'll do it.

**Comment by yamafaktory** [comment]
@vjeux does it match your expectations? Thanks!

**Comment by yamafaktory** [comment]
@vjeux Can you check again that one, thanks!

File: src/printer.js [hunk 2]
```diff
@@ -1834,8 +1841,9 @@ function genericPrintNoParens(path, options, print) {
 function printStatementSequence(path, options, print) {
   let printed = [];
 
-  path.map(function(stmtPath, i) {
-    var stmt = stmtPath.getValue();
+  path.map(stmtPath => {
```
Comment (vjeux) [inline src/printer.js]: can you revert those 3 lines, they are unrelated.

File: src/printer.js [hunk 3]
```diff
@@ -1209,13 +1209,20 @@ function genericPrintNoParens(path, options, print) {
...
-            return printStatementSequence(consequentPath, options, print);
-          },
-          "consequent"
-        );
-
+        const cons = path.call(consequentPath => {
+          let printed = [];
+          path.map(p => {
+            const value = p.getValue();
+            const parent = p.getParentNode();
```
Comment (vjeux) [inline src/printer.js]: can you avoid creating those two variables, you are only using them once and it makes it more verbose than needs be

File: src/printer.js (hunk 2 above)
Comment (yamafaktory) [inline src/printer.js]: Oops, correct!

File: src/printer.js (hunk 3 above)
Comment (yamafaktory) [inline src/printer.js]: Yeah, you're right, was doing that for readability only.

File: src/printer.js (hunk 2 above)
Comment (yamafaktory) [inline src/printer.js]: Actually the `i` is unused.

Comment (vjeux) [inline src/printer.js]: You should send a separate pull request to remove the i, not add it to a random one :)

**Comment by yamafaktory** [comment]
@vjeux done!

File: src/printer.js (hunk 2 above)
Comment (yamafaktory) [inline src/printer.js]: No pbl, thanks will do it!

File: src/printer.js [hunk 4]
```diff
@@ -1209,13 +1209,18 @@ function genericPrintNoParens(path, options, print) {
...
-          function(consequentPath) {
-            return printStatementSequence(consequentPath, options, print);
-          },
-          "consequent"
-        );
-
+        const cons = path.call(consequentPath => {
+          let printed = [];
+          path.map(p => {
+            const parentParent = path.getParentNode(1);
```
Comment (vjeux) [inline src/printer.js]: `parentParent` and `last` do not change on every iteration, you can put them outside of the loop

File: src/printer.js [hunk 5]
```diff
@@ -1209,13 +1209,18 @@ function genericPrintNoParens(path, options, print) {
...
+            const last = parentParent && parentParent.cases &&
+              parentParent.cases[parentParent.cases.length - 1];
```
Comment (vjeux) [inline src/printer.js]: use `util.getLast()`

File: src/printer.js (hunk 4 above)
Comment (yamafaktory) [inline src/printer.js]: Oh you're right!

**Comment by yamafaktory** [comment]
@vjeux partially done. Strangely moving parentParent and last out of the loop breaks it...

**Comment by yamafaktory** [comment]
@vjeux Forget about what I said before, fixed now!

File: src/printer.js [hunk 6]
```diff
@@ -1209,13 +1209,17 @@ function genericPrintNoParens(path, options, print) {
...
-            return printStatementSequence(consequentPath, options, print);
-          },
-          "consequent"
-        );
-
+        const parent = path.getParentNode();
+        const lastCase = util.getLast(parent.cases);
+        const cons = path.call(consequentPath => {
+          let printed = [];
+          path.map(p => {
```
Comment (vjeux) [inline src/printer.js]: I just realized that map creates an array with the returned values. So you can do

```js
return join(hardline, path.map(p => {
  ...
  return concat(...);
});
```

to make the code shorter.

Sorry my feedback is coming in waves. This is the only last thing I'm seeing with your code!

Comment (vjeux) [inline src/printer.js]: Shouldn't this be consequentPath?

Comment (yamafaktory) [inline src/printer.js]: You mean instead of `p`?

File: src/printer.js [hunk 7]
```diff
@@ -1209,13 +1209,15 @@ function genericPrintNoParens(path, options, print) {
...
-          function(consequentPath) {
-            return printStatementSequence(consequentPath, options, print);
-          },
-          "consequent"
-        );
-
+        const parent = path.getParentNode();
+        const lastCase = util.getLast(parent.cases);
+        const cons = path.call(consequentPath => {
+          return join(hardline, path.map(p => {
```
Comment (vjeux) [inline src/printer.js]: You are doing `path.call` in order to get `consequentPath` but you're not using it. So either the `path.call` is useless and you should remove it, or there's a problem with the code and `path.map` should be `consequentPath.map` and it happens to be working because path is mutated under the scenes.

Comment (yamafaktory) [inline src/printer.js]: That was definitely the second solution. I need consequentPath in this case. Sorry for the confusion, I refactored it so many times before that I didn't saw that one 👍.

**Comment by yamafaktory** [comment]
@vjeux should be good to go now 🤞.

**Comment by vjeux** [comment]
Yay!
