### PR TITLE
Markdown: fix incorrect prettification of multi-line markdown footnote

### LINKED ISSUE #5958: incorrect prettification of multi-line markdown footnote
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAJOAnOByAzgAgEN9cZD4BbBGAbQD0AzCCGKFuAXQDoAdKP+kxZt4HJH3yT86LHiL4KAVwA2MAJYBaZWqhx8Q1u3wB3QsoDWOgOb4ARoTDn8MABZ7CtiADc9pcnCpYABoiKAATEhcIY2sJKSjjfDUYOTNlZxY0gE87CGVlCEdcXigpfBAgkAgAB3VoXGRQQgwMaIAFZoQGlEIvCDUwipBbDAdzOBgAZWqHa2QYDEU4SpcYCmUAdRdkuFwZsDhJruS1L2Ss5HBcBsqdXEwYNtGrCkJkBjN7yoArXAAPABCo0cE0mhCoABkdHB3p9liBfn9JtZlHAAIqKdiw5RfEAzDD3DCXV4YcxhaJQIbVDA6GAbAauZAADgADJVqRB7htRtVLtTdpgfEMsABHRRqLBPQgvN5ID44+H3ChqeaLRUo9GY+DY3FkWz0sKMpAAJkqC0Iam0UCsAGEIBRXpc2Lohop7gAVDzdeX3AC+vqAA)
```sh
--parser markdown
```

**Input:**
```markdown
Here's a statement[^footnote].

[^footnote]:
    Here's a multi-line footnote walking back the above statement, and showing
    how it's all totally bollocks.
    
```

**Output:**
```markdown
Here's a statement[^footnote].

[^footnote]:

  Here's a multi-line footnote walking back the above statement, and showing
  how it's all totally bollocks.

```

**Expected behavior:**

[Kramdown](http://kramdown.gettalong.org) will only parse the multi-line footnote if there's no line between the `[^footnote]:` line and the actual footnote. So the fact that prettier inserts a newline there means that it changes the output of the markdown (using Kramdown, at least).

### PR DESCRIPTION
**Pull request by sasurau4**
fix #5958

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-markdown/printer-markdown.js [hunk 1]
```diff
@@ -357,12 +357,27 @@ function genericPrint(path, options, print) {
...
+                          child => child.value === "\n"
+                        );
+
+                      return index === 0
+                        ? isMultilineFootnote
+                          ? group(concat([softline, childPath.call(print)]))
+                          : group(
+                              concat([
+                                softline,
+                                softline,
```
Comment (thorn0) [inline src/language-markdown/printer-markdown.js]: Why do we need two softlines here?

Comment (sasurau4) [reply src/language-markdown/printer-markdown.js]: I don't know why but I think the same reason that softline is inserted between headers such like `#`  🤔

Comment (sasurau4) [reply src/language-markdown/printer-markdown.js]: I realized that it caused the issue, so I remove it.
Thanks for pointed out!
