### PR TITLE
test: fix snapshots

### LINKED ISSUE #2956: One test fails on master on Travis CI, but not locally
https://travis-ci.org/prettier/prettier/jobs/282316211

```
Summary of all failing tests
FAIL tests_integration/__tests__/write.js
  ● do not write file with --write + formated file › (stdout)
    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    - "formated.js%s %dms
    + "formated.jss
      "
      
      at Object.test (tests_integration/runPrettier.js:98:32)
          at Promise (<anonymous>)
          at <anonymous>
```

Edit: #2957

### PR DESCRIPTION
**Pull request by ikatyang**
Not sure why, but the build failed.

- remove `--no-color`
- use `strip-ansi` to enforce no colored snapshots
- update snapshots

Fixes #2956

### CODE REVIEW

File: tests_integration/__tests__/__snapshots__/write.js.snap [hunk 1]
```diff
@@ -3,7 +3,7 @@
 exports[`do not write file with --write + formated file (stderr) 1`] = `""`;
 
 exports[`do not write file with --write + formated file (stdout) 1`] = `
-"formated.js[2K[1G[90m%s %dms[39m
+"formated.js%s %dms
```
Comment (lydell) [inline tests_integration/__tests__/__snapshots__/write.js.snap]: Should we open a new issue about the `%s` and `%d` here? Looks like a bug to me.

Comment (lydell) [reply tests_integration/__tests__/__snapshots__/write.js.snap]: #2960
