### PR TITLE
fix inconsistent parsing of injected expressions in styled-components' css

### LINKED ISSUE #8095: Inconsistent parsing of injected expressions in styled-components' css
note the presence/absence of `;` after injected expression
```ts
const Header = styled.div`
  ${something()};
margin:4px;
`
```
is parsed and formatted as
```ts
const Header = styled.div`
  ${something()};
  margin: 4px;
`;
```
---
```ts
const Header = styled.div`
  ${something()}
margin:4px;
`
```
is parsed and formatted as
```ts
const Header = styled.div`
  ${something()}
  margin:4px;
`;
```
---
```ts
const Header = styled.div`
  ${something()};
  & > ${Child}:not(:first-child) {
margin-left:5px;
}
`
```
is parsed and formatted as
```ts
const Header = styled.div`
  ${something()};
  & > ${Child}:not(:first-child) {
    margin-left: 5px;
  }
`;
```
---
```ts
const Header = styled.div`
  ${something()}
  & > ${Child}:not(:first-child) {
margin-left:5px;
}
`
```
is not parsed
```
Error: Couldn't insert all the expressions
    at transformCssDoc (https://prettier.io/lib/standalone.js:22171:11)
    at Object.embed$4 [as embed] (https://prettier.io/lib/standalone.js:22011:18)
    at Object.printSubtree (https://prettier.io/lib/standalone.js:15781:31)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:15898:29)
    at https://prettier.io/lib/standalone.js:15863:16
    at Object.printComments (https://prettier.io/lib/standalone.js:15586:17)
    at printGenerically (https://prettier.io/lib/standalone.js:15862:22)
    at FastPath.call (https://prettier.io/lib/standalone.js:15700:16)
    at printPathNoParens (https://prettier.io/lib/standalone.js:25178:91)
    at Object.genericPrint$3 [as print] (https://prettier.io/lib/standalone.js:23541:28)
```

### PR DESCRIPTION
**Pull request by thecodrr**
Fixes #8095 

This fixes this error:

```
Error: Couldn't insert all the expressions
    at transformCssDoc (https://prettier.io/lib/standalone.js:22171:11)
    at Object.embed$4 [as embed] (https://prettier.io/lib/standalone.js:22011:18)
    at Object.printSubtree (https://prettier.io/lib/standalone.js:15781:31)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:15898:29)
    at https://prettier.io/lib/standalone.js:15863:16
    at Object.printComments (https://prettier.io/lib/standalone.js:15586:17)
    at printGenerically (https://prettier.io/lib/standalone.js:15862:22)
    at FastPath.call (https://prettier.io/lib/standalone.js:15700:16)
    at printPathNoParens (https://prettier.io/lib/standalone.js:25178:91)
    at Object.genericPrint$3 [as print] (https://prettier.io/lib/standalone.js:23541:28)
```

When this is parsed:
```js
const Header = styled.div`
  ${something()}
  & > ${Child}:not(:first-child) {
margin-left:5px;
}
`
```

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
What about this?
**Prettier pr-8097**
[Playground link](https://deploy-preview-8097--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuc0DOMAEAJOBDAEzgCdMBeTDATwBs4CA6AgSwDcADAHSk0wBJgaCAFs4MABbMoAcwAUASgC+3XgDJMAPn7AAwpJoFFAvcwMAmRUigQYspADNmxDAFow+gvMzBuwvMWkpFzp7GCQAVgAHAA8Abm5lKHYQABoQCEiYZnRkUH9iCAB3AAV-BDRkEDwaQrwqCrSAI2I8MABrMQBlSNapaWQYYgBXODS4YUb6IgIAGTwZIbxpOAAxCGI-GCyZSrwhmAhUkHEYYRoAdUl4NB6wOE7y5izWJ6pKsDQGkCk0EhhilrSPzIezVX5pABWaGiACEWu0unhRDMpHAQWDRiAodFOn06ABFIY2NEODFpHrOEiVRp4SY0I6RYhSGDnZgECTIAAcAAZyQVfucWpFKoy4L9iKw0WkAI5E+AAjIVFB4NAuKBwej0I7EOCypxwAFLYGkmjgkC-YTMAbDTFoPFwQnE9GmzEwWms9niZBmNKDPCmPo6ETGkBi8JHIa-AAqtKVoJdaVYIwAklAiLBOmAmZkAIJpzowWgk+O-RSKIA)
```sh
--parser babel
```

**Input:**
```jsx
const Header = styled.div`
  ${something()}
  & > ${Child}${Child2}:not(:first-child) {
margin-left:5px;
}
`
```

**Output:**
```jsx
Error: Couldn't insert all the expressions
    at transformCssDoc (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:24233:13)
    at Object.embed$3 [as embed] (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:24077:20)
    at Object.printSubtree (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:16837:30)
    at callPluginPrintFunction (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:16958:33)
    at https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:16922:49
    at Object.printComments (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:16595:21)
    at printGenerically (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:16922:24)
    at FastPath.call (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:16715:22)
    at printPathNoParens (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:28820:92)
    at Object.genericPrint$3 [as print] (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:27330:32)
```

**Comment by thecodrr** [comment]
@thorn0 looking into it. thanks for pointing it out.

**Comment by thecodrr** [comment]
@thorn0 should be working as expected now.

File: src/language-js/embed.js [hunk 1]
```diff
@@ -286,29 +286,39 @@ function replacePlaceholders(quasisDoc, expressionDocs) {
...
+        }
 
-      replaceCounter++;
-      parts = parts
-        .slice(0, atPlaceholderIndex)
-        .concat(["${", expression, "}" + suffix])
-        .concat(rest);
+        placeholder = "@prettier-placeholder" + placeholder;
+        const placeholderMatch = placeholder.match(
+          /@prettier-placeholder-(.+)-id([\S\s]*)/
```
Comment (thorn0) [inline src/language-js/embed.js:306]: Please make this regexp stricter to avoid problems like the following:

**Prettier pr-8097**
[Playground link](https://deploy-preview-8097--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBnGBPANnAJgOlwEsA3AAwBJgAzCCAXwFojccACYN+skAGhAgAHGEWipkoAIYAnaRADuABRkJxKSVnmSM4-gCNpksAGs4MAMqCjRKAHNkMaQFc4-OAFs9eXHgAykuydJWzgAMQhpd0kYETtkEEknGAg+EAALGHcsAHU0onhUKzA4c1V80nyMeLBUXRAbVDhpGEVDWyjkag1G-gArVAAPACFDEzNzSXc4Xxs4Tu7XEH6B8xtbHABFJwh4eawekCtpRul4vUkvLFTBaRsYbJYYNOQADgAGfhuIRuzDQXibnATiQ5vwAI7beCtIRqBKoRhQOB4PCpaRwCFENGtYIdJBdfaLRruIgOZyEtabSFzPELfgwC4PXBPZAAJjphiIWDWAGEIO5cSAgQBWVJORoAFQuanxBxILgAklAfLBzGBbsIAIJK8yYHB7Rr0ehAA)
```sh
--parser babel
```

**Input:**
```jsx
styled.div`${foo}-idle { }`
```

**Output:**
```jsx
TypeError: Cannot read property 'type' of undefined
    at propagateBreaksOnEnterFn (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:15880:15)
    at traverseDoc (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:15740:13)
    at Object.propagateBreaks (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:15905:5)
    at printAstToDoc (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:16940:16)
    at coreFormat (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:17200:17)
    at format (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:17420:77)
    at formatWithCursor (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:17436:14)
    at https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:33586:14
    at Object.format (https://deploy-preview-8097--prettier.netlify.app/lib/standalone.js:33595:14)
    at formatCode (https://deploy-preview-8097--prettier.netlify.app/worker.js:233:21)
```

Comment (thecodrr) [reply src/language-js/embed.js]: Fixed both of them.

File: src/language-js/embed.js [hunk 2]
```diff
@@ -284,31 +285,42 @@ function replacePlaceholders(quasisDoc, expressionDocs) {
...
+        const placeholderID = placeholderMatch[1];
+        // When the expression has a suffix appended, like:
+        // animation: linear ${time}s ease-out;
+        const suffix = placeholderMatch[2];
+        const expression = expressions[placeholderID];
+        tokens.push("${", expression, "}" + suffix);
+        replaceCounter++;
+      });
+
+      parts.splice(idx + tokensCount, 1, ...tokens);
```
Comment (thorn0) [inline src/language-js/embed.js:319]: The original `doc.parts` must not be modified in a `mapDoc` callback.

File: changelog_unreleased/javascript/pr-8097.md [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+const SingleConcat = styled.div`
+  ${something()}
+  & > ${Child}:not(:first-child) {
+    margin-left: 5px;
+  }
+`;
+
+const MultiConcats = styled.div`
+  ${something()}
+  & > ${Child}:not(:first-child) {
```
Comment (thorn0) [inline changelog_unreleased/javascript/pr-8097.md:53]: It's not the actual output.

Comment (thecodrr) [reply changelog_unreleased/javascript/pr-8097.md]: Fixed both of the issues.

File: src/language-js/embed.js (hunk 2 above)
Comment (thorn0) [inline src/language-js/embed.js:319]: Overall looks good, but the logic can be simplified. Instead of modifying (`splice`ing) the same array repetitively, it would be more straightforward to create an empty array first and add elements to it, wouldn't it?

File: src/language-js/embed.js [hunk 4]
```diff
@@ -267,7 +267,8 @@ function replacePlaceholders(quasisDoc, expressionDocs) {
     if (!doc || !doc.parts || !doc.parts.length) {
       return doc;
     }
-    let { parts } = doc;
+
+    let parts = doc.parts.slice();
```
Comment (fisker) [inline src/language-js/embed.js:271]:
```suggestion
    let parts = [...doc.parts];
```

File: src/language-js/embed.js (hunk 2 above)
Comment (thecodrr) [reply src/language-js/embed.js]: Done.

File: src/language-js/embed.js (hunk 4 above)
Comment (thecodrr) [reply src/language-js/embed.js]: No need anymore.

File: src/language-js/embed.js [hunk 5]
```diff
@@ -316,10 +317,9 @@ function replacePlaceholders(quasisDoc, expressionDocs) {
         replaceCounter++;
       });
 
-      parts.splice(idx + tokensCount, 1, ...tokens);
-      tokensCount += tokens.length - 1;
+      replacedParts.push(...tokens);
```
Comment (thorn0) [inline src/language-js/embed.js:320]: Why is the `tokens` array needed? Why not push directly to `replacedParts`?

Comment (thorn0) [reply src/language-js/embed.js:320]: Also, what if `placeholderMatch === null`?

Comment (thorn0) [reply src/language-js/embed.js]: I think the code can be simplified further if you pass the regex to `split` like it's done in the `printHtmlTemplateLiteral` function in the same file. What do you think?

Comment (thecodrr) [reply src/language-js/embed.js]: Done.

File: src/language-js/embed.js [hunk 6]
```diff
@@ -284,31 +285,32 @@ function replacePlaceholders(quasisDoc, expressionDocs) {
...
+        replacedParts.push(part);
+        return;
+      }
+
+      // When we have multiple placeholders in one line, like:
+      // ${Child}${Child2}:not(:first-child)
+      const components = part.split(/@prettier-placeholder-(\d+)-id/);
+      components.forEach((component, idx) => {
+        // The placeholder is always at odd indices
+        if (idx % 2 === 0 || !component) {
```
Comment (thorn0) [inline src/language-js/embed.js:301]: Why is `|| !component` needed?

Comment (thorn0) [reply src/language-js/embed.js:301]: While you're at it, please remove this unneeded cloning: `const expressions = expressionDocs.slice();`. Seems to be a leftover from something.

Comment (thecodrr) [reply src/language-js/embed.js:301]: `|| !component` is a sanity check. I will remove it..

Okay, will do.

Comment (thecodrr) [reply src/language-js/embed.js]: Done.
