### PR TITLE
fix(cli): validate options for every `config-precedence`

### LINKED ISSUE #2890: Config is only validated when using --config-precedence=cli-override
```
$ prettier --version
1.7.0

$ echo '{"printWidth": 0.5}' > .prettierrc

$ echo 'test' | prettier
Error: Invalid --print-width value.
Expected an integer, but received: 0.5

$ echo 'test' | prettier --config-precedence file-override
test;

$ echo 'test' | prettier --config-precedence prefer-file
test;
```

### PR DESCRIPTION
**Pull request by ikatyang**
Main:

- Fixes #2890

Side:

- before
  - validation errors -> "--trailing-comma ..."
- after
  - validation errors from cli -> "--trailing-comma ..."
  - validation errors from config files -> "trailingComma ..."

### CODE REVIEW

File: src/cli-validator.js [hunk 1]
```diff
@@ -12,18 +12,30 @@ function validateArgv(argv) {
...
 
-function validateIntOption(value, option) {
-  if (!/^\d+$/.test(value)) {
+function getOptionName(type, option) {
+  return type === "cli" ? `--${option.name}` : kebabToCamel(option.name);
+}
+
+function kebabToCamel(str) {
+  return str.replace(/-([a-z])/g, (_, char) => char.toUpperCase());
+}
```
Comment (lydell) [inline src/cli-validator.js]: This is the third copy we have of this function now. `dashify`, on the other hands, comes from npm. Surely Sindre Sorhus must have a kebabToCamel dependency we can use?

File: src/cli-validator.js [hunk 2]
```diff
@@ -12,18 +12,30 @@ function validateArgv(argv) {
...
+
+function validateIntOption(type, value, option) {
+  if (!/^\d+$/.test(value) || (type === "api" && typeof value !== "number")) {
```
Comment (lydell) [inline src/cli-validator.js]: I like how you've really thought things through and found even more edge cases we were missing!

File: src/cli-util.js [hunk 3]
```diff
@@ -574,44 +592,55 @@ function normalizeArgv(rawArgv, options) {
...
   return normalized;
 
+  function getOptionName(option) {
+    return type === "cli" ? `--${option.name}` : kebabToCamel(option.name);
+  }
+
+  function getRedirectName(option, choice) {
+    return type === "cli"
+      ? `--${option.name}=${choice.redirect}`
+      : `{ ${kebabToCamel(option.name)}: ${JSON.stringify(choice.redirect)} }`;
```
Comment (lydell) [inline src/cli-util.js]: Nice tweak.

File: src/cli-validator.js (hunk 1 above)
Comment (ikatyang) [reply src/cli-validator.js]: https://github.com/sindresorhus/camelcase

File: src/cli-util.js [hunk 4]
```diff
@@ -178,11 +180,21 @@ function applyConfigPrecedence(argv, options) {
...
-        return Object.assign({}, parseArgsToOptions(argv), options);
+        return Object.assign(
+          {},
+          parseArgsToOptions(argv),
+          normalizeConfigs("api", options, constant.detailedOptionMap)
+        );
       case "prefer-file":
-        return options || parseArgsToOptions(argv);
+        return (
+          normalizeConfigs("api", options, constant.detailedOptionMap) ||
```
Comment (lydell) [inline src/cli-util.js]: Maybe do `normalizeConfigs` (which I would name `normalizeConfig` btw, because with the "s" it sounds like an array of config objects) in the function that calls `applyConfigPrecedence`? It feels a bit odd that `applyConfigPrecedence` also deals with normalizing config, and then we also get rid of the repetition in each `case` of the `switch`.

File: src/cli-util.js [hunk 5]
```diff
@@ -542,29 +543,36 @@ function groupBy(array, getKey) {
   }, Object.create(null));
 }
 
-function normalizeArgv(rawArgv, options) {
+/** @param {'api' | 'cli'} type */
+function normalizeConfig(type, rawConfigs, options) {
```
Comment (lydell) [inline src/cli-util.js]: Oops, sorry, the "plural confusion" applies to `rawConfigs` as well – I think `rawConfig` would be better ... sorry for all the nitpicks :(
