### PR TITLE
Fixed wrong trailing comma position after comment in scss

### LINKED ISSUE #6920: SCSS: extra comma added to map, before last comment
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKASAtgTwLRYCGADkgAQAU6ZZA5AGYQS3kCMANGQPRdkDCELFgQxqdAEaEATizIAmTj36DhsdAEoA3CHYgIxGAEtoAZ2ShpUiAHcACtIRmUhAG4RDAEx0hxUwmABrOBgAZWJ-QygAc2QYKQBXOF0ACxgsABsAdWTDeBNwsDgQx1zDF1ycZHATM11IkzgpGFs-KKJkekJ0ht0AKxMADwAhP0DgkMJhABlIuA6unpB+gZDIqPS4AEV4iHh57qSQcKkGqSqTMBrvYilImEzPGGTkAA4ABl0biAbMv2Iqm5wU4uOa6ACOO3gLX0ThAhBMeCgcDgHhR3ikcAhhgxLUIbUI+0WDSwhliCUOJjWG22uzmSE6B10MEI4geHieyAUIDihEM6TWAiEBJQUGgoJA8QaABUWU4GYsXIkAJJQVGwEJgW4GACCqpCMBwG0JcAAviagA)
```sh
--parser scss
```

**Input:**
```scss

$my-map: (
  'foo': 1, // Comment
  'bar': 2, // Comment
);
```

**Output:**
```scss
$my-map: (
  "foo": 1,
  // Comment
    "bar": 2,
  //        ^ <----- trailingComma should not printed
  // Comment
);

```

**Expected behavior:**

```scss
$my-map: (
  "foo": 1,
  // Comment
    "bar": 2
  // Comment
);
```

should not print trailingComma

### LINKED ISSUE #16599: Wrong trailing comma position after comment in scss
**Prettier 3.3.3**
Playground doesn't support `scss` it seems

```sh
# Options (if any):
"trailingComma": "es5"
```

**Input:**

```scss
$z-indexes: (
    header: 1035,
    overlay: 1202 // TODO: change to 1050 after bootstrap modals will be removed
);
```

**Output:**

```scss
$z-indexes: (
    header: 1035,
    overlay: 1202 // TODO: change to 1050 after bootstrap modals will be removed,
);
```

**Expected output:**

```scss
$z-indexes: (
    header: 1035,
    overlay: 1202, // TODO: change to 1050 after bootstrap modals will be removed
);
```

**Why?**

It should add a comma to the last item not to the comment. It will also add it endless times, we already have like 5 repeated commas

### PR DESCRIPTION
**Pull request by Ma-hawaj**
## Description

Fixes #16599 
Fixes #6920

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing 
guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-css/print/comma-separated-value-group.js [hunk 1]
```diff
@@ -66,13 +67,19 @@ function printCommaSeparatedValueGroup(path, options, print) {
...
   for (let i = 0; i < node.groups.length; ++i) {
-    parts.push(printed[i]);
-
     const iPrevNode = node.groups[i - 1];
     const iNode = node.groups[i];
     const iNextNode = node.groups[i + 1];
     const iNextNextNode = node.groups[i + 2];
 
+    // if the node is comment and last node print it in a line suffix
+    if (isInlineValueCommentNode(iNode) && iNextNode === undefined) {
```
Comment (fisker) [inline src/language-css/print/comma-separated-value-group.js:76]:
```suggestion
    // If the node is comment and last node print it in a line suffix
    if (isInlineValueCommentNode(iNode) && !iNextNode) {
```

File: tests/format/scss/trailing-comma/trailingComma.scss [hunk 2]
```diff
@@ -0,0 +1,4 @@
+$z-indexes: (
+    header: 1035,
+    overlay: 1202 // The comma shoud be printed before the comment when trailing-comma = es5
+);
```
Comment (fisker) [inline tests/format/scss/trailing-comma/trailingComma.scss:4]:
```suggestion
);

```

**Comment by Ma-hawaj** [comment]
Thanks for the fast response, appreciate it.

**Review by fisker — APPROVED** [review]

File: src/language-css/print/comma-separated-value-group.js [hunk 3]
```diff
@@ -400,6 +407,12 @@ function printCommaSeparatedValueGroup(path, options, print) {
       continue;
     }
 
+    // don't print line when the next node is a comment and last node
+    // it will be printed with the comment in a  linesuffix
```
Comment (dcyriller) [inline src/language-css/print/comma-separated-value-group.js:411]:
```suggestion
    // it will be printed with the comment in a line suffix
```
should resolve the CI issue

**Review by sosukesuzuki — APPROVED** [review]

**Review by sosukesuzuki — CHANGES_REQUESTED** [review]
Oh full tests fail on this change. Please fix it.

You can run full tests by `FULL_TEST=1 yarn test`

**Comment by Ma-hawaj** [comment]
@sosukesuzuki Can you assist me with this ?
what is the difference between normal yarn test and the one you mentioned.
when specifying FULL_TEST=1 the output of the test becomes different and I don't know the reason.
It prints the comment in a new line when in normal test it doesn't and I can't figure out why it does this 

This is the output Doc
```json
{
    "type": "group",
    "contents": {
        "type": "indent",
        "contents": {
            "type": "fill",
            "parts": [
                [
                    [
                        [
                            [
                                [
                                    "",
                                    "overlay"
                                ],
                                {
                                    "type": "group",
                                    "contents": [
                                        ":",
                                        {
                                            "type": "line"
                                        }
                                    ],
                                    "break": false
                                }
                            ],
                            [
                                "1202",
                                ""
                            ]
                        ],
                        {
                            "type": "line-suffix",
                            "contents": [
                                " ",
                                "// The comma shoud be printed before the comment when trailing-comma = es5"
                            ]
                        }
                    ],
                    {
                        "type": "break-parent"
                    }
                ]
            ]
        }
    },
    "break": false
}
```

image

**Comment by sosukesuzuki** [comment]
@Ma-hawaj You can know about the full tests on https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md#deeper-testing

**Comment by Ma-hawaj** [comment]
Seems like there is a bug with the parser it self since if there is a trailing comma it doesn't consider the comment as part of the comma separated group while when there is not it counts it as a part of the comma separated group.
Do we have access to the parser since I saw that it is imported as a node module.

**Comment by fisker** [comment]
Can be related to #16583

**Comment by Ma-hawaj** [comment]
It is now working functionally but the parsing tree a bit different when reparsing so the full test fails.

**Comment by Ma-hawaj** [comment]
Currently it has this weird behavior in the main release code. 
Some times it print the comment in a new line and some times it print it in the same line such as the example below:
Input:
```scss
.simplification {
  foo: (
    calc(), // It is a comment
  );
}

.simplification {
  foo: (
    calc() // not a comment anymore
  );
}

$z-indexes: (
  header: 1035,
  header: 1035,
  overlay: 1202, // TODO
  header: 1035,
  header: 1035,
);
```

Output:
```scss
.simplification {
  foo: (calc(), // It is a comment);
}

.simplification {
  foo: (
    calc() // not a comment anymore
  );
}

$z-indexes: (
  header: 1035,
  header: 1035,
  overlay: 1202,
  // TODO
  header: 1035,
  header: 1035,
);

```

which also breaks the code for the first example.

**Comment by fisker** [comment]
I'm working on it.

File: tests/format/scss/trailing-comma/__snapshots__/format.test.js.snap [hunk 4]
```diff
@@ -190,6 +294,50 @@ a {
...
+  'foo': 1, // Comment
+  'bar': 2, // Comment
+);
+
+=====================================output=====================================
+$my-map: (
+  "foo": 1,
+  // Comment
+  "bar": 2, // Comment
+);
```
Comment (fisker) [inline tests/format/scss/trailing-comma/__snapshots__/format.test.js.snap:314]: This is actually wrong, the first comment should not print on separate line, but it's a different issue, we can deal with it later.

Comment (Ma-hawaj) [reply tests/format/scss/trailing-comma/__snapshots__/format.test.js.snap:314]: OK, I thought it is the default behavior since it was like this in the released version.

**Comment by fisker** [comment]
@Ma-hawaj This should be good enough to merge, but some issues need to be improved. Eg https://github.com/prettier/prettier/pull/16617#discussion_r1794833149 #16743 , and the TODO comment in code.

File: tests/format/scss/trailing-comma/__snapshots__/format.test.js.snap (hunk 4 above)
Comment (fisker) [reply tests/format/scss/trailing-comma/__snapshots__/format.test.js.snap:314]: It's bug, but we don't have a comment attach logic in CSS printer, it's not easy to fix(I guess).

Comment (fisker) [reply tests/format/scss/trailing-comma/__snapshots__/format.test.js.snap:314]: I could be wrong, if we always print comments with other elements instead of a separate element, it should be fixed? Don't know.

**Comment by Ma-hawaj** [comment]
@fisker Thanks for your support.
It was a pleasure contributing to this project.
I hope I could do more of contributions in the future.
