### PR TITLE
Fix unstable comment in binary expression

### LINKED ISSUE #1210: Unstable comment in binary expression
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBZAhjAFgOgLYCWUAFADpQAEFZlVFA9AFQUAkAYgDYQDubBAHqjjEAfAF4ADDgDMADhwSKAZwLwx3DQEoKAWgqceFOACdjEYxQAmceGHiWrAV2NEA5hWxxydKs2sAHLgBPPAQYCggAMwoANyk5BRwKABUIZTg4DyxMkzNjABoKYzg8CBjM7AIlCkg8UNgKdChLbx9mY0dKSK5uCkZ6VqpLCDBHepgcACMISyCcJTAzDg4ACTgCVyxwnUHqbiJh7nnFiGWATQoAagp95p4cIigTNY2tzVbtPWsYlXgAfUiEAg8GMf2yrxg+VaEihUHeUBA+RAEH8MAI0CUyFA6FMPAACjiEJiUOgYhACJZESB0EoYMhIugOEo4EjJsZ0GAANY2ADK-g5bmQMA6LJAwzA9MZzKRRGZxhgePZrjw6ElTNFACslPwAELsrm89ChAAyRDgaulyMcMH81oATEKRUj+cY5cgQJN0JMglwEc6XLAAOoU7DIWQwkD+MzMwPs-zuqNwOXlKnFACOjgIxUV6GVqqQDPVSOZhEdjlFKigrg4cAAio5geaC1LRTAvcHLKGkHakcL0AQOG4AMIQOr5kBQaDmpGOZnJL3EwvMgC+y6AA)

**Input:**
```jsx
Math.min(
  (
    /* $FlowFixMe(>=0.38.0 site=www) - Flow error detected during the
     * deployment of v0.38.0. To see the error, remove this comment and
     * run flow */
    document.body.scrollHeight -
    (window.scrollY + window.innerHeight)
  ) - devsite_footer_height,
  0,
)

```

**Output:**
```jsx
Math.min(
  /* $FlowFixMe(>=0.38.0 site=www) - Flow error detected during the
     * deployment of v0.38.0. To see the error, remove this comment and
     * run flow */
  document.body.scrollHeight -
  (window.scrollY + window.innerHeight) -
    devsite_footer_height,
  0
);

```

**Second Output:**
```jsx
Math.min(
  /* $FlowFixMe(>=0.38.0 site=www) - Flow error detected during the
     * deployment of v0.38.0. To see the error, remove this comment and
     * run flow */
  document.body.scrollHeight -
    (window.scrollY + window.innerHeight) -
    devsite_footer_height,
  0
);

```

### PR DESCRIPTION
**Pull request by thorn0**
Closes #1210

~~Based on #8476, which should be merged first.~~ (done)

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

File: src/language-js/utils.js [hunk 1]
```diff
@@ -408,6 +408,10 @@ function hasTrailingComment(node) {
   return node.comments && node.comments.some((comment) => comment.trailing);
 }
 
+function hasTrailingLineComment(node) {
+  return node.comments && !node.comments.every(handleComments.isBlockComment);
+}
```
Comment (fisker) [inline src/language-js/utils.js:413]: Forgot check `comment.trailing`?

**Comment by thorn0** [comment]
I tried to fix https://github.com/prettier/prettier/issues/7746 too, but that one turned out to be a much more difficult case.
