### PR TITLE
Fix `prettier` installed in a directory not named prettier

### LINKED ISSUE #4637: pre-commit fails to run with prettier with "Cannot read property 'split' of null"
I think this is essentially the same issue as https://github.com/prettier/prettier/issues/4588

prettier fails to run with run with [pre-commit](https://github.com/pre-commit/pre-commit) on master.

This project [ostensibly supports being run via pre-commit](https://github.com/prettier/prettier/blob/master/.pre-commit-hooks.yaml) - until this is fixed, maybe we should remove support? (I'll try take a stab this weekend)

### Repro:
Run the following for a minimal repro
```bash
cd $(mktemp -d)
git init
virtualenv --python=python3.6 venv -q
venv/bin/pip install pre-commit -q
echo "repos:
-   repo: https://github.com/prettier/prettier
    rev: 1.13.4
    hooks:
    -   id: prettier
        name: prettier
        types: ['markdown']" > .pre-commit-config.yaml
echo "bleep bloop" > README.md
venv/bin/pre-commit install -f --install-hooks
venv/bin/pre-commit run prettier --files README.md
```

This produces the following error:
```
╔═ markl@dev21-uswest1cdevc: /tmp/tmp.FOLsd7AHcz git:(master) ✗
╚═ ♪ venv/bin/pre-commit run prettier --files README.md
prettier.................................................................Failed
hookid: prettier

/nail/home/markl/.cache/pre-commit/repoowychjtg/node_modules/find-parent-dir/index.js:10
  var parts = path.split(/(\/|\\)/);
                   ^

TypeError: Cannot read property 'split' of null
    at splitPath (/nail/home/markl/.cache/pre-commit/repoowychjtg/node_modules/find-parent-dir/index.js:10:20)
    at Object.exports.sync [as findParentDir] (/nail/home/markl/.cache/pre-commit/repoowychjtg/node_modules/find-parent-dir/index.js:44:18)
    at loadPlugins (/nail/home/markl/.cache/pre-commit/repoowychjtg/src/common/load-plugins.js:21:36)
    at Object.getSupportInfo (/nail/home/markl/.cache/pre-commit/repoowychjtg/index.js:21:16)
    at updateContextOptions (/nail/home/markl/.cache/pre-commit/repoowychjtg/src/cli/util.js:883:35)
    at pushContextPlugins (/nail/home/markl/.cache/pre-commit/repoowychjtg/src/cli/util.js:916:3)
    at updateContextArgv (/nail/home/markl/.cache/pre-commit/repoowychjtg/src/cli/util.js:927:3)
    at Object.createContext (/nail/home/markl/.cache/pre-commit/repoowychjtg/src/cli/util.js:863:3)
    at Object.run (/nail/home/markl/.cache/pre-commit/repoowychjtg/src/cli/index.js:8:24)
    at Object.<anonymous> (/nail/home/markl/.cache/pre-commit/repoowychjtg/bin/prettier.js:5:23)
```

cc @asottile

### PR DESCRIPTION
**Pull request by asottile**
Resolves #4637 

Verified via:

```bash
git clone git@github.com:prettier/prettier /tmp/wat
cd /tmp/wat
nodeenv nenv
. nenv/bin/activate
npm install -g .
# code was modified here!
prettier --help
```

### CODE REVIEW

**Comment by hawkrives** [comment]
Doesn't that prevent the use of globally installed plugins? Is that a case that needs to be handled?

File: src/common/load-plugins.js [hunk 1]
```diff
@@ -18,10 +18,9 @@ function loadPlugins(plugins, pluginSearchDirs) {
   }
   // unless pluginSearchDirs are provided, auto-load plugins from node_modules that are parent to Prettier
   if (!pluginSearchDirs.length) {
-    const autoLoadDir = thirdParty.findParentDir(
-      thirdParty.findParentDir(__dirname, "prettier"),
-      "node_modules"
```
Comment (ikatyang) [inline src/common/load-plugins.js]: Actually, why don't we just find the parent `"node_modules"`? I don't think it's possible that there's any `"node_modules"` between `__dirname` and `"prettier"`.

cc @kachkaev

Comment (asottile) [reply src/common/load-plugins.js]: that does seem to work for me as well, (verified by editing the installed files to this in a nodeenv with `npm install -g`d `prettier`)
