### PR TITLE
Fix string print

### LINKED ISSUE #18348: [regression] Format complex strings into invalid code
**Prettier 3.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAHSgAnTgFQAsBLAZxwDMSAbOHcnAQwFcYIBaAcwTgCcm8ACYBCHABEIOKBBg4AthCElKATwZzlfOGBg1VAOmx5CU7d14D4OPi1wByVUz64uLGgAccPKP0FwOW1gSeQCiOE9+MntjdFRsbBCPCD45eHkPGn8qPgh5HEwQAAEAIyYSiNR0zP9CgG5EjJS01Q96fCYKOUpc-MLS8sqYVrgyeoSoElh+SiYwegAJCLa+HGBjBSmANSiSaCQcMhg+Ka4G3GYjg4AKAEocAF4APhwYAwAFXK4BeXOcBTgMCYQkETAOS0ifAAsoDgaDzgBfCZwAAeyVSDGmfFm8xwEJWMKBIKBaw2XBoEDKNDIByOJygXAA2gBdP44ClgJjUg4AJR0KSEAB46acADSHY6nFlPNlCOBtKByqBgEijXn8vhCkUM8XapnMmUbVHomAAISmygZAEEyGQSFwoKFYDSJfT9Wzjc0AHJMUK0yUMtlTeAuLkHEoQCB0JhQRETSh2XR7XDhSHXeTbXb7V1iw4QFh8eb+t3i0JE0Hg5b8QlwoG3SuQ0kXbQwAu4ADyJQAVjo3j04HAAF5wa7rC7-DNQHZ8O3QUUbf6dGA3e7PV5wDJZeAGDxfH4GJfXMj5wtwcXAHC70b8ABucAAwnknTAXccWPQEbd5+OAeWgd--k-bAkSgbBPQxC9UxWChOhwOVZncOQEXOSAoCOHAoKidVIE1YUAy4cV8X4F4Hibf4AH1yN3WQIEog4oHcGgAJwVBUEOEhhwOAB2AAGABGABmcUuEHEgvDtTicAAJh4gBWKSNkKOUcNqZAMKrPhrgXAoQC4gw+IMWTCmY-5CgTZUYGTHByOUlJ-GuM8+FFGBRRIW5gBvZwcAgB5yJ4GBxA1QQUjIK0PBIO46hUa43MoFJrk81YoAeHi6igQUSAMOgGRgIg0oAany24fJIRkoGZa4IFuOpEsOB5NPMpNoAc9yIAMKYSEsrkOLgABJNCgWVOAAFE6GfMgHNFJgDAiDcEBfW4EWcr8mAeNrbKsB8slta5yMgLlRnme9trIUa5udI8DCEAx5CYDxdrAbR-DO59ArIR6xPYPhbi-OBqpbNtvPayYupoHrjs6U6xvmiayAMAAxKaZuh50vzaoIIdteGOrIcIZ0uxHpuoSZcaiRbGss6BrP8wKVK+0LwruYA-MBWm7PpsKSAeCnkyZgGXBwOBkNquAHmAWbxsC4nOuTdtNX4JBGUZTAVZAMsiCUFXCmZUVldV6gIiELWQGZHWOtBnr+qOGN5hemGkB55rHPcvXCnVzXVfnfXVRoI3VeZAw4r4Ya5iIa5Haga4YHcvhA5SEOwDDiPrm+4BY4AawtB5s5gAAyXPjYgAB3UDVez+qdyyeZn3z3LyCuuBia2yG7dgSbvqWuuyEW5zSG7pbzZIbrh0xqHzpfB3E0pyPnY8ryYAeOAd1ydhhjaOpXbVwENb94zjYN33jYDoOE6TqfebctO4+D0Pw-P5rU9qnzY5qav5qiygU4MTPFXLkh860qra2lkwDG3LhAAAPhA421FV4jDAdnKq7larJWNsAkgoCy6IIAPxwCQDAOoXcG5N1Hq3GA1woCig7p3PuPcu493glMZutoyGTwsrzWetUF6xzlO9E4Hgvof0AWZH2u8QDlwzhaZBXkuax0HsPfghCxYIBYKEAQJQ6D4JmgxNR5Q6CiiLicIEGi8FvEMZ1PRZ5ULUDcOozRbxrH2gLJY0UnkaDviQDeCAJAhA4B4n-bBXifF+KQJlTkNAaAtQRAiTsPZdDEKYZ8CAKxhjt2-nAVQy0lobX8KPNhTUZ5UOkasBeLJXIPDKT5YA6CwCKx1rA2QIw6mimLlAOpyFopLxPrfZOf1gBEOBEIMh7wq7j0mlVGh5BfrX1PnfdhTt3LRREORIgnQ2ZWBCi1W4-NcBvA8CwXGLUapeT4A8IhOT4BkPGdVPZByw6xwlvNL8tzcYHg8JkVQUcqEzRRMcToX5Mr7NeXdD5MVvnS1JjOOhtDRQiG+js8WKMJ4uQhXjGkJBhZeWSucoK8BHwDVsLoeKLlvp1B2QwHcdy3mgpIKKKAgccZoq-PS1FUQHi0qgEtQZwzRnPnydPduy056rFkYyJer9x6siWXnXOHA+IiGzplC0qJ2yfyXunDJP1cq5CLtIOAuqCAjGGnwXImljbiBYJkDB-hfGPNgDgYRIB8rqoyflY2tx3VRUpYcl1qgGG4pGki-lHCinACDgleeFSzZRpaYvBudMQp0rWllBAXBcpyrSk8FKaUOAcGKXVPgYrK5zElXUOGZArXzEusqlEqqHLpL9aKPi1VaqrSIT0PIZC3ofQEfFP6ooaBnL7gYdgZDsYkzxsNX5AgJrXB4i0sqzJbjXCYLcKBq66iixoMjcevd67cqRSMktz525fm3ayvg+dAV3OuOexl-AW1eTAA8bdqI-lkCEWAdy4baoeGzR4QUYAU05Tyh4QqtwBlCCGYe3l81rhgEZB4HWpKXlEGpfoL5X7okIrtcuM8F70WijfTO-B0TRQXIfNAOkLAiV8GDU7UNP7I1lNkcBtNRAM0kCzalEgub80+Xbb0Ue3b+FfRakmoh7BhOHVE-FOdVDGQkCXZVNdECqpCKCb4niCqHgsvvZe3OqGKEMonQ+1x3itM6fpbh7u4tdM7vGnUJjqwyDZrIIKJe2V2MZrIOB5zzAHi+b4nUJgHm2O5RC+BzpjIyABw1aocucBGRMDixk-OSXYvFrfrARLyWA4SufBBogOq9UGqNSa+K5rLVg05MIQWSKHXG2dTF1Lqg3Wqw9R17DgI2yIvHjSfD+maQwDIx2+QXaZOfRSPRme+bTnAB-kIJA6qLSini8thtooCvzQ29t2A5HJu9ro0vXhPavrIXJbE3sCTfBJJSZ8pyABlVQ8gIzbvYI9-CBAmAETnu4vB5rDtfWNqKRxtjLFIBEDxT8XsRGGwQXGxbAC5EgyHmDYcpyl7yPR2ZvgncIATb4VNmcM2WrAGippvxOm-rkvYFaE1TBPl-RundOZBSye1VOZJgnSKRPE6ObT4dygyBcgpEXO7-BUlnn3vpkHxsrS4Fw3BIHKR3V7rhsL0XxcJepCZ7DkAxHOhy9Vgr+r49ldE6O2rvH6u6E8-Hnzo7pO+mc8RxadrhRjZCONu7MROmDMy-h6rf3RWSu+DK20Y1prrj2FN0r07sm+Ba0wPYCg38LSXlyPdhQBy5AVEFp1PGBRVa++Nt5VYgfD6exwCUNgzBlcJtWI9OANrmCK4awn4nOAi6F5wOnxUxfCj2HynwfKMRVb2EfSUs5EAdfDAANIZPrfFgFca9swA9yAL30U0FAhAcbHT-8C6qwaWvOAB-FX50LiXC-7LQ-F1K4Qcr0fY-t-N53q3WtU99-X5n5Jkv1B5Bc8a96BoBQDKBB8QAakQdIDT94FVZy9IDWkYDa85AmAG92YUgcBm9W8YwzdnwLczssCe9cof9YN7VjZh8SAx9KCp9vI40P9BFzlyAtdxcs8ADJpjYbNjdCg48O8Vck8OtjkkoxZFskAnJ1sXJ19QkDtLcvokArt4lIZ7RI5gAloJkyUesXBK8-ds4+BsFmCRcIltd2DddODVZscepBC94Tdfwd5CDE93UkAo4hcWDjC2D-8zCIB9d-IeCQBiB6BqJs9GCsCIAID0CD5fEQjrCQBnlXCjCxc59PlvC0FAQ-CAi-9giBDvJwiqBREHDic1dDDWCkjKp9c3F3x0jwhMiACCijscj69Ii6jgcOs6VgYZYFFMd2iLYMdmV8cx19Mp131ncY4tCoA+s+VudCciDNJ+0L0kByJklp4uR7xRdLFSjpdvZTMYjfpp1Oh8Fh1R1ecBCJol5Dd+4loxtpM5Dptek5tRCLQkBjYwAToQcbMNtbp7pBNO1jibinJ6ELsxicBFC3hGFbtTDUknsXs3sR0IBPs3RvtfsKiAdVZHcWjjIwdnETFIdocvwbcpMTo0Tbj75ZthUbA3dFRN9t9P5njXjg89D79dVw8n9I8KtNJY9sCTpmjVcv809Fsajdcc90J89aTIYUC690CLksCcC6t0CXjIZuTVgSCiA+9+TKCR8aCJ8bl4iSiIS9djZ4s-CrROSFToiiidT3CNj9d18jSTTbRFTzT65NdLS9TzClIBDbT5T7SzTWjiiXTPCpd9dLCMdPSuSfTCg4inS3DEjXTNjChzjQzTSPShCuFfIljkwVi1iTErSZdtjPUcMkVhtDj7dXoTj60bMvx5iRsloMYTpx1yA0VndGN4pUzUoYBBRY4vMIsN8ioySuZ5NC0YBlM-oNMLMqdFVFkaT9YSSL8z8wiGBGTH9DVWTo9jZ6zIUKAgD0JyU5SqM3xaMjAhDRYMUERyUhZyNoyTCAzVAmz-jJyEoxztNs4ks+Al1tUH9mTlyRo2So5N9sCYx7A5BVk7x69DzCgNSy8giACwLYjolNDWwBYhYI5rIZTA0HcBCOcTlnIZ8kjF8mcG1qofdt4PZChEt+8hBsF5tkSNtkSDEjEIcodQdoAbEsTNFGKVFdFsSRA+IEQnjVZfCsEKSKL5t-IaKuR3wmKoAWK7E8F2KdE-AuKeK+LCgyA0jBKVtFRKKxZVK8MDBaLMSZKcSiN5LDLuLeKdCEcNKhBkcxYDKGL51zFjE2L50OKFLnLPxhCGAHjFRlKQBIjLLyLsELLVZfLS9PZJCttyDdKakgqgE98MFjZfL-L1LArr9S5ChfK4C2gQdojxDASELFd41MCZwAFMopSZwGDcUQovxgrSLnzyLSrui0crC41kSAUERkK9oIADp3o4AABxQEEMR7Qa-gU9DyR86nBuP4gwfySiqamYmawESq6a0SnhAQgwHS5ahanSjqkklC7qugXq0hQssnfzU5FjMgR7X0NC58bmEksnHZIi3KEi8ReqpHXOX1cBBtdLLLceL69fTubNdszzVNbs8DPs2NJLIc73EvYisRL696mKCuYmIQGKS666shH6W4aKcicgcQUEIkzSdaAQ1TXGsgfGoEQmmKeaxPH6cnT+FZNZKq-GKqKBRm8m5miaNyRc5kvkSgfgBAW2H8qrStVvX3CgR1fKNqeLTfe4TkKAQCkAjAzaa6T1MqgQ5NaIhECIVS+m3aVZDmxvCaJBPW9m9ZYKfGbm98pk-VHAPmgWoaKPSrVEzm-8hWvPQI0ZXxKmZQSgfm7Qe1OYeYW0EKbvXvIOV4aokXUIAU4YRrVWKWhtWWmC6qdWo2zWzmhELqnq+YAamAIakaom1yRaHW+gF+G9CZclPHTqg282+mB6oEk7Tmn68quGLsogXa+ZXAMmimpgKmvpclSnJ8xefOEQB84Jfxeq5E-OIesixyyxcmPaxYgRDMmgVYiJdY2M0NVMl8qVT+IenTGVfeGc+kuciA6Oa2pc5-Z2woKdNoXQOAXxcfcC0fSg14KQfPCIk+iM+CwGEbPeH8f4f4McIBoB8kSkLkF0ZWEAEEvefw6+pPEAecEAZ7V7KMOB+2gOoW01bWEyIBjkSBg4dYEAGyANDK6BiMIQQwHidqI2E2ZBlmAKTmzmchwoShwwAyHxOB9hgwGhnhnhmh5SLIKwZMOGGh82AwcJOgc-JBthpQDhgwfh+R3hn5K8W0ZMFNSgGAXBwoPaJ6S5X4mY1hkAHhqSWh7h5Rvh5R0x+NYRwQUR-Sbog8PgNwcaFR5wVxmGdxlx1RLxniHRkh-aQ63Owu4a-O-gYxnhgScx2Rkx5RgAFkUescsaSaodSYUdQlUoAEd3xYADwaAQwoB-B0nHHjRtB1HoBJHRcBwAns7gnmEx5xpImEmYnkGBGSmbGhHnB7GqNHGJGPHfHnQVGpGan6HdHa7Obmm0nZJWm5G0mDIlH5nbHunp4xGnGoLUhVQ4ZEnkSOnlGDJ4AjhVHynZw0JHGBm3GrG0n2nDm3gLn5oqmIlRm2mWnFnqG9mlnMm4AcmHmvmfm8mbnRg3g6AtHHnpGLG0nEm3mVHoWDI-ncmHEqNvmEWSmaHbmDATguAiAHFqmZGXnIWPn3nYXJGkX-m7mCn+AintxAWjmRm8W5nDAoXkm0mrnDAeG4XSWUWuRCnin2n4WHmaWcWnmZGdZdG8aCaPTkAKHlGAA2WZuJgl6F1lkpjltCZFh59FkFoV8F2Jnhpl65lJ4l-lvJ9FzF7FsF0Z0Vkh9M6ATMje7MvUqZwwPSLh3V-ZwlxxrpkR3p8RkGZeAMrZ-SAyXZpV5xzxvJjZyyUYRx3ZuliFhR4lr1nps531zqf1lJQNwSPS8SpeaF6JpN1ZlRiRuNk2JabSf4cCM0C0U4G0O0B0caA4MpctwWNEb0a6g4XRijAB0B-4OUBUJUFUNUUkEAOnBnVQJ1xxxNnQOxwt1NvZCEwNgATmzf+w9ZoeNbuZ8efAtaXkpDiW1cteQfYFwoyQnYWeZYUYLYcbnfTcl0zZoZDYvYMDMavZ9acZLfxcMDMdDdfbOc4b9ZLeZDLcAcxB5ZoAOFmGpGlx-BAlMguBqs5WwCQZABtbQmQFAGcB1XeGcAQDIGQBAC5CLkZzw9FBMYEDAA1RgCutCAABkmFkBIPVLSO93ewAB1AQDwfDtR28OAZDkocjyjx7DwOYU4ZAN8M8KAjcEgMT2wCT40fgEIeaLkdsFYC294CAO0aefDhAIQZD+Tk4Z8LkAgSl5wLZhjyBiTu0BkOgAARRYFkF44dgs9I67DIBREe1OFs-s-gHM6g9I5yYc7uzw5QE6A4F8EfsfuQ7+VoFOEfHkFunw9F2Q6s-JDgCtHzpOFQLgHeH4Do98F86Y5AGxfkBoFY9IEOeE-mGGrQhlhvE6lUHw7AFtGQ5vHfH6iVCo7OwVyEE+1UDoAK4k+olUvY7ui4-KZ4+Q6mFUtSE+B+wS6c785AGE5nH4Hw7KAqBoA4BfGQ93GDFY58VymQAAA550QBtAcmSBtBZuuB5vGOJPjF9uhBDukApJSODk4BvsShgu7vSONwKgoNH6aOYw3Afs4B4YUhbp87ROQu2AIAQBokgA)

```sh
# Options (if any):
--single-quote
```

**Input:**

```ts
/*
 * This file is auto-generated! Do not modify it directly.
 * To re-generate run 'yarn gulp generate-runtime-helpers'
 */

import template from "@babel/template";
import type * as t from "@babel/types";

interface Helper {
  minVersion: string;
  ast: () => t.Program;
  metadata: HelperMetadata;
}

export interface HelperMetadata {
  globals: string[];
  locals: Record<string, string[]>;
  dependencies: Record<string, string[]>;
  exportBindingAssignments: string[];
  exportName: string;
  internal: boolean;
}

function helper(minVersion: string, source: string, metadata: HelperMetadata): Helper {
  return Object.freeze({
    minVersion,
    ast: () => template.program.ast(source, { preserveComments: true }),
    metadata,
  })
}

export { helpers as default };
const helpers: Record<string, Helper> = {
  __proto__: null,
  // size: 7013, gzip size: 2052
  "decorate": helper(
    "7.1.5",
    "function _decorate(e,r,t,i){var o=_getDecoratorsApi();if(i)for(var n=0;n<i.length;n++)o=i[n](o);var s=r(function(e){o.initializeInstanceElements(e,a.elements)},t),a=o.decorateClass(_coalesceClassElements(s.d.map(_createElementDescriptor)),e);return o.initializeClassElements(s.F,a.elements),o.runClassFinishers(s.F,a.finishers)}function _getDecoratorsApi(){_getDecoratorsApi=function(){return e};var e={elementsDefinitionOrder:[[\"method\"],[\"field\"]],initializeInstanceElements:function(e,r){[\"method\",\"field\"].forEach(function(t){r.forEach(function(r){r.kind===t&&\"own\"===r.placement&&this.defineClassElement(e,r)},this)},this)},initializeClassElements:function(e,r){var t=e.prototype;[\"method\",\"field\"].forEach(function(i){r.forEach(function(r){var o=r.placement;if(r.kind===i&&(\"static\"===o||\"prototype\"===o)){var n=\"static\"===o?e:t;this.defineClassElement(n,r)}},this)},this)},defineClassElement:function(e,r){var t=r.descriptor;if(\"field\"===r.kind){var i=r.initializer;t={enumerable:t.enumerable,writable:t.writable,configurable:t.configurable,value:void 0===i?void 0:i.call(e)}}Object.defineProperty(e,r.key,t)},decorateClass:function(e,r){var t=[],i=[],o={static:[],prototype:[],own:[]};if(e.forEach(function(e){this.addElementPlacement(e,o)},this),e.forEach(function(e){if(!_hasDecorators(e))return t.push(e);var r=this.decorateElement(e,o);t.push(r.element),t.push.apply(t,r.extras),i.push.apply(i,r.finishers)},this),!r)return{elements:t,finishers:i};var n=this.decorateConstructor(t,r);return i.push.apply(i,n.finishers),n.finishers=i,n},addElementPlacement:function(e,r,t){var i=r[e.placement];if(!t&&-1!==i.indexOf(e.key))throw new TypeError(\"Duplicated element (\"+e.key+\")\");i.push(e.key)},decorateElement:function(e,r){for(var t=[],i=[],o=e.decorators,n=o.length-1;n>=0;n--){var s=r[e.placement];s.splice(s.indexOf(e.key),1);var a=this.fromElementDescriptor(e),l=this.toElementFinisherExtras((0,o[n])(a)||a);e=l.element,this.addElementPlacement(e,r),l.finisher&&i.push(l.finisher);var c=l.extras;if(c){for(var p=0;p<c.length;p++)this.addElementPlacement(c[p],r);t.push.apply(t,c)}}return{element:e,finishers:i,extras:t}},decorateConstructor:function(e,r){for(var t=[],i=r.length-1;i>=0;i--){var o=this.fromClassDescriptor(e),n=this.toClassDescriptor((0,r[i])(o)||o);if(void 0!==n.finisher&&t.push(n.finisher),void 0!==n.elements){e=n.elements;for(var s=0;s<e.length-1;s++)for(var a=s+1;a<e.length;a++)if(e[s].key===e[a].key&&e[s].placement===e[a].placement)throw new TypeError(\"Duplicated element (\"+e[s].key+\")\")}}return{elements:e,finishers:t}},fromElementDescriptor:function(e){var r={kind:e.kind,key:e.key,placement:e.placement,descriptor:e.descriptor};return Object.defineProperty(r,Symbol.toStringTag,{value:\"Descriptor\",configurable:!0}),\"field\"===e.kind&&(r.initializer=e.initializer),r},toElementDescriptors:function(e){if(void 0!==e)return toArray(e).map(function(e){var r=this.toElementDescriptor(e);return this.disallowProperty(e,\"finisher\",\"An element descriptor\"),this.disallowProperty(e,\"extras\",\"An element descriptor\"),r},this)},toElementDescriptor:function(e){var r=e.kind+\"\";if(\"method\"!==r&&\"field\"!==r)throw new TypeError('An element descriptor\\'s .kind property must be either \"method\" or \"field\", but a decorator created an element descriptor with .kind \"'+r+'\"');var t=toPropertyKey(e.key),i=e.placement+\"\";if(\"static\"!==i&&\"prototype\"!==i&&\"own\"!==i)throw new TypeError('An element descriptor\\'s .placement property must be one of \"static\", \"prototype\" or \"own\", but a decorator created an element descriptor with .placement \"'+i+'\"');var o=e.descriptor;this.disallowProperty(e,\"elements\",\"An element descriptor\");var n={kind:r,key:t,placement:i,descriptor:Object.assign({},o)};return\"field\"!==r?this.disallowProperty(e,\"initializer\",\"A method descriptor\"):(this.disallowProperty(o,\"get\",\"The property descriptor of a field descriptor\"),this.disallowProperty(o,\"set\",\"The property descriptor of a field descriptor\"),this.disallowProperty(o,\"value\",\"The property descriptor of a field descriptor\"),n.initializer=e.initializer),n},toElementFinisherExtras:function(e){return{element:this.toElementDescriptor(e),finisher:_optionalCallableProperty(e,\"finisher\"),extras:this.toElementDescriptors(e.extras)}},fromClassDescriptor:function(e){var r={kind:\"class\",elements:e.map(this.fromElementDescriptor,this)};return Object.defineProperty(r,Symbol.toStringTag,{value:\"Descriptor\",configurable:!0}),r},toClassDescriptor:function(e){var r=e.kind+\"\";if(\"class\"!==r)throw new TypeError('A class descriptor\\'s .kind property must be \"class\", but a decorator created a class descriptor with .kind \"'+r+'\"');this.disallowProperty(e,\"key\",\"A class descriptor\"),this.disallowProperty(e,\"placement\",\"A class descriptor\"),this.disallowProperty(e,\"descriptor\",\"A class descriptor\"),this.disallowProperty(e,\"initializer\",\"A class descriptor\"),this.disallowProperty(e,\"extras\",\"A class descriptor\");var t=_optionalCallableProperty(e,\"finisher\");return{elements:this.toElementDescriptors(e.elements),finisher:t}},runClassFinishers:function(e,r){for(var t=0;t<r.length;t++){var i=(0,r[t])(e);if(void 0!==i){if(\"function\"!=typeof i)throw new TypeError(\"Finishers must return a constructor.\");e=i}}return e},disallowProperty:function(e,r,t){if(void 0!==e[r])throw new TypeError(t+\" can't have a .\"+r+\" property.\")}};return e}function _createElementDescriptor(e){var r,t=toPropertyKey(e.key);\"method\"===e.kind?r={value:e.value,writable:!0,configurable:!0,enumerable:!1}:\"get\"===e.kind?r={get:e.value,configurable:!0,enumerable:!1}:\"set\"===e.kind?r={set:e.value,configurable:!0,enumerable:!1}:\"field\"===e.kind&&(r={configurable:!0,writable:!0,enumerable:!0});var i={kind:\"field\"===e.kind?\"field\":\"method\",key:t,placement:e.static?\"static\":\"field\"===e.kind?\"own\":\"prototype\",descriptor:r};return e.decorators&&(i.decorators=e.decorators),\"field\"===e.kind&&(i.initializer=e.value),i}function _coalesceGetterSetter(e,r){void 0!==e.descriptor.get?r.descriptor.get=e.descriptor.get:r.descriptor.set=e.descriptor.set}function _coalesceClassElements(e){for(var r=[],isSameElement=function(e){return\"method\"===e.kind&&e.key===o.key&&e.placement===o.placement},t=0;t<e.length;t++){var i,o=e[t];if(\"method\"===o.kind&&(i=r.find(isSameElement)))if(_isDataDescriptor(o.descriptor)||_isDataDescriptor(i.descriptor)){if(_hasDecorators(o)||_hasDecorators(i))throw new ReferenceError(\"Duplicated methods (\"+o.key+\") can't be decorated.\");i.descriptor=o.descriptor}else{if(_hasDecorators(o)){if(_hasDecorators(i))throw new ReferenceError(\"Decorators can't be placed on different accessors with for the same property (\"+o.key+\").\");i.decorators=o.decorators}_coalesceGetterSetter(o,i)}else r.push(o)}return r}function _hasDecorators(e){return e.decorators&&e.decorators.length}function _isDataDescriptor(e){return void 0!==e&&!(void 0===e.value&&void 0===e.writable)}function _optionalCallableProperty(e,r){var t=e[r];if(void 0!==t&&\"function\"!=typeof t)throw new TypeError(\"Expected '\"+r+\"' to be a function\");return t}",
        {
      globals: ["Object","TypeError","Symbol","ReferenceError"],
      locals: {"_decorate":["body.0.id"],"_getDecoratorsApi":["body.1.id","body.0.body.body.0.declarations.0.init.callee","body.1.body.body.0.expression.left"],"_createElementDescriptor":["body.2.id","body.0.body.body.2.declarations.1.init.arguments.0.arguments.0.arguments.0"],"_coalesceGetterSetter":["body.3.id","body.4.body.body.0.body.body.1.consequent.alternate.body.1.expression.callee"],"_coalesceClassElements":["body.4.id","body.0.body.body.2.declarations.1.init.arguments.0.callee"],"_hasDecorators":["body.5.id","body.1.body.body.1.declarations.0.init.properties.4.value.body.body.1.test.expressions.1.arguments.0.body.body.0.test.argument.callee","body.4.body.body.0.body.body.1.consequent.consequent.body.0.test.left.callee","body.4.body.body.0.body.body.1.consequent.consequent.body.0.test.right.callee","body.4.body.body.0.body.body.1.consequent.alternate.body.0.test.callee","body.4.body.body.0.body.body.1.consequent.alternate.body.0.consequent.body.0.test.callee"],"_isDataDescriptor":["body.6.id","body.4.body.body.0.body.body.1.consequent.test.left.callee","body.4.body.body.0.body.body.1.consequent.test.right.callee"],"_optionalCallableProperty":["body.7.id","body.1.body.body.1.declarations.0.init.properties.11.value.body.body.0.argument.properties.1.value.callee","body.1.body.body.1.declarations.0.init.properties.13.value.body.body.3.declarations.0.init.callee"]},
      exportBindingAssignments: [],
      exportName: "_decorate",
      dependencies: {"toArray":["body.1.body.body.1.declarations.0.init.properties.9.value.body.body.0.consequent.argument.callee.object.callee"],"toPropertyKey":["body.1.body.body.1.declarations.0.init.properties.10.value.body.body.2.declarations.0.init.callee","body.2.body.body.0.declarations.1.init.callee"]},
      internal: false,
    }
  
  ),
}

```

**Output:**

```ts
/*
 * This file is auto-generated! Do not modify it directly.
 * To re-generate run 'yarn gulp generate-runtime-helpers'
 */

import template from "@babel/template";
import type * as t from "@babel/types";

interface Helper {
  minVersion: string;
  ast: () => t.Program;
  metadata: HelperMetadata;
}

export interface HelperMetadata {
  globals: string[];
  locals: Record<string, string[]>;
  dependencies: Record<string, string[]>;
  exportBindingAssignments: string[];
  exportName: string;
  internal: boolean;
}

function helper(
  minVersion: string,
  source: string,
  metadata: HelperMetadata,
): Helper {
  return Object.freeze({
    minVersion,
    ast: () => template.program.ast(source, { preserveComments: true }),
    metadata,
  });
}

export { helpers as default };
const helpers: Record<string, Helper> = {
  __proto__: null,
  // size: 7013, gzip size: 2052
  decorate: helper(
    "7.1.5",
    'function _decorate(e,r,t,i){var o=_getDecoratorsApi();if(i)for(var n=0;n<i.length;n++)o=i[n](o);var s=r(function(e){o.initializeInstanceElements(e,a.elements)},t),a=o.decorateClass(_coalesceClassElements(s.d.map(_createElementDescriptor)),e);return o.initializeClassElements(s.F,a.elements),o.runClassFinishers(s.F,a.finishers)}function _getDecoratorsApi(){_getDecoratorsApi=function(){return e};var e={elementsDefinitionOrder:[["method"],["field"]],initializeInstanceElements:function(e,r){["method","field"].forEach(function(t){r.forEach(function(r){r.kind===t&&"own"===r.placement&&this.defineClassElement(e,r)},this)},this)},initializeClassElements:function(e,r){var t=e.prototype;["method","field"].forEach(function(i){r.forEach(function(r){var o=r.placement;if(r.kind===i&&("static"===o||"prototype"===o)){var n="static"===o?e:t;this.defineClassElement(n,r)}},this)},this)},defineClassElement:function(e,r){var t=r.descriptor;if("field"===r.kind){var i=r.initializer;t={enumerable:t.enumerable,writable:t.writable,configurable:t.configurable,value:void 0===i?void 0:i.call(e)}}Object.defineProperty(e,r.key,t)},decorateClass:function(e,r){var t=[],i=[],o={static:[],prototype:[],own:[]};if(e.forEach(function(e){this.addElementPlacement(e,o)},this),e.forEach(function(e){if(!_hasDecorators(e))return t.push(e);var r=this.decorateElement(e,o);t.push(r.element),t.push.apply(t,r.extras),i.push.apply(i,r.finishers)},this),!r)return{elements:t,finishers:i};var n=this.decorateConstructor(t,r);return i.push.apply(i,n.finishers),n.finishers=i,n},addElementPlacement:function(e,r,t){var i=r[e.placement];if(!t&&-1!==i.indexOf(e.key))throw new TypeError("Duplicated element ("+e.key+")");i.push(e.key)},decorateElement:function(e,r){for(var t=[],i=[],o=e.decorators,n=o.length-1;n>=0;n--){var s=r[e.placement];s.splice(s.indexOf(e.key),1);var a=this.fromElementDescriptor(e),l=this.toElementFinisherExtras((0,o[n])(a)||a);e=l.element,this.addElementPlacement(e,r),l.finisher&&i.push(l.finisher);var c=l.extras;if(c){for(var p=0;p<c.length;p++)this.addElementPlacement(c[p],r);t.push.apply(t,c)}}return{element:e,finishers:i,extras:t}},decorateConstructor:function(e,r){for(var t=[],i=r.length-1;i>=0;i--){var o=this.fromClassDescriptor(e),n=this.toClassDescriptor((0,r[i])(o)||o);if(void 0!==n.finisher&&t.push(n.finisher),void 0!==n.elements){e=n.elements;for(var s=0;s<e.length-1;s++)for(var a=s+1;a<e.length;a++)if(e[s].key===e[a].key&&e[s].placement===e[a].placement)throw new TypeError("Duplicated element ("+e[s].key+")")}}return{elements:e,finishers:t}},fromElementDescriptor:function(e){var r={kind:e.kind,key:e.key,placement:e.placement,descriptor:e.descriptor};return Object.defineProperty(r,Symbol.toStringTag,{value:"Descriptor",configurable:!0}),"field"===e.kind&&(r.initializer=e.initializer),r},toElementDescriptors:function(e){if(void 0!==e)return toArray(e).map(function(e){var r=this.toElementDescriptor(e);return this.disallowProperty(e,"finisher","An element descriptor"),this.disallowProperty(e,"extras","An element descriptor"),r},this)},toElementDescriptor:function(e){var r=e.kind+"";if("method"!==r&&"field"!==r)throw new TypeError(\'An element descriptor\\'s .kind property must be either "method" or "field", but a decorator created an element descriptor with .kind "\'+r+\'"\');var t=toPropertyKey(e.key),i=e.placement+"";if("static"!==i&&"prototype"!==i&&"own"!==i)throw new TypeError(\'An element descriptor\\'s .placement property must be one of "static", "prototype" or "own", but a decorator created an element descriptor with .placement "\'+i+\'"\');var o=e.descriptor;this.disallowProperty(e,"elements","An element descriptor");var n={kind:r,key:t,placement:i,descriptor:Object.assign({},o)};return"field"!==r?this.disallowProperty(e,"initializer","A method descriptor"):(this.disallowProperty(o,"get","The property descriptor of a field descriptor"),this.disallowProperty(o,"set","The property descriptor of a field descriptor"),this.disallowProperty(o,"value","The property descriptor of a field descriptor"),n.initializer=e.initializer),n},toElementFinisherExtras:function(e){return{element:this.toElementDescriptor(e),finisher:_optionalCallableProperty(e,"finisher"),extras:this.toElementDescriptors(e.extras)}},fromClassDescriptor:function(e){var r={kind:"class",elements:e.map(this.fromElementDescriptor,this)};return Object.defineProperty(r,Symbol.toStringTag,{value:"Descriptor",configurable:!0}),r},toClassDescriptor:function(e){var r=e.kind+"";if("class"!==r)throw new TypeError(\'A class descriptor\\'s .kind property must be "class", but a decorator created a class descriptor with .kind "\'+r+\'"\');this.disallowProperty(e,"key","A class descriptor"),this.disallowProperty(e,"placement","A class descriptor"),this.disallowProperty(e,"descriptor","A class descriptor"),this.disallowProperty(e,"initializer","A class descriptor"),this.disallowProperty(e,"extras","A class descriptor");var t=_optionalCallableProperty(e,"finisher");return{elements:this.toElementDescriptors(e.elements),finisher:t}},runClassFinishers:function(e,r){for(var t=0;t<r.length;t++){var i=(0,r[t])(e);if(void 0!==i){if("function"!=typeof i)throw new TypeError("Finishers must return a constructor.");e=i}}return e},disallowProperty:function(e,r,t){if(void 0!==e[r])throw new TypeError(t+" can\'t have a ."+r+" property.")}};return e}function _createElementDescriptor(e){var r,t=toPropertyKey(e.key);"method"===e.kind?r={value:e.value,writable:!0,configurable:!0,enumerable:!1}:"get"===e.kind?r={get:e.value,configurable:!0,enumerable:!1}:"set"===e.kind?r={set:e.value,configurable:!0,enumerable:!1}:"field"===e.kind&&(r={configurable:!0,writable:!0,enumerable:!0});var i={kind:"field"===e.kind?"field":"method",key:t,placement:e.static?"static":"field"===e.kind?"own":"prototype",descriptor:r};return e.decorators&&(i.decorators=e.decorators),"field"===e.kind&&(i.initializer=e.value),i}function _coalesceGetterSetter(e,r){void 0!==e.descriptor.get?r.descriptor.get=e.descriptor.get:r.descriptor.set=e.descriptor.set}function _coalesceClassElements(e){for(var r=[],isSameElement=function(e){return"method"===e.kind&&e.key===o.key&&e.placement===o.placement},t=0;t<e.length;t++){var i,o=e[t];if("method"===o.kind&&(i=r.find(isSameElement)))if(_isDataDescriptor(o.descriptor)||_isDataDescriptor(i.descriptor)){if(_hasDecorators(o)||_hasDecorators(i))throw new ReferenceError("Duplicated methods ("+o.key+") can\'t be decorated.");i.descriptor=o.descriptor}else{if(_hasDecorators(o)){if(_hasDecorators(i))throw new ReferenceError("Decorators can\'t be placed on different accessors with for the same property ("+o.key+").");i.decorators=o.decorators}_coalesceGetterSetter(o,i)}else r.push(o)}return r}function _hasDecorators(e){return e.decorators&&e.decorators.length}function _isDataDescriptor(e){return void 0!==e&&!(void 0===e.value&&void 0===e.writable)}function _optionalCallableProperty(e,r){var t=e[r];if(void 0!==t&&"function"!=typeof t)throw new TypeError("Expected \'"+r+"\' to be a function");return t}',
    {
      globals: ["Object", "TypeError", "Symbol", "ReferenceError"],
      locals: {
        _decorate: ["body.0.id"],
        _getDecoratorsApi: [
          "body.1.id",
          "body.0.body.body.0.declarations.0.init.callee",
          "body.1.body.body.0.expression.left",
        ],
        _createElementDescriptor: [
          "body.2.id",
          "body.0.body.body.2.declarations.1.init.arguments.0.arguments.0.arguments.0",
        ],
        _coalesceGetterSetter: [
          "body.3.id",
          "body.4.body.body.0.body.body.1.consequent.alternate.body.1.expression.callee",
        ],
        _coalesceClassElements: [
          "body.4.id",
          "body.0.body.body.2.declarations.1.init.arguments.0.callee",
        ],
        _hasDecorators: [
          "body.5.id",
          "body.1.body.body.1.declarations.0.init.properties.4.value.body.body.1.test.expressions.1.arguments.0.body.body.0.test.argument.callee",
          "body.4.body.body.0.body.body.1.consequent.consequent.body.0.test.left.callee",
          "body.4.body.body.0.body.body.1.consequent.consequent.body.0.test.right.callee",
          "body.4.body.body.0.body.body.1.consequent.alternate.body.0.test.callee",
          "body.4.body.body.0.body.body.1.consequent.alternate.body.0.consequent.body.0.test.callee",
        ],
        _isDataDescriptor: [
          "body.6.id",
          "body.4.body.body.0.body.body.1.consequent.test.left.callee",
          "body.4.body.body.0.body.body.1.consequent.test.right.callee",
        ],
        _optionalCallableProperty: [
          "body.7.id",
          "body.1.body.body.1.declarations.0.init.properties.11.value.body.body.0.argument.properties.1.value.callee",
          "body.1.body.body.1.declarations.0.init.properties.13.value.body.body.3.declarations.0.init.callee",
        ],
      },
      exportBindingAssignments: [],
      exportName: "_decorate",
      dependencies: {
        toArray: [
          "body.1.body.body.1.declarations.0.init.properties.9.value.body.body.0.consequent.argument.callee.object.callee",
        ],
        toPropertyKey: [
          "body.1.body.body.1.declarations.0.init.properties.10.value.body.body.2.declarations.0.init.callee",
          "body.2.body.body.0.declarations.1.init.callee",
        ],
      },
      internal: false,
    },
  ),
};

```

**Expected output:**

Valid TS code

This appears to be a regression in v3.7.0.
cc @fisker

### PR DESCRIPTION
**Pull request by fisker**
## Description

Fixes #18348

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

### CODE REVIEW

File: src/utils/make-string.js [hunk 1]
```diff
@@ -1,22 +1,36 @@
...
+    }
+
+    if (quote) {
+      return quote;
+    }
+
+    return "\\" + escaped;
+  });
+
+  return enclosingQuote + raw + enclosingQuote;
```
Comment (fisker) [inline src/utils/make-string.js:31]: This part is tricky to refactor...

File: src/utils/make-string.js [hunk 2]
```diff
@@ -1,22 +1,28 @@
 /** @import {Quote} from "./get-preferred-quote.js" */
 
 // Matches _any_ escape and unescaped quotes (both single and double).
-const REGEX = /\\?(?<quote>["'])/gu;
+const REGEX = /(\\.)|(["'])/gsu;
```
Comment (fisker) [inline src/utils/make-string.js]: @liuxingbaoyu

Do you understand, why I can't change to `/(\\["'])|(["'])/gu` to only match quote?

Change to `/(\\["'\\])|(["'])/gu` seems work, but I can't understand.

Comment (fisker) [reply src/utils/make-string.js]: There is another version in this repo, been here for years.

https://github.com/prettier/prettier/blob/fd69335e513232c9b7aad78c93b42d8d3dd00ae7/src/utils/public.js#L80-L120

But we don't need `unescapeUnnecessaryEscapes` anymore, that's why I try to write a new version.

Comment (liuxingbaoyu) [reply src/utils/make-string.js]: `"A descriptor\\'s .kind must be \"method\" or \"field\".".replace(/(\\["'])|(["'])/gu,(v)=>{console.log(v);return v;})` 
It seems to be working fine in my test?

Comment (fisker) [reply src/utils/make-string.js]:
```
String.raw`A descriptor\'s .kind must be \"method\" or \"field\".`.replace(/(\\["'])|(["'])/gu,(v)=>{console.log(v);return v;})
```

Need to unescape the `\'` too.

Comment (fisker) [reply src/utils/make-string.js]: You can play with this PR. And try to change the regexp

File: tests/format/js/quotes/switch-quote/__snapshots__/format.test.js.snap [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+=====================================output=====================================
+console.log([
+  // 18351
+  'A descriptor\\'s .kind must be "method" or "field".',
+  'A descriptor\\'s .kind must be "method" or "field".',
+  'A descriptor\\\\\\'s .kind must be "method" or "field".',
+  'A descriptor\\\\\\'s .kind must be "method" or "field".',
+  'A descriptor\\\\\\'s .kind must be "method" or "field". \\\\',
+  'A descriptor\\\\\\'s .kind must be "method" or "field". \\n',
+  'A descriptor\\\\\\'s .kind must be "method" or "field". \\\\n',
```
Comment (fisker) [inline tests/format/js/quotes/switch-quote/__snapshots__/format.test.js.snap]: @liuxingbaoyu 

`'` and `\'` should format as `\'`.
`\\'` and `\\\'` should format as `\\\'`.

Comment (fisker) [reply tests/format/js/quotes/switch-quote/__snapshots__/format.test.js.snap]: I'm going to merge and let it go...

File: src/utils/make-string.js (hunk 2 above)
Comment (liuxingbaoyu) [reply src/utils/make-string.js]: I think the reason previous versions used `.` was because the authors used `\.` to pair quotation marks.

**Comment by liuxingbaoyu** [comment]
Scanner2 is much faster, but I'm not sure if it has any bugs. :)

```
PS F:\git\prettier> node .\benchmarks\swap-quote.js
swap-quote
┌─────────┬────────────┬──────────────────┬───────────────────┬────────────────────────┬────────────────────────┬─────────┐
│ (index) │ Task name  │ Latency avg (ns) │ Latency med (ns)  │ Throughput avg (ops/s) │ Throughput med (ops/s) │ Samples │
├─────────┼────────────┼──────────────────┼───────────────────┼────────────────────────┼────────────────────────┼─────────┤
│ 0       │ 'regex'    │ '531.32 ± 0.37%' │ '500.00 ± 0.00'   │ '2026096 ± 0.02%'      │ '2000000 ± 0'          │ 1882091 │
│ 1       │ 'scanner'  │ '426.07 ± 4.52%' │ '400.00 ± 100.00' │ '2751509 ± 0.03%'      │ '2500000 ± 500000'     │ 2347037 │
│ 2       │ 'scanner2' │ '142.92 ± 2.85%' │ '100.00 ± 0.00'   │ '8269451 ± 0.02%'      │ '10000000 ± 0'         │ 6997070 │
└─────────┴────────────┴──────────────────┴───────────────────┴────────────────────────┴────────────────────────┴─────────┘
swap-quote
┌─────────┬────────────┬──────────────────┬───────────────────┬────────────────────────┬────────────────────────┬─────────┐
│ (index) │ Task name  │ Latency avg (ns) │ Latency med (ns)  │ Throughput avg (ops/s) │ Throughput med (ops/s) │ Samples │
├─────────┼────────────┼──────────────────┼───────────────────┼────────────────────────┼────────────────────────┼─────────┤
│ 0       │ 'regex'    │ '3337.5 ± 0.46%' │ '3100.0 ± 100.00' │ '322112 ± 0.03%'       │ '322581 ± 10753'       │ 299622  │
│ 1       │ 'scanner'  │ '2409.2 ± 0.43%' │ '2200.0 ± 200.00' │ '444489 ± 0.05%'       │ '454545 ± 45455'       │ 415074  │
│ 2       │ 'scanner2' │ '625.63 ± 0.26%' │ '600.00 ± 0.00'   │ '1649170 ± 0.01%'      │ '1666667 ± 0'          │ 1598384 │
└─────────┴────────────┴──────────────────┴───────────────────┴────────────────────────┴────────────────────────┴─────────┘
swap-quote
┌─────────┬────────────┬──────────────────┬──────────────────┬────────────────────────┬────────────────────────┬─────────┐
│ (index) │ Task name  │ Latency avg (ns) │ Latency med (ns) │ Throughput avg (ops/s) │ Throughput med (ops/s) │ Samples │
├─────────┼────────────┼──────────────────┼──────────────────┼────────────────────────┼────────────────────────┼─────────┤
│ 0       │ 'regex'    │ '29973 ± 0.44%'  │ '28200 ± 700.00' │ '34817 ± 0.13%'        │ '35461 ± 859'          │ 33364   │
│ 1       │ 'scanner'  │ '22278 ± 0.39%'  │ '21300 ± 1000.0' │ '46532 ± 0.10%'        │ '46948 ± 2305'         │ 44889   │
│ 2       │ 'scanner2' │ '5691.2 ± 0.47%' │ '5200.0 ± 0.00'  │ '189153 ± 0.05%'       │ '192308 ± 0'           │ 175709  │
└─────────┴────────────┴──────────────────┴──────────────────┴────────────────────────┴────────────────────────┴─────────┘
```

```js
import assert from "node:assert/strict";
import { runBenchmark } from "./utilities.js";

// Matches _any_ escape and unescaped quotes (both single and double).
const REGEX = /\\(["'\\])|(["'])/gu;

function regex(rawText, enclosingQuote) {
  const otherQuote = enclosingQuote === '"' ? "'" : '"';

  // Escape and unescape single and double quotes as needed to be able to
  // enclose `rawText` with `enclosingQuote`.
  const raw = rawText.replaceAll(REGEX, (match, escaped, unescaped) => {
    // If we matched an escape, and the escaped character is a quote of the
    // other type than we intend to enclose the string with, there's no need for
    // it to be escaped, so return it _without_ the backslash.
    if (escaped) {
      return escaped === otherQuote ? otherQuote : match;
    }

    // If we matched an unescaped quote and it is of the _same_ type as we
    // intend to enclose the string with, it must be escaped, so return it with
    // a backslash.
    return unescaped === enclosingQuote ? "\\" + unescaped : unescaped;
  });

  return enclosingQuote + raw + enclosingQuote;
}

function scanner(rawText, enclosingQuote) {
  const quoteCode = enclosingQuote.charCodeAt(0);

  let pos = 0;
  let result = "";
  let lastIsEscape = false;
  while (pos < rawText.length) {
    let char = rawText.charCodeAt(pos);
    if (char === 92 /* \ */) {
      lastIsEscape = !lastIsEscape;
    } else {
      if (char === quoteCode) {
        char = quoteCode
        if (!lastIsEscape) {
          result += "\\";
        }
      }
      lastIsEscape = false;
    }
    result += String.fromCharCode(char);
    pos++;
  }
  return enclosingQuote + result + enclosingQuote;
}

function scanner2(rawText, enclosingQuote) {
  const quoteCode = enclosingQuote.charCodeAt(0);

  let pos = 0;
  let concatedPos = 0;
  let result = "";
  let hasEscape = false;
  while (pos < rawText.length) {
    let char = rawText.charCodeAt(pos);
    if (char === 92 /* \ */) {
      hasEscape = !hasEscape;
    } else {
      if (char === quoteCode) {
        char = quoteCode
        if (!hasEscape) {
          result += rawText.slice(concatedPos, pos) + "\\";
          concatedPos = pos;
        }
      }
      hasEscape = false;
    }
    pos++;
  }
  if (concatedPos !== pos) {
    result += rawText.slice(concatedPos);
  }
  return enclosingQuote + result + enclosingQuote;
}

for (const size of [1, 1e1, 1e2]) {
  const text = "A descriptor\\'s .kind must be \"method\" or \"field\".".repeat(size);
  const expected = regex(text, "'");

  await runBenchmark(
    {
      name: `swap-quote`,
      assert: (result) => assert.equal(result, expected),
    },
    {
      regex: () => regex(text, "'"),
      scanner: () => scanner(text, "'"),
      scanner2: () => scanner2(text, "'"),
    },
  );
}

```

**Comment by fisker** [comment]
I didn't seen unescaping "another quote"?

**Comment by fisker** [comment]
test text not escape correctly, use `String.raw`.

**Comment by liuxingbaoyu** [comment]
Oh, you're right!
This seems to work.
```js
import assert from "node:assert/strict";
import { runBenchmark } from "./utilities.js";

// Matches _any_ escape and unescaped quotes (both single and double).
const REGEX = /\\(["'\\])|(["'])/gu;

function regex(rawText, enclosingQuote) {
  const otherQuote = enclosingQuote === '"' ? "'" : '"';

  // Escape and unescape single and double quotes as needed to be able to
  // enclose `rawText` with `enclosingQuote`.
  const raw = rawText.replaceAll(REGEX, (match, escaped, unescaped) => {
    // If we matched an escape, and the escaped character is a quote of the
    // other type than we intend to enclose the string with, there's no need for
    // it to be escaped, so return it _without_ the backslash.
    if (escaped) {
      return escaped === otherQuote ? otherQuote : match;
    }

    // If we matched an unescaped quote and it is of the _same_ type as we
    // intend to enclose the string with, it must be escaped, so return it with
    // a backslash.
    return unescaped === enclosingQuote ? "\\" + unescaped : unescaped;
  });

  return enclosingQuote + raw + enclosingQuote;
}

function scanner2(rawText, enclosingQuote) {
  const quoteCode = enclosingQuote.charCodeAt(0);
  const otherQuoteCode = quoteCode === 34 /* " */ ? 39 /* ' */ : 34 /* " */;

  let pos = 0;
  let concatedPos = 0;
  let result = "";
  let hasEscape = false;
  while (pos < rawText.length) {
    let char = rawText.charCodeAt(pos);
    if (char === 92 /* \ */) {
      hasEscape = !hasEscape;
    } else {
      if (char === quoteCode) {
        char = quoteCode
        if (!hasEscape) {
          result += rawText.slice(concatedPos, pos) + "\\";
          concatedPos = pos;
        }
      } else if (char === otherQuoteCode) {
        if (hasEscape) {
          result += rawText.slice(concatedPos, pos - 1);
          concatedPos = pos;
        }
      }
      hasEscape = false;
    }
    pos++;
  }
  if (concatedPos !== pos) {
    result += rawText.slice(concatedPos);
  }
  return enclosingQuote + result + enclosingQuote;
}

for (const size of [1, 1e1, 1e2]) {
  const text = String.raw`A descriptor\'s .kind must be \"method\" or \"field\".`.repeat(size);
  const expected = regex(text, "'");

  await runBenchmark(
    {
      name: `swap-quote`,
      assert: (result) => assert.equal(result, expected),
    },
    {
      regex: () => regex(text, "'"),
      scanner2: () => scanner2(text, "'"),
    },
  );
}

```

**Comment by fisker** [comment]
perf of this function not really matters now. It used be, but we stopped removing unnecessary `\`, and don't even remove unnecessary `\` before quote. https://github.com/prettier/prettier/blob/fd69335e513232c9b7aad78c93b42d8d3dd00ae7/src/utils/print-string.js#L34

**Comment by fisker** [comment]
Very low chance to call this function. 😄

**Comment by fisker** [comment]
Can you post result for https://github.com/prettier/prettier/pull/18351#issuecomment-3588198294? Not on computer.

**Comment by liuxingbaoyu** [comment]
It still has performance advantages, but since it's rarely used, the original one is more reliable.
```
PS F:\git\prettier> node .\benchmarks\swap-quote.js
swap-quote
┌─────────┬────────────┬──────────────────┬──────────────────┬────────────────────────┬────────────────────────┬─────────┐
│ (index) │ Task name  │ Latency avg (ns) │ Latency med (ns) │ Throughput avg (ops/s) │ Throughput med (ops/s) │ Samples │
├─────────┼────────────┼──────────────────┼──────────────────┼────────────────────────┼────────────────────────┼─────────┤
│ 0       │ 'regex'    │ '546.83 ± 0.38%' │ '500.00 ± 0.00'  │ '1915367 ± 0.02%'      │ '2000000 ± 0'          │ 1828706 │
│ 1       │ 'scanner2' │ '175.32 ± 1.18%' │ '200.00 ± 0.00'  │ '6517912 ± 0.03%'      │ '5000000 ± 0'          │ 5703747 │
└─────────┴────────────┴──────────────────┴──────────────────┴────────────────────────┴────────────────────────┴─────────┘
swap-quote
┌─────────┬────────────┬──────────────────┬───────────────────┬────────────────────────┬────────────────────────┬─────────┐
│ (index) │ Task name  │ Latency avg (ns) │ Latency med (ns)  │ Throughput avg (ops/s) │ Throughput med (ops/s) │ Samples │
├─────────┼────────────┼──────────────────┼───────────────────┼────────────────────────┼────────────────────────┼─────────┤
│ 0       │ 'regex'    │ '3379.3 ± 0.33%' │ '3200.0 ± 100.00' │ '306339 ± 0.03%'       │ '312500 ± 9470'        │ 295921  │
│ 1       │ 'scanner2' │ '988.51 ± 0.42%' │ '900.00 ± 0.00'   │ '1056706 ± 0.02%'      │ '1111111 ± 0'          │ 1011622 │
└─────────┴────────────┴──────────────────┴───────────────────┴────────────────────────┴────────────────────────┴─────────┘
swap-quote
┌─────────┬────────────┬──────────────────┬───────────────────┬────────────────────────┬────────────────────────┬─────────┐
│ (index) │ Task name  │ Latency avg (ns) │ Latency med (ns)  │ Throughput avg (ops/s) │ Throughput med (ops/s) │ Samples │
├─────────┼────────────┼──────────────────┼───────────────────┼────────────────────────┼────────────────────────┼─────────┤
│ 0       │ 'regex'    │ '31582 ± 0.36%'  │ '30500 ± 900.00'  │ '32416 ± 0.10%'        │ '32787 ± 997'          │ 31664   │
│ 1       │ 'scanner2' │ '8707.3 ± 0.38%' │ '8400.0 ± 200.00' │ '118096 ± 0.04%'       │ '119048 ± 2769'        │ 114847  │
└─────────┴────────────┴──────────────────┴───────────────────┴────────────────────────┴────────────────────────┴─────────┘
```

**Comment by fisker** [comment]
Oh,I understand why I can't match `\["']` now, `\["'\]` make sure  first two backslash matched in `\\'`, so `'` won't mismatched as escaped.

**Comment by fisker** [comment]
look behind assetion to check double `\` should also work, not sure.

**Comment by fisker** [comment]
@liuxingbaoyu  Thanks for the issue report and help in this PR. Will release it after another issues get fixed.

**Comment by liuxingbaoyu** [comment]
You're welcome, thank you for your quick fix!
